# Test build for the io/ split (preset/sequencer/settings) and voice lifecycle.
# Usage: make -f Makefile.test   (from the tests/ dir)
#        make -f Makefile.test run
#        make -f Makefile.test clean

CC = gcc
CFLAGS = -g -O0 -Wall -I../src -I../include
LDFLAGS = -L../lib/linux -lGL -lrt -ldl -lX11 -lkissfft-float -lraylib -lportaudio -lm

SRC = ../src
OBJDIR = obj

APP_SRCS = \
	$(SRC)/voice.c \
	$(SRC)/modsystem.c \
	$(SRC)/oscillator.c \
	$(SRC)/wavetable.c \
	$(SRC)/dstruct.c \
	$(SRC)/blit_synth.c \
	$(SRC)/filters.c \
	$(SRC)/fft.c \
	$(SRC)/notes.c \
	$(SRC)/sample.c \
	$(SRC)/io.c \
	$(SRC)/io/preset_io.c \
	$(SRC)/io/sequencer_io.c \
	$(SRC)/io/settings_io.c \
	$(SRC)/vizfx.c

APP_OBJS = $(patsubst $(SRC)/%.c,$(OBJDIR)/%.o,$(APP_SRCS))

TESTS = test_io test_voice test_vizfx

all: $(TESTS)

$(OBJDIR)/%.o: $(SRC)/%.c | $(OBJDIR) $(OBJDIR)/io
	$(CC) -c $< -o $@ $(CFLAGS)

$(OBJDIR)/%.o: dsp/%.c | $(OBJDIR)
	$(CC) -c $< -o $@ $(CFLAGS)

$(OBJDIR):
	mkdir -p $(OBJDIR)

$(OBJDIR)/io:
	mkdir -p $(OBJDIR)/io

test_io: $(OBJDIR)/test_io.o $(APP_OBJS)
	$(CC) -o $@ $^ $(LDFLAGS)

test_voice: $(OBJDIR)/test_voice.o $(APP_OBJS)
	$(CC) -o $@ $^ $(LDFLAGS)

test_vizfx: $(OBJDIR)/test_vizfx.o $(APP_OBJS)
	$(CC) -o $@ $^ $(LDFLAGS)

run: all
	./test_io
	./test_voice
	./test_vizfx

clean:
	rm -rf $(OBJDIR) test_io test_voice

.PHONY: all run clean
