# Test build for the io/ split (preset/sequencer/settings) and voice lifecycle.
# Usage: make -f Makefile.test   (from the tests/ dir)
#        make -f Makefile.test run
#        make -f Makefile.test clean

CC = gcc
CFLAGS = -g -O0 -Wall -I../src -I../include
LDFLAGS = -L../lib/linux -lGL -lrt -ldl -lX11 -lkissfft-float -lraylib -lportaudio -lm

SRC = ../src
OBJDIR = obj

APP_SRCS = \
	$(SRC)/voice.c \
	$(SRC)/modsystem.c \
	$(SRC)/oscillator.c \
	$(SRC)/wavetable.c \
	$(SRC)/dstruct.c \
	$(SRC)/blit_synth.c \
	$(SRC)/filters.c \
	$(SRC)/fft.c \
	$(SRC)/notes.c \
	$(SRC)/sample.c \
	$(SRC)/graph_gui.c \
	$(SRC)/io.c \
	$(SRC)/io/preset_io.c \
	$(SRC)/io/sequencer_io.c \
	$(SRC)/io/settings_io.c

APP_OBJS = $(patsubst $(SRC)/%.c,$(OBJDIR)/%.o,$(APP_SRCS))

# Sequencer/appstate sources are only linked into test_sequencer: appstate.o
# references rebuildPatternGraph() (a gui.c symbol) which test_sequencer stubs.
SEQ_SRCS = \
	$(SRC)/sequencer.c \
	$(SRC)/appstate.c \
	$(SRC)/input.c \
	$(SRC)/settings.c
SEQ_OBJS = $(patsubst $(SRC)/%.c,$(OBJDIR)/%.o,$(SEQ_SRCS))

TESTS = test_io test_voice test_modsystem test_mod_voice test_graph_nav test_sequencer

all: $(TESTS)

$(OBJDIR)/%.o: $(SRC)/%.c | $(OBJDIR) $(OBJDIR)/io
	$(CC) -c $< -o $@ $(CFLAGS)

$(OBJDIR)/%.o: dsp/%.c | $(OBJDIR)
	$(CC) -c $< -o $@ $(CFLAGS)

$(OBJDIR):
	mkdir -p $(OBJDIR)

$(OBJDIR)/io:
	mkdir -p $(OBJDIR)/io

test_io: $(OBJDIR)/test_io.o $(APP_OBJS)
	$(CC) -o $@ $^ $(LDFLAGS)

test_voice: $(OBJDIR)/test_voice.o $(APP_OBJS)
	$(CC) -o $@ $^ $(LDFLAGS)

test_modsystem: $(OBJDIR)/test_modsystem.o $(APP_OBJS)
	$(CC) -o $@ $^ $(LDFLAGS)

test_mod_voice: $(OBJDIR)/test_mod_voice.o $(APP_OBJS)
	$(CC) -o $@ $^ $(LDFLAGS)

test_graph_nav: $(OBJDIR)/test_graph_nav.o $(APP_OBJS)
	$(CC) -o $@ $^ $(LDFLAGS)

test_sequencer: $(OBJDIR)/test_sequencer.o $(APP_OBJS) $(SEQ_OBJS)
	$(CC) -o $@ $^ $(LDFLAGS)

run: all
	./test_io
	./test_voice
	./test_modsystem
	./test_mod_voice
	./test_graph_nav
	./test_sequencer

clean:
	rm -rf $(OBJDIR) test_io test_voice test_modsystem test_mod_voice test_graph_nav test_sequencer

.PHONY: all run clean
