appstate.h File Reference
#include "gui.h"
#include "input.h"
Data Structures
struct ApplicationState
Functions
void initApplicationState ()
ApplicationState * createApplicationState ()
void incrementScene ()
void decrementScene ()
Function Documentation
createApplicationState()
ApplicationState * createApplicationState ()
                                          {
    ApplicationState* as = (ApplicationState*)malloc(sizeof(ApplicationState));
    as->selectedPattern = -1;
    as->selectedArrangerCell[0] = 0;
    as->selectedArrangerCell[1] = 0;
    as->selectedStep = 0;
    as->currentScene = SCENE_ARRANGER;
    as->inputState = createInputState(INPUT_TYPE_KEYBOARD);
    return as;
}
Referenced by main().
decrementScene()
void decrementScene ()
Referenced by main().
incrementScene()
void incrementScene ()
Referenced by main().
initApplicationState()
void initApplicationState ()