input.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include "input.h"
Functions
InputState * createInputState (InputDeviceType type)
void updateInputState (InputState *state)
void addToHistory (InputState *state, KeyMapping keyCode)
bool isKeyHeld (InputState *state, KeyMapping keyCode)
bool isKeyJustPressed (InputState *state, KeyMapping keyCode)
int getMappedKeyCode (InputState *state, KeyMapping key)
Function Documentation
addToHistory()
void addToHistory (InputState * state, KeyMapping keyCode)
                                                        {
    state->inputHistory[state->historyIndex] = keyCode;
    state->historyIndex++;
    if(state->historyIndex > MAX_INPUT_HISTORY){
        state->historyIndex = 0;
    }
}
Referenced by isKeyJustPressed().
createInputState()
InputState * createInputState (InputDeviceType type)
                                                   {
    InputState* state = (InputState*)malloc(sizeof(InputState));
    if(!state) return NULL;
    state->deviceType = type;
    state->currentMap = (type == INPUT_TYPE_KEYBOARD) ? KEYBOARD_MAP : GAMEPAD_MAP;
    state->inputHistory = (int*)malloc(MAX_INPUT_HISTORY * sizeof(int));
    if (!state->inputHistory) {
        free(state);
        return NULL;
    }
    for(int i = 0; i < MAX_INPUT_HISTORY; i++){
        state->inputHistory[i] = 0;
    }
    state->historyIndex = 0;
    for(int i = 0; i < KEY_MAPPING_COUNT; i++){
        state->keys[i].isPressed = 0;
        state->keys[i].wasPressed = 0;
    }
    return state;
}
Referenced by createApplicationState(), and main().
getMappedKeyCode()
int getMappedKeyCode (InputState * state, KeyMapping key)
                                                        {
    return state->currentMap[key];
}
isKeyHeld()
bool isKeyHeld (InputState * state, KeyMapping keyCode)
                                                      {
    return state->keys[keyCode].isPressed;
}
Referenced by main().
isKeyJustPressed()
bool isKeyJustPressed (InputState * state, KeyMapping keyCode)
                                                             {
    if(state->keys[keyCode].isPressed && !state->keys[keyCode].wasPressed) addToHistory(state, keyCode);
    return state->keys[keyCode].isPressed && !state->keys[keyCode].wasPressed;
}
Referenced by main().
updateInputState()
void updateInputState (InputState * state)
                                         {
    for (int i = 0; i < KEY_MAPPING_COUNT; i++) {
        state->keys[i].wasPressed = state->keys[i].isPressed;
        state->keys[i].isPressed = IsKeyDown(state->currentMap[i]);
    }
}
Referenced by main().