input.h File Reference
#include <stdbool.h>
#include "raylib.h"
Data Structures
struct KeyState
struct InputState
struct AppStateData
Macros
#define MAX_INPUT_HISTORY 128
Typedefs
typedef void(* SceneInputHandler) (InputState *input, AppStateData *data)
Enumerations
enum InputDeviceType { INPUT_TYPE_KEYBOARD
, INPUT_TYPE_GAMEPAD
 }
enum KeyMapping {
KM_LEFT
, KM_RIGHT
, KM_UP
, KM_DOWN
,
KM_SELECT
, KM_START
, KM_EDIT
, KM_FUNCTION
,
KM_NAV_LEFT
, KM_NAV_RIGHT
, KEY_MAPPING_COUNT
 }
Functions
InputState * createInputState (InputDeviceType type)
bool isKeyHeld (InputState *state, KeyMapping keyCode)
bool isKeyJustPressed (InputState *state, KeyMapping keyCode)
void updateInputState (InputState *state)
int getMappedKeyCode (InputState *state, KeyMapping key)
Macro Definition Documentation
MAX_INPUT_HISTORY
#define MAX_INPUT_HISTORY 128
Referenced by addToHistory(), and createInputState().
Typedef Documentation
SceneInputHandler
typedef void(* SceneInputHandler) (InputState *input, AppStateData *data)
Enumeration Type Documentation
InputDeviceType
enum InputDeviceType
Enumerator
INPUT_TYPE_KEYBOARD
INPUT_TYPE_GAMEPAD
             {
    INPUT_TYPE_KEYBOARD,
    INPUT_TYPE_GAMEPAD
} InputDeviceType;
KeyMapping
enum KeyMapping
Enumerator
KM_LEFT
KM_RIGHT
KM_UP
KM_DOWN
KM_SELECT
KM_START
KM_EDIT
KM_FUNCTION
KM_NAV_LEFT
KM_NAV_RIGHT
KEY_MAPPING_COUNT
             {
    KM_LEFT,
    KM_RIGHT,
    KM_UP,
    KM_DOWN,
    KM_SELECT,
    KM_START,
    KM_EDIT,
    KM_FUNCTION,
    KM_NAV_LEFT,
    KM_NAV_RIGHT,
    KEY_MAPPING_COUNT
} KeyMapping;
Function Documentation
createInputState()
InputState * createInputState (InputDeviceType type)
                                                   {
    InputState* state = (InputState*)malloc(sizeof(InputState));
    if(!state) return NULL;
    state->deviceType = type;
    state->currentMap = (type == INPUT_TYPE_KEYBOARD) ? KEYBOARD_MAP : GAMEPAD_MAP;
    state->inputHistory = (int*)malloc(MAX_INPUT_HISTORY * sizeof(int));
    if (!state->inputHistory) {
        free(state);
        return NULL;
    }
    for(int i = 0; i < MAX_INPUT_HISTORY; i++){
        state->inputHistory[i] = 0;
    }
    state->historyIndex = 0;
    for(int i = 0; i < KEY_MAPPING_COUNT; i++){
        state->keys[i].isPressed = 0;
        state->keys[i].wasPressed = 0;
    }
    return state;
}
Referenced by createApplicationState(), and main().
getMappedKeyCode()
int getMappedKeyCode (InputState * state, KeyMapping key)
                                                        {
    return state->currentMap[key];
}
isKeyHeld()
bool isKeyHeld (InputState * state, KeyMapping keyCode)
                                                      {
    return state->keys[keyCode].isPressed;
}
Referenced by main().
isKeyJustPressed()
bool isKeyJustPressed (InputState * state, KeyMapping keyCode)
                                                             {
    if(state->keys[keyCode].isPressed && !state->keys[keyCode].wasPressed) addToHistory(state, keyCode);
    return state->keys[keyCode].isPressed && !state->keys[keyCode].wasPressed;
}
Referenced by main().
updateInputState()
void updateInputState (InputState * state)
                                         {
    for (int i = 0; i < KEY_MAPPING_COUNT; i++) {
        state->keys[i].wasPressed = state->keys[i].isPressed;
        state->keys[i].isPressed = IsKeyDown(state->currentMap[i]);
    }
}
Referenced by main().