io.c File Reference
#include <string.h>
#include "io.h"
Functions
FileResult saveSettings (const char *filename, Settings *settings)
Saves application settings to a binary file.
FileResult loadSettings (const char *filename, Settings *settings)
Loads application settings from a binary file.
FileResult saveColourScheme (const char *filename, ColourScheme *colourScheme)
Saves a colour scheme to a binary file.
FileResult loadColourScheme (const char *filename, ColourScheme *colourScheme)
Loads a colour scheme from a binary file.
FileResult loadColourSchemeTxt (const char *filename, Color *colourArray[], int arraySize)
Loads a colour scheme from a text file format.
SequencerFileResult saveSequencerState (const char *filename, Arranger *arranger, PatternList *patterns)
Loads the complete sequencer state from a binary file.
SequencerFileResult loadSequencerState (const char *filename, Arranger *arranger, PatternList *patterns)
Loads the complete sequencer state from a binary file.
Function Documentation
loadColourScheme()
FileResult loadColourScheme (const char * filename, ColourScheme * colourScheme)
Loads a colour scheme from a binary file.
Parameters
filename Path to the colour scheme file to load
colourScheme Pointer to ColourScheme structure to populate
Returns
FileResult indicating success (FILE_OK) or specific error codes:
FILE_ERROR_OPEN if file cannot be opened
FILE_ERROR_FORMAT if file has invalid magic number
FILE_ERROR_READ if reading colour scheme data fails
                                                                              {
    FILE* file = fopen(filename, "rb");
    if (!file) return FILE_ERROR_OPEN;
    
    char magic[4];
    if (fread(magic, 1, 4, file) != 4 || memcmp(magic, "CSC1", 4) != 0) {
        fclose(file);
        return FILE_ERROR_FORMAT;
    }
    
    if (fread(colourScheme, sizeof(ColourScheme), 1, file) != 1) {
        fclose(file);
        return FILE_ERROR_READ;
    }
    
    fclose(file);
    return FILE_OK;
}
loadColourSchemeTxt()
FileResult loadColourSchemeTxt (const char * filename, Color * colourArray[], int arraySize)
Loads a colour scheme from a text file format.
Parameters
filename Path to the text-based colour scheme file
colourScheme Pointer to ColourScheme structure to populate
Returns
FileResult indicating success (FILE_OK) or specific error codes:
FILE_ERROR_OPEN if file cannot be opened
FILE_ERROR_FORMAT if file format is invalid
FILE_ERROR_READ if reading colour data fails
                                                                                          {
    FILE* file = fopen(filename, "rb");
    if (!file) return FILE_ERROR_OPEN;
    
    char line[32];
    for (int i = 0; i < arraySize; i++) {
        if (!fgets(line, sizeof(line), file)) {
            fclose(file);
            return FILE_ERROR_READ;
        }
        
        int r, g, b;
        if (sscanf(line, "%d,%d,%d", &r, &g, &b) != 3 ||
            r < 0 || r > 255 || g < 0 || g > 255 || b < 0 || b > 255) {
            fclose(file);
            return FILE_ERROR_FORMAT;
        }
        
        colourArray[i]->r = r;
        colourArray[i]->g = g;
        colourArray[i]->b = b;
    }
    
    fclose(file);
    return FILE_OK;
}
Referenced by main().
loadSequencerState()
SequencerFileResult loadSequencerState (const char * filename, Arranger * arranger, PatternList * patterns)
Loads the complete sequencer state from a binary file.
Parameters
filename Path to the sequencer state file to load
arranger Pointer to Arranger structure to populate with playhead, channel and song data
patterns Pointer to PatternList structure to populate with pattern data
Returns
SequencerFileResult indicating success (SEQ_OK) or specific error codes:
SEQ_ERROR_OPEN if file cannot be opened
SEQ_ERROR_FORMAT if file format or section headers are invalid
                                                                                                        {
    FILE* file = fopen(filename, "rb");
    if (!file) return SEQ_ERROR_OPEN;
    if (!readAndVerifyChunkHeader(file, MAGIC_HEADER)) {
        fclose(file);
        return SEQ_ERROR_FORMAT;
    }
    if (!readAndVerifyChunkHeader(file, PATTERN_SECTION)) {
        fclose(file);
        return SEQ_ERROR_FORMAT;
    }
    // Read patterns
    if (fread(&patterns->pattern_count, sizeof(int), 1, file) != 1) {
        fclose(file);
        return SEQ_ERROR_READ;
    }
    if (patterns->pattern_count > MAX_PATTERNS) {
        fclose(file);
        return SEQ_ERROR_FORMAT;
    }
    for (int i = 0; i < patterns->pattern_count; i++) {
        Pattern* p = &patterns->patterns[i];
        if (fread(&p->pattern_size, sizeof(int), 1, file) != 1 ||
            fread(p->notes, sizeof(int), MAX_SEQUENCE_LENGTH * NOTE_INFO_SIZE, file)
                != MAX_SEQUENCE_LENGTH * NOTE_INFO_SIZE) {
            fclose(file);
            return SEQ_ERROR_READ;
        }
    }
    // Read arranger section
    if (!readAndVerifyChunkHeader(file, ARRANGER_SECTION)) {
        fclose(file);
        return SEQ_ERROR_FORMAT;
    }
    if (fread(arranger->playhead_indices, sizeof(int), MAX_SEQUENCER_CHANNELS, file) != MAX_SEQUENCER_CHANNELS ||
        fread(&arranger->activeChannels, sizeof(int), 1, file) != 1 ||
        fread(&arranger->selected_x, sizeof(int), 1, file) != 1 ||
        fread(&arranger->selected_y, sizeof(int), 1, file) != 1 ||
        fread(&arranger->loop, sizeof(int), 1, file) != 1 ||
        fread(&arranger->beats_per_minute, sizeof(int), 1, file) != 1 ||
        fread(&arranger->playing, sizeof(int), 1, file) != 1 ||
        fread(arranger->song, sizeof(int), MAX_SEQUENCER_CHANNELS * MAX_SONG_LENGTH, file)
            != MAX_SEQUENCER_CHANNELS * MAX_SONG_LENGTH) {
        fclose(file);
        return SEQ_ERROR_READ;
    }
    fclose(file);
    return SEQ_OK;
}
Referenced by main().
loadSettings()
FileResult loadSettings (const char * filename, Settings * settings)
Loads application settings from a binary file.
Parameters
filename Path to the settings file to load
settings Pointer to Settings structure to populate
Returns
FileResult indicating success (FILE_OK) or specific error codes:
FILE_ERROR_OPEN if file cannot be opened
FILE_ERROR_FORMAT if file has invalid magic number
FILE_ERROR_READ if reading settings data fails
                                                                  {
    FILE* file = fopen(filename, "rb");
    if (!file) return FILE_ERROR_OPEN;
    
    char magic[4];
    if (fread(magic, 1, 4, file) != 4 || memcmp(magic, "SET1", 4) != 0) {
        fclose(file);
        return FILE_ERROR_FORMAT;
    }
    
    if (fread(settings, sizeof(Settings), 1, file) != 1) {
        fclose(file);
        return FILE_ERROR_READ;
    }
    
    fclose(file);
    return FILE_OK;
}
saveColourScheme()
FileResult saveColourScheme (const char * filename, ColourScheme * colourScheme)
Saves a colour scheme to a binary file.
Parameters
filename Path to save the colour scheme file
colourScheme Pointer to ColourScheme structure to save
Returns
FileResult indicating success (FILE_OK) or specific error codes:
FILE_ERROR_OPEN if file cannot be created/opened for writing
                                                                              {
    FILE* file = fopen(filename, "wb");
    if (!file) return FILE_ERROR_OPEN;
    
    const char magic[] = "CSC1";
    fwrite(magic, 1, 4, file);
    fwrite(colourScheme, sizeof(ColourScheme), 1, file);
    
    fclose(file);
    return FILE_OK;
}
Referenced by main().
saveSequencerState()
SequencerFileResult saveSequencerState (const char * filename, Arranger * arranger, PatternList * patterns)
Loads the complete sequencer state from a binary file.
Parameters
filename Path to the sequencer state file to load
arranger Pointer to Arranger structure to populate with playhead, channel and song data
patterns Pointer to PatternList structure to populate with pattern data
Returns
SequencerFileResult indicating success (SEQ_OK) or specific error codes:
SEQ_ERROR_OPEN if file cannot be opened
SEQ_ERROR_FORMAT if file format or section headers are invalid
                                                                                                        {
    FILE* file = fopen(filename, "wb");
    if (!file) return SEQ_ERROR_OPEN;
    // Write file header
    if (!writeChunkHeader(file, MAGIC_HEADER)) {
        fclose(file);
        return SEQ_ERROR_WRITE;
    }
    // Write patterns section
    if (!writeChunkHeader(file, PATTERN_SECTION)) {
        fclose(file);
        return SEQ_ERROR_WRITE;
    }
    // Write pattern count and patterns
    fwrite(&patterns->pattern_count, sizeof(int), 1, file);
    for (int i = 0; i < patterns->pattern_count; i++) {
        Pattern* p = &patterns->patterns[i];
        fwrite(&p->pattern_size, sizeof(int), 1, file);
        fwrite(p->notes, sizeof(int), MAX_SEQUENCE_LENGTH * NOTE_INFO_SIZE, file);
    }
    // Write arranger section
    if (!writeChunkHeader(file, ARRANGER_SECTION)) {
        fclose(file);
        return SEQ_ERROR_WRITE;
    }
    // Write complete arranger struct
    fwrite(arranger->playhead_indices, sizeof(int), MAX_SEQUENCER_CHANNELS, file);
    fwrite(&arranger->activeChannels, sizeof(int), 1, file);
    fwrite(&arranger->selected_x, sizeof(int), 1, file);
    fwrite(&arranger->selected_y, sizeof(int), 1, file);
    fwrite(&arranger->loop, sizeof(int), 1, file);
    fwrite(&arranger->beats_per_minute, sizeof(int), 1, file);
    fwrite(&arranger->playing, sizeof(int), 1, file);
    fwrite(arranger->song, sizeof(int), MAX_SEQUENCER_CHANNELS * MAX_SONG_LENGTH, file);
    fclose(file);
    return SEQ_OK;
}
Referenced by main().
saveSettings()
FileResult saveSettings (const char * filename, Settings * settings)
Saves application settings to a binary file.
Parameters
filename Path to save the settings file
settings Pointer to Settings structure to save
Returns
FileResult indicating success (FILE_OK) or specific error codes:
FILE_ERROR_OPEN if file cannot be created/opened for writing
                                                                  {
    FILE* file = fopen(filename, "wb");
    if (!file) return FILE_ERROR_OPEN;
    
    const char magic[] = "SET1";
    fwrite(magic, 1, 4, file);
    fwrite(settings, sizeof(Settings), 1, file);
    
    fclose(file);
    return FILE_OK;
}