modsystem.h File Reference
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
Data Structures
struct Parameter
struct Mod
struct ModConnection
struct ModList
struct ParamList
struct LFO
struct Random
struct EnvelopeStage
struct Envelope
Macros
#define MAX_MODS 128
#define MAX_PARAMS 1024
#define MAX_CONNECTIONS 8
#define MAX_ENVELOPE_STAGES 8
#define DEBUG_LOG(msg, ...)
#define DEBUG_FREE(msg, ptr)
Typedefs
typedef struct Parameter Parameter
typedef struct Mod Mod
typedef struct ModConnection ModConnection
typedef struct EnvelopeStage EnvelopeStage
Enumerations
enum LfoShape { LS_SIN
, LS_SQU
, LS_RMP
, LS_COUNT
 }
enum RandomType { RT_SNH
, RT_DRK
, RT_COUNT
 }
enum ModType {
MT_LFO
, MT_ENV
, MT_RND
, MT_OFS
,
MT_COUNT
 }
enum ModulationOperation {
MO_MUL
, MO_DIV
, MO_ADD
, MO_SUB
,
MO_COUNT
 }
Functions
void initModSystem ()
ModList * createModList ()
ParamList * createParamList ()
void addToModList (ModList *list, Mod *mod)
void addToParamList (ParamList *list, Parameter *param)
bool addModulation (ParamList *paramList, Mod *source, Parameter *destination, float amount, ModulationOperation type)
void updateMod (Mod *mod, float deltaTime)
void processModulations (ParamList *paramList, ModList *modList, float deltaTime)
LFO * createLFO (ParamList *paramList, ModList *modList, int index, float rate, int shape, char *name)
Random * createRandom (ParamList *paramList, ModList *modList, int index, float rate, RandomType type, char *name)
Envelope * createEnvelope (ParamList *paramList, ModList *modList, int index, float sampleRate, char *name)
void addEnvelopeStage (ParamList *paramList, Envelope *env, bool isRising, float duration, float targetLevel, float initialCurvature, char *name)
Envelope * createADSR (ParamList *paramList, ModList *modList, float a, float d, float s, float r, char *name)
Envelope * createAD (ParamList *paramList, ModList *modList, float a, float d, char *name)
void generateSine (void *self)
void generateSquare (void *self)
void generateRamp (void *self)
void generateRandom (void *self)
void generateDrunk (void *self)
float applyCurve (float x, float curvature)
void generateEnvelope (void *self)
void triggerEnvelope (Envelope *env)
Parameter * createParameter (ParamList *paramList, const char *name, float initialValue, float minValue, float maxValue)
void setParameterValue (Parameter *param, float value)
void setParameterBaseValue (Parameter *param, float value)
float getParameterValue (Parameter *param)
int getParameterValueAsInt (Parameter *param)
void modifyParameterBaseValue (Parameter *parameter, float relativeValue)
void modifyParameterValue (Parameter *parameter, float relativeValue)
void incParameterBaseValue (Parameter *parameter, float relativeValue)
ModConnection * createConnection (ParamList *paramList, Mod *source, float amount, ModulationOperation type)
void incrementConnectionType (ModConnection *modConnection)
void decrementConnectionType (ModConnection *modConnection)
void freeModList (ModList *list)
void freeParameter (Parameter *param)
void freeMod (Mod *mod)
void freeLFO (LFO *lfo)
void freeRandom (Random *rnd)
void freeEnvelope (Envelope *env)
void cleanupModSystem (ModList *list)
Macro Definition Documentation
DEBUG_FREE
#define DEBUG_FREE(msg, ptr)
Value:
DEBUG_LOG("Freeing %s at %p", msg, (void*)ptr)
DEBUG_LOG
#define DEBUG_LOG(msg, ...)
Value:
fprintf(stderr, "[DEBUG] " msg "\n", ##__VA_ARGS__)
MAX_CONNECTIONS
#define MAX_CONNECTIONS 8
MAX_ENVELOPE_STAGES
#define MAX_ENVELOPE_STAGES 8
Referenced by addEnvelopeStage().
MAX_MODS
#define MAX_MODS 128
Referenced by addToModList().
MAX_PARAMS
#define MAX_PARAMS 1024
Referenced by addToParamList().
Typedef Documentation
EnvelopeStage
typedef struct EnvelopeStage EnvelopeStage
Mod
typedef struct Mod Mod
ModConnection
typedef struct ModConnection ModConnection
Parameter
typedef struct Parameter Parameter
Enumeration Type Documentation
LfoShape
enum LfoShape
Enumerator
LS_SIN
LS_SQU
LS_RMP
LS_COUNT
             {
    LS_SIN, // sinusoid
    LS_SQU, // Square
    LS_RMP, // Ramp
    LS_COUNT
} LfoShape;
ModType
enum ModType
Enumerator
MT_LFO
MT_ENV
MT_RND
MT_OFS
MT_COUNT
             {
    MT_LFO, // Low-frequency oscillator
    MT_ENV, // Envelope
    MT_RND, // Random
    MT_OFS, // Constant Offset
    MT_COUNT
} ModType;
ModulationOperation
enum ModulationOperation
Enumerator
MO_MUL
MO_DIV
MO_ADD
MO_SUB
MO_COUNT
             {
    MO_MUL,
    MO_DIV,
    MO_ADD,
    MO_SUB,
    MO_COUNT
} ModulationOperation;
RandomType
enum RandomType
Enumerator
RT_SNH
RT_DRK
RT_COUNT
             {
    RT_SNH, // Sample and hold-ish
    RT_DRK, // Meandering drunk
    RT_COUNT
} RandomType;
Function Documentation
addEnvelopeStage()
void addEnvelopeStage (ParamList * paramList, Envelope * env, bool isRising, float duration, float targetLevel, float initialCurvature, char * name)
                                                                                                                                                 {
    //DEBUG_LOG("add env stage");
    if (env->stageCount >= MAX_ENVELOPE_STAGES) {
        return;
    }
    
    char nameBuf[32];
    int idx = env->stageCount;
    
    EnvelopeStage* stage = &env->stages[idx];
    stage->isRising = isRising;
    stage->isSustain = (duration <= 0.0f);
    stage->name = name;
    
    sprintf(nameBuf, "env%d_dur%d", env->base.index, idx);
    stage->duration = createParameter(paramList, nameBuf, duration, 0.001f, 10.0f);
    
    stage->targetLevel = targetLevel;
    
    sprintf(nameBuf, "env%d_curve%d", env->base.index, idx);
    stage->curvature = createParameter(paramList, nameBuf, initialCurvature, -1.0f, 1.0f);
    
    env->stageCount++;
}
Referenced by createAD(), and createADSR().
addModulation()
bool addModulation (ParamList * paramList, Mod * source, Parameter * destination, float amount, ModulationOperation type)
                                                                                                                      {
    ModConnection* conn = createConnection(paramList, source, amount, type);
    if (!conn) return false;
    if (destination->modulators == NULL) {
        destination->modulators = conn;
    } else {
        // Add to front of list
        conn->next = destination->modulators;
        destination->modulators->previous = conn;
        destination->modulators = conn;
    }
    destination->modulator_count++;
    return true;
}
Referenced by initialize_voice(), and main().
addToModList()
void addToModList (ModList * list, Mod * mod)
                                           {
    //DEBUG_LOG("add mod");
    if (list->count < MAX_MODS) {
        list->mods[list->count++] = mod;
    }
}
Referenced by createEnvelope(), createLFO(), and createRandom().
addToParamList()
void addToParamList (ParamList * list, Parameter * param)
                                                      {
    if (list->count < MAX_PARAMS) {
        list->params[list->count++] = param;
    }
}
Referenced by createParameter().
applyCurve()
float applyCurve (float x, float curvature)
                                           {
    // Ensure inputs are in valid ranges
    x = fmaxf(0.0f, fminf(1.0f, x));
    curvature = fmaxf(0.0f, fminf(1.0f, curvature));
    
    if (fabsf(curvature - 0.5f) < 0.001f) {
        return x; // Linear interpolation
    }
    
    // Convert curvature from [0,1] to [-4,4] for more pronounced effect
    float curve_amount = (curvature - 0.5f) * 8.0f;
    
    // Apply exponential curve
    if (curve_amount > 0) {
        return powf(x, 1.0f + curve_amount);
    } else {
        return 1.0f - powf(1.0f - x, 1.0f - curve_amount);
    }
}
Referenced by drawEnvelopeGui(), and generateEnvelope().
cleanupModSystem()
void cleanupModSystem (ModList * list)
                                     {
    if (!list) return;
    
    for (int i = 0; i < list->count; i++) {
        Mod* mod = list->mods[i];
        if (!mod) continue;
        // Free mod-specific resources
        switch (mod->type) {
            case MT_LFO:
                freeLFO((LFO*)mod);
                break;
            case MT_RND:
                freeRandom((Random*)mod);
                break;
            case MT_ENV:
                freeEnvelope((Envelope*)mod);
                break;
            default:
                freeMod(mod);
        }
    }
    free(list);
}
Referenced by main(), and main().
createAD()
Envelope * createAD (ParamList * paramList, ModList * modList, float a, float d, char * name)
                                                                                        {
    Envelope* env = createEnvelope(paramList, modList, 4, 44100, name);
    addEnvelopeStage(paramList, env, true, a, 1.0f, 0.95f, "A"); // Attack
    addEnvelopeStage(paramList, env, false, d, 0.0f, 0.1f, "D"); // Decay
    return env;
}
Referenced by initialize_voice().
createADSR()
Envelope * createADSR (ParamList * paramList, ModList * modList, float a, float d, float s, float r, char * name)
                                                                                                            {
    //DEBUG_LOG("create adsr");
    Envelope* env = createEnvelope(paramList, modList, 4, 44100, name);
    addEnvelopeStage(paramList, env, true, a, 1.0f, 0.75f, "A"); // Attack
    addEnvelopeStage(paramList, env, false, d, 0.7f, 0.75f, "D"); // Decay
    addEnvelopeStage(paramList, env, true, s, 0.7f, 0.5f, "S"); // Sustain
    addEnvelopeStage(paramList, env, false, r, 0.0f, 0.75f, "R"); // Release
    return env;
}
Referenced by initialize_voice(), and main().
createConnection()
ModConnection * createConnection (ParamList * paramList, Mod * source, float amount, ModulationOperation type)
                                                                                                           {
    //DEBUG_LOG("create con");
    ModConnection* conn = (ModConnection*)malloc(sizeof(ModConnection));
    if (conn) {
        conn->source = source;
        conn->amount = createParameter(paramList, "mod amount", 1.0f, 0.0f, 1.0f);
        conn->type = createParameterEx(paramList, "mod operation", (float)type, 0.0f, (float)MT_COUNT, 1.0f, 10.0f); // Set modulation type
        conn->next = NULL;
        conn->previous = NULL;
    }
    return conn;
}
Referenced by addModulation().
createEnvelope()
Envelope * createEnvelope (ParamList * paramList, ModList * modList, int index, float sampleRate, char * name)
                                                                                                          {
    //DEBUG_LOG("create env");
    Envelope* env = (Envelope*)malloc(sizeof(Envelope));
    
    // Initialize base mod
    env->base.name = name;
    env->base.index = index;
    env->base.type = MT_ENV;
    env->base.output = createParameter(paramList, "env output", 0.0f, 0.0f, 1.0f);
    env->base.generate = generateEnvelope;
    //env->base.destinations = NULL;
    //env->base.dependencies = NULL;
    env->base.dependency_count = 0;
    env->base.processed = false;
    env->base.visiting = false;
    
    // Initialize envelope properties
    env->sampleRate = sampleRate;
    env->currentLevel = 0.0f;
    env->currentStageIndex = 0;
    env->stageCount = 0;
    env->currentTime = 0.0f;
    env->totalElapsedTime = 0.0f;
    env->isTriggered = false;
    env->isSustaining = false;
    env->loop = false;
    
    addToModList(modList, &env->base);
    return env;
}
Referenced by createAD(), and createADSR().
createLFO()
LFO * createLFO (ParamList * paramList, ModList * modList, int index, float rate, int shape, char * name)
                                                                                                     {
    //DEBUG_LOG("Create LFO");
    LFO* lfo = (LFO*)malloc(sizeof(LFO));
    memset(lfo, 0, sizeof(LFO));
    
    // Initialize base Mod
    //lfo->base.dependencies = NULL;
    lfo->base.name = name;
    lfo->base.dependency_count = 0;
    lfo->base.processed = false;
    lfo->base.visiting = false;
    lfo->base.index = index;
    lfo->base.type = MT_LFO;
    //lfo->base.destinations = NULL;
    lfo->base.output = createParameter(paramList,"LFO output", 0.0f, -1.0f, 1.0f);
    switch(shape){
        case LS_SIN:
            lfo->base.generate = generateSine;
            break;
        case LS_SQU:
            lfo->base.generate = generateSquare;
            break;
        case LS_RMP:
            lfo->base.generate = generateRamp;
            break;
    }
    
    // Initialize LFO-specific parameters
    lfo->rate = createParameter(paramList, "LFO rate", rate, 0.1f, 100.0f);
    lfo->phase = createParameter(paramList, "LFO phase", 0.0f, 0.0f, 1.0f);
    lfo->shape = shape;
    addToModList(modList, &lfo->base);
    return lfo;
}
Referenced by main().
createModList()
ModList * createModList ()
                         {
    ModList* list = (ModList*)malloc(sizeof(ModList));
    if (!list) return NULL;
    list->count = 0;
    return list;
}
Referenced by initialize_voice(), main(), and main().
createParameter()
Parameter * createParameter (ParamList * paramList, const char * name, float initialValue, float minValue, float maxValue)
                                                                                                                       {
    //DEBUG_LOG("create param");
    Parameter* param = (Parameter*)malloc(sizeof(Parameter));
    if (param) {
        param->name = strdup(name);
        param->minValue = minValue;
        param->maxValue = maxValue;
        param->baseValue = _clampValue(initialValue, minValue, maxValue);
        param->currentValue = param->baseValue;
        param->fineIncrement = 0.01f;
        param->coarseIncrement = 0.10f;
        param->modulators = NULL;
        param->modulator_count = 0;
        param->onChange = NULL;
    }
    
    addToParamList(paramList, param);
    return param;
}
Referenced by addEnvelopeStage(), createConnection(), createEnvelope(), createLFO(), createOperator(), createParameterEx(), createRandom(), initialize_voice(), and main().
createParamList()
ParamList * createParamList ()
                             {
    ParamList* list = (ParamList*)malloc(sizeof(ParamList));
    if (!list) return NULL;
    list->count = 0;
    return list;
}
Referenced by initialize_voice().
createRandom()
Random * createRandom (ParamList * paramList, ModList * modList, int index, float rate, RandomType type, char * name)
                                                                                                                {
    Random* rnd = (Random*)malloc(sizeof(Random));
    rnd->base.name = name;
    rnd->base.index = index;
    rnd->base.type = MT_RND;
    //rnd->base.destinations = NULL;
    rnd->lastPhase = 0.0f;
    rnd->lastRandom = 0.0f;
    rnd->base.output = createParameter(paramList, "RNG output", 0.0f, -1.0f, 1.0f);
    switch(type){
        case RT_SNH:
            rnd->base.generate = generateRandom;
            break;
        case RT_DRK:
            rnd->base.generate = generateDrunk;
            break;
    }
    rnd->rate = createParameter(paramList, "RNG rate", rate, 0.1f, 100.0f);
    rnd->phase = createParameter(paramList, "RNG phase", 0.0f, 0.0f, 1.0f);
    rnd->shape = type;
    
    addToModList(modList, &rnd->base);
    return rnd;
}
Referenced by main().
decrementConnectionType()
void decrementConnectionType (ModConnection * modConnection)
freeEnvelope()
void freeEnvelope (Envelope * env)
                                 {
    if (!env) return;
    
    freeParameter(env->base.output);
    
    for (int i = 0; i < env->stageCount; i++) {
        freeParameter(env->stages[i].duration);
        freeParameter(env->stages[i].curvature);
    }
    
    free(env);
}
Referenced by cleanupModSystem().
freeLFO()
void freeLFO (LFO * lfo)
                       {
    if (!lfo) return;
    
    // Free parameters in specific order
    if (lfo->phase) {
        freeParameter(lfo->phase);
        lfo->phase = NULL;
    }
    if (lfo->rate) {
        freeParameter(lfo->rate);
        lfo->rate = NULL;
    }
    if (lfo->base.output) {
        freeParameter(lfo->base.output);
        lfo->base.output = NULL;
    }
    
    free(lfo);
}
Referenced by cleanupModSystem().
freeMod()
void freeMod (Mod * mod)
                       {
    if (!mod) {
        return;
    }
    
    if (mod->output) {
        freeParameter(mod->output);
        mod->output = NULL;
    }
    
    free(mod);
}
Referenced by cleanupModSystem(), and freeModList().
freeModList()
void freeModList (ModList * list)
                                {
    if (!list) {
        return;
    }
    for (int i = 0; i < list->count; i++) {
        freeMod(list->mods[i]);
    }
    free(list);
}
Referenced by main().
freeParameter()
void freeParameter (Parameter * param)
                                     {
    if (!param) {
        return;
    }
    ModConnection* current = param->modulators;
    while (current != NULL) {
        ModConnection* next = current->next;
        if (current) {
            free(current);
        }
        current = next;
    }
    param->modulators = NULL;
    if (param->name) {
        free(param->name);
        param->name = NULL;
    }
    free(param);
}
Referenced by freeEnvelope(), freeLFO(), freeMod(), freeParamList(), and freeRandom().
freeRandom()
void freeRandom (Random * rnd)
                             {
    if (!rnd) return;
    
    freeParameter(rnd->base.output);
    freeParameter(rnd->rate);
    freeParameter(rnd->phase);
    
    free(rnd);
}
Referenced by cleanupModSystem().
generateDrunk()
void generateDrunk (void * self)
                              {
    Random* rnd = (Random*)self;
    float phase = getParameterValue(rnd->phase);
    
    rnd->lastRandom = ((float)rand() / (float)RAND_MAX) * 2.0f - 1.0f;
    rnd->lastRandom *= 0.5f * ((float)rand() / (float)RAND_MAX);
    rnd->lastPhase = phase;
    setParameterBaseValue(rnd->base.output, rnd->base.output->currentValue + rnd->lastRandom);
    setParameterValue(rnd->base.output, rnd->base.output->currentValue + rnd->lastRandom);
}
Referenced by createRandom().
generateEnvelope()
void generateEnvelope (void * self)
                                  {
    Envelope* env = (Envelope*)self;
    if (!env || !env->isTriggered || env->currentStageIndex >= env->stageCount) {
        return;
    }
    
    EnvelopeStage* stage = &env->stages[env->currentStageIndex];
    if (!stage->duration || !stage->curvature) {
        return;
    }
    float dt = 1.0f / env->sampleRate;
    env->currentTime += dt;
    
    float t = env->currentTime / stage->duration->currentValue;
    float shapedT = applyCurve(t, stage->curvature->currentValue);
    
    float startLevel = (env->currentStageIndex > 0) ?
                      env->stages[env->currentStageIndex-1].targetLevel :
                      0.0f;
    
    env->currentLevel = startLevel + (stage->targetLevel - startLevel) * shapedT;
    if (t >= 1.0f) {
            //printf("stage %i complete\n", env->currentStageIndex);
        env->currentTime = 0.0f;
        env->currentLevel = stage->targetLevel;
        if (++env->currentStageIndex >= env->stageCount) {
            env->isTriggered = false;
            //printf("TRIGGER OFF!!!!!!\n");
        }
    }
    // Important: Update output parameter
    setParameterBaseValue(env->base.output, env->currentLevel);
    setParameterValue(env->base.output, env->currentLevel);
}
Referenced by createEnvelope().
generateRamp()
void generateRamp (void * self)
                              {
    LFO* lfo = (LFO*)self;
    float value = (getParameterValue(lfo->phase) - 1.0f) * 2.0f;
    setParameterBaseValue(lfo->base.output, value);
    setParameterValue(lfo->base.output, value);
}
Referenced by createLFO().
generateRandom()
void generateRandom (void * self)
                                {
    Random* rnd = (Random*)self;
    float phase = getParameterValue(rnd->phase);
    
    if (phase < rnd->lastPhase) {
        rnd->lastRandom = ((float)rand() / (float)RAND_MAX) * 2.0f - 1.0f;
    }
    
    rnd->lastPhase = phase;
    setParameterBaseValue(rnd->base.output, rnd->lastRandom);
    setParameterValue(rnd->base.output, rnd->lastRandom);
}
Referenced by createRandom().
generateSine()
void generateSine (void * self)
                              {
    LFO* lfo = (LFO*)self;
    float value = sinf(getParameterValue(lfo->phase) * 2.0f * M_PI);
    setParameterBaseValue(lfo->base.output, value);
    setParameterValue(lfo->base.output, value);
}
Referenced by createLFO().
generateSquare()
void generateSquare (void * self)
                                {
    LFO* lfo = (LFO*)self;
    float value = getParameterValue(lfo->phase) < 0.5f ? 1.0f : -1.0f;
    setParameterBaseValue(lfo->base.output, value);
    setParameterValue(lfo->base.output, value);
}
Referenced by createLFO().
getParameterValue()
float getParameterValue (Parameter * param)
                                          {
    //DEBUG_LOG("get param");
    return param->currentValue;
}
Referenced by generateDrunk(), generateRamp(), generateRandom(), generateSine(), generateSquare(), main(), modifyParameterValue(), processModulations(), sine_op(), and updateMod().
getParameterValueAsInt()
int getParameterValueAsInt (Parameter * param)
                                            {
    return (int)round(param->currentValue);
}
Referenced by processModulations().
incParameterBaseValue()
void incParameterBaseValue (Parameter * parameter, float relativeValue)
                                                                     {
    float currentValue = parameter->baseValue;
    float sign = 1.0f;
    if(relativeValue < 0.0f){
        sign = -1.0f;
    }
    if(abs(relativeValue) > 1){
        setParameterBaseValue(parameter, currentValue + parameter->coarseIncrement * sign);
    } else {
        setParameterBaseValue(parameter, currentValue + parameter->fineIncrement * sign);
    }
}
Referenced by createModMappingGroup().
incrementConnectionType()
void incrementConnectionType (ModConnection * modConnection)
initModSystem()
void initModSystem ()
                    {
    //paramList = createParamList();
}
Referenced by main(), and main().
modifyParameterBaseValue()
void modifyParameterBaseValue (Parameter * parameter, float relativeValue)
                                                                        {
    float currentValue = parameter->baseValue;
    setParameterBaseValue(parameter, currentValue + relativeValue);
}
Referenced by main().
modifyParameterValue()
void modifyParameterValue (Parameter * parameter, float relativeValue)
                                                                    {
    float currentValue = getParameterValue(parameter);
    setParameterValue(parameter, currentValue + relativeValue);
}
processModulations()
void processModulations (ParamList * paramList, ModList * modList, float deltaTime)
                                                                                 {
    if (!modList) return;
    if (!paramList) return;
    for (int i = 0; i < modList->count; i++) {
        Mod* mod = modList->mods[i];
        updateMod(mod, deltaTime);
        if (!mod->generate) continue;
        
        mod->generate(mod);
    }
    
    for(int i = 0; i < paramList->count; i++){
        ModConnection* conn = paramList->params[i]->modulators;
        float finalValue = paramList->params[i]->baseValue;
        while (conn != NULL) {
            float modValue = getParameterValue(conn->source->output);
            switch(getParameterValueAsInt(conn->type)) {
                case MO_ADD:
                    finalValue += modValue;
                    break;
                case MO_MUL:
                    finalValue *= modValue;
                    break;
                case MO_SUB:
                    finalValue -= modValue;
                    break;
                case MO_DIV:
                    if (modValue != 0.0f) {
                        finalValue /= modValue;
                    }
                    break;
                default:
                    break;
            }
            
            ModConnection* next = conn->next;
            conn = next;
        }
        setParameterValue(paramList->params[i], finalValue);
    }
}
Referenced by main().
setParameterBaseValue()
void setParameterBaseValue (Parameter * param, float value)
                                                          {
    //DEBUG_LOG("set param");
    float clamped = _clampValue(value, param->minValue, param->maxValue);
    param->baseValue = clamped;
    if (param->onChange) {
        param->onChange(param, clamped);
    }
}
Referenced by generateDrunk(), generateEnvelope(), generateRamp(), generateRandom(), generateSine(), generateSquare(), incParameterBaseValue(), modifyParameterBaseValue(), and updateMod().
setParameterValue()
void setParameterValue (Parameter * param, float value)
                                                      {
    //DEBUG_LOG("set param");
    float clamped = _clampValue(value, param->minValue, param->maxValue);
    param->currentValue = clamped;
    if (param->onChange) {
        param->onChange(param, clamped);
    }
}
Referenced by generateDrunk(), generateEnvelope(), generateRamp(), generateRandom(), generateSine(), generateSquare(), modifyParameterValue(), processModulations(), and updateMod().
triggerEnvelope()
void triggerEnvelope (Envelope * env)
                                   {
    //DEBUG_LOG("triggering env");
    env->currentStageIndex = 0;
    env->isTriggered = true;
}
updateMod()
void updateMod (Mod * mod, float deltaTime)
                                          {
    //DEBUG_LOG("update mod");
    if (mod == NULL) return;
    
    switch(mod->type){
        case MT_ENV:
            Envelope* env = (Envelope*)mod;
            if (env->isTriggered) {
                env->currentTime += deltaTime;
            }
            break;
        case MT_LFO:
            LFO* lfo = (LFO*)mod;
            float l_phase = getParameterValue(lfo->phase);
            float l_rate = getParameterValue(lfo->rate);
            l_phase += l_rate * deltaTime;
            if (l_phase >= 1.0f) l_phase -= 1.0f;
            setParameterBaseValue(lfo->phase, l_phase);
            setParameterValue(lfo->phase, l_phase);
            break;
        case MT_RND:
            Random* rand = (Random*)mod;
            float r_phase = getParameterValue(rand->phase);
            float r_rate = getParameterValue(rand->rate);
            r_phase += r_rate * deltaTime;
            if (r_phase >= 1.0f) r_phase -= 1.0f;
            setParameterBaseValue(rand->phase, r_phase);
            setParameterValue(rand->phase, r_phase);
        default:
            break;
    }
    //DEBUG_LOG("update mod DONE");
}
Referenced by processModulations().