sequencer.h File Reference
#include "settings.h"
Data Structures
struct Pattern
Represents a musical pattern containing a sequence of notes. each row is a note, each column contains the octave and a note index from 0-12.
struct PatternList
struct Arranger
struct Sequencer
Macros
#define MAX_PATTERNS 255
#define MAX_SONG_LENGTH 255
#define MAX_SEQUENCE_LENGTH 24
#define NOTE_INFO_SIZE 2
Functions
PatternList * createPatternList ()
Creates a new PatternList.
Arranger * createArranger ()
Creates a new Arranger with the given settings.
void addChannel (Arranger *arranger, int channelIndex)
Adds a new channel to the Arranger at the specified index.
void removeChannel (Arranger *arranger, int channelIndex)
Removes a channel from the Arranger at the specified index.
int addPattern (PatternList *patternList, int patternSize, int notes[][NOTE_INFO_SIZE])
Adds a new pattern to the PatternList.
void addPatternToArranger (Arranger *arranger, int patternId, int sequencer_id, int column)
Adds a blank pattern to the PatternList.
void addBlankIfEmpty (PatternList *patternList, Arranger *arranger, int sequencerId, int row)
Adds a blank pattern to the Arranger if the specified location is empty.
Sequencer * createSequencer (Arranger *arranger)
Creates a new Sequencer based on the current state of the Arranger.
int * getStep (PatternList *patternList, int patternIndex, int noteIndex)
Retrieves a step (note) from a pattern.
int * getCurrentStep (PatternList *patternList, int patternIndex, int noteIndex)
Retrieves the current step (note) from a pattern.
int * selectArrangerCell (Arranger *arranger, int checkBlankPattern, int relativex, int relativey, int *selectedArrangerCell)
Selects a cell in the Arranger and updates the selected coordinates.
int selectStep (PatternList *patternList, int patternIndex, int selectedStep)
Selects a step in a pattern and ensures it is within bounds.
int * editCurrentNote (PatternList *patternList, int patternIndex, int noteIndex, int note[NOTE_INFO_SIZE])
Edits the current note in a pattern.
int * editCurrentNoteRelative (PatternList *patternList, int patternIndex, int noteIndex, int note[NOTE_INFO_SIZE])
Edits the current note in a pattern with relative changes.
void incrementSequencer (Sequencer *sequencer, PatternList *patternList, Arranger *arranger)
Advances the sequencer to the next step for all active channels.
void editStep (PatternList *patternList, int patternIndex, int noteIndex, int note[NOTE_INFO_SIZE])
Edits a step in a pattern.
void stopPlaying (Arranger *arranger)
Stops playback in the Arranger.
void startPlaying (Sequencer *sequencer, PatternList *patternList, Arranger *arranger, int playMode)
Starts playback in the Sequencer and Arranger from the current cursor position, resetting all pattern playback posiitons.
Macro Definition Documentation
MAX_PATTERNS
#define MAX_PATTERNS 255
Referenced by loadSequencerState().
MAX_SEQUENCE_LENGTH
#define MAX_SEQUENCE_LENGTH 24
Referenced by loadSequencerState(), and saveSequencerState().
MAX_SONG_LENGTH
#define MAX_SONG_LENGTH 255
Referenced by addChannel(), createArranger(), drawArrangerGui(), loadSequencerState(), removeChannel(), saveSequencerState(), and selectArrangerCell().
NOTE_INFO_SIZE
#define NOTE_INFO_SIZE 2
Referenced by addBlankPattern(), addPattern(), createArranger(), editCurrentNote(), editCurrentNoteRelative(), editStep(), loadSequencerState(), and saveSequencerState().
Function Documentation
addBlankIfEmpty()
void addBlankIfEmpty (PatternList * patternList, Arranger * arranger, int sequencerId, int row)
Adds a blank pattern to the Arranger if the specified location is empty.
Parameters
patternList Pointer to the PatternList.
arranger Pointer to the Arranger.
sequencerId Channel index.
row Row index.
                                                                                            {
    int patternID = addBlankPattern(patternList);
    if(arranger->song[sequencerId][row] == -1){
        addPatternToArranger(arranger, patternID, sequencerId, row);
    }
}
Referenced by main().
addChannel()
void addChannel (Arranger * arranger, int channelIndex)
Adds a new channel to the Arranger at the specified index.
Parameters
arranger Pointer to the Arranger.
channelIndex Index at which to add the new channel.
                                                     {
    if(arranger->enabledChannels < MAX_SEQUENCER_CHANNELS && channelIndex >= 0){
        if(channelIndex < arranger->enabledChannels){ //copy all subsequent channels to the right
            memmove(arranger->song[channelIndex + 1], arranger->song[channelIndex], (MAX_SEQUENCER_CHANNELS - channelIndex) * MAX_SONG_LENGTH * sizeof(int));
        }
        arranger->voiceTypes[channelIndex] = 0;
        for(int i = 0; i < MAX_SONG_LENGTH; i++){ //init with empty pattern refs
            arranger->song[channelIndex][i] = -1;
        }
        arranger->enabledChannels++;
    } else {
        printf("\t ERROR: max sequencer channels (%i) reached, can't insert at %i.\n", MAX_SEQUENCER_CHANNELS, channelIndex);
    }
}
addPattern()
int addPattern (PatternList * patternList, int patternSize, int notes[][NOTE_INFO_SIZE])
Adds a new pattern to the PatternList.
Parameters
patternList Pointer to the PatternList.
patternSize Size of the pattern.
notes Array of notes to add to the pattern.
Returns
The index of the newly added pattern.
                                                                                       {
    patternList->patterns[patternList->pattern_count].pattern_size = patternSize;
    for(int i = 0; i < patternSize; i++){
        for(int j = 0; j < NOTE_INFO_SIZE; j++){
            patternList->patterns[patternList->pattern_count].notes[i][j] = notes[i][j];
        }
    }
    patternList->pattern_count++;
    return patternList->pattern_count - 1;
}
Referenced by addBlankPattern().
addPatternToArranger()
void addPatternToArranger (Arranger * arranger, int patternId, int sequencer_id, int column)
Adds a blank pattern to the PatternList.
Parameters
patternList Pointer to the PatternList.
Returns
The index of the newly added pattern.
                                                                                       {
    arranger->song[sequencer_id][row] = patternId;
}
Referenced by addBlankIfEmpty().
createArranger()
Arranger * createArranger ()
Creates a new Arranger with the given settings.
Parameters
settings Pointer to the settings to initialize the Arranger.
Returns
A pointer to the newly created Arranger.
Referenced by main().
createPatternList()
PatternList * createPatternList ()
Creates a new PatternList.
Returns
A pointer to the newly created PatternList.
                                {
    PatternList * patternList = (PatternList*)malloc(sizeof(PatternList));
    patternList->pattern_count = 0;
    return patternList;
}
Referenced by main().
createSequencer()
Sequencer * createSequencer (Arranger * arranger)
Creates a new Sequencer based on the current state of the Arranger.
Parameters
arranger Pointer to the Arranger.
Returns
A pointer to the newly created Sequencer.
                                              {
    Sequencer* sequencer = (Sequencer*)malloc(sizeof(Sequencer));
    
    for(int i = 0; i < arranger->enabledChannels; i++){
        sequencer->playhead_index[i] = 0;
        sequencer->selected_index[i] = 0;
        sequencer->pattern_index[i] = arranger->song[i][0];
        if(sequencer->pattern_index[i] == -1){
            sequencer->running[i] = 0;
        } else {
            sequencer->running[i] = 1;
        }
    }
    return sequencer;
}
Referenced by main().
editCurrentNote()
int * editCurrentNote (PatternList * patternList, int patternIndex, int noteIndex, int note[NOTE_INFO_SIZE])
Edits the current note in a pattern.
Parameters
patternList Pointer to the PatternList.
patternIndex Index of the pattern.
noteIndex Index of the note to edit.
note New note data.
Returns
Pointer to the edited note data.
                                                                                                         {
    if(patternList->patterns[patternIndex].notes[noteIndex][0] == OFF){
        patternList->patterns[patternIndex].notes[noteIndex][0] = C;
        patternList->patterns[patternIndex].notes[noteIndex][1] = 3;
    } else {
        patternList->patterns[patternIndex].notes[noteIndex][0] = note[0];
        patternList->patterns[patternIndex].notes[noteIndex][1] = note[1];
    }
}
Referenced by main().
editCurrentNoteRelative()
int * editCurrentNoteRelative (PatternList * patternList, int patternIndex, int noteIndex, int note[NOTE_INFO_SIZE])
Edits the current note in a pattern with relative changes.
Parameters
patternList Pointer to the PatternList.
patternIndex Index of the pattern.
noteIndex Index of the note to edit.
note Relative changes to the note data. [1,0] would increase note chromatically, [0,1] would increase octave.
Returns
Pointer to the edited note data.
                                                                                                                 {
    
    int newNote[NOTE_INFO_SIZE] =
    {
        patternList->patterns[patternIndex].notes[noteIndex][0] + note[0],
        patternList->patterns[patternIndex].notes[noteIndex][1] + note[1]
    };
    if(newNote[0] < 0){
        newNote[0] = B;
        newNote[1]--;
    }
    if(newNote[0] >= NOTE_COUNT){
        newNote[0] = C;
        newNote[1]++;
    }
    if(newNote[1] > MAX_OCTAVES - 1){
        newNote[1] = MAX_OCTAVES - 1;
    }
    if(newNote[1] < 0){
        newNote[1] = 0;
    }
    patternList->patterns[patternIndex].notes[noteIndex][0] = newNote[0];
    patternList->patterns[patternIndex].notes[noteIndex][1] = newNote[1];
}
Referenced by main().
editStep()
void editStep (PatternList * patternList, int patternIndex, int noteIndex, int note[NOTE_INFO_SIZE])
Edits a step in a pattern.
Parameters
patternList Pointer to the PatternList.
patternIndex Index of the pattern.
noteIndex Index of the note to edit.
note New note data.
                                                                                                  { //TO-DO: error checking
    if (noteIndex >= 0 && noteIndex < patternList->patterns[patternIndex].pattern_size) {
        for (int j = 0; j < NOTE_INFO_SIZE; j++) {
            patternList->patterns[patternIndex].notes[patternIndex][j] = note[j];
        }
    }
}
getCurrentStep()
int * getCurrentStep (PatternList * patternList, int patternIndex, int noteIndex)
Retrieves the current step (note) from a pattern.
Parameters
patternList Pointer to the PatternList.
patternIndex Index of the pattern.
noteIndex Index of the note.
Returns
Pointer to the note data.
                                                                              {
    return patternList->patterns[patternIndex].notes[noteIndex];
}
getStep()
int * getStep (PatternList * patternList, int patternIndex, int noteIndex)
Retrieves a step (note) from a pattern.
Parameters
patternList Pointer to the PatternList.
patternIndex Index of the pattern.
noteIndex Index of the note.
Returns
Pointer to the note data.
                                                                       {
    return patternList->patterns[patternIndex].notes[noteIndex];
}
Referenced by drawSequencerGui().
incrementSequencer()
void incrementSequencer (Sequencer * sequencer, PatternList * patternList, Arranger * arranger)
Advances the sequencer to the next step for all active channels.
Parameters
sequencer Pointer to the Sequencer.
patternList Pointer to the PatternList.
arranger Pointer to the Arranger.
                                                                                           { //TO-DO: add pattern mode func
    //printf("s:%i p: %i inc. ", sequencer->sequencer_id, sequencer->pattern_index);
    for(int i = 0; i < arranger->enabledChannels; i++){
        int patternSize = patternList->patterns[sequencer->pattern_index[i]].pattern_size;
        if(sequencer->playhead_index[i] + 1 > patternSize - 1){
            //printf("\n\tEOP. ");
            int nextRowIndex = arranger->playhead_indices[i] + 1;
            if(arranger->song[i][nextRowIndex] > -1){
                //printf("\n\t\tPattern Switch. \n");
                arranger->playhead_indices[i]++;
                sequencer->pattern_index[i] = arranger->song[i][nextRowIndex];
            } else {
                if(arranger->loop){
                    //printf("\n\t\tLoop. \n");
                    arranger->playhead_indices[i] = 0;
                } else {
                    //printf("\n\t\tEnd. \n");
                    sequencer->running[i] = 0;
                }
            }
        }
        if(sequencer->pattern_index[i] > -1){
            sequencer->playhead_index[i] = (sequencer->playhead_index[i] + 1) % patternList->patterns[sequencer->pattern_index[i]].pattern_size;
        }
    }
    
}
removeChannel()
void removeChannel (Arranger * arranger, int channelIndex)
Removes a channel from the Arranger at the specified index.
Parameters
arranger Pointer to the Arranger.
channelIndex Index of the channel to remove.
                                                         {
    // Check if the channel index is valid
    if (channelIndex < 0 || channelIndex >= arranger->enabledChannels) {
        printf("\t ERROR: invalid channel index %d (enabled channels: %d).\n", channelIndex, arranger->enabledChannels);
        return;
    }
    // Shift channels to the left if necessary
    if (channelIndex < arranger->enabledChannels - 1) {
        memmove(arranger->song[channelIndex], arranger->song[channelIndex + 1], (arranger->enabledChannels - channelIndex - 1) * MAX_SONG_LENGTH * sizeof(int));
    }
    arranger->enabledChannels--;
}
selectArrangerCell()
int * selectArrangerCell (Arranger * arranger, int checkBlankPattern, int relativex, int relativey, int * selectedArrangerCell)
Selects a cell in the Arranger and updates the selected coordinates.
Parameters
arranger Pointer to the Arranger.
checkBlankPattern Whether to check for blank patterns.
relativex Relative x-coordinate offset.
relativey Relative y-coordinate offset.
selectedArrangerCell Array to store the selected coordinates.
Returns
Pointer to the selected coordinates.
                                                                                                                           {
    int newx, newy;
    newx = arranger->selected_x + relativex;
    newy = arranger->selected_y + relativey;
    if(newx > arranger->enabledChannels - 1){
        newx = arranger->enabledChannels - 1;
    }
    if(newx < 0){
        newx = 0;
    }
    if(newy > MAX_SONG_LENGTH - 1){
        newy = MAX_SONG_LENGTH - 1;
    }
    if(newy < 0){
        newy = 0;
    }
    if(arranger->song[newx][newy] != -1 || !checkBlankPattern){
        arranger->selected_x = newx;
        arranger->selected_y = newy;
    }
    selectedArrangerCell[0] = arranger->selected_x;
    selectedArrangerCell[1] = arranger->selected_y;
    //printf("SELECTED: %i,%i\n", selectedArrangerCell[0], selectedArrangerCell[1]);
    return selectedArrangerCell;
}
Referenced by main().
selectStep()
int selectStep (PatternList * patternList, int patternIndex, int selectedStep)
Selects a step in a pattern and ensures it is within bounds.
Parameters
patternList Pointer to the PatternList.
patternIndex Index of the pattern.
selectedStep Index of the step to select.
Returns
The selected step index.
                                                                            {
    int sequenceLength = patternList->patterns[patternIndex].pattern_size;
    if(selectedStep >= sequenceLength){
        selectedStep = sequenceLength - 1;
    }
    if(selectedStep < 0){
        selectedStep = 0;
    }
    return selectedStep;
}
Referenced by main().
startPlaying()
void startPlaying (Sequencer * sequencer, PatternList * patternList, Arranger * arranger, int playMode)
Starts playback in the Sequencer and Arranger from the current cursor position, resetting all pattern playback posiitons.
Parameters
sequencer Pointer to the Sequencer.
patternList Pointer to the PatternList.
arranger Pointer to the Arranger.
playMode Playback mode.
                                                                                                   {
    arranger->playing = 1;
    int playRow = arranger->selected_x;
    for(int i = 0; i < arranger->enabledChannels; i++){
        arranger->playhead_indices[i] = playRow;
        sequencer->playhead_index[i] = 0;
        sequencer->pattern_index[i] = arranger->song[i][playRow];
        if(sequencer->pattern_index[i] == -1){
            sequencer->running[i] = 0;
        } else {
            sequencer->running[i] = 1;
        }
    }
}
Referenced by main().
stopPlaying()
void stopPlaying (Arranger * arranger)
Stops playback in the Arranger.
Parameters
arranger Pointer to the Arranger.
                                    {
    arranger->playing = 0;
}
Referenced by main().