voice.h File Reference
#include <stdlib.h>
#include "settings.h"
#include "oscillator.h"
#include "sample.h"
#include "notes.h"
#include "modsystem.h"
#include "blit_synth.h"
Data Structures
struct Voice
struct VoiceManager
struct Instrument
Macros
#define MAX_VOICES_PER_CHANNEL 6
#define MAX_LFOS 8
#define MAX_ENVELOPES 8
Enumerations
enum VoiceType { VOICE_TYPE_OSCILLATOR
, VOICE_TYPE_SAMPLE
, VOICE_TYPE_FM
, VOICE_TYPE_BLEP
 }
enum InstrumentType { IT_OSCILLATOR
, IT_SAMPLE
, IT_FM
, IT_BLEP
 }
Functions
VoiceManager * createVoiceManager ()
void initVoicePool (VoiceManager *vm, int seqChannel, int voiceCount, VoiceType vt)
void initialize_voice (Voice *voice, VoiceType voiceType, Sample *sample)
void initialize_voice_sample (Voice *voice, Sample sample, int voice_id, ModList *modList)
void initialize_voice_blep (Voice *voice, int voice_id, ModList *modList)
void initialize_voice_fm (Voice *voice, int voice_id, ModList *modList)
void init_instrument (Instrument *instrument, Sample *sample)
Macro Definition Documentation
MAX_ENVELOPES
#define MAX_ENVELOPES 8
MAX_LFOS
#define MAX_LFOS 8
MAX_VOICES_PER_CHANNEL
#define MAX_VOICES_PER_CHANNEL 6
Referenced by initVoicePool().
Enumeration Type Documentation
InstrumentType
enum InstrumentType
Enumerator
IT_OSCILLATOR
IT_SAMPLE
IT_FM
IT_BLEP
             {
    IT_OSCILLATOR,
    IT_SAMPLE,
    IT_FM,
    IT_BLEP
} InstrumentType;
VoiceType
enum VoiceType
Enumerator
VOICE_TYPE_OSCILLATOR
VOICE_TYPE_SAMPLE
VOICE_TYPE_FM
VOICE_TYPE_BLEP
             {
    VOICE_TYPE_OSCILLATOR,
    VOICE_TYPE_SAMPLE,
    VOICE_TYPE_FM,
    VOICE_TYPE_BLEP
} VoiceType;
Function Documentation
createVoiceManager()
VoiceManager * createVoiceManager ()
                                  {
    VoiceManager* vm = (VoiceManager*)malloc(sizeof(VoiceManager));
    for(int i = 0; i < MAX_SEQUENCER_CHANNELS; i++){
        vm->voiceCount[i] = 0;
    }
    return vm;
}
init_instrument()
void init_instrument (Instrument * instrument, Sample * sample)
                                                             {
    instrument = (Instrument*)malloc(sizeof(Instrument));
    instrument->sample = sample;
}
Referenced by main().
initialize_voice()
void initialize_voice (Voice * voice, VoiceType voiceType, Sample * sample)
                                                                         {
    voice->left_phase = 0.0f;
    voice->right_phase = 0.0f;
    voice->note[0] = OFF;
    voice->note[1] = 0;
    voice->paramList = createParamList();
    voice->modList = createModList();
    voice->frequency = createParameter(voice->paramList, "frequency", 440.0f, 0.001f, 20000.0f);
    voice->samples_elapsed = 0;
    voice->instrument_index = 0;
    voice->active = 0;
    voice->volume = createParameter(voice->paramList, "volume", 1.0f, 0.0f, 1.0f);
    voice->type = voiceType;
    switch(voice->type){
        case VOICE_TYPE_BLEP:
            voice->env_count = 2;
            voice->envelope[0] = createAD(voice->paramList, voice->modList, .25f, .25f, "AD1");
            voice->envelope[1] = createAD(voice->paramList, voice->modList, .25f, .25f, "AD2");
            addModulation(voice->paramList, &voice->envelope[0]->base, voice->volume, 1.0f, MO_MUL);
            addModulation(voice->paramList, &voice->envelope[1]->base, voice->frequency, 400.5f, MO_ADD);
            break;
        case VOICE_TYPE_SAMPLE:
            voice->source.sample = *sample;
            voice->env_count = 1;
            voice->sample_position = 0.0f; // Initialize sample position
            voice->envelope[0] = createADSR(voice->paramList, voice->modList, 0.5f, 1.2f, 1.5f, 1.1f, "ADSR1");
            break;
        case VOICE_TYPE_FM:
            voice->source.operators[0] = createOperator(voice->paramList, 1.0f);
            voice->source.operators[1] = createOperator(voice->paramList, 2.0f);
            voice->source.operators[2] = createOperator(voice->paramList, 4.0f);
            voice->source.operators[3] = createOperator(voice->paramList, 3.0f);
            voice->sample_position = 0.0f; // Initialize sample position
            voice->env_count = 4;
            for(int i = 0; i < voice->env_count; i++){
                voice->envelope[i] = createAD(voice->paramList, voice->modList, 0.05f, 1.2f, "ADSR1");
                addModulation(voice->paramList, &voice->envelope[i]->base, voice->source.operators[i]->level, 1.0f, MO_MUL);
            }
            addModulation(voice->paramList, &voice->envelope[0]->base, voice->volume, 1.0f, MO_MUL);
            break;
        default:
            break;
    }
}
Referenced by initVoicePool(), and main().
initialize_voice_blep()
void initialize_voice_blep (Voice * voice, int voice_id, ModList * modList)
initialize_voice_fm()
void initialize_voice_fm (Voice * voice, int voice_id, ModList * modList)
initialize_voice_sample()
void initialize_voice_sample (Voice * voice, Sample sample, int voice_id, ModList * modList)
initVoicePool()
void initVoicePool (VoiceManager * vm, int seqChannel, int voiceCount, VoiceType vt)
                                                                                  {
    if(seqChannel >= MAX_SEQUENCER_CHANNELS - 1 || seqChannel < 0) seqChannel %= MAX_SEQUENCER_CHANNELS - 1;
    if(voiceCount >= MAX_VOICES_PER_CHANNEL) voiceCount = MAX_VOICES_PER_CHANNEL;
    for(int i = 0; i < voiceCount; i++){
        initialize_voice(vm->voicePools[seqChannel][i], vt, NULL);
        vm->voiceCount[seqChannel]++;
    }
}