/* gui_gui_core.c -- generated by the gui module split (lawn-mowing-gui).
 * One module per screen; shared node helpers live in gui_core.c.
 * Cross-module state/helpers: see gui_internal.h. */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "dstruct.h"
#include "raylib.h"
#include "gui.h"
#include "graph_gui.h"
#include "input.h"
#include "modsystem.h"
#include "notes.h"
#include "voice.h"
#include "io/preset_io.h"
#include "io.h"
#include "gui_internal.h"


/* ---- module state (shared with the screen modules via gui_internal.h) ---- */

GuiNode *createActionBtnGuiNode(int x, int y, int w, int h, int padding, NodeAlignment na, const char *name, bool selected, ActionCallback cb, void *ctx);

GuiNode *createDialGuiNode(int x, int y, int w, int h, int padding, NodeAlignment na, const char *name, bool selected, OnPressCallback cb, Parameter *p);

void drawActionBtnGuiNode(void *self);

void drawColourRectangle(int x, int y, int w, int h, float roundness, float line_w, bool highlighted);

void drawRotatedDial(int x, int y, int w, int h, int radius, int startAngle, int offsetAngle);

void drawValueDisplay(int x, int y, int w, int h, char *text);

void drawWrapperNode(void *self);

Font textFont;

Font symbolFont;

Font pixelFont;

ColourScheme cs;

static FontConfig gFontConfig;

static bool gThemeLoaded;

Texture2D dial;

void initCustomFont(Font *f, char *path, int charCount, int width, int height) {
	*f = LoadFontEx(path, width, NULL, charCount);
	if(f->texture.id == 0) {
		printf("Failed to load font: %s\n", path);
	} else {
		printf("Successfully loaded font: %s\n", path);
	}
}



void initDefaultColourScheme(ColourScheme *colourScheme) {
	colourScheme->backgroundColor = (Color){ 207, 110, 58, 255 };
	colourScheme->fontColour = (Color){ 99, 17, 0, 255 };
	colourScheme->secondaryFontColour = (Color){ 176, 53, 0, 255 };
	colourScheme->outlineColour = (Color){ 219, 148, 103, 255 };
	colourScheme->defaultCell = (Color){ 148, 68, 16, 255 };
	colourScheme->highlightedCell = (Color){ 214, 60, 17, 255 };
	colourScheme->selectedCell = (Color){ 235, 161, 75, 255 };
	colourScheme->blankCell = (Color){ 94, 23, 29, 255 };
	colourScheme->reddish = (Color){ 170, 38, 49, 255 };
	colourScheme->panel = (Color){ 80, 60, 60, 255 };
	colourScheme->panelBorder = (Color){ 10, 0, 0, 255 };
	colourScheme->valueDisplayBg = (Color){ 50, 40, 40, 255 };
	colourScheme->label = (Color){ 200, 180, 180, 255 };
	colourScheme->labelSelected = (Color){ 255, 180, 180, 255 };
	colourScheme->dial = (Color){ 255, 0, 0, 255 };
	colourScheme->valueText = (Color){ 255, 0, 0, 255 };
	colourScheme->vline = (Color){ 60, 255, 150, 255 };
	colourScheme->poly = (Color){ 255, 80, 80, 255 };
	colourScheme->waveformBg = (Color){ 0, 0, 0, 255 };
	colourScheme->waveform = (Color){ 255, 0, 0, 255 };
	colourScheme->waveformAlt = (Color){ 0, 255, 0, 255 };
	colourScheme->sampleBg = (Color){ 60, 10, 10, 255 };
	colourScheme->sampleAltBg = (Color){ 10, 50, 10, 255 };
	colourScheme->sampleBorder = (Color){ 200, 80, 60, 255 };
	colourScheme->stepBorder = (Color){ 80, 20, 20, 255 };
	colourScheme->stepClosed = (Color){ 80, 30, 30, 255 };
	colourScheme->arrangerPlayhead = (Color){ 255, 0, 0, 255 };
	colourScheme->arrangerCellText = (Color){ 200, 180, 180, 255 };
	colourScheme->wrapperBorder = (Color){ 10, 5, 5, 255 };
	colourScheme->modStripLfo = (Color){ 0, 255, 255, 255 };
	colourScheme->modStripEnv = (Color){ 130, 255, 130, 255 };
	colourScheme->modStripRnd = (Color){ 255, 80, 255, 255 };
	colourScheme->modStripOfs = (Color){ 190, 190, 190, 255 };
	colourScheme->modStripDefault = (Color){ 210, 210, 210, 255 };
	colourScheme->layerDim = (Color){ 0, 0, 0, 170 };
	colourScheme->spectrogramPlayhead = (Color){ 255, 0, 0, 255 };
	colourScheme->routeAdd = (Color){ 255, 120, 80, 255 };
	colourScheme->routeMul = (Color){ 120, 200, 255, 255 };
}



ColourScheme *getColourScheme() {
	return &cs;
}


void setFontConfig(const FontConfig *cfg) {
	if(!cfg) {
		return;
	}
	gFontConfig = *cfg;
}


FontConfig *getFontConfig(void) {
	return &gFontConfig;
}


void markThemeLoaded(void) {
	gThemeLoaded = true;
}



void clearBg() {
	ClearBackground(cs.backgroundColor);
}


RenderTexture2D createPresentTarget(void) {
	return LoadRenderTexture(SCREEN_W, SCREEN_H);
}

/* Task 6: window-scale keyboard controls. nextWholeScale/prevWholeScale
 * are pure step math (pinned by test_window_scale_helpers);
 * setWindowScale clamps to [0.25, 8] and resizes the window. */

static float g_windowScale = 1.0f;


float nextWholeScale(float s) {
	float n = floorf(s) + 1.0f;
	if(n < 0.25f) n = 0.25f;
	return n;
}


float prevWholeScale(float s) {
	float n = ceilf(s) - 1.0f;
	if(n < 0.25f) n = 0.25f;
	return n;
}


float getWindowScale(void) { return g_windowScale; }


void setWindowScale(float scale) {
	if(scale < 0.25f) scale = 0.25f;
	if(scale > 8.0f) scale = 8.0f;
	g_windowScale = scale;
	SetWindowSize((int)roundf(SCREEN_W * scale), (int)roundf(SCREEN_H * scale));
}


void presentFrame(RenderTexture2D gfx) {
	BeginDrawing();
	ClearBackground(BLACK);
	int sw = GetScreenWidth();
	int sh = GetScreenHeight();
	float s = fminf((float)sw / SCREEN_W, (float)sh / SCREEN_H);
	int dw = (int)(SCREEN_W * s);
	int dh = (int)(SCREEN_H * s);
	DrawTexturePro(gfx.texture, (Rectangle){ 0, 0, SCREEN_W, -SCREEN_H },
	               (Rectangle){ (sw - dw) / 2, (sh - dh) / 2, dw, dh },
	               (Vector2){ 0, 0 }, 0.0f, WHITE);
	EndDrawing();
}


void InitGUI(void) {
	const int screenWidth = SCREEN_W;
	const int screenHeight = SCREEN_H;

	if(!gThemeLoaded) {
		initDefaultColourScheme(&cs);
	}

	/* Fall back to hardcoded defaults if main() never set gFontConfig.
	 * The harness boots directly into InitGUI without going through the
	 * cfg/theme loader path, so it relies on these fallbacks. */
	if(gFontConfig.path[0] == '\0') {
		strncpy(gFontConfig.path, "resources/fonts/console.ttf", sizeof(gFontConfig.path) - 1);
		gFontConfig.path[sizeof(gFontConfig.path) - 1] = '\0';
		gFontConfig.size = 9;
		gFontConfig.spacing = 0;
	}

	SetConfigFlags(FLAG_WINDOW_RESIZABLE);
	InitWindow(screenWidth, screenHeight, "Spectrax");
	textFont = LoadFont("resources/fonts/setback.png");
	pixelFont = LoadFontEx(gFontConfig.path, gFontConfig.size, NULL, 255);
	initCustomFont(&symbolFont, "resources/fonts/iconzfin.png", 8, 10, 12);
	Image dialimg = LoadImage("resources/images/dial2.png");
	dial = LoadTextureFromImage(dialimg);
	UnloadImage(dialimg);
	SetTargetFPS(60);
}


void drawRotatedDial(int x, int y, int w, int h, int radius, int startAngle, int offsetAngle) {
	DrawCircleSector((Vector2){ x + radius, y + radius }, radius + 2, startAngle, startAngle + offsetAngle, 32, cs.dial);
	DrawTexturePro(dial, (Rectangle){ 0, 0, 48, 48 }, (Rectangle){ x + radius, y + radius, w, h }, (Vector2){ radius, radius }, startAngle + offsetAngle, WHITE);
}


void drawValueDisplay(int x, int y, int w, int h, char *text) {
	DrawRectangle(x, y, w, h, cs.valueDisplayBg);
	DrawTextEx(pixelFont, text, (Vector2){ x + 4, y + 4 }, 9, 1, cs.valueText);
}


void drawColourRectangle(int x, int y, int w, int h, float roundness, float line_w, bool highlighted) {
	/* Square panel with a drop shadow (offset by the border width)
	 * instead of the old rounded-rectangle border. The shadow is drawn
	 * first so it reads as an edge behind the panel. */
	(void)roundness;
	int o = (int)line_w;
	Color shadowColour = highlighted ? (Color){ 0, 0, 0, 200 } : (Color){ 0, 0, 0, 140 };
	DrawRectangle(x + o, y + o, w, h, shadowColour);
	DrawRectangle(x, y, w, h, cs.panel);
	if(highlighted) {
		DrawRectangleLinesEx((Rectangle){ x, y, w, h }, line_w, cs.highlightedCell);
	} else {
		DrawRectangleLinesEx((Rectangle){ x, y, w, h }, line_w, cs.panelBorder);
	}
}


void drawDialGuiNode(void *self) {
	GuiNode *gn = (GuiNode *)self;
	if(!gn->p) {
		return;
	}
	/* Use baseValue (unmodulated) so the dial reflects the user's actual
	 * setting rather than the envelope-modulated currentValue. The dial
	 * is a control surface; the modulated value is for the audio path. */
	char paramValue[50];
	snprintf(paramValue, 50, "%05.2f", gn->p->baseValue);
	float range = gn->p->maxValue - gn->p->minValue;
	float angle = 0.0f;
	if(range > 0.0f) {
		angle = (gn->p->baseValue - gn->p->minValue) / (range / 100) * 2.7;
	}
	int tmpx = gn->x;
	int tmpy = gn->y;
	drawColourRectangle(tmpx, tmpy, gn->w, gn->h, 0.125, 2.0, gn->selected);
	tmpx += gn->padding + 2;
	tmpy += gn->padding;
	/* Compact geometry so the dial + value + label stack fits the
	 * ~31px-tall cells the reflow gives the FM/envelope rows. The old
	 * 24px dial + label at +30 overflowed the cell and clipped the
	 * label into the row below (the reported unreadable control
	 * labels). 20px dial, label right under it at +22 -> 31px total. */
	drawRotatedDial(tmpx, tmpy, 20, 20, 10, -225, angle);
	tmpx += 28;
	tmpy += 2;
	drawValueDisplay(tmpx, tmpy, 38, 14, paramValue);
	DrawTextEx(pixelFont, gn->name, (Vector2){ tmpx - 28, tmpy + 18 }, 9, 1, gn->selected ? cs.labelSelected : cs.label);
}


GuiNode *createDialGuiNode(int x, int y, int w, int h, int padding, NodeAlignment na, const char *name, bool selected, OnPressCallback cb, Parameter *p) {
	GuiNode *gn = createGuiNode(x, y, w, h, padding, na, name, 1, selected);
	if(gn == NULL) {
		printf("createDialGuiNode error, could not create.");
		return NULL;
	}
	gn->callback = cb;
	gn->p = p;
	gn->drawable = true;
	gn->draw = drawDialGuiNode;
	return gn;
}


GuiNode *createActionBtnGuiNode(int x, int y, int w, int h, int padding, NodeAlignment na, const char *name, bool selected, ActionCallback cb, void *ctx) {
	GuiNode *gn = createGuiNode(x, y, w, h, padding, na, name, 1, selected);
	if(gn == NULL) {
		printf("createActionBtnGuiNode error, could not create.");
		return NULL;
	}
	gn->actionCb = cb;
	gn->actionCtx = ctx;
	gn->drawable = true;
	gn->draw = drawActionBtnGuiNode;
	return gn;
}


void drawActionBtnGuiNode(void *self) {
	GuiNode *gn = (GuiNode *)self;
	drawColourRectangle(gn->x, gn->y, gn->w, gn->h, 0.125, 2.0, gn->selected);
	Color labelColour = gn->selected ? cs.labelSelected : cs.label;
	DrawTextEx(pixelFont, gn->name, (Vector2){ gn->x + gn->padding + 4, gn->y + gn->padding + 4 }, 10, 1, labelColour);
}

/* Task 6: route-destination picker node. Same rect as a dial, but with
 * a brighter outline and the dial's name (strdup'd by cbOpenRouteLayer).
 * Selecting one and EDIT'ing fires cbRouteToDest which toggles the
 * source's route into this destination. */

void drawDiscreteDialGuiNode(void *self) {
	GuiNode *gn = (GuiNode *)self;
	if(!gn->p) {
		return;
	}
	/* baseValue (unmodulated) -- see drawDialGuiNode comment. */
	char paramValue[50];
	snprintf(paramValue, 50, "%i", (int)gn->p->baseValue);
	float range = gn->p->maxValue - gn->p->minValue;
	float angle = 0.0f;
	if(range > 0.0f) {
		angle = (gn->p->baseValue - gn->p->minValue) / (range / 100) * 2.7;
	}
	int tmpx = gn->x;
	int tmpy = gn->y;

	drawColourRectangle(tmpx, tmpy, gn->w, gn->h, 0.125, 2.0, gn->selected);
	tmpx += gn->padding;
	tmpy += gn->padding;
	/* Compact geometry -- see drawDialGuiNode. */
	drawRotatedDial(tmpx, tmpy, 20, 20, 10, -225, angle);
	tmpx += 6;
	tmpy += 5;
	drawValueDisplay(tmpx, tmpy, 10, 14, paramValue);

	DrawTextEx(pixelFont, gn->name, (Vector2){ tmpx, tmpy + 16 }, 9, 1, gn->selected ? cs.labelSelected : cs.label);
}


void drawWrapperNode(void *self) {
	GuiNode *gn = (GuiNode *)self;
	DrawRectangleRec((Rectangle){ gn->x, gn->y, gn->w, gn->h }, cs.panel);
	DrawRectangleLinesEx((Rectangle){ gn->x, gn->y, gn->w, gn->h }, 2.0, cs.wrapperBorder);
}

/* Task 3: per-instrument chip row. Drawn for each enabled channel above
 * the arranger grid. Bg colour comes from a fixed 8-colour palette keyed
 * by the arranger's per-channel labelColourIdx. Content shows V:{count}
 * top-left, type tag (FM/SMP/BLP) top-right, 8-char channel label
 * centred, current patch name bottom-left, and a voice-active light
 * bottom-right per voice in vm->voiceCount[ch].
 *
 * IMPORTANT: this MUST early-return when vm or inst is NULL — the nav
 * test in tests/dsp/test_graph_nav.c builds chips with NULL refs so it
 * can exercise the graph layout (chipRow RIGHT/DOWN navigation) without
 * needing a real VoiceManager or Instrument. */

const char *voiceTypeTag(VoiceType t) {
	switch(t) {
		case VOICE_TYPE_FM:     return "FM";
		case VOICE_TYPE_BLEP:   return "BLP";
		case VOICE_TYPE_GRAIN:  return "GRN";
		case VOICE_TYPE_SPECTRAL: return "SPC";
		case VOICE_TYPE_SAMPLE:
		default:                return "SMP";
	}
}


bool isSelectedDialNode(const Graph *g) {
	if(!g || !g->selected) return false;
	GuiNode *n = g->selected;
	/* Both continuous (drawDialGuiNode) and discrete (drawDiscreteDialGuiNode)
	 * dials expose a value-callback OnPressCallback and respond to EDIT+arrow.
	 * Some discrete dials (e.g. ROUTE) overwrite draw with the discrete variant
	 * after createDialGuiNode; both must pass the guard so the harness can
	 * drive them via the scripted EDIT<arrow> opcodes. */
	return (n->draw == drawDialGuiNode || n->draw == drawDiscreteDialGuiNode)
		&& n->callback != NULL;
}


void DrawGUI(int currentScene) {
	switch (currentScene) {
		case SCENE_ARRANGER:
			gui_arranger_draw();
			break;
		case SCENE_PATTERN:
			gui_pattern_draw();
			break;
		case SCENE_INSTRUMENT:
			gui_instrument_draw();
			break;
		default:
			break;
	}
}
