/* gui_gui_instrument.c -- generated by the gui module split (lawn-mowing-gui).
 * One module per screen; shared node helpers live in gui_core.c.
 * Cross-module state/helpers: see gui_internal.h. */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "dstruct.h"
#include "raylib.h"
#include "gui.h"
#include "graph_gui.h"
#include "gui_style.h"
#include "input.h"
#include "modsystem.h"
#include "notes.h"
#include "voice.h"
#include "io/preset_io.h"
#include "io.h"
#include "gui_internal.h"
#include "gui_inst_internal.h"

void appendFMInstControlNode(Graph *g, GuiNode *container, char *name, int weight, bool selected, Instrument *inst) {
	/* Task 5.2: the FM controls box is a ScrollContainer (rowH 35, the
	 * AD-env standard) so every per-op control — including the outLevel /
	 * pitch / gain dests that only existed on the routing layer — has a
	 * reachable base dial. Content is 5 rows (one op per row + a misc
	 * row), viewport is 3 rows, so a scrollbar appears for the last two.
	 * One op per row keeps the 5 dial labels (FEEDBACK1 etc.) from
	 * colliding, which 2 ops/row does. */
	const int fmRowH = 35;
	GuiNode *fmScroll = createScrollContainer(0, 0, 100, fmRowH * 3, fmRowH, "fm_ctrl");
	fmScroll->drawable = true;
	fmScroll->draw = drawWrapperNode;

	GuiNode *oprow[4];
	GuiNode *miscrow = createGuiNode(0, 0, 100, 100, 1, na_horizontal, "FMR5", 0, 0);
	for(int i = 0; i < 4; i++) {
		char nm[8];
		snprintf(nm, sizeof(nm), "FMR%d", i + 1);
		oprow[i] = createGuiNode(0, 0, 100, 100, 1, na_horizontal, nm, 0, 0);
	}

	GuiNode *dials[4][5]; /* per-op: ratio, feedback, level, outLevel, pitch */
	const char *labels[5] = { "RATIO", "FEEDBACK", "LEVEL", "OUTLV", "PITCH" };
	for(int i = 0; i < 4; i++) {
		Parameter *p[5];
		p[0] = inst->id.fm.ops[i]->ratio;
		p[1] = inst->id.fm.ops[i]->feedbackAmount;
		p[2] = inst->id.fm.ops[i]->level;
		p[3] = inst->id.fm.ops[i]->outLevel;
		p[4] = inst->id.fm.ops[i]->pitch;
		for(int j = 0; j < 5; j++) {
			char dname[16];
			snprintf(dname, sizeof(dname), "%s%d", labels[j], i + 1);
			bool isSel = (i == 0 && j == 0) ? selected : 0;
			dials[i][j] = createDialGuiNode(0, 0, 100, 100, 2, na_horizontal, dname, isSel, incParameterBaseValue, p[j]);
		}
	}
	GuiNode *alg = createDialGuiNode(0, 0, 100, 100, 2, na_horizontal, "ALG", 0, incParameterBaseValue, inst->id.fm.selectedAlgorithm);
	GuiNode *pan = createDialGuiNode(0, 0, 100, 100, 2, na_horizontal, "PAN", 0, incParameterBaseValue, inst->panning);
	GuiNode *gain = createDialGuiNode(0, 0, 100, 100, 2, na_horizontal, "GAIN", 0, incParameterBaseValue, inst->gain);
	alg->draw = drawDiscreteDialGuiNode;
	pan->draw = drawDiscreteDialGuiNode;
	gain->draw = drawDiscreteDialGuiNode;
	if(selected) {
		g->selected = dials[0][0];
	}

	for(int i = 0; i < 4; i++) {
		for(int j = 0; j < 5; j++) {
			appendItem(oprow[i], dials[i][j], 1);
		}
		/* Task 5.2 follow-up: the op row's arrangement (equal-width
		 * dials filling the row) is a named layout, applied from
		 * layout.json — the first module to dogfood the layout tier. */
		applyLayout(oprow[i], "fm-op-row");
		appendItem(fmScroll, oprow[i], 1);
	}

	appendItem(miscrow, alg, 1);
	appendItem(miscrow, pan, 1);
	appendItem(miscrow, gain, 1);
	applyLayout(miscrow, "fm-op-row");
	appendItem(fmScroll, miscrow, 1);

	appendItem(container, fmScroll, weight);
}


