/* gui_gui_instrument.c -- generated by the gui module split (lawn-mowing-gui).
 * One module per screen; shared node helpers live in gui_core.c.
 * Cross-module state/helpers: see gui_internal.h. */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "dstruct.h"
#include "raylib.h"
#include "gui.h"
#include "graph_gui.h"
#include "input.h"
#include "modsystem.h"
#include "notes.h"
#include "voice.h"
#include "io/preset_io.h"
#include "io.h"
#include "gui_internal.h"
#include "gui_inst_internal.h"
#include "gui_layer.h"

/* Spec #1+2: dest cells in the route picker are now outline-only — no
 * label, no fill, just an osc orange/gold rectangle. The label of the
 * dial this cell maps to is drawn by the ROUTELINES overlay (see
 * drawRouteLinesNode) on top of the selected cell so the user can still
 * read what they're about to route into. Erase mode tints the outline
 * routeMul-blue to make the destructive intent obvious. */
typedef struct DestCtx {
	Instrument *inst;
	int srcIdx;
	Parameter *dest;
} DestCtx;
static bool connFromSource(ModConnection *c, Mod *src);

/* T9: word-wrap a message to fit `r`, centred vertically. Used for the
 * function-held "tap EDIT to clear modulations for …" / "no active
 * modulations." states on the selected dest cell. */
static void drawWrappedCellText(const char *text, Rectangle r) {
	if(!text || r.width <= 4.0f || r.height <= 4.0f) {
		return;
	}
	const int fontSize = 7;
	float spacing = 0.5f;
	char buf[192];
	strncpy(buf, text, sizeof(buf) - 1);
	buf[sizeof(buf) - 1] = '\0';
	/* Split into lines that fit the rect width. */
	const int maxLines = 3;
	char *lines[maxLines];
	float widths[maxLines];
	int lineCount = 0;
	char *tok = strtok(buf, " ");
	while(tok && lineCount < maxLines) {
		char candidate[192];
		if(lineCount > 0) {
			snprintf(candidate, sizeof(candidate), "%s %s", lines[lineCount - 1], tok);
			/* re-measure the combined line */
			Vector2 m = MeasureTextEx(pixelFont, candidate, fontSize, spacing);
			if(m.x <= r.width - 4.0f) {
				/* merge into the current line */
				size_t used = strlen(lines[lineCount - 1]);
				snprintf(lines[lineCount - 1] + used, sizeof(buf) - used, " %s", tok);
				widths[lineCount - 1] = m.x;
				tok = strtok(NULL, " ");
				continue;
			}
		}
		if(lineCount >= maxLines) {
			break;
		}
		lines[lineCount] = buf; /* placeholder; replaced below */
		/* Write the token into a dedicated slot. strtok modifies buf, so
		 * copy the token into a fresh buffer owned by lines[]. */
		char *slot = strdup(tok);
		if(!slot) {
			break;
		}
		lines[lineCount] = slot;
		Vector2 m = MeasureTextEx(pixelFont, slot, fontSize, spacing);
		widths[lineCount] = m.x;
		lineCount++;
		tok = strtok(NULL, " ");
	}
	if(lineCount == 0) {
		return;
	}
	float totalH = lineCount * (fontSize + 2.0f);
	float y = r.y + (r.height - totalH) / 2.0f;
	for(int i = 0; i < lineCount; i++) {
		float x = r.x + (r.width - widths[i]) / 2.0f;
		DrawTextEx(pixelFont, lines[i], (Vector2){ x, y }, fontSize, spacing, cs.labelSelected);
		y += fontSize + 2.0f;
	}
	for(int i = 0; i < lineCount; i++) {
		free(lines[i]);
	}
}

/* S2 (user report): dest buttons that sit over the scrollable mod-wrap
 * are drawn by the picker layer, which has no scissor of its own — so a
 * row scrolled under the wrap's top edge still paints its outline over
 * the FM/preset controls above. When the dest dial lives under the
 * mod_wrap scroll container, return the wrap viewport so the caller can
 * clip the picker drawing to it. */
static GuiNode *findScrollContainerByName(GuiNode *n, const char *name);
static GuiNode *findDialNodeForParam(GuiNode *node, Parameter *p);

static bool destModWrapViewport(GuiNode *root, Parameter *dest, Rectangle *vp) {
	if(!root || !dest || !vp) {
		return false;
	}
	GuiNode *wrap = findScrollContainerByName(root, "mod_wrap");
	if(!wrap) {
		return false;
	}
	GuiNode *dial = findDialNodeForParam(root, dest);
	GuiNode *p = dial;
	while(p && p != wrap) {
		p = p->container;
	}
	if(!p) {
		return false;
	}
	ScrollContainer *sc = (ScrollContainer *)wrap;
	vp->x = (float)sc->base.x;
	vp->y = (float)sc->base.y;
	vp->width = (float)sc->base.w;
	vp->height = (float)sc->base.h;
	return true;
}

static void drawRouteDestNode(void *self) {
	GuiNode *gn = (GuiNode *)self;
	if(!gn) {
		return;
	}
	(void)drawColourRectangle; /* intentionally unused now */
	DestCtx *dc = (DestCtx *)gn->actionCtx;
	Rectangle r = { gn->x, gn->y, gn->w, gn->h };
	float thickness = gn->selected ? 3.0f : 2.0f;

	/* S2: destination buttons inside the scrollable mod container must
	 * not paint over unrelated UI when their dial has scrolled out of
	 * view. Per-dest BeginScissorMode() here is NOT an option: raylib's
	 * batch flushes on every scissor switch mid-layer-draw, which
	 * corrupts the translucent layer dim + every other queued draw in
	 * the same frame (the dim stopped covering the screen above the
	 * wrap, and FM-area dest buttons vanished). Instead skip the draw
	 * outright when the dest's dial sits fully outside the wrap
	 * viewport. */
	bool occluded = false;
	{
		Rectangle vp = { 0, 0, 0, 0 };
		Graph *bg = getSelectedInstGraph();
		if(bg && bg->root && dc && dc->dest && destModWrapViewport(bg->root, dc->dest, &vp)) {
			if(r.y + r.height <= vp.y || r.y >= vp.y + vp.height) {
				occluded = true;
			}
		}
	}
	if(occluded) {
		return;
	}

	/* T9: KM_FUNCTION held (g_routeErase is set each frame from the
	 * held state) overrides the visuals — every dest shows whether it is
	 * routed or not; the selected one gets the instruction text. */
	if(g_routeErase && dc && dc->inst && dc->dest && dc->srcIdx >= 0 && dc->srcIdx < modSourceCount(dc->inst->modList)) {
		int mi = modIndexAt(dc->inst->modList, dc->srcIdx);
		Mod *src = (mi >= 0) ? dc->inst->modList->mods[mi] : NULL;
		bool routed = src && connFromSource(dc->dest->modulators, src);
		if(routed) {
			/* routed: oscillate bright↔dark red */
			float k = 0.5f + 0.5f * sinf(GetTime() * 6.0f);
			Color red = { 200, 30, 30, 255 };
			red.r = (unsigned char)(120 + 135 * k);
			DrawRectangleLinesEx(r, thickness, red);
			if(gn->selected && src && src->name && dc->dest->name) {
				char msg[160];
				snprintf(msg, sizeof(msg), "tap EDIT to clear modulations for %s_%s", src->name, dc->dest->name);
				drawWrappedCellText(msg, r);
			}
			return;
		}
		/* unrouted: static dim green + text */
		DrawRectangleLinesEx(r, thickness, (Color){ 60, 110, 60, 255 });
		if(gn->selected) {
			drawWrappedCellText("no active modulations.", r);
		}
		return;
	}

	/* T10: KM_EDIT held on a ROUTED dest — draw a semi-transparent amount
	 * dial at the cell (the function-held states above take precedence;
	 * when both are held the erase visuals win). */
	if(g_pickerEditHeld && gn->selected && dc && dc->inst && dc->dest &&
	   dc->srcIdx >= 0 && dc->srcIdx < modSourceCount(dc->inst->modList)) {
		int mi = modIndexAt(dc->inst->modList, dc->srcIdx);
		Mod *src = (mi >= 0) ? dc->inst->modList->mods[mi] : NULL;
		ModConnection *conn = NULL;
		if(src) {
			for(ModConnection *c = dc->dest->modulators; c; c = c->next) {
				if(connFromSource(c, src)) {
					conn = c;
					break;
				}
			}
		}
		if(conn) {
			float amt = conn->amount ? getParameterValue(conn->amount) : 1.0f;
			Vector2 ctr = { r.x + r.width / 2.0f, r.y + r.height / 2.0f };
			float radius = (r.width < r.height ? r.width : r.height) * 0.5f;
			Color dialCol = getColourScheme()->routeAdd;
			dialCol.a = 150;
			float sweep = (amt / 2.0f) * 360.0f; /* amount 0..2 -> 0..360 */
			DrawRing(ctr, radius * 0.55f, radius, 90.0f, 90.0f + sweep, 32, dialCol);
			DrawRing(ctr, radius * 0.55f, radius, 0.0f, 360.0f, 32, (Color){ 255, 255, 255, 40 });
			char buf[16];
			snprintf(buf, sizeof(buf), "%.2f", amt);
			Vector2 m = MeasureTextEx(pixelFont, buf, 7, 1);
			DrawTextEx(pixelFont, buf, (Vector2){ ctr.x - m.x / 2.0f, ctr.y - m.y / 2.0f }, 7, 1, (Color){ 255, 255, 255, 220 });
			return;
		}
	}

	/* Default selected visual: green oscillation between labelSelected
	 * and a brighter mix (unless the function-held states above apply). */
	Color outline;
	if(gn->selected) {
		float k = 0.5f + 0.5f * sinf(GetTime() * 4.0f);
		Color base = cs.labelSelected;
		int br = (int)base.r + 40;
		int bg = (int)base.g + 40;
		int bb = (int)base.b + 40;
		outline.r = (unsigned char)(base.r + ((br > 255 ? 255 : br) - base.r) * k);
		outline.g = (unsigned char)(base.g + ((bg > 255 ? 255 : bg) - base.g) * k);
		outline.b = (unsigned char)(base.b + ((bb > 255 ? 255 : bb) - base.b) * k);
		outline.a = 255;
	} else {
		outline = cs.routeAdd;
	}
	DrawRectangleLinesEx(r, thickness, outline);
}



void addRuntimeSource(Instrument *inst) {
	if(!inst || !inst->modList || modSourceCount(inst->modList) >= MAX_ENVELOPES) {
		return;
	}
	/* Task 8: the audio thread iterates inst->paramList/modList every
	 * buffer; hold the rebuilding flag while we mutate the lists. The
	 * audio lock closes the flag's check-then-use race. */
	pthread_mutex_lock(&g_audioLock);
	inst->rebuilding = true;
	Mod *env = createAD(inst->paramList, inst->modList, 0.25f, 4.25f, "AD+");
	/* Task 3 fix: mirror the freshly-created envelope into inst->envelopes[]
	 * BEFORE syncing envelopeCount, so the old builder's rebuildInstrumentGraph
	 * call below can dereference inst->envelopes[envIndex] safely. Task 4 will
	 * replace this builder with a modList-based one and the mirror goes away. */
	if(env && inst->envelopeCount < MAX_ENVELOPES) {
		inst->envelopes[inst->envelopeCount] = env;
	}
	/* Task 3: envelopeCount tracks the SOURCE count (non-atten) so the
	 * harness ASSERT envcount + the voice aliasing stay aligned even
	 * though the modList also holds connection attenuators. */
	inst->envelopeCount = modSourceCount(inst->modList);
	/* Task 2.4: structural mutations re-clone every voice's mod graph. */
	if(inst->vm) {
		rebuildVoicesForInstrument(inst->vm, inst);
	}
	rebuildInstrumentGraph();
	inst->rebuilding = false;
	pthread_mutex_unlock(&g_audioLock);
}


void removeSource(Instrument *inst, int srcIndex) {
	if(!inst || !inst->modList) {
		return;
	}
	/* `srcIndex` is a SOURCE position (0-based over non-atten mods). Core
	 * sources (0..coreEnvelopeCount-1) are protected; runtime sources can
	 * be removed. Resolve to the modList index (attenuators interleave). */
	if(srcIndex < inst->coreEnvelopeCount || srcIndex >= modSourceCount(inst->modList)) {
		return;
	}
	int mi = modIndexAt(inst->modList, srcIndex);
	if(mi < 0) {
		return;
	}
	/* Task 8: hold the rebuilding flag while we mutate + free from the
	 * modList/paramList the audio thread iterates. The audio lock
	 * closes the flag's check-then-use race. */
	pthread_mutex_lock(&g_audioLock);
	inst->rebuilding = true;
	removeMod(inst->modList, inst->paramList, inst->modList->mods[mi]);
	/* Task 3 fix: clear the mirror slot so the old builder's
	 * rebuildInstrumentGraph does not deref a freed envelope. Task 4 will
	 * remove the mirror entirely when it replaces the builder. */
	if(mi < MAX_ENVELOPES) {
		inst->envelopes[mi] = NULL;
	}
	/* Task 3: keep envelopeCount synced with the source count. */
	inst->envelopeCount = modSourceCount(inst->modList);
	/* Task 2.4: structural mutations re-clone every voice's mod graph. */
	if(inst->vm) {
		rebuildVoicesForInstrument(inst->vm, inst);
	}
	rebuildInstrumentGraph();
	inst->rebuilding = false;
	pthread_mutex_unlock(&g_audioLock);
}


void removeSelectedSource(void) {
	if(!igui || !igui->vm || !igui->selectedInstrument) {
		return;
	}
	GuiNode *sel = getSelectedInstGraph()->selected;
	if(!sel) {
		return;
	}
	GuiNode *n = sel;
	while(n && n->container) {
		if(strcmp(n->container->name, "mod_wrap") == 0) {
			int idx = 0;
			ListElement *l = n->container->items->head;
			while(l && *(GuiNode **)l->data != n) {
				idx++;
				l = l->next;
			}
			Instrument *inst = igui->vm->instruments[*igui->selectedInstrument];
			/* idx - 1: account for the mod-wrap header row that Task 4
			 * adds. With the header absent the mapping currently
			 * under-counts by 1; that is intentional and matches the
			 * brief's transitional note. */
			removeSource(inst, idx - 1);
			return;
		}
		n = n->container;
	}
}

/* Compatibility wrapper — preserves the no-header mapping that existed
 * before Task 3, used by callers that have not yet been ported to the
 * header-offset index used by removeSelectedSource. */

void removeSelectedEnvelope(void) {
	if(!igui || !igui->vm || !igui->selectedInstrument) {
		return;
	}
	GuiNode *sel = getSelectedInstGraph()->selected;
	if(!sel) {
		return;
	}
	GuiNode *n = sel;
	while(n && n->container) {
		if(strcmp(n->container->name, "mod_wrap") == 0) {
			int idx = 0;
			ListElement *l = n->container->items->head;
			while(l && *(GuiNode **)l->data != n) {
				idx++;
				l = l->next;
			}
			Instrument *inst = igui->vm->instruments[*igui->selectedInstrument];
			if(idx < inst->envelopeCount) {
				removeSource(inst, idx);
			}
			return;
		}
		n = n->container;
	}
}


static void freeModStripGuiNode(void *self) {
	ModStripGuiNode *msgn = (ModStripGuiNode *)self;
	freeModStrip(&msgn->strip);
	vizfxUnregisterModStrip(msgn->channel);
}

static void drawModStripGuiNode(void *self) {
	ModStripGuiNode *msgn = (ModStripGuiNode *)self;
	GuiNode *gn = (GuiNode *)msgn;
	drawModStrip(&msgn->strip, (Rectangle){ gn->x, gn->y, gn->w, gn->h });
}


ModStripGuiNode *createModStripGuiNode(int x, int y, int w, int h, VoiceManager *vm, int channel) {
	ModStripGuiNode *msgn = malloc(sizeof(ModStripGuiNode));
	GuiNode *gn = (GuiNode *)msgn;
	if(!initGuiNode(gn, x, y, w, h, 0, na_horizontal, "modstrip", 0, 0)) {
		printf("ModStripGuiNode init problem.\n");
		free(msgn);
		return NULL;
	}
	initModStrip(&msgn->strip, vm->voicePools[channel], vm->voiceCount[channel], w, h);
	msgn->channel = channel;
	gn->drawable = true;
	gn->draw = drawModStripGuiNode;
	gn->destructor = freeModStripGuiNode;
	vizfxRegisterModStrip(channel, &msgn->strip);
	return msgn;
}

/* Task 4: Unified mod-source container. Each entry row in the mod-wrap
 * represents one Mod (core envelope or runtime envelope/LFO/RND). The
 * wrap is rebuilt from inst->modList, so the type-changing cbCycleSourceType
 * + addRuntimeSource + removeSource trio all funnel through the same
 * modList->count sync path. The header row (MODS + ADD) at index 0
 * makes removeSelectedSource's `idx - 1` mapping correct. */
typedef struct {
	Instrument *inst;
	int idx;
} SourceCtx;

static SourceCtx g_sourceCtx[MAX_ENVELOPES];

/* g_destCtx and the picker's dest buttons are built in cbOpenRouteLayer
 * and read by cbRouteToDest + the probe helper. */
static DestCtx g_destCtx[MAX_PARAMS];


/* Spec #4+#5: gradient + label overlay. The gradient renderer needs the
 * runtime source so it can map MO_ADD vs MO_MUL onto the warm/cool
 * endpoints of each line. drawRouteLinesNode is the only consumer. */
typedef struct {
	Instrument *inst;
	int srcIdx;
	Mod *srcMod;
} RouteLinesCtx;

static RouteLinesCtx g_routeLinesCtx;


static void cbRouteToDest(void *ctx);
static bool connFromSource(ModConnection *c, Mod *src);
typedef struct DestCtx DestCtx;
static int findRouteButtonRect(GuiNode *root, Rectangle *out);
static GuiNode *findDialNodeForParam(GuiNode *node, Parameter *p);
void cbOpenRouteLayer(void *ctx);

/* Probe helper: returns true when running under the --probe-route
 * diagnostic. Tests that link gui_inst_mod.c without main.c get a
 * weak fallback that always returns false. */
#include "main.h"
__attribute__((weak)) bool isProbeRouteActive(void);

static void refreshSourceCtx(Instrument *inst) {
	for(int i = 0; i < MAX_ENVELOPES; i++) {
		g_sourceCtx[i].inst = inst;
		g_sourceCtx[i].idx = i;
	}
}

/* Re-point a captured SourceCtx (ROUTE / DEL / clear-all entry) at the
 * CURRENTLY DISPLAYED instrument and validate its idx against that
 * instrument's modList. The captured ctx can be NULL or stale: boot
 * graphs are built by createInstrumentGui BEFORE igui is assigned (so
 * the selected-channel refresh inside appendModSourceEntry never runs),
 * and switching channels does not rebuild the graphs. The pressed button
 * always lives in the displayed graph, so the route target is the
 * displayed instrument — sc->idx indexes its modList because the graph's
 * rows are rebuilt on every modList mutation. */
static Instrument *resolveSourceCtx(SourceCtx *sc) {
	InstrumentGui *ig = igui;
	if(!ig || !sc) {
		return NULL;
	}
	Instrument *inst = ig->vm->instruments[*ig->selectedInstrument];
	if(!inst || !inst->modList) {
		return NULL;
	}
	sc->inst = inst;
	/* `idx` is a SOURCE position (0-based over non-atten mods). Validate
	 * against the source count; consumers resolve to a modList index via
	 * modIndexAtSource(). */
	if(sc->idx < 0 || sc->idx >= modSourceCount(inst->modList)) {
		return NULL;
	}
	return inst;
}

/* Resolve a SourceCtx source-position to a modList index (skipping the
 * connection-internal attenuators addModulation interleaves). -1 if the
 * position is out of range for the displayed instrument. */
static int scModIndex(const SourceCtx *sc) {
	InstrumentGui *ig = igui;
	if(!ig || !sc) {
		return -1;
	}
	Instrument *inst = ig->vm->instruments[*ig->selectedInstrument];
	if(!inst || !inst->modList) {
		return -1;
	}
	return modIndexAt(inst->modList, sc->idx);
}

/* The actual Mod for a SourceCtx, or NULL. Uses sc->inst if set,
 * else resolves the displayed instrument's modList by source position. */
static Mod *scMod(const SourceCtx *sc) {
	if(!sc) {
		return NULL;
	}
	Instrument *inst = sc->inst;
	if(!inst || !inst->modList) {
		InstrumentGui *ig = igui;
		if(!ig) {
			return NULL;
		}
		inst = ig->vm->instruments[*ig->selectedInstrument];
		if(!inst || !inst->modList) {
			return NULL;
		}
	}
	int mi = modIndexAt(inst->modList, sc->idx);
	if(mi < 0) {
		return NULL;
	}
	return inst->modList->mods[mi];
}

/* N1 (user report): when a ROUTE picker closes via a mutation that
 * rebuilds the base graph, the rebuild resets the base selection to the
 * boot node (RATIO1). Find the source's ROUTE button in the freshly
 * built graph (its actionCtx is the &g_sourceCtx[idx] slot the builder
 * just refreshed) and put the cursor back on it. */
static GuiNode *findSourceRouteNode(GuiNode *n, int srcIdx) {
	if(!n) {
		return NULL;
	}
	if(n->actionCb == cbOpenRouteLayer && n->actionCtx) {
		SourceCtx *sc = (SourceCtx *)n->actionCtx;
		if(sc->idx == srcIdx) {
			return n;
		}
	}
	if(n->itemCount > 0 && n->items) {
		ListElement *e = n->items->head;
		for(int i = 0; i < n->itemCount; i++) {
			GuiNode *hit = findSourceRouteNode(*(GuiNode **)e->data, srcIdx);
			if(hit) {
				return hit;
			}
			e = e->next;
		}
	}
	return NULL;
}

static int findSourceRouteRect(GuiNode *root, int srcIdx, Rectangle *out) {
	GuiNode *n = findSourceRouteNode(root, srcIdx);
	if(!n || !out) {
		return 0;
	}
	*out = (Rectangle){ n->x, n->y, n->w, n->h };
	return 1;
}

static void reselectSourceRoute(int srcIdx) {
	Graph *base = getSelectedInstGraph();
	if(!base || !base->root) {
		return;
	}
	GuiNode *btn = findSourceRouteNode(base->root, srcIdx);
	if(btn) {
		changeGraphSelection(base, btn);
	}
}


/* Probe-only helper: wire the most recently added runtime source into
 * the first few routable parameters of the selected instrument. Wires
 * up to PROBE_ROUTE_COUNT destinations (skipping the ALGO parameter
 * which is a discrete selector). Returns the number of modulations
 * added. Gated behind g_probeRoute from main.c (zero effect when
 * --probe-route is absent). */
#define PROBE_ROUTE_COUNT 4
int probePickFirstRoute(void) {
	InstrumentGui *ig = igui;
	if(!ig || !ig->vm) {
		return 0;
	}
	Instrument *inst = ig->vm->instruments[*ig->selectedInstrument];
	if(!inst || !inst->modList || !inst->paramList) {
		return 0;
	}
	int srcIdx = inst->modList->count - 1;
	if(srcIdx < 0) {
		return 0;
	}
	Mod *m = inst->modList->mods[srcIdx];
	/* Skip attenuators (connection-internal nodes) — pick the last
	 * real source so the probe's routes draw via a visible row. */
	while(m && m->type == MT_ATTEN && srcIdx > 0) {
		srcIdx--;
		m = inst->modList->mods[srcIdx];
	}
	if(!m || m->type == MT_ATTEN) {
		return 0;
	}
	int added = 0;
	for(int i = 0; i < inst->paramList->count && added < PROBE_ROUTE_COUNT; i++) {
		Parameter *dest = inst->paramList->params[i];
		if(!dest) {
			continue;
		}
		if(dest->modulator_count > 0) {
			continue;
		}
		if(!addModulation(inst->paramList, inst->modList, m, dest, 1.0f, MO_ADD)) {
			continue;
		}
		added++;
	}
	if(added == 0) {
		return 0;
	}
	/* Point the gradient overlay at this source so the line + end-
	 * circles actually render. */
	g_routeLinesCtx.inst = inst;
	g_routeLinesCtx.srcIdx = srcIdx;
	g_routeLinesCtx.srcMod = m;
	return added;
}

/* Spec #3 (picker bookkeeping): how many ROUTE picker layers are
 * currently open. Bumped in cbOpenRouteLayer, decremented in any path
 * that closes one. Used by cbRouteToDest's rebuild path so a single
 * EDIT can rebuild the ROUTE graph in place without re-pushing the
 * picker. Also used by syncRouteLinesOverlay to decide whether the
 * gradient overlay should be visible (it tracks the picker state, not
 * the ROUTE button hover). */
int g_routePickerCount = 0;

/* Spec #6 (erase mode): the second EDIT on a dest that already has a
 * route, or any dest EDIT while this flag is true, calls
 * removeModulation instead of addModulation. Toggled by guiSetRouteEraseMode
 * from the topmost ROUTE layer's input handler when the user holds the
 * erase modifier; reset to false on every ROUTE pop. */
bool g_routeErase = false;
bool g_pickerEditHeld = false;

void guiSetRouteEraseMode(bool on) {
	g_routeErase = on;
}

/* T10: per-frame KM_EDIT held state, surfaced to the picker draw so a
 * routed dest shows its amount dial while the user holds EDIT. */
void guiSetPickerEditHeld(bool on) {
	g_pickerEditHeld = on;
}

/* T11: per-connection attenuation editor, opened by a double-tap of EDIT
 * on a ROUTED destination. A mini state machine inside the picker:
 *   - arrows move focus across [amount, curve, polarity, reset];
 *   - LEFT/RIGHT adjust the amount when it is focused;
 *   - KM_EDIT fires the focused control (curve/polarity toggle, reset);
 *   - KM_FUNCTION held (or KM_SELECT) exits back to the routing layer.
 * The editor does not pop the picker — it overlays the selection. */
static bool g_attenEditorOpen = false;
static int g_attenEditorFocus = 0;
static DestCtx *g_attenEditorCtx = NULL;
static ModConnection *g_attenEditorConn = NULL;
static Mod *g_attenEditorAtten = NULL;

/* Double-tap detection: a routed dest's first EDIT press defers its
 * toggle; a second press within the window opens the editor instead. */
static double g_pickerLastEditPress = -10.0;
static bool g_pickerPendingToggle = false;
static DestCtx *g_pickerPendingCtx = NULL;

#define ATTEN_EDIT_WINDOW 0.3
#define ATTEN_AMT_MIN 0.0f
#define ATTEN_AMT_MAX 2.0f
#define ATTEN_AMT_STEP 0.1f

void guiPickerClosed(void) {
	g_attenEditorOpen = false;
	g_pickerPendingToggle = false;
	g_pickerPendingCtx = NULL;
}

static void attenEditorOpen(DestCtx *dc, Mod *src) {
	ModConnection *conn = NULL;
	for(ModConnection *c = dc->dest->modulators; c; c = c->next) {
		if(connFromSource(c, src)) {
			conn = c;
			break;
		}
	}
	g_attenEditorCtx = dc;
	g_attenEditorConn = conn;
	g_attenEditorAtten = conn ? conn->source : NULL;
	g_attenEditorFocus = 0;
	g_attenEditorOpen = true;
}

static void attenEditorAdjust(int dir) {
	if(!g_attenEditorCtx || !g_attenEditorConn) {
		return;
	}
	if(g_attenEditorFocus != 0) {
		return;
	}
	float amt = g_attenEditorConn->amount ? getParameterValue(g_attenEditorConn->amount) : 1.0f;
	amt += (float)dir * ATTEN_AMT_STEP;
	if(amt < ATTEN_AMT_MIN) {
		amt = ATTEN_AMT_MIN;
	}
	if(amt > ATTEN_AMT_MAX) {
		amt = ATTEN_AMT_MAX;
	}
	if(g_attenEditorConn->amount) {
		setParameterBaseValue(g_attenEditorConn->amount, amt);
	}
}

static void attenEditorFire(void) {
	if(!g_attenEditorAtten) {
		return;
	}
	switch(g_attenEditorFocus) {
		case 1: /* curve */
			if(g_attenEditorAtten->data.atten.attenCurve) {
				setParameterBaseValue(g_attenEditorAtten->data.atten.attenCurve,
				                     getParameterValueAsInt(g_attenEditorAtten->data.atten.attenCurve) ? 0 : 1);
			}
			break;
		case 2: /* polarity */
			if(g_attenEditorAtten->data.atten.attenPolarity) {
				setParameterBaseValue(g_attenEditorAtten->data.atten.attenPolarity,
				                     getParameterValueAsInt(g_attenEditorAtten->data.atten.attenPolarity) ? 0 : 1);
			}
			break;
		case 3: /* reset */
			if(g_attenEditorConn && g_attenEditorConn->amount) {
				setParameterBaseValue(g_attenEditorConn->amount, 1.0f);
			}
			if(g_attenEditorAtten->data.atten.attenCurve) {
				setParameterBaseValue(g_attenEditorAtten->data.atten.attenCurve, 0.0f);
			}
			if(g_attenEditorAtten->data.atten.attenPolarity) {
				setParameterBaseValue(g_attenEditorAtten->data.atten.attenPolarity, 0.0f);
			}
			break;
		default:
			break;
	}
}

/* Editor input — returns true when it consumed the frame's input. */
bool guiPickerEditorInput(InputState *is) {
	if(!g_attenEditorOpen) {
		return false;
	}
	if(isKeyHeld(is, KM_FUNCTION)) {
		g_attenEditorOpen = false;
		return true;
	}
	if(isKeyJustPressed(is, KM_SELECT)) {
		g_attenEditorOpen = false;
		return true;
	}
	if(isKeyJustPressed(is, KM_UP)) {
		g_attenEditorFocus = (g_attenEditorFocus + 3) % 4;
		return true;
	}
	if(isKeyJustPressed(is, KM_DOWN)) {
		g_attenEditorFocus = (g_attenEditorFocus + 1) % 4;
		return true;
	}
	if(isKeyJustPressed(is, KM_LEFT)) {
		attenEditorAdjust(-1);
		return true;
	}
	if(isKeyJustPressed(is, KM_RIGHT)) {
		attenEditorAdjust(1);
		return true;
	}
	if(isKeyJustPressed(is, KM_EDIT)) {
		attenEditorFire();
		return true;
	}
	return true;
}

/* Held-adjust (user report): the T10 amount dial is not just a readout —
 * while KM_EDIT is HELD on a routed dest, LEFT/RIGHT change the
 * connection's amount instead of navigating the picker (the dial is a
 * control surface). The double-tap editor (guiPickerEditorInput, above)
 * owns the full curve/polarity/reset panel and takes precedence when
 * open. Returns true when it consumed the frame's input. */
bool guiPickerHeldAmountAdjust(InputState *is) {
	if(g_attenEditorOpen || !g_pickerEditHeld) {
		return false;
	}
	InstrumentGui *ig = igui;
	if(!ig) {
		return false;
	}
	Layer *route = findLayerByName(&ig->overlayLayers, "ROUTE");
	if(!route || !route->graph || !route->graph->selected) {
		return false;
	}
	GuiNode *sel = route->graph->selected;
	DestCtx *dc = (sel && sel->actionCb == cbRouteToDest) ? (DestCtx *)sel->actionCtx : NULL;
	if(!dc || !dc->inst || !dc->dest || dc->srcIdx < 0 || dc->srcIdx >= modSourceCount(dc->inst->modList)) {
		return false;
	}
	int mi_ = modIndexAt(dc->inst->modList, dc->srcIdx); Mod *src = (mi_ >= 0) ? dc->inst->modList->mods[mi_] : NULL;
	if(!src) {
		return false;
	}
	ModConnection *conn = NULL;
	for(ModConnection *c = dc->dest->modulators; c; c = c->next) {
		if(connFromSource(c, src)) {
			conn = c;
			break;
		}
	}
	if(!conn || !conn->amount) {
		return false;
	}
	int dir = 0;
	float step = ATTEN_AMT_STEP;
	if(isKeyJustPressed(is, KM_LEFT)) {
		dir = -1;
	}
	if(isKeyJustPressed(is, KM_RIGHT)) {
		dir = 1;
	}
	if(isKeyJustPressed(is, KM_UP)) {
		dir = 1;
		step = 0.5f;
	}
	if(isKeyJustPressed(is, KM_DOWN)) {
		dir = -1;
		step = 0.5f;
	}
	if(dir == 0) {
		return false;
	}
	float amt = getParameterValue(conn->amount) + (float)dir * step;
	if(amt < ATTEN_AMT_MIN) {
		amt = ATTEN_AMT_MIN;
	}
	if(amt > ATTEN_AMT_MAX) {
		amt = ATTEN_AMT_MAX;
	}
	setParameterBaseValue(conn->amount, amt);
	return true;
}

/* Deferred toggle: fires the routed dest's remove ~0.3s after a single
 * EDIT tap that was NOT followed by a double-tap. */
void guiPickerUpdateDeferred(void) {
	if(!g_pickerPendingToggle || !g_pickerPendingCtx) {
		return;
	}
	if(GetTime() - g_pickerLastEditPress < ATTEN_EDIT_WINDOW) {
		return;
	}
	/* R4 (user report): if EDIT is STILL held when the double-tap window
	 * expires, this is the T10 readout hold (KM_EDIT-held amount dial),
	 * NOT a tap — cancel the deferred toggle so the picker doesn't pop
	 * out from under the user mid-hold. Only a completed tap (key
	 * released before expiry) fires the remove. */
	if(g_pickerEditHeld) {
		g_pickerPendingToggle = false;
		g_pickerPendingCtx = NULL;
		return;
	}
	DestCtx *dc = g_pickerPendingCtx;
	g_pickerPendingToggle = false;
	g_pickerPendingCtx = NULL;
	InstrumentGui *ig = igui;
	if(!ig || !dc->inst || dc->srcIdx < 0 || dc->srcIdx >= modSourceCount(dc->inst->modList) || !dc->dest) {
		return;
	}
	int mi_ = modIndexAt(dc->inst->modList, dc->srcIdx); Mod *src = (mi_ >= 0) ? dc->inst->modList->mods[mi_] : NULL;
	if(!src) {
		return;
	}
	popLayer(&ig->overlayLayers);
	if(g_routePickerCount > 0) {
		g_routePickerCount--;
	}
	g_routeErase = false;
	pthread_mutex_lock(&g_audioLock);
	dc->inst->rebuilding = true;
	removeModulation(dc->inst->paramList, dc->inst->modList, dc->dest, src);
	if(dc->inst->vm) {
		rebuildVoicesForInstrument(dc->inst->vm, dc->inst);
	}
	rebuildInstrumentGraph();
	dc->inst->rebuilding = false;
	pthread_mutex_unlock(&g_audioLock);
	syncRouteLinesOverlay(ig);
	reselectSourceRoute(dc->srcIdx);
}

bool guiRouteEraseMode(void) {
	return g_routeErase;
}

/* Spec #3 helper: true when any non-passive layer on the stack is
 * named "ROUTE". Drives the "overlay visible" decision from the picker
 * state alone (no hover coupling) so the picker and overlay stay
 * coupled across edit/rebuild. */
static bool routePickerIsOpen(const InstrumentGui *ig) {
	if(!ig || !ig->overlayLayers.count <= 0) {
		return false;
	}
	const LayerStack *stack = &ig->overlayLayers;
	for(int i = stack->count - 1; i >= 0; i--) {
		const Layer *l = &stack->layers[i];
		if(l->name && strcmp(l->name, "ROUTE") == 0 && !l->passive) {
			return true;
		}
	}
	return false;
}

/* Task 5: delete-confirm modal for runtime mod sources.
 *
 * The DEL button on each runtime mod-source entry pushes a YES/NO confirm
 * layer. NO just pops; YES pops first (so the layer is gone before the
 * graph rebuild from removeSource reshuffles everything) and then calls
 * removeSource(inst, idx), which rebuilds the instrument graph. The
 * SourceCtx for the entry was refreshed by refreshSourceCtx() above when
 * the graph was last built, so inst+idx are still valid as long as no
 * other mutation has happened in the interim. */

static void cbDeleteCancel(void *ctx) {
	(void)ctx;
	InstrumentGui *ig = igui;
	if(ig) {
		popLayer(&ig->overlayLayers);
	}
}


static void cbDeleteConfirmYes(void *ctx) {
	SourceCtx *sc = (SourceCtx *)ctx;
	InstrumentGui *ig = igui;
	if(ig) {
		popLayer(&ig->overlayLayers);
	}
	if(sc) {
		removeSource(sc->inst, sc->idx);
	}
}

/* T12: clear-all-routes confirm. KM_FUNCTION+KM_EDIT on a source's ROUTE
 * button pushes a confirm layer ("clear all modulations for ENV_xyz?")
 * with NO selected by default; YES removes every route FROM that source
 * (attenuator-aware) and rebuilds. */
static char g_clearAllMsg[96];

static void drawClearAllText(void *self) {
	GuiNode *gn = (GuiNode *)self;
	if(!gn || !g_clearAllMsg[0]) {
		return;
	}
	Vector2 m = MeasureTextEx(pixelFont, g_clearAllMsg, 9, 1);
	float x = gn->x + (gn->w - m.x) / 2.0f;
	float y = gn->y + (gn->h - m.y) / 2.0f;
	DrawTextEx(pixelFont, g_clearAllMsg, (Vector2){ x, y }, 9, 1, cs.labelSelected);
}

static void cbClearAllCancel(void *ctx) {
	(void)ctx;
	InstrumentGui *ig = igui;
	if(ig) {
		popLayer(&ig->overlayLayers);
	}
}

static void cbClearAllConfirmYes(void *ctx) {
	SourceCtx *sc = (SourceCtx *)ctx;
	InstrumentGui *ig = igui;
	if(ig) {
		popLayer(&ig->overlayLayers);
	}
	if(!sc || !sc->inst || sc->idx < 0 || sc->idx >= modSourceCount(sc->inst->modList)) {
		return;
	}
	Mod *src = scMod(sc);
	if(!src) {
		return;
	}
	pthread_mutex_lock(&g_audioLock);
	sc->inst->rebuilding = true;
	removeModulationsForSource(sc->inst->paramList, sc->inst->modList, src);
	if(sc->inst->vm) {
		rebuildVoicesForInstrument(sc->inst->vm, sc->inst);
	}
	rebuildInstrumentGraph();
	sc->inst->rebuilding = false;
	pthread_mutex_unlock(&g_audioLock);
	syncRouteLinesOverlay(ig);
	reselectSourceRoute(sc->idx);
}

void cbOpenClearAllLayer(void *ctx) {
	SourceCtx *sc = (SourceCtx *)ctx;
	InstrumentGui *ig = igui;
	if(!ig || !sc) {
		return;
	}
	Instrument *inst = resolveSourceCtx(sc);
	if(!inst) {
		return;
	}
	Mod *src = scMod(sc);
	if(!src || !src->name) {
		return;
	}
	snprintf(g_clearAllMsg, sizeof(g_clearAllMsg), "clear all modulations for %s?", src->name);
	Graph *g = createGraph(na_horizontal);
	const int py = (SCREEN_H - 90) / 2;
	const int px = (SCREEN_W - 300) / 2;
	GuiNode *label = createGuiNode(px, py, 300, 28, 0, na_horizontal, "CLEARALL_TEXT", 0, 0);
	label->drawable = true;
	label->draw = drawClearAllText;
	appendItem(g->root, label, 1);
	GuiNode *noBtn = createActionBtnGuiNode(px + 30, py + 44, 100, 22, 0, na_horizontal, "NO", 0, cbClearAllCancel, sc);
	noBtn->name = strdup("CLEARALL_NO");
	GuiNode *yesBtn = createActionBtnGuiNode(px + 170, py + 44, 100, 22, 0, na_horizontal, "YES", 0, cbClearAllConfirmYes, sc);
	yesBtn->name = strdup("CLEARALL_YES");
	appendItem(g->root, noBtn, 1);
	appendItem(g->root, yesBtn, 1);
	changeGraphSelection(g, noBtn);
	Layer *layer = createLayer(g, px, py, 300, 90, "CLEARALL", true, true);
	pushLayer(&ig->overlayLayers, layer);
}


static void cbDeleteSource(void *ctx) {
	SourceCtx *sc = (SourceCtx *)ctx;
	InstrumentGui *ig = igui;
	if(!ig || !sc) {
		return;
	}
	if(!resolveSourceCtx(sc)) {
		return;
	}
	Graph *g = createGraph(na_horizontal);
	const int py = (SCREEN_H - 80) / 2;
	const int px = (SCREEN_W - 280) / 2;
	GuiNode *noBtn = createActionBtnGuiNode(px + 30, py + 44, 100, 22, 0, na_horizontal, "NO", 0, cbDeleteCancel, NULL);
	noBtn->name = strdup("DELETE_NO");
	GuiNode *yesBtn = createActionBtnGuiNode(px + 150, py + 44, 100, 22, 0, na_horizontal, "YES", 0, cbDeleteConfirmYes, sc);
	yesBtn->name = strdup("DELETE_YES");
	appendItem(g->root, noBtn, 1);
	appendItem(g->root, yesBtn, 1);
	changeGraphSelection(g, noBtn);
	Layer *layer = createLayer(g, px, py, 280, 80, "DELETE", true, true);
	pushLayer(&ig->overlayLayers, layer);
}

/* Task 6: route-destination picker.
 *
 * cbOpenRouteLayer (actionCb on the ROUTE button) walks the instrument
 * graph, gathers every routable dial (a dial node = a GuiNode whose draw
 * is drawDialGuiNode or drawDiscreteDialGuiNode and whose Parameter
 * pointer is non-NULL), then pushes a dim, full-screen overlay. The
 * overlay's graph holds one selectable action-button node per routable
 * dial, named after the dial. The first dial is auto-selected so the
 * harness + a fresh player can press EDIT to route into the first dial
 * without navigating. Selecting any dest node and EDIT'ing fires
 * cbRouteToDest which toggles the source's route (add 1.0/MO_ADD or
 * remove) and pops the layer.
 *
 * Why file-static g_destCtx[]: each dest node carries a DestCtx* so the
 * actionCb can find inst + srcIdx + the dest Parameter without having
 * to walk the graph again at EDIT time. Mirrors g_sourceCtx from Task 4.
 *
 * IMPORTANT: appendItem runs reflowCoordinates, which OVERWRITES child
 * rects. We must set each dest node's x/y/w/h to the dial's rect AFTER
 * appendItem, otherwise the picking buttons overlap the dial at the dial's
 * position. set x/y/w/h here explicitly; reflow would otherwise reset
 * them to the container's last-children default. */


static void collectRoutableDialsRecurse(GuiNode *node, Parameter **outParams, GuiNode **outNodes, int cap, int *n) {
	if(!node || *n >= cap) {
		return;
	}
	/* A routable dial = draw == drawDialGuiNode || draw == drawDiscreteDialGuiNode
	 * and p != NULL (dials created with a non-NULL Parameter). */
	if(node->draw && node->p && (node->draw == drawDialGuiNode || node->draw == drawDiscreteDialGuiNode)) {
		if(*n < cap) {
			outParams[*n] = node->p;
			outNodes[*n] = node;
			(*n)++;
		}
	}
	if(node->items) {
		ListElement *le = node->items->head;
		while(le) {
			/* Items store the child pointer BY VALUE in an 8-byte block
			 * (appendItem -> appendToList copies sizeof(GuiNode*)). Read
			 * the pointer with *(GuiNode **)le->data, matching every other
			 * graph walk (freeGuiNode, collectSelectables, navigateGraph).
			 * Casting le->data directly treats the block address as the
			 * node and reads past the allocation. */
			GuiNode *cn = *(GuiNode **)le->data;
			if(cn && cn != node) {
				collectRoutableDialsRecurse(cn, outParams, outNodes, cap, n);
			}
			le = le->next;
		}
	}
}


static void collectRoutableDials(GuiNode *node, Parameter **outParams, GuiNode **outNodes, int cap, int *n) {
	*n = 0;
	collectRoutableDialsRecurse(node, outParams, outNodes, cap, n);
}


/* Spec #6: route erase mode is a temporary destructive toggle that
 * lives for the duration of one ROUTE picker open. The picker bookkeeping
 * (g_routePickerCount) is the authority on whether the overlay should be
 * pushed; cbRouteToDest is the single point where picker count, erase
 * flag, and the picked modList mutation come together. */

static void cbRouteToDest(void *ctx) {
	DestCtx *dc = (DestCtx *)ctx;
	InstrumentGui *ig = igui;
	if(!ig) {
		return;
	}
	if(!dc || !dc->inst || !dc->dest) {
		return;
	}
	/* Walk the destination's modulator chain to decide whether to add
	 * or remove. There is no public hasModulation() — the connection
	 * list is the source of truth. */
	int mi_ = modIndexAt(dc->inst->modList, dc->srcIdx); Mod *src = (mi_ >= 0) ? dc->inst->modList->mods[mi_] : NULL;
	if(!src) {
		return;
	}
	/* Spec #6: KM_FUNCTION+KM_EDIT erases mode. Hold the rebuilding
	 * flag + audio lock, walk dc->dest->modulators removing EVERY
	 * connection whose source == src, leave the picker layer open
	 * so the user can clear several destinations in a row, and
	 * skip the post-edit pop+rebuild. */
	if(g_routeErase) {
		pthread_mutex_lock(&g_audioLock);
		dc->inst->rebuilding = true;
		for(;;) {
			ModConnection *match = NULL;
			for(ModConnection *c = dc->dest->modulators; c; c = c->next) {
				if(connFromSource(c, src)) {
					match = c;
					break;
				}
			}
			if(!match) {
				break;
			}
			removeModulation(dc->inst->paramList, dc->inst->modList, dc->dest, src);
		}
		if(dc->inst->vm) {
			rebuildVoicesForInstrument(dc->inst->vm, dc->inst);
		}
		dc->inst->rebuilding = false;
		pthread_mutex_unlock(&g_audioLock);
		/* No pop, no rebuild — the picker stays open and the
		 * gradient overlay reflects the new topology next frame. */
		g_routeErase = false;
		(void)ig;
		return;
	}
	bool already = false;
	for(ModConnection *c = dc->dest->modulators; c; c = c->next) {
		if(connFromSource(c, src)) {
			already = true;
			break;
		}
	}
	/* T11: an UNROUTED dest adds immediately (single-EDIT). A ROUTED
	 * dest defers its toggle: a second EDIT within the window is a
	 * double-tap → open the attenuation editor (no route mutation); a
	 * single tap without the repeat fires the remove ~0.3s later via
	 * guiPickerUpdateDeferred. This keeps the double-tap from
	 * destroying the route on its first press. */
	if(!already) {
		popLayer(&ig->overlayLayers);
		if(g_routePickerCount > 0) {
			g_routePickerCount--;
		}
		g_routeErase = false;
		pthread_mutex_lock(&g_audioLock);
		dc->inst->rebuilding = true;
		addModulation(dc->inst->paramList, dc->inst->modList, src, dc->dest, 1.0f, MO_ADD);
		if(dc->inst->vm) {
			rebuildVoicesForInstrument(dc->inst->vm, dc->inst);
		}
		rebuildInstrumentGraph();
		dc->inst->rebuilding = false;
		pthread_mutex_unlock(&g_audioLock);
		syncRouteLinesOverlay(ig);
		reselectSourceRoute(dc->srcIdx);
		return;
	}
	{
		double now = GetTime();
		if(now - g_pickerLastEditPress < ATTEN_EDIT_WINDOW) {
			/* Double-tap on a routed dest — open the editor. */
			g_pickerPendingToggle = false;
			g_pickerPendingCtx = NULL;
			g_pickerLastEditPress = now;
			attenEditorOpen(dc, src);
			return;
		}
		g_pickerLastEditPress = now;
		g_pickerPendingToggle = true;
		g_pickerPendingCtx = dc;
	}
}

/* cbOpenRouteLayer builds the picking layer. Each routable dial becomes
 * a selectable button drawn at the dial's own x/y/w/h so the visual
 * position matches the underlying dial exactly. */

/* T8: ghost (preview) lines — a faint, desaturated line from the source's
 * ROUTE button to EVERY potential destination, so the user sees where a
 * line would land before routing. Drawn beneath the dest buttons (first
 * child of the picker graph) and beneath the real gradient route lines
 * (the ROUTELINES layer above). */
static void drawPickerGhostLines(void *self) {
	GuiNode *gn = (GuiNode *)self;
	(void)gn;
	RouteLinesCtx *rc = &g_routeLinesCtx;
	Graph *base = getSelectedInstGraph();
	if(!base || !base->root) {
		return;
	}
	Rectangle anchor = { 0, 0, 0, 0 };
	findSourceRouteRect(base->root, rc->srcIdx, &anchor);
	if(anchor.width <= 0.0f || anchor.height <= 0.0f) {
		return;
	}
	Color ghost = getColourScheme()->routeAdd;
	ghost.r = (unsigned char)((ghost.r + 128) / 2);
	ghost.g = (unsigned char)((ghost.g + 128) / 2);
	ghost.b = (unsigned char)((ghost.b + 128) / 2);
	ghost.a = 60;
	Vector2 from = { anchor.x + anchor.width / 2, anchor.y + anchor.height / 2 };
	for(int i = 0; i < g_routePickerCount && i < MAX_PARAMS; i++) {
		Parameter *dest = g_destCtx[i].dest;
		if(!dest) {
			continue;
		}
		GuiNode *dialNode = findDialNodeForParam(base->root, dest);
		if(!dialNode) {
			continue;
		}
		Vector2 to = { dialNode->x + dialNode->w / 2.0f, dialNode->y + dialNode->h / 2.0f };
		DrawLineEx(from, to, 2.0f, ghost);
	}
}


void cbOpenRouteLayer(void *ctx) {
	SourceCtx *sc = (SourceCtx *)ctx;
	InstrumentGui *ig = igui;
	if(!ig || !sc) {
		return;
	}
	Instrument *inst = resolveSourceCtx(sc);
	if(!inst) {
		return;
	}
	/* Build the destination list by walking the CURRENT instrument graph
	 * (we want the dials as they appear RIGHT NOW — before our own
	 * rebuild — so the user can see what they will route into). */
	Graph *instGraph = getSelectedInstGraph();
	if(!instGraph || !instGraph->root) {
		return;
	}
	Parameter *params[MAX_PARAMS];
	GuiNode *nodes[MAX_PARAMS];
	int n = 0;
	collectRoutableDials(instGraph->root, params, nodes, MAX_PARAMS, &n);
	if(n <= 0) {
		return;
	}
	/* One Graph holds all dest nodes. The Layer dims the rest of the
	 * screen. The first dial is selected so EDIT routes into it
	 * immediately. */
	/* The dest button's name must outlive the paramList / instrument
	 * graph — when rebuildInstrumentGraph() later frees the previous
	 * graph's nodes, params[i]->name's storage goes with it. The
	 * initial heap-copy done by createActionBtnGuiNode (via
	 * initGuiNode) already achieves that, so no further strdup is
	 * needed. */
	Graph *g = createGraph(na_vertical);
	GuiNode *firstDest = NULL;
	GuiNode *destBtns[MAX_PARAMS];
	/* T8: ghost-lines overlay node — first child so it draws beneath the
	 * dest buttons. Pinned to the full screen in Loop 2 (reflow stamps
	 * it as a band otherwise). */
	GuiNode *ghost = createGuiNode(0, 0, 100, 100, 0, na_vertical, "GHOST", 0, 0);
	ghost->drawable = true;
	ghost->draw = drawPickerGhostLines;
	appendItem(g->root, ghost, 1);
	/* Loop 1: create + append each button. Do NOT pin rects here —
	 * appendItem runs reflowCoordinates, which re-stamps x/y/w/h of
	 * EVERY child already in the container. Pinning after a single
	 * appendItem only to be over-written by the next iteration's
	 * reflow (and by every subsequent iter) leaves only the LAST
	 * button correctly aligned with its dial. */
	for(int i = 0; i < n; i++) {
		g_destCtx[i].inst = sc->inst;
		g_destCtx[i].srcIdx = sc->idx;
		g_destCtx[i].dest = params[i];
		GuiNode *destBtn = createActionBtnGuiNode(0, 0, 100, 100, 0, na_horizontal, params[i]->name, 0, cbRouteToDest, &g_destCtx[i]);
		destBtn->draw = drawRouteDestNode;
		destBtns[i] = destBtn;
		appendItem(g->root, destBtn, 1);
		if(i == 0) {
			firstDest = destBtn;
		}
	}
	/* Loop 2: now that every append has run, no further reflow will
	 * happen — pin the ghost overlay to the full screen and each
	 * button's rect to its dial's rect so the picker visually lines
	 * up with the underlying dials. */
	ghost->x = 0;
	ghost->y = 0;
	ghost->w = SCREEN_W;
	ghost->h = SCREEN_H;
	for(int i = 0; i < n; i++) {
		destBtns[i]->x = nodes[i]->x;
		destBtns[i]->y = nodes[i]->y;
		destBtns[i]->w = nodes[i]->w;
		destBtns[i]->h = nodes[i]->h;
	}
	/* N2 (user report): pick the destination CLOSEST to the source's
	 * ROUTE button rather than the first dial collected — entering the
	 * routing layer should land the cursor near where the user just
	 * was, not jump to the top of the screen. Compare centre-to-centre
	 * using the pinned dest rects. */
	{
		Rectangle anchor = { 0, 0, 0, 0 };
		findSourceRouteRect(instGraph->root, sc->idx, &anchor);
		GuiNode *closest = NULL;
		float bestD = -1.0f;
		if(anchor.width > 0.0f && anchor.height > 0.0f) {
			float ax = anchor.x + anchor.width / 2.0f;
			float ay = anchor.y + anchor.height / 2.0f;
			for(int i = 0; i < n; i++) {
				float cx = destBtns[i]->x + destBtns[i]->w / 2.0f;
				float cy = destBtns[i]->y + destBtns[i]->h / 2.0f;
				float d = (cx - ax) * (cx - ax) + (cy - ay) * (cy - ay);
				if(bestD < 0.0f || d < bestD) {
					bestD = d;
					closest = destBtns[i];
				}
			}
		}
		if(!closest) {
			closest = firstDest;
		}
		if(closest) {
			changeGraphSelection(g, closest);
		}
	}
	Layer *layer = createLayer(g, 0, 0, SCREEN_W, SCREEN_H, "ROUTE", true, true);
	pushLayer(&ig->overlayLayers, layer);
	g_routePickerCount++;
	g_routeErase = false;
	/* Spec #3: the gradient overlay rides on top of the picker so the
	 * user can see existing routes while picking. Reuse the existing
	 * sync path so this stays in lock-step with the standalone
	 * hover-driven case. */
	syncRouteLinesOverlay(ig);
}

/* Task 7: route-lines overlay. When a ROUTE button is FOCUSED (selected),
* draw colour-coded lines from the source's route button to every
 * destination dial it currently modulates. Draw-only, non-interactive. */


static int findDialRectForParam(GuiNode *node, Parameter *p, Rectangle *out) {
	if(!node || !p) {
		return 0;
	}
	if((node->draw == drawDialGuiNode || node->draw == drawDiscreteDialGuiNode) && node->p == p) {
		*out = (Rectangle){ node->x, node->y, node->w, node->h };
		return 1;
	}
	if(node->items) {
		ListElement *e = node->items->head;
		for(int i = 0; i < node->itemCount && e; i++) {
			if(findDialRectForParam(*(GuiNode **)e->data, p, out)) {
				return 1;
			}
			e = e->next;
		}
	}
	return 0;
}

/* Find the ROUTE button (actionCb == cbOpenRouteLayer) in the base graph. */

static int findRouteButtonRect(GuiNode *node, Rectangle *out) {
	if(!node) {
		return 0;
	}
	if(node->actionCb == cbOpenRouteLayer) {
		*out = (Rectangle){ node->x, node->y, node->w, node->h };
		return 1;
	}
	if(node->items) {
		ListElement *e = node->items->head;
		for(int i = 0; i < node->itemCount && e; i++) {
			if(findRouteButtonRect(*(GuiNode **)e->data, out)) {
				return 1;
			}
			e = e->next;
		}
	}
	return 0;
}


/* Spec #2 helper: find the GuiNode that hosts a given Parameter. We
 * need this so we can call dialLabelPos on it (Spec #2). */
static GuiNode *findDialNodeForParam(GuiNode *node, Parameter *p) {
	if(!node || !p) {
		return NULL;
	}
	if((node->draw == drawDialGuiNode || node->draw == drawDiscreteDialGuiNode) && node->p == p) {
		return node;
	}
	if(node->items) {
		ListElement *e = node->items->head;
		for(int i = 0; i < node->itemCount && e; i++) {
			GuiNode *r = findDialNodeForParam(*(GuiNode **)e->data, p);
			if(r) {
				return r;
			}
			e = e->next;
		}
	}
	return NULL;
}


/* Spec #4: pre-baked gradient palette. The picker draws many line
 * segments per frame from a single source to N destinations; computing
 * a fresh Color each segment was the per-frame hot spot. A 64-step LUT
 * interpolating between the routeAdd (orange) and routeMul (blue)
 * accent colours is built once on the first call and reused. The same
 * palette is used for the per-line end-circle fill. */
#define ROUTE_LINE_LUT_STEPS 64
static Color g_routeLineLut[ROUTE_LINE_LUT_STEPS];
static bool g_routeLineLutInit = false;

static void buildRouteLineLut(void) {
	if(g_routeLineLutInit) {
		return;
	}
	/* Spec #4: lerp from cs.routeAdd (warm orange) to (255,220,60)
	 * (warm yellow). Static LUT — computed once on first use. */
	Color a = cs.routeAdd;
	Color b = (Color){ 255, 220, 60, 255 };
	for(int i = 0; i < ROUTE_LINE_LUT_STEPS; i++) {
		float t = (float)i / (float)(ROUTE_LINE_LUT_STEPS - 1);
		g_routeLineLut[i] = (Color){
			(unsigned char)((float)a.r + ((float)b.r - (float)a.r) * t),
			(unsigned char)((float)a.g + ((float)b.g - (float)a.g) * t),
			(unsigned char)((float)a.b + ((float)b.b - (float)a.b) * t),
			255
		};
	}
	g_routeLineLutInit = true;
}


/* A connection is "from src" when its source IS src, or when it routes
 * through src's attenuator (MT_ATTEN with input == src). Line drawing,
 * route matching and erase/toggle detection must follow the attenuator. */
static bool connFromSource(ModConnection *c, Mod *src) {
	if(!c || !src) {
		return false;
	}
	if(c->source == src) {
		return true;
	}
	return c->source && c->source->type == MT_ATTEN && c->source->data.atten.input == src;
}


static void drawRouteLinesNode(void *self) {
	GuiNode *gn = (GuiNode *)self;
	RouteLinesCtx *rc = &g_routeLinesCtx;
	(void)gn;
	if(!rc->inst || rc->srcIdx < 0 || rc->srcIdx >= modSourceCount(rc->inst->modList)) {
		return;
	}
	int mi_ = modIndexAt(rc->inst->modList, rc->srcIdx); Mod *src = (mi_ >= 0) ? rc->inst->modList->mods[mi_] : NULL;
	Graph *base = getSelectedInstGraph();
	if(!base || !base->root) {
		return;
	}
	Rectangle anchor = { 0, 0, 0, 0 };
	findSourceRouteRect(base->root, rc->srcIdx, &anchor);
	if(anchor.width <= 0.0f || anchor.height <= 0.0f) {
		return;
	}
	buildRouteLineLut();
	Vector2 from = { anchor.x + anchor.width / 2, anchor.y + anchor.height / 2 };
	for(int i = 0; i < rc->inst->paramList->count; i++) {
		Parameter *p = rc->inst->paramList->params[i];
		if(!p) {
			continue;
		}
		ModConnection *c = p->modulators;
		while(c) {
			if(connFromSource(c, src)) {
				GuiNode *dialNode = findDialNodeForParam(base->root, p);
				if(!dialNode) {
					c = c->next;
					continue;
				}
				Rectangle r = { dialNode->x, dialNode->y, dialNode->w, dialNode->h };
				Vector2 to = { r.x + r.width / 2, r.y + r.height / 2 };
				/* Spec #4: gradient along the line via 16 DrawLineEx
				 * segments, each coloured by t along the
				 * source->dest vector. */
				const int SEGMENTS = 16;
				const float lineThickness = 2.5f;
				for(int s = 0; s < SEGMENTS; s++) {
					float t0 = (float)s / (float)SEGMENTS;
					float t1 = (float)(s + 1) / (float)SEGMENTS;
					Vector2 p0 = { from.x + (to.x - from.x) * t0, from.y + (to.y - from.y) * t0 };
					Vector2 p1 = { from.x + (to.x - from.x) * t1, from.y + (to.y - from.y) * t1 };
					int lutIdx = (int)(t0 * (float)(ROUTE_LINE_LUT_STEPS - 1));
					if(lutIdx < 0) {
						lutIdx = 0;
					}
					if(lutIdx >= ROUTE_LINE_LUT_STEPS) {
						lutIdx = ROUTE_LINE_LUT_STEPS - 1;
					}
					DrawLineEx(p0, p1, lineThickness, g_routeLineLut[lutIdx]);
				}
				/* Spec #4: end-cap circles tinted by the LUT
				 * extremes — warm orange at the source, warm yellow
				 * at the destination. */
				DrawCircleV(from, 3.5f, g_routeLineLut[0]);
				DrawCircleV(to, 3.5f, g_routeLineLut[ROUTE_LINE_LUT_STEPS - 1]);
				/* Spec #2: echo the destination dial's label on top
				 * of the dest cell using dialLabelPos, so the user
				 * can read what they're about to wire into. */
				if(p->name) {
					Vector2 labelPos = dialLabelPos(dialNode, 0, 0);
					DrawTextEx(pixelFont, p->name, labelPos, 9, 1, cs.labelSelected);
				}
				/* Skip the remaining chained connections from the
				 * same source so we don't draw the same line twice. */
				break;
			}
			c = c->next;
		}
	}
}


/* Spec #3: ROUTELINES is pushed when EITHER the ROUTE button is the
 * selected action (legacy hover) OR a ROUTE picker is currently open.
 * The picker count is the authority on the latter case — we don't
 * try to re-derive it from the layer stack to keep this loop free of
 * graph-walk logic. When the picker is open the overlay rides on top
 * of the picker so the user can see existing routes while picking.
 * The overlay is passive (transparent to input) so ROUTE stays modal. */
void syncRouteLinesOverlay(InstrumentGui *ig) {
	if(!ig) {
		return;
	}
	Graph *base = getSelectedInstGraph();
	GuiNode *sel = base ? base->selected : NULL;
	bool onRouteBtn = sel && sel->actionCb == cbOpenRouteLayer;
	bool pickerOpen = g_routePickerCount > 0;
	bool shouldShow = onRouteBtn || pickerOpen;
	Layer *existing = findLayerByName(&ig->overlayLayers, "ROUTELINES");
	if(shouldShow) {
		if(existing) {
			return; /* already up — no-op so we don't churn layers */
		}
		if(onRouteBtn) {
			SourceCtx *sc = (SourceCtx *)sel->actionCtx;
			if(sc && sc->inst) {
				g_routeLinesCtx.inst = sc->inst;
				g_routeLinesCtx.srcIdx = sc->idx;
			}
		}
		/* When only the picker is open (no source button is currently
		 * hovered), the picker already bumped g_routeLinesCtx before
		 * it pushed the picker — nothing to copy here. */
		Graph *g = createGraph(na_horizontal);
		GuiNode *lines = createGuiNode(0, 0, SCREEN_W, SCREEN_H, 0, na_horizontal, "routelines", 0, 0);
		lines->drawable = true;
		lines->draw = drawRouteLinesNode;
		appendItem(g->root, lines, 1);
		Layer *l = createLayer(g, 0, 0, SCREEN_W, SCREEN_H, "ROUTELINES", false, true);
		/* Spec #3: passive overlay. ROUTE stays modal — arrow keys
		 * and EDIT go to the picker, not the overlay. Set this BEFORE
		 * pushLayer: pushLayer takes ownership of `l` and frees the
		 * malloc'd struct, so post-push edits go to freed memory. */
		setLayerPassive(l, true);
		pushLayer(&ig->overlayLayers, l);
	} else if(existing) {
		/* Walk down from the top and remove the overlay; we don't
		 * assume it's at the very top because a confirmation modal
		 * could have pushed on top of it. */
		for(int i = ig->overlayLayers.count - 1; i >= 0; i--) {
			if(strcmp(ig->overlayLayers.layers[i].name, "ROUTELINES") == 0) {
				Layer *popped = (Layer *)malloc(sizeof(Layer));
				if(!popped) {
					break;
				}
				*popped = ig->overlayLayers.layers[i];
				/* Shift the rest down to keep the array contiguous. */
				for(int j = i; j < ig->overlayLayers.count - 1; j++) {
					ig->overlayLayers.layers[j] = ig->overlayLayers.layers[j + 1];
				}
				ig->overlayLayers.count--;
				destroyLayer(popped);
				break;
			}
		}
	}
}


void cbAddModSource(void *ctx) {
	Instrument *inst = (Instrument *)ctx;
	addRuntimeSource(inst);
}


static void cbCycleSourceType(void *ctx) {
	SourceCtx *sc = (SourceCtx *)ctx;
	if(!sc || !sc->inst) {
		return;
	}
	Mod *mod = scMod(sc);
	if(!mod || mod->type == MT_ATTEN) {
		return;
	}
	ModType next = MT_ENV;
	switch(mod->type) {
		case MT_ENV: next = MT_LFO; break;
		case MT_LFO: next = MT_RND; break;
		default:     next = MT_ENV; break;
	}
	/* Task 8: hold the rebuilding flag while we mutate the lists the audio
	 * thread iterates. The audio lock closes the flag's check-then-use
	 * race. */
	pthread_mutex_lock(&g_audioLock);
	sc->inst->rebuilding = true;
	if(changeModType(sc->inst->modList, mod, next, sc->inst->paramList)) {
		sc->inst->envelopeCount = modSourceCount(sc->inst->modList);
		if(sc->inst->vm) {
			rebuildVoicesForInstrument(sc->inst->vm, sc->inst);
		}
		rebuildInstrumentGraph();
	}
	sc->inst->rebuilding = false;
	pthread_mutex_unlock(&g_audioLock);
}


static const char *modTypeTag(ModType t) {
	switch(t) {
		case MT_LFO: return "LFO";
		case MT_RND: return "RND";
		case MT_ATTEN: return "ATTN";
		default:     return "ENV";
	}
}


void appendModSourceEntry(Graph *g, GuiNode *container, Instrument *inst, int idx, int weight, bool selected) {
	Mod *mod = NULL;
	if(inst && inst->modList) {
		int mi = modIndexAt(inst->modList, idx);
		mod = (mi >= 0) ? inst->modList->mods[mi] : NULL;
	}
	/* Attenuators are connection-internal: they never appear as source
	 * rows (no row, no type-cycling, no ROUTE button). Their routes are
	 * managed through the real source they shape. */
	if(!mod || mod->type == MT_ATTEN) {
		return;
	}
	/* The source-row action buttons (ROUTE/TYPE/DEL) capture &g_sourceCtx[idx],
	 * a SHARED array. refreshSourceCtx clobbers the whole array, so it must
	 * reflect the instrument that owns the interactive (SELECTED) graph —
	 * a non-selected channel's build refreshing it would leave the selected
	 * channel's captured ctx pointing at the wrong instrument. Refresh from
	 * the selected channel's build only (idempotent per row). */
	{
		InstrumentGui *ig = igui;
		if(ig && inst == ig->vm->instruments[*ig->selectedInstrument]) {
			refreshSourceCtx(inst);
		}
	}
	bool core = idx < inst->coreEnvelopeCount;
	GuiNode *wrap = createGuiNode(0, 0, 100, 100, 2, na_horizontal, "MODSRC", 0, 0);
	wrap->drawable = true;
	wrap->draw = drawWrapperNode;

	if(!core) {
		GuiNode *typeBtn = createActionBtnGuiNode(0, 0, 100, 100, 2, na_horizontal,
		                                         modTypeTag(mod->type), 0, cbCycleSourceType, &g_sourceCtx[idx]);
		typeBtn->name = strdup(modTypeTag(mod->type));
		appendItem(wrap, typeBtn, 3);
	}

	switch(mod->type) {
		case MT_ENV: {
			EnvState *e = &mod->data.env;
			appendItem(wrap, createDialGuiNode(0, 0, 100, 100, 2, na_horizontal, "ATTACK", selected, incParameterBaseValue, e->stages[0].duration), 4);
			appendItem(wrap, createDialGuiNode(0, 0, 100, 100, 2, na_horizontal, "CURVE", 0, incParameterBaseValue, e->stages[0].curvature), 4);
			appendItem(wrap, createDialGuiNode(0, 0, 100, 100, 2, na_horizontal, "DECAY", 0, incParameterBaseValue, e->stages[1].duration), 4);
			appendItem(wrap, createDialGuiNode(0, 0, 100, 100, 2, na_horizontal, "CURVE", 0, incParameterBaseValue, e->stages[1].curvature), 4);
			break;
		}
		case MT_LFO: {
			LfoState *l = &mod->data.lfo;
			appendItem(wrap, createDialGuiNode(0, 0, 100, 100, 2, na_horizontal, "RATE", selected, incParameterBaseValue, l->rate), 4);
			if(l->shape) {
				appendItem(wrap, createDialGuiNode(0, 0, 100, 100, 2, na_horizontal, "SHAPE", 0, incParameterBaseValue, l->shape), 4);
			}
			break;
		}
		case MT_RND: {
			RndState *r = &mod->data.rnd;
			appendItem(wrap, createDialGuiNode(0, 0, 100, 100, 2, na_horizontal, "RATE", selected, incParameterBaseValue, r->rate), 4);
			if(r->shape) {
				appendItem(wrap, createDialGuiNode(0, 0, 100, 100, 2, na_horizontal, "SHAPE", 0, incParameterBaseValue, r->shape), 4);
			}
			break;
		}
		default:
			break;
	}

	/* M2 (user report): every source row gets a ROUTE button — the four
	 * core envelopes are first-class modulation SOURCES too (their params
	 * are voice-aliased only as destinations of the delete path, which
	 * stays runtime-only). The TYPE selector + DEL stay runtime-only. */
	appendItem(wrap, createActionBtnGuiNode(0, 0, 100, 100, 2, na_horizontal, "ROUTE", 0, cbOpenRouteLayer, &g_sourceCtx[idx]), 3);
	if(!core) {
		/* Task 5: DEL opens the YES/NO confirm layer; cbDeleteSource reads
		 * inst+idx off the per-entry SourceCtx slot refreshed by
		 * refreshSourceCtx() above. */
		appendItem(wrap, createActionBtnGuiNode(0, 0, 100, 100, 2, na_horizontal, "DEL", 0, cbDeleteSource, &g_sourceCtx[idx]), 2);
	}
	appendItem(wrap, createBlankGuiNode(), 1);
	appendItem(container, wrap, weight);
	(void)g;
}


/* task scroll: walk a graph for the named scroll container and bring
 * the current selection into view. Called once per frame from
 * gui_instrument_draw before drawNode runs, so the scissor in the
 * scrollable branch of drawNode clips against the correct offset on
 * the same frame selection changes. */
static GuiNode *findScrollContainerByName(GuiNode *n, const char *name) {
	if(!n) {
		return NULL;
	}
	if(n->scrollable && n->name && strcmp(n->name, name) == 0) {
		return n;
	}
	if(n->itemCount > 0 && n->items) {
		ListElement *cur = n->items->head;
		for(int i = 0; i < n->itemCount; i++) {
			GuiNode *hit = findScrollContainerByName(*(GuiNode **)cur->data, name);
			if(hit) {
				return hit;
			}
			cur = cur->next;
		}
	}
	return NULL;
}

void syncModWrapScroll(void) {
	if(!igui || !igui->vm || !igui->selectedInstrument) {
		return;
	}
	/* S1 (user report): while the ROUTE picker is open the wrap is owned
	 * by syncPickerBaseScroll (which scrolls to the picker's selected
	 * dest). syncing to the base selection too makes the two fight every
	 * frame and the wrap settles somewhere mid-scroll — the source of the
	 * "returns scrolled down slightly" state after the picker closes. */
	if(g_routePickerCount > 0) {
		return;
	}
	Graph *g = igui->instrumentScreenGraphs[*igui->selectedInstrument];
	if(!g || !g->root) {
		return;
	}
	GuiNode *sel = g->selected;
	if(!sel) {
		return;
	}
	GuiNode *sc = findScrollContainerByName(g->root, "mod_wrap");
	if(!sc) {
		return;
	}
	scrollToVisible((ScrollContainer *)sc, sel);
}

/* T7: while the ROUTE picker is up, re-pin every dest button to its base
 * dial's CURRENT rect. The base mod container may have scrolled (base
 * selection nav, or the picker itself via syncPickerBaseScroll), moving
 * the dials the buttons overlay — the pins from cbOpenRouteLayer go stale
 * the moment anything scrolls. */
void syncPickerDestRects(void) {
	InstrumentGui *ig = igui;
	if(!ig) {
		return;
	}
	Layer *route = findLayerByName(&ig->overlayLayers, "ROUTE");
	if(!route || !route->graph || !route->graph->root) {
		return;
	}
	Graph *base = getSelectedInstGraph();
	if(!base || !base->root) {
		return;
	}
	ListElement *e = route->graph->root->items->head;
	for(int i = 0; i < route->graph->root->itemCount && e; i++) {
		GuiNode *btn = *(GuiNode **)e->data;
		if(btn->actionCb != cbRouteToDest) {
			e = e->next;
			continue;
		}
		DestCtx *dc = (DestCtx *)btn->actionCtx;
		if(!dc || !dc->dest) {
			e = e->next;
			continue;
		}
		Rectangle r;
		if(findDialRectForParam(base->root, dc->dest, &r)) {
			btn->x = (uint16_t)r.x;
			btn->y = (uint16_t)r.y;
			btn->w = (uint16_t)r.width;
			btn->h = (uint16_t)r.height;
		}
		e = e->next;
	}
}

/* T11: draw the attenuation editor panel (4 rows: amount / curve /
 * polarity / reset) centred on screen, focused row highlighted. Runs
 * after layerStackDraw so it overlays the picker. */
void guiPickerEditorDraw(void) {
	if(!g_attenEditorOpen || !g_attenEditorCtx || !g_attenEditorConn) {
		return;
	}
	const int rows = 4;
	const int rowH = 18;
	const int pw = 220;
	const int ph = rows * rowH + 10;
	int px = (SCREEN_W - pw) / 2;
	int py = (SCREEN_H - ph) / 2;
	DrawRectangle(px, py, pw, ph, (Color){ 20, 20, 25, 210 });
	DrawRectangleLinesEx((Rectangle){ px, py, pw, ph }, 1, cs.labelSelected);

	float amt = g_attenEditorConn->amount ? getParameterValue(g_attenEditorConn->amount) : 1.0f;
	int curve = g_attenEditorAtten && g_attenEditorAtten->data.atten.attenCurve ? getParameterValueAsInt(g_attenEditorAtten->data.atten.attenCurve) : 0;
	int pol = g_attenEditorAtten && g_attenEditorAtten->data.atten.attenPolarity ? getParameterValueAsInt(g_attenEditorAtten->data.atten.attenPolarity) : 0;

	const char *labels[4];
	char amtBuf[24];
	char curveBuf[24];
	char polBuf[24];
	snprintf(amtBuf, sizeof(amtBuf), "AMOUNT  %.2f", amt);
	snprintf(curveBuf, sizeof(curveBuf), "CURVE  %s", curve ? "CURVED" : "LINEAR");
	snprintf(polBuf, sizeof(polBuf), "POLARITY  %s", pol ? "UNI" : "BI");
	labels[0] = amtBuf;
	labels[1] = curveBuf;
	labels[2] = polBuf;
	labels[3] = "RESET";

	for(int i = 0; i < rows; i++) {
		int ry = py + 5 + i * rowH;
		if(i == g_attenEditorFocus) {
			DrawRectangle(px + 3, ry, pw - 6, rowH - 2, (Color){ 60, 90, 60, 160 });
		}
		DrawTextEx(pixelFont, labels[i], (Vector2){ px + 8, ry + 3 }, 9, 1,
		           i == g_attenEditorFocus ? cs.labelSelected : cs.label);
	}
}

/* T7: picker-driven base scroll. When the picker's selected dest lives
 * inside the scrollable mod container but is scrolled out of view, scroll
 * the base container so the dest's row is revealed (the picker buttons
 * then follow via syncPickerDestRects, and the route lines via their
 * live-rect reads). Dests in the FM/preset sections don't scroll — the
 * mod container only contains the modulator source rows. */
/* T11: per-frame reset — when the ROUTE picker is gone, the editor and
 * any deferred toggle are stale and must clear (covers every pop path
 * uniformly: KM_SELECT, the add path, the deferred toggle itself). */
void guiPickerFrameSync(void) {
	if(!igui || !findLayerByName(&igui->overlayLayers, "ROUTE")) {
		g_attenEditorOpen = false;
		g_pickerPendingToggle = false;
		g_pickerPendingCtx = NULL;
	}
}

void syncPickerBaseScroll(void) {
	InstrumentGui *ig = igui;
	if(!ig) {
		return;
	}
	Layer *route = findLayerByName(&ig->overlayLayers, "ROUTE");
	if(!route || !route->graph || !route->graph->selected) {
		return;
	}
	DestCtx *dc = (DestCtx *)route->graph->selected->actionCtx;
	if(!dc || !dc->dest) {
		return;
	}
	Graph *base = getSelectedInstGraph();
	if(!base || !base->root) {
		return;
	}
	GuiNode *modwrap = findScrollContainerByName(base->root, "mod_wrap");
	if(!modwrap) {
		return;
	}
	GuiNode *dial = findDialNodeForParam(base->root, dc->dest);
	if(!dial) {
		return;
	}
	GuiNode *p = dial;
	while(p && p != modwrap) {
		p = p->container;
	}
	if(!p) {
		return;
	}
	scrollToVisible((ScrollContainer *)modwrap, dial);
}


