/* gui_gui_instrument.c -- generated by the gui module split (lawn-mowing-gui).
 * One module per screen; shared node helpers live in gui_core.c.
 * Cross-module state/helpers: see gui_internal.h. */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "dstruct.h"
#include "raylib.h"
#include "gui.h"
#include "graph_gui.h"
#include "input.h"
#include "modsystem.h"
#include "notes.h"
#include "voice.h"
#include "io/preset_io.h"
#include "io.h"
#include "gui_internal.h"
#include "gui_inst_internal.h"

static void appendMetaControlNode(Graph *g, GuiNode *container, Instrument *inst, VoiceManager *vm, int channel, int weight, bool selected);
static void cbOpenLoadList(void *ctx);
static void commitPresetName(PresetNameGuiNode *pn);
static Graph *createInstGraph(Instrument *inst, VoiceManager *vm, int channel, bool selected);
static GuiNode *createPresetNameGuiNode(int x, int y, int w, int h, Instrument *inst, bool selected);
static void guiBuildDirtyConfirmLayer(InstrumentGui *ig, Instrument *inst);
static void guiBuildLoadListLayer(InstrumentGui *ig);
static void guiBuildOverwriteLayer(InstrumentGui *ig, const char *pendingName);
static void guiOpenLoadList(void);
static void guiSetOverwritePending(const char *name);
static void guiShowDirtyConfirmModal(Instrument *inst);
static bool isPresetNameNode(GuiNode *n);

/* ---- module-private state ---- */
InstrumentGui *igui;

/* Task 8: the current preset-name node. Set on every graph build
 * (createPresetNameGuiNode). The SAVE action button uses it to commit
 * the instrument under the name currently shown. */
static PresetNameGuiNode *g_presetNameNode;


/* Task 9: preset-load-list state. g_loadList is populated by guiOpenLoadList
 * by enumerating data/instrument_presets/ .ipb files, stripping the
 * extension, and sorting alphabetically. While g_loadListActive is true,
 * handlePresetUiInput routes UP/DOWN/START/SELECT to the load-list node
 * regardless of which node is selected in the instrument graph. */
#define LOADLIST_MAX 256
#define LOADLIST_NAME_MAX 32
typedef struct {
	char names[LOADLIST_MAX][LOADLIST_NAME_MAX];
	int count;
	int highlight;
} PresetLoadList;

void createInstrumentGui(VoiceManager *vm, int *selectedInstrument, int scene) {
	InstrumentGui *ig = (InstrumentGui *)malloc(sizeof(InstrumentGui));
	if(!ig) return;
	memset(ig, 0, sizeof(InstrumentGui));
	ig->vm = vm;
	ig->selectedInstrument = selectedInstrument;

	for(int i = 0; i < vm->enabledChannels; i++) {
		bool isSelected = *selectedInstrument == i;
		ig->instrumentScreenGraphs[i] = createInstGraph(vm->instruments[i], vm, i, isSelected);
		ig->instrumentCount++;
	}
	/* Task 7: initialise the overlay layer stack. The stack starts empty;
	 * modals push layers on demand, the instrument input/draw path drains
	 * it when empty. */
	initLayerStack(&ig->overlayLayers);
	igui = ig;
}


Graph *getSelectedInstGraph() {
	return igui->instrumentScreenGraphs[*igui->selectedInstrument];
}



InstrumentGui *getInstrumentGui(void) {
	return igui;
}





MixRing *arrangerMixRing;


static PresetLoadList g_loadList;

static bool g_loadListActive = false;


bool guiIsLoadListActive(void) { return g_loadListActive; }

/* qsort helper: compare two fixed-width name strings lexicographically. */

static int loadListCmp(const void *a, const void *b) {
	const char *na = (const char *)a;
	const char *nb = (const char *)b;
	return strncmp(na, nb, LOADLIST_NAME_MAX);
}

/* Strip the trailing ".ipb" from a filename in-place; no-op if the
 * suffix is absent. */

static void stripIpbExtension(char *s) {
	size_t len = strlen(s);
	const char *suffix = ".ipb";
	size_t slen = strlen(suffix);
	if(len > slen && strcmp(s + len - slen, suffix) == 0) {
		s[len - slen] = '\0';
	}
}


static void guiOpenLoadList(void);


void guiOpenLoadList(void) {
	g_loadList.count = 0;
	g_loadList.highlight = 0;
	DirectoryList *dl = createDirectoryList();
	if(dl) {
		populateDirectoryList(dl, "data/instrument_presets/");
		for(size_t i = 0; i < dl->count && g_loadList.count < LOADLIST_MAX; i++) {
			/* Take only the basename so we don't show the dir prefix. */
			const char *path = dl->file_paths[i];
			const char *slash = strrchr(path, '/');
			const char *base = slash ? slash + 1 : path;
			strncpy(g_loadList.names[g_loadList.count], base, LOADLIST_NAME_MAX - 1);
			g_loadList.names[g_loadList.count][LOADLIST_NAME_MAX - 1] = '\0';
			stripIpbExtension(g_loadList.names[g_loadList.count]);
			g_loadList.count++;
		}
		freeDirectoryList(dl);
	}
	if(g_loadList.count > 1) {
		qsort(g_loadList.names, (size_t)g_loadList.count, LOADLIST_NAME_MAX, loadListCmp);
	}
	g_loadListActive = true;
	/* Task 7: also push the load-list layer so the user can navigate
	 * the presets within an overlay graph. */
	if(igui) {
		guiBuildLoadListLayer(igui);
	}
}


static void guiCloseLoadList(void) {
	g_loadListActive = false;
	if(igui) {
		popLayer(&igui->overlayLayers);
	}
}

/* Task 8: overwrite-modal state. The modal is the only modal in the app
 * (per the brief), so a single-state-machine + a pending-name slot is
 * sufficient. g_overwriteChoice is the user's current YES/NO selection
 * while the modal is up (defaults to NO = false on open). */

static ModalState g_modalState = MODAL_NONE;

static char g_pendingName[33];

static bool g_overwriteChoice; /* false = NO, true = YES */


static void guiSetOverwritePending(const char *name) {
	if(!name) {
		return;
	}
	strncpy(g_pendingName, name, sizeof(g_pendingName) - 1);
	g_pendingName[sizeof(g_pendingName) - 1] = '\0';
	g_overwriteChoice = false; /* safe default = NO */
	g_modalState = MODAL_CONFIRM_OVERWRITE;
	/* Task 7: push the overwrite-confirm layer so the user can
	 * navigate YES/NO with arrow keys + START. */
	if(igui) {
		guiBuildOverwriteLayer(igui, name);
	}
}


/* Task 6: forward decl — defined further down. Used by both
 * guiSavePreset() and the overwrite-confirmation path. */

static void markInstrumentSavedAs(Instrument *inst, const char *name);


PresetFileResult guiSavePreset(Instrument *inst, const char *name) {
	if(!inst || !name) {
		return PRESET_ERROR_FORMAT;
	}
	PresetFileResult r;
	if(inst->selectedPresetIndex) {
		int curSlot = getParameterValueAsInt(inst->selectedPresetIndex);
		if(curSlot >= inst->presetBank->presetCount) {
			/* Task 8: parked on a blank slot -- save INTO it so the
			 * bank doesn't grow past the slot the user is viewing. */
			r = saveInstrumentAsPresetToSlot(inst, name, "data/instrument_presets/", curSlot);
		} else {
			r = saveInstrumentAsPreset(inst, name, "data/instrument_presets/");
		}
	} else {
		r = saveInstrumentAsPreset(inst, name, "data/instrument_presets/");
	}
	if(r == PRESET_EXISTS) {
		/* Defer the actual overwrite to the modal: the user hasn't
		 * confirmed yet. handlePresetUiInput drives the modal and
		 * calls saveInstrumentAsPresetOverwrite() on YES. We still
		 * propagate PRESET_EXISTS to the caller (commitPresetName)
		 * so it can skip firing either flash — the modal is the UI. */
		guiSetOverwritePending(name);
	} else if(r == PRESET_OK) {
		/* Task 6: save success → live state now matches disk, so
		 * the dirty flag clears and the loaded snapshot updates
		 * to this preset's name. */
		markInstrumentSavedAs(inst, name);
	}
	return r;
}

/* Task 6 stub: full modal layer lands in Task 7. Currently this is
 * a no-op so the load-list button can call it without crashing.
 * Task 7 will replace this body with a modalState push and a
 * three-way choice (discard / save / cancel) that falls through
 * to guiOpenLoadList() on discard. */
// (removed in Task 7: real implementation is below)


static void guiShowDirtyConfirmModal(Instrument *inst) {
	if(!inst) {
		return;
	}
	/* Task 7: the dirty-confirm layer's SAVE branch uses g_pendingName,
	 * so seed it from the currently-loaded preset's name. The user
	 * edited this preset and we're offering to flush those edits to
	 * the same slot on disk. */
	strncpy(g_pendingName, inst->loaded.name, sizeof(g_pendingName) - 1);
	g_pendingName[sizeof(g_pendingName) - 1] = '\0';
	if(igui) {
		guiBuildDirtyConfirmLayer(igui, inst);
	}
}

/* Task 6 helper: after a successful save (or overwrite) the live
 * instrument now matches a specific preset on disk. Locate the slot
 * in the bank by name and stamp the LoadedPreset snapshot, which
 * also clears the dirty bit. Sharing this between the new-save
 * branch in guiSavePreset() and the overwrite branch in
 * handlePresetUiInput() keeps the two save paths from drifting. */

static void markInstrumentSavedAs(Instrument *inst, const char *name) {
	if(!inst || !name || !name[0]) {
		return;
	}
	PresetBank *pb = inst->presetBank;
	if(!pb) {
		return;
	}
	for(int i = 0; i < pb->presetCount; i++) {
		if(strncmp(pb->patches[i].name, name, sizeof(pb->patches[i].name)) == 0) {
			markPresetLoaded(inst, name);
			return;
		}
	}
}

/* Task 7: Layer-based overlay system. The three modals (overwrite,
 * dirty-confirm, load-list) each build a self-contained Graph of
 * action nodes and push it as a Layer on the instrument's overlay
 * stack. Input is routed to the topmost layer; drawing stacks
 * bottom-up. */

/* Modal-side callbacks. These close the topmost layer (pop it) and
 * perform the user-confirmed action. They store the pending state
 * in file-static globals below so they don't need to thread
 * per-layer state. */

static void cbOverwriteConfirm(void *ctx) {
	Instrument *inst = (Instrument *)ctx;
	InstrumentGui *ig = igui;
	if(inst && ig) {
		saveInstrumentAsPresetOverwrite(inst, g_pendingName, "data/instrument_presets/");
		markInstrumentSavedAs(inst, g_pendingName);
	}
	if(ig) {
		popLayer(&ig->overlayLayers);
	}
	g_modalState = MODAL_NONE;
}


static void cbOverwriteCancel(void *ctx) {
	(void)ctx;
	InstrumentGui *ig = igui;
	if(ig) {
		popLayer(&ig->overlayLayers);
	}
	g_modalState = MODAL_NONE;
}


static void cbDirtyDiscard(void *ctx) {
	Instrument *inst = (Instrument *)ctx;
	InstrumentGui *ig = igui;
	/* Discard edits and proceed straight to the load list. */
	if(inst) {
		markPresetLoaded(inst, NULL);
	}
	if(ig) {
		popLayer(&ig->overlayLayers);
	}
	if(inst) {
		guiOpenLoadList();
	}
}


static void cbDirtySave(void *ctx) {
	Instrument *inst = (Instrument *)ctx;
	InstrumentGui *ig = igui;
	/* Save with the currently-staged name. If it exists, push the
	 * overwrite layer on top of this one; otherwise commit and
	 * pop straight to the load list. */
	if(inst && inst->presetBank) {
		PresetFileResult r = saveInstrumentAsPreset(inst, g_pendingName, "data/instrument_presets/");
		if(r == PRESET_OK) {
			markInstrumentSavedAs(inst, g_pendingName);
			if(ig) {
				popLayer(&ig->overlayLayers);
			}
			guiOpenLoadList();
			return;
		}
		if(r == PRESET_EXISTS) {
			/* Replace the dirty-confirm with overwrite-confirm.
			 * Pop the dirty layer first so the overwrite layer
			 * is the only thing on the stack. */
			if(ig) {
				popLayer(&ig->overlayLayers);
			}
			guiBuildOverwriteLayer(ig, g_pendingName);
			return;
		}
	}
	/* Any other error: just close the dirty-confirm and bail. */
	if(ig) {
		popLayer(&ig->overlayLayers);
	}
}


static void cbDirtyCancel(void *ctx) {
	(void)ctx;
	InstrumentGui *ig = igui;
	if(ig) {
		popLayer(&ig->overlayLayers);
	}
}


static void cbLoadListPick(void *ctx) {
	/* ctx is the index into g_loadList.names (and inst->presetBank->patches). */
	int idx = (int)(intptr_t)ctx;
	InstrumentGui *ig = igui;
	Instrument *inst = ig ? ig->vm->instruments[*ig->selectedInstrument] : NULL;
	if(!inst || !inst->presetBank || idx < 0 || idx >= g_loadList.count) {
		if(ig) {
			popLayer(&ig->overlayLayers);
		}
		g_loadListActive = false;
		return;
	}
	if(idx < inst->presetBank->presetCount) {
		/* Task 8 slot model: the chosen preset lands in the CURRENT
		 * bank slot (the one the user had selected via PREV/NEXT), not
		 * appended somewhere new. This makes "load a preset into this
		 * blank slot" work: the blank slot (index >= presetCount) gets
		 * the loaded patch, and the selection stays on that slot. */
		int slot = getParameterValueAsInt(inst->selectedPresetIndex);
		if(slot < 0 || slot >= PRESET_BANK_SLOTS) {
			slot = 0;
		}
		inst->presetBank->patches[slot] = inst->presetBank->patches[idx];
		applyInstrumentPreset(inst, inst->presetBank->patches[slot]);
		/* Task 6: refresh the loaded-preset snapshot so dirty=false and
		 * loaded.name is set. Without this the dirty-confirm gate in
		 * cbOpenLoadList never opens because isInstrumentDirty returns
		 * false on a fresh instrument with no baseline name. */
		markPresetLoaded(inst, inst->presetBank->patches[slot].name);
		if(inst->selectedPresetIndex) {
			inst->selectedPresetIndex->baseValue = (float)slot;
			inst->selectedPresetIndex->currentValue = (float)slot;
		}
		if(inst->vm) {
			pthread_mutex_lock(&g_audioLock);
			inst->rebuilding = true;
			rebuildVoicesForInstrument(inst->vm, inst);
			inst->rebuilding = false;
			pthread_mutex_unlock(&g_audioLock);
		}
		rebuildInstrumentGraph();
	}
	if(ig) {
		popLayer(&ig->overlayLayers);
	}
	g_loadListActive = false;
}


static void cbLoadListCancel(void *ctx) {
	(void)ctx;
	InstrumentGui *ig = igui;
	if(ig) {
		popLayer(&ig->overlayLayers);
	}
	g_loadListActive = false;
}

/* Build the overwrite-confirm layer. The graph has two action
 * buttons: YES (confirms overwrite) and NO (cancels). Both pop
 * the layer; YES additionally commits the overwrite. */

static void guiBuildOverwriteLayer(InstrumentGui *ig, const char *pendingName) {
	if(!ig) {
		return;
	}
	if(pendingName) {
		strncpy(g_pendingName, pendingName, sizeof(g_pendingName) - 1);
		g_pendingName[sizeof(g_pendingName) - 1] = '\0';
	}
	g_overwriteChoice = false; /* safe default: NO */
	g_modalState = MODAL_CONFIRM_OVERWRITE;

	/* The layer's graph. We use a vertical container as the root
	 * and the two action buttons as children. The createGraph()
	 * root covers the whole screen — the actual visual panel is
	 * drawn by the layer's draw step (DrawRectangle + DrawText),
	 * not by the graph nodes themselves. Action buttons need a
	 * position and size; we give them the same y to make the
	 * horizontal nav obvious (LEFT/RIGHT). */
	Graph *g = createGraph(na_horizontal);
	const int py = (SCREEN_H - 80) / 2;
	const int px = (SCREEN_W - 280) / 2;
	GuiNode *noBtn = createActionBtnGuiNode(px + 30, py + 44, 100, 22, 0, na_horizontal, "NO", 0, cbOverwriteCancel, NULL);
	noBtn->name = strdup("OVERWRITE_NO");
	GuiNode *yesBtn = createActionBtnGuiNode(px + 150, py + 44, 100, 22, 0, na_horizontal, "YES", 0, cbOverwriteConfirm, ig->vm->instruments[*ig->selectedInstrument]);
	yesBtn->name = strdup("OVERWRITE_YES");
	appendItem(g->root, noBtn, 1);
	appendItem(g->root, yesBtn, 1);
	changeGraphSelection(g, noBtn);

	Layer *layer = createLayer(g, px, py, 280, 80, "OVERWRITE", true, true);
	pushLayer(&ig->overlayLayers, layer);
}

/* Build the dirty-confirm layer. Three-way: DISCARD, CANCEL, SAVE.
 * The graph is a single row of three action buttons. */

static void guiBuildDirtyConfirmLayer(InstrumentGui *ig, Instrument *inst) {
	if(!ig) {
		return;
	}
	(void)inst; /* inst is recovered from the ig->vm at callback time */
	g_modalState = MODAL_CONFIRM_OVERWRITE; /* keep legacy field in sync */

	Graph *g = createGraph(na_horizontal);
	const int pw = 360;
	const int ph = 70;
	const int px = (SCREEN_W - pw) / 2;
	const int py = (SCREEN_H - ph) / 2;
	GuiNode *discardBtn = createActionBtnGuiNode(px + 10, py + 38, 100, 22, 0, na_horizontal, "DISCARD", 1, cbDirtyDiscard, ig->vm->instruments[*ig->selectedInstrument]);
	GuiNode *saveBtn = createActionBtnGuiNode(px + 130, py + 38, 100, 22, 0, na_horizontal, "SAVE", 0, cbDirtySave, ig->vm->instruments[*ig->selectedInstrument]);
	GuiNode *cancelBtn = createActionBtnGuiNode(px + 250, py + 38, 100, 22, 0, na_horizontal, "CANCEL", 0, cbDirtyCancel, NULL);
	discardBtn->name = strdup("DIRTY_DISCARD");
	saveBtn->name = strdup("DIRTY_SAVE");
	cancelBtn->name = strdup("DIRTY_CANCEL");
	appendItem(g->root, discardBtn, 1);
	appendItem(g->root, saveBtn, 1);
	appendItem(g->root, cancelBtn, 1);
	g->selected = discardBtn;

	Layer *layer = createLayer(g, px, py, pw, ph, "DIRTY_CONFIRM", true, true);
	pushLayer(&ig->overlayLayers, layer);
}

/* Build the load-list layer. The graph is a vertical list of
 * action buttons, one per preset in the bank. Up/Down moves
 * through the list; START triggers cbLoadListPick with the
 * preset index. */

static void guiBuildLoadListLayer(InstrumentGui *ig) {
	if(!ig) {
		return;
	}
	g_loadListActive = true;

	Graph *g = createGraph(na_vertical);
	const int pw = 200;
	const int rowH = 14;
	const int maxRows = 8;
	int ph = (g_loadList.count < maxRows ? g_loadList.count : maxRows) * rowH + 8;
	if(ph < rowH * 2) {
		ph = rowH * 2;
	}
	const int px = (SCREEN_W - pw) / 2;
	const int py = (SCREEN_H - ph) / 2;

	int rows = g_loadList.count;
	if(rows > maxRows) {
		rows = maxRows;
	}
	GuiNode *firstEntry = NULL;
	for(int i = 0; i < rows; i++) {
		GuiNode *row = createActionBtnGuiNode(px, py + i * rowH, pw, rowH, 0, na_horizontal, g_loadList.names[i], 0, cbLoadListPick, (void *)(intptr_t)i);
		row->name = strdup(g_loadList.names[i]);
		appendItem(g->root, row, 1);
		if(!firstEntry) {
			firstEntry = row;
		}
	}
	/* Cancel/back button lives at the bottom of the list so the
	 * default selection is the first preset entry. */
	GuiNode *cancelBtn = createActionBtnGuiNode(px, py + ph - rowH, pw, rowH, 0, na_horizontal, "< BACK", 0, cbLoadListCancel, NULL);
	cancelBtn->name = strdup("LOADLIST_BACK");
	appendItem(g->root, cancelBtn, 1);
	if(firstEntry) {
		changeGraphSelection(g, firstEntry);
	} else {
		changeGraphSelection(g, cancelBtn);
	}

	Layer *layer = createLayer(g, px, py, pw, ph, "LOADLIST", true, true);
	pushLayer(&ig->overlayLayers, layer);
}


/* Task 7: stub fill. Pushed here as a layer so the LOAD button
 * gates the load list on the dirty bit (Task 6). */
// (the real guiShowDirtyConfirmModal definition is later in this file
// once getSelectedInstInstrument / guiBuildDirtyConfirmLayer are visible)


#define NAME_CHARS "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 _-. "

static int charIndex(char c) {
	if(c >= 'a' && c <= 'z') {
		c -= 32;
	}
	for(int i = 0; i < (int)strlen(NAME_CHARS); i++) {
		if(NAME_CHARS[i] == c) {
			return i;
		}
	}
	return 0;
}


static void cycleNameChar(PresetNameGuiNode *pn, int delta) {
	int idx = charIndex(pn->name[pn->cursor]);
	int count = (int)strlen(NAME_CHARS);
	idx = (idx + delta + count) % count;
	pn->name[pn->cursor] = NAME_CHARS[idx];
}

/* Task 5: forward decl so commitPresetName (defined below) can call it
 * before the static definition. The real implementation lives next to
 * effectiveNameLen further down. */

static int currentFrameIndex(void);


static void commitPresetName(PresetNameGuiNode *pn) {
	/* trim + default, then run the save flow (overwrite check happens here) */
	if(strlen(pn->name) == 0 || strspn(pn->name, " ") == strlen(pn->name)) {
		strncpy(pn->name, "UNNAMED", sizeof(pn->name) - 1);
		pn->name[sizeof(pn->name) - 1] = '\0';
	}
	/* Task 5: strip trailing spaces. The old "Xm1  " (cursor-left-padded
	 * to 32 chars) used to bypass the EXISTS check because strncmp(_,32)
	 * matched the trailing NULs of the shorter stored name. With the
	 * trim the save call below always sees the same "Xm1" the bank
	 * already holds, so PRESET_EXISTS fires and the modal opens. */
	for(int i = (int)strlen(pn->name) - 1; i >= 0 && pn->name[i] == ' '; i--) {
		pn->name[i] = '\0';
	}
	pn->editing = false;
	PresetFileResult r = guiSavePreset(pn->inst, pn->name);
	/* PRESET_OK -> green/success flash. PRESET_EXISTS is handled out of
	 * band by the modal (guiSetOverwritePending), so it's NOT an error
	 * from the user's perspective; the flash fires when the overwrite
	 * actually commits via saveInstrumentAsPresetOverwrite.
	 *
	 * Every other PresetFileResult (format / io / null arg) is a real
	 * failure — light the red error flash. */
	if(r == PRESET_OK) {
		pn->savedFlashUntil = currentFrameIndex() + 30;
	} else if(r != PRESET_EXISTS) {
		pn->errorFlashUntil = currentFrameIndex() + 30;
	}
}

/* Forward decls so handlePresetUiInput can activate the SAVE/LOAD buttons. */

static void cbFocusNameNode(void *ctx);

static void cbOpenLoadList(void *ctx);

static void cbPresetPrev(void *ctx);

static void cbPresetNext(void *ctx);
/* Task 4: forward decls for the unified mod-source container's
 * action buttons (ADD button in the mod-wrap header + TYPE cycler on
 * each runtime entry). */


/* Task 5: DEL button (per runtime entry) opens a YES/NO confirm layer
 * that, on YES, calls removeSource(inst, idx) and pops the layer. The
 * implementation lives further down, after SourceCtx is defined. */


/* Task 7+: PREV/NEXT action buttons. Activate on KM_EDIT (same as
 * SAVE/LOAD). The Instrument is the ctx. setParameterBaseValue triggers
 * selectedPresetIndex's onChange (cb_setInstrumentPreset) which applies
 * the new preset and rebuilds voices. */

static void cbPresetPrev(void *ctx) {
	Instrument *inst = (Instrument *)ctx;
	if(!inst || !inst->selectedPresetIndex || !inst->presetBank) {
		return;
	}
	int cur = getParameterValueAsInt(inst->selectedPresetIndex);
	if(cur > 0) {
		setParameterBaseValue(inst->selectedPresetIndex, (float)(cur - 1));
	}
}

/* Task 8: PREV/NEXT walk the full PRESET_BANK_SLOTS range, including
 * blank slots (indices >= presetCount hold a default FM patch). */

static void cbPresetNext(void *ctx) {
	Instrument *inst = (Instrument *)ctx;
	if(!inst || !inst->selectedPresetIndex || !inst->presetBank) {
		return;
	}
	int cur = getParameterValueAsInt(inst->selectedPresetIndex);
	if(cur < PRESET_BANK_SLOTS - 1) {
		setParameterBaseValue(inst->selectedPresetIndex, (float)(cur + 1));
	}
}

/* Task 6: TYPE action button cycles SAMPLE -> FM -> BLEP -> SAMPLE for the
 * currently focused instrument. ctx is the VoiceManager (the brief asks for
 * VM-resolution rather than a stored channel so the same callback can serve
 * every meta row across all channels). We locate the channel by pointer
 * identity against getSelectedInstInstrument() BEFORE the swap (because
 * setInstrumentVoiceType frees the old Instrument and replaces it). If the
 * swap succeeds we tear down + rebuild the affected instrument screen so
 * the new voice-type-specific row (appendFMInstControlNode / appendSample
 * / appendBlep) appears below the meta row, and the dial / preset bindings
 * move onto the new Instrument's params.
 *
 * Task 4: replaced by cbTypePrev / cbTypeNext (PREV/NEXT action buttons on
 * the meta row). The cycle order is identical; the old single-button
 * `cbCycleVoiceType` is gone, but the behaviour is split into ±1 steps so
 * the user can step backward if they overshoot. */

/* Task 4: voiceType cycle helpers. The META row's PREV/NEXT buttons
 * step the focused instrument's voiceType through the 3-element ring
 * SAMPLE -> FM -> BLEP (and the reverse). Exposed for the unit test
 * test_type_cycle_order (gui.h). Unknown types fall through to FM so
 * the caller's `setInstrumentVoiceType` always lands on a valid type. */

VoiceType nextVoiceType(VoiceType t) {
	switch(t) {
		case VOICE_TYPE_SAMPLE: return VOICE_TYPE_FM;
		case VOICE_TYPE_FM:     return VOICE_TYPE_BLEP;
		case VOICE_TYPE_BLEP:   return VOICE_TYPE_SAMPLE;
		default:                return VOICE_TYPE_FM;
	}
}


VoiceType prevVoiceType(VoiceType t) {
	switch(t) {
		case VOICE_TYPE_SAMPLE: return VOICE_TYPE_BLEP;
		case VOICE_TYPE_BLEP:   return VOICE_TYPE_FM;
		case VOICE_TYPE_FM:     return VOICE_TYPE_SAMPLE;
		default:                return VOICE_TYPE_FM;
	}
}

/* Task 4: resolve the channel whose Instrument is `sel` by pointer
 * identity. Returns -1 if no match. Both cbTypePrev and cbTypeNext
 * call this; the channel must be captured BEFORE setInstrumentVoiceType
 * because that call frees the old Instrument. */

static int resolveTypeChannel(VoiceManager *vm, Instrument *sel) {
	if(!vm || !sel) return -1;
	for(int i = 0; i < vm->enabledChannels; i++) {
		if(vm->instruments[i] == sel) return i;
	}
	return -1;
}


static void cbTypePrev(void *ctx) {
	VoiceManager *vm = (VoiceManager *)ctx;
	Instrument *sel = getSelectedInstInstrument();
	int ch = resolveTypeChannel(vm, sel);
	if(ch < 0) return;
	if(setInstrumentVoiceType(vm, ch, prevVoiceType(sel->voiceType))) {
		rebuildInstrumentGraph();
	}
}


static void cbTypeNext(void *ctx) {
	VoiceManager *vm = (VoiceManager *)ctx;
	Instrument *sel = getSelectedInstInstrument();
	int ch = resolveTypeChannel(vm, sel);
	if(ch < 0) return;
	if(setInstrumentVoiceType(vm, ch, nextVoiceType(sel->voiceType))) {
		rebuildInstrumentGraph();
	}
}

/* Task 4: the type-tag label drawn between the PREV and NEXT action
 * buttons on the instrument-screen META row. It's a static text node
 * (not an action button and not a dial) — the tag updates every time
 * the graph rebuilds after a PREV/NEXT click, so we re-derive it from
 * the currently focused Instrument. The selected outline matches the
 * action buttons so the cursor is visible when the user navigates onto
 * the label cell. */

static void drawTypeLabelGuiNode(void *self) {
	GuiNode *gn = (GuiNode *)self;
	/* the current tag comes from the selected instrument's voiceType */
	Instrument *inst = getSelectedInstInstrument();
	const char *tag = inst ? voiceTypeTag(inst->voiceType) : "--";
	int tw = MeasureText(tag, 10);
	DrawTextEx(pixelFont, tag, (Vector2){ gn->x + (gn->w - tw) / 2, gn->y + (gn->h - 10) / 2 }, 10, 1, cs.label);
	if(gn->selected) DrawRectangleLinesEx((Rectangle){ gn->x, gn->y, gn->w, gn->h }, 2.0, cs.outlineColour);
}

/* Task 4: number of valid cursor slots for the preset name node. name[33]
 * holds 32 chars + 1 NUL. effectiveNameLen returns the exclusive upper bound
 * on the cursor index (the number of editable slots). NULL or empty name
 * returns 0 so the cursor stays pinned at slot 0. Capped at PRESET_NAME_MAX. */
/* ... holds 32 chars + 1 NUL. effectiveNameLen returns the exclusive upper bound
 * on the cursor index (the number of editable slots). NULL or empty name
 * returns 0 so the cursor stays pinned at slot 0. Capped at PRESET_NAME_MAX. */
#define PRESET_NAME_MAX 32

static int effectiveNameLen(const char *name) {
	if(!name || !name[0]) {
		return 0;
	}
	int n = (int)strlen(name);
	if(n > PRESET_NAME_MAX) {
		n = PRESET_NAME_MAX;
	}
	return n;
}

/* Task 5: cheap wall-clock frame index used by the save/error flash
 * bookkeeping in PresetNameGuiNode. raylib's GetTime returns seconds
 * since InitWindow(); multiplying by 60 gives a 60fps counter. Not
 * exactly frame-accurate (the real dt may differ), but stable enough
 * for "flash for ~0.5s after a save". Flash getters compare against
 * this with a strict `>` so the flash dies exactly at the boundary. */

static int currentFrameIndex(void) {
	return (int)(GetTime() * 60.0f);
}


bool handlePresetUiInput(InputState *is, Instrument *inst) {
	/* Task 7: while ANY overlay layer is open we route the entire input
	 * stream to the topmost layer's graph via layerStackInput. This
	 * replaces the old "is modal open" / "is load-list active" branches
	 * — those state flags are still maintained (for legacy assertions)
	 * but the input is now driven by the layer system's navigateGraph +
	 * actionCb machinery. Returning true here is critical: the rest of
	 * the instrument input must NOT run while a layer is up, otherwise
	 * arrow keys would simultaneously navigate the layer AND change
	 * instrument parameter values. */
	InstrumentGui *ig = getInstrumentGui();
	if(ig && !layerStackIsEmpty(&ig->overlayLayers)) {
		Layer *top = topLayer(&ig->overlayLayers);
		/* The ROUTELINES overlay is draw-only (Task 7): it must NOT
		 * capture the input stream — only the real modal layers do. */
		bool isPassiveOverlay = top && top->name && strcmp(top->name, "ROUTELINES") == 0;
		if(!isPassiveOverlay) {
			layerStackInput(&ig->overlayLayers, is);
			return true;
		}
	}

	/* Task 8: while the overwrite modal is up we consume ALL input and
	 * drive the modal state machine. This must run BEFORE the name-node
	 * check so a modal doesn't accidentally drop back to name editing. */
	if(g_modalState == MODAL_CONFIRM_OVERWRITE) {
		if(isKeyJustPressed(is, KM_LEFT) || isKeyJustPressed(is, KM_RIGHT)) {
			g_overwriteChoice = !g_overwriteChoice;
			return true;
		}
		if(isKeyJustPressed(is, KM_START)) {
			if(g_overwriteChoice) {
				/* User confirmed overwrite — actually overwrite now.
				 * saveInstrumentAsPresetOverwrite skips the EXISTS check
				 * and replaces the bank slot at g_pendingName. */
				saveInstrumentAsPresetOverwrite(inst, g_pendingName, "data/instrument_presets/");
				/* Task 6: after a successful overwrite, live state now
				 * matches the on-disk preset, so refresh the LoadedPreset
				 * snapshot and clear the dirty bit. */
				markInstrumentSavedAs(inst, g_pendingName);
			}
			/* Either branch: close the modal. On NO we just drop back to
			 * the name-edit screen so the user can change the name. */
			g_modalState = MODAL_NONE;
			return true;
		}
		if(isKeyJustPressed(is, KM_SELECT)) {
			/* SELECT also dismisses (same as choosing NO) — handy escape. */
			g_modalState = MODAL_NONE;
			return true;
		}
		/* Consume anything else while the modal is up so the underlying
		 * scene doesn't react to stray presses. */
		return true;
	}

	/* Task 9: while the load-list is open we hijack UP/DOWN/START/SELECT
	 * to drive list navigation. We don't need the selected node to be
	 * the load-list node — the LOAD button's callback already opened the
	 * list, and we should keep routing input to it regardless of where
	 * the user navigated in the meantime. */
	if(g_loadListActive) {
		if(g_loadList.count == 0) {
			/* Nothing to load — just close on any input and fall through. */
			guiCloseLoadList();
			return true;
		}
		if(isKeyJustPressed(is, KM_UP)) {
			g_loadList.highlight = (g_loadList.highlight + g_loadList.count - 1) % g_loadList.count;
			return true;
		}
		if(isKeyJustPressed(is, KM_DOWN)) {
			g_loadList.highlight = (g_loadList.highlight + 1) % g_loadList.count;
			return true;
		}
		if(isKeyJustPressed(is, KM_START)) {
			/* Find the highlighted preset in the bank and apply it. The
			 * name list came from the directory, so the bank's patches
			 * are 1:1 with the displayed names. */
			const char *want = g_loadList.names[g_loadList.highlight];
			if(inst && inst->presetBank) {
				for(int i = 0; i < inst->presetBank->presetCount; i++) {
					if(strcmp(inst->presetBank->patches[i].name, want) == 0) {
						applyInstrumentPreset(inst, inst->presetBank->patches[i]);
						/* Mirror the preset-selector callback pattern
						 * (see cb_setInstrumentPreset): the selector param
						 * was recreated at 0 by applyInstrumentPreset, so
						 * write the index directly to avoid re-entering
						 * the onChange callback. */
						if(inst->selectedPresetIndex) {
							inst->selectedPresetIndex->baseValue = (float)i;
							inst->selectedPresetIndex->currentValue = (float)i;
						}
						if(inst->vm) {
							inst->rebuilding = true;
							rebuildVoicesForInstrument(inst->vm, inst);
							inst->rebuilding = false;
						}
						/* NOTE: arranger->channelSlots[channel] is the
						 * authoritative "which patch this channel uses"
						 * slot for save/load sequencing. There's no
						 * backref from inst or vm to the arranger, so
						 * updating the slot from here would require a new
						 * GUI-side getter or a vm->arranger field. We
						 * skip it for now — loading updates the live
						 * instrument, and the next save-song round-trip
						 * will reconcile channelSlots when needed. */
						break;
					}
				}
			}
			guiCloseLoadList();
			return true;
		}
		if(isKeyJustPressed(is, KM_SELECT)) {
			/* Cancel without loading. */
			guiCloseLoadList();
			return true;
		}
		/* List is open but no relevant key was pressed — fall through
		 * to the rest of the instrument input path so L/R navigation
		 * (handled downstream) still works. */
		return false;
	}

	(void)inst;
	Graph *g = getSelectedInstGraph();
	GuiNode *sel = (g) ? g->selected : NULL;
	/* KM_EDIT (z) on a preset action button (SAVE/LOAD) activates it.
	 * KM_START deliberately does NOT fire buttons -- START is reserved
	 * for modal confirmation/cancel semantics. Holding KM_EDIT to fire
	 * the button mirrors the dial-edit gesture (KM_EDIT + arrow edits
	 * the selected dial); here KM_EDIT alone activates the button. */
	if(sel && isKeyJustPressed(is, KM_EDIT)) {
		/* Generic actionCb dispatch (Task 4): any selected GuiNode whose
		 * actionCb is non-NULL fires on KM_EDIT. PREV/NEXT get a follow-up
		 * rebuild so the dials re-address the freshly-built paramList; the
		 * new mod-source callbacks (cbAddModSource / cbCycleSourceType)
		 * rebuild internally and need no extra rebuild here.
		 *
		 * IMPORTANT: the callback may rebuild the graph and FREE `sel`
		 * (cbAddModSource, cbCycleSourceType, cbDeleteSource all do). So
		 * snapshot the callback pointer BEFORE firing; reading `sel` after
		 * the call is a use-after-free. */
		ActionCallback cb = sel->actionCb;
		if(cb) {
			bool needsRebuild = (cb == cbPresetPrev || cb == cbPresetNext);
			cb(sel->actionCtx);
			/* PREV/NEXT apply a preset, which rebuilds the paramList;
			 * the graph's dials still point at the freed params. Rebuild
			 * so the dials re-address the new params. cbTypePrev/cbTypeNext
			 * and the source callbacks rebuild internally. */
			if(needsRebuild) {
				rebuildInstrumentGraph();
			}
			return true;
		}
	}
	/* Task 4: edit mode is no longer auto-armed by a fresh selection. The
	 * user must press KM_EDIT to enter, and KM_EDIT/KM_SELECT to exit.
	 * Arrows cycle chars / move the cursor only while editing; when not
	 * editing they fall through to normal navigation. */
	if(!sel || !isPresetNameNode(sel)) {
		return false;
	}
	PresetNameGuiNode *pn = (PresetNameGuiNode *)sel;

	if(!pn->editing) {
		/* Selected but not editing: KM_EDIT (z) enters edit mode, KM_START
		 * commits, and arrows + KM_SELECT fall through to normal navigation. */
		if(isKeyJustPressed(is, KM_EDIT)) {
			pn->editing = true;
			return true;
		}
		if(isKeyJustPressed(is, KM_START)) {
			commitPresetName(pn);
			return true;
		}
		return false;
	}

	/* Editing: arrows cycle the active char (UP/DOWN) and move the cursor
	 * (LEFT/RIGHT, bounded to effectiveNameLen); KM_START commits; KM_EDIT
	 * and KM_SELECT toggle edit off. */
	if(isKeyJustPressed(is, KM_UP)) {
		cycleNameChar(pn, 1);
		return true;
	}
	if(isKeyJustPressed(is, KM_DOWN)) {
		cycleNameChar(pn, -1);
		return true;
	}
	if(isKeyJustPressed(is, KM_LEFT)) {
		if(pn->cursor > 0) {
			pn->cursor--;
		}
		return true;
	}
	if(isKeyJustPressed(is, KM_RIGHT)) {
		if(pn->cursor < effectiveNameLen(pn->name)) {
			pn->cursor++;
		}
		return true;
	}
	if(isKeyJustPressed(is, KM_START)) {
		/* trim + default, then run the save flow (overwrite check happens here) */
		pn->editing = false;
		commitPresetName(pn);
		return true;
	}
	if(isKeyJustPressed(is, KM_EDIT)) {
		pn->editing = false;
		return true;
	}
	if(isKeyJustPressed(is, KM_SELECT)) {
		pn->editing = false;
		return true;
	}
	return false;
}


static void drawPresetNameGuiNode(void *self) {
	PresetNameGuiNode *pn = (PresetNameGuiNode *)self;
	GuiNode *gn = (GuiNode *)pn;
	/* Task 5: pick the background tint based on which flash (if any) is
	 * active. Error flash wins over saved flash if both somehow fire in
	 * the same frame — PRESET_OK and PRESET_ERROR_* are mutually
	 * exclusive in commitPresetName, but be defensive anyway. Default
	 * is the original solid black. */
	Color bg = BLACK;
	if(currentFrameIndex() < pn->errorFlashUntil) {
		bg = cs.sampleBg;
	} else if(currentFrameIndex() < pn->savedFlashUntil) {
		bg = cs.sampleAltBg;
	}
	DrawRectangleRec((Rectangle){ gn->x, gn->y, gn->w, gn->h }, bg);
	/* Selected-but-not-editing outline: the "you can press z to edit me"
	 * affordance. The inverted cursor block already covers the editing
	 * state, so the outline is only drawn outside edit mode. */
	if(gn->selected && !pn->editing) {
		DrawRectangleLinesEx((Rectangle){ gn->x, gn->y, gn->w, gn->h }, 2.0f, cs.sampleBorder);
	}
	/* copy the current name into the node once per selection */
	int n = (int)strlen(pn->name);
	if(n < 32) {
		n = 32;
	}
	int cellW = gn->w / 32;
	if(cellW < 20) {
		cellW = 20;
	}
	for(int i = 0; i < 32; i++) {
		int cx = gn->x + i * cellW;
		int cy = gn->y;
		char ch = (i < (int)strlen(pn->name)) ? pn->name[i] : ' ';
		if(pn->editing && i == pn->cursor) {
			DrawRectangle(cx, cy, cellW, gn->h, RED);          /* inverted cursor block */
			DrawText((char[]){ ch, '\0' }, cx + 1, cy + gn->h / 2 - 15, 30, BLACK);
		} else {
			DrawText((char[]){ ch, '\0' }, cx + 1, cy + gn->h / 2 - 15, 30, RED);
		}
	}
}


static bool isPresetNameNode(GuiNode *n) {
	return n && n->draw == drawPresetNameGuiNode;
}

/* Task 5: flash getters. Strict `>` so the flash dies exactly on the
 * boundary frame. isPresetNameNode guards the downcast. */

bool presetNameGuiNodeSavedFlashActive(GuiNode *n) {
	if(!isPresetNameNode(n)) {
		return false;
	}
	PresetNameGuiNode *pn = (PresetNameGuiNode *)n;
	return currentFrameIndex() < pn->savedFlashUntil;
}


/* Task 3: KM_EDIT + arrow dispatch guard. The action button and preset
 * name / load-list nodes also live in the instrument graph; calling
 * their `callback` slot with a float delta would either be meaningless
 * (action buttons have no Parameter*) or, for the name node, dispatch
 * into a NULL/stale function pointer and crash. Only true for a real
 * dial node (drawDialGuiNode + non-NULL OnPressCallback). */

static GuiNode *createPresetNameGuiNode(int x, int y, int w, int h, Instrument *inst, bool selected) {
	PresetNameGuiNode *pn = malloc(sizeof(PresetNameGuiNode));
	if(!pn) {
		return NULL;
	}
	GuiNode *gn = (GuiNode *)pn;
	if(!initGuiNode(gn, x, y, w, h, 0, na_horizontal, "PRESET_NAME", 1, 0)) {
		free(pn);
		return NULL;
	}
	pn->inst = inst;
	memset(pn->name, 0, sizeof(pn->name));
	/* seed from the current preset's name so the node shows what's loaded */
	if(inst && inst->selectedPresetIndex && inst->presetBank) {
		int idx = getParameterValueAsInt(inst->selectedPresetIndex);
		if(idx >= 0 && idx < inst->presetBank->presetCount) {
			strncpy(pn->name, inst->presetBank->patches[idx].name, sizeof(pn->name) - 1);
		}
	}
	pn->cursor = 0;
	pn->editing = false;
	g_presetNameNode = pn;
	/* Task 5: no flash active at construction. 0 is also strictly <= any
	 * currentFrameIndex() that returns >= 0 after raylib InitWindow. */
	pn->savedFlashUntil = 0;
	pn->errorFlashUntil = 0;
	gn->drawable = true;
	gn->draw = drawPresetNameGuiNode;
	return gn;
}

/* Task 8: SAVE action. Captures the current instrument under the name
 * shown in the preset-name node (g_presetNameNode), running the same
 * commit flow as KM_START on the name node. This makes the SAVE button
 * an actual save: guiSavePreset returns PRESET_EXISTS when the name is
 * already in the bank, which opens the overwrite-confirm modal. */

static void cbFocusNameNode(void *ctx) {
	(void)ctx;
	if(g_presetNameNode) {
		commitPresetName(g_presetNameNode);
	}
}

static void cbOpenLoadList(void *ctx) {
	/* Task 6: gate the load list on the dirty bit. If the user has
	 * edits in flight, yanking the instrument away to a different
	 * preset silently throws those edits on the floor — push the
	 * dirty-confirm modal instead and let the user pick
	 * discard/save/cancel. Task 7 fills in the modal body; for now
	 * the no-op stub returns without opening the list. */
	Instrument *inst = (Instrument *)ctx;
	if(inst && isInstrumentDirty(inst)) {
		guiShowDirtyConfirmModal(inst);
		return;
	}
	guiOpenLoadList();
}

/* Task 9: scrollable preset-load-list node. The list contents live in
 * the file-static g_loadList state populated by guiOpenLoadList(); this
 * node is purely a renderer + presence-in-the-graph. Identifying the
 * node by draw fn pointer (mirroring isPresetNameNode) lets handlePresetUiInput
 * route input even when the graph's selected node has moved on. */
#define LOADLIST_VISIBLE_ROWS 6
#define LOADLIST_ROW_PX 12


static void drawPresetLoadListNode(void *self) {
	GuiNode *gn = (GuiNode *)self;
	DrawRectangleRec((Rectangle){ gn->x, gn->y, gn->w, gn->h }, BLACK);
	DrawRectangleLinesEx((Rectangle){ gn->x, gn->y, gn->w, gn->h }, 1.0f, cs.stepBorder);
	if(!g_loadListActive) {
		/* Closed: render an inert placeholder so the layout doesn't
		 * collapse in tests / harness. */
		DrawText("(CLOSED)", gn->x + 6, gn->y + 6, 10, cs.stepClosed);
		return;
	}
	int rows = LOADLIST_VISIBLE_ROWS;
	if(rows > g_loadList.count) {
		rows = g_loadList.count;
	}
	for(int i = 0; i < rows; i++) {
		int ry = gn->y + 4 + i * LOADLIST_ROW_PX;
		bool isHi = (i == g_loadList.highlight);
		if(isHi) {
			DrawRectangle(gn->x + 2, ry - 1, gn->w - 4, LOADLIST_ROW_PX - 2, RED);
		}
		Color fg = isHi ? BLACK : RED;
		const char *label = g_loadList.names[i];
		DrawText(label, gn->x + 6, ry, 10, fg);
	}
}





void appendPresetControlNode(Graph *g, GuiNode *container, char *name, int weight, bool selected, Instrument *inst) {
	GuiNode *btnwrap = createGuiNode(0, 0, 100, 100, 0, na_horizontal, "PRESET_CONTROLS", 0, 0);
	btnwrap->draw = drawWrapperNode;
	btnwrap->drawable = true;
	/* PREV/NEXT action buttons replace the old PRESET dial. The dial
	 * had display problems (it showed the modulated currentValue and
	 * swung wildly when the algo param got a coarse >-range increment)
	 * and its left/right increment semantics weren't obvious in the
	 * arcade UX. Two action buttons + a KM_EDIT fire is unambiguous. */
	GuiNode *prevBtn = createActionBtnGuiNode(0, 0, 100, 100, 2, na_horizontal, "PREV", selected, cbPresetPrev, inst);
	GuiNode *pad1 = createBlankGuiNode();
	GuiNode *nameNode = createPresetNameGuiNode(0, 0, 100, 100, inst, 0);
	GuiNode *saveBtn = createActionBtnGuiNode(0, 0, 100, 100, 2, na_horizontal, "SAVE", 0, cbFocusNameNode, inst);
	GuiNode *loadBtn = createActionBtnGuiNode(0, 0, 100, 100, 2, na_horizontal, "LOAD", 0, cbOpenLoadList, inst);
	GuiNode *nextBtn = createActionBtnGuiNode(0, 0, 100, 100, 2, na_horizontal, "NEXT", 0, cbPresetNext, inst);
	appendItem(btnwrap, prevBtn, 1);
	appendItem(btnwrap, pad1, 7);
	appendItem(btnwrap, nameNode, 4);
	appendItem(btnwrap, saveBtn, 1);
	appendItem(btnwrap, loadBtn, 1);
	appendItem(btnwrap, nextBtn, 1);
	appendItem(container, btnwrap, weight);
	/* Task 7: the preset load list is no longer a child node in the
	 * PRESET controls row. It now lives as its own overlay Layer,
	 * pushed onto ig->overlayLayers when the user opens it (see
	 * guiOpenLoadList / guiBuildLoadListLayer). The action button
	 * (loadBtn) is still here so the user can request the list, but
	 * the list itself is rendered in the overlay. */
	if(selected) {
		g->selected = prevBtn;
	}
}

/* Task 4: meta row (PREV action btn | TYPE label | NEXT action btn |
 * VOICES dial | WIDTH blank). Sits at the top of instwrap, above the
 * preset row and the voice-type-specific control row. Mirrors the
 * horizontal wrapper + action-buttons + dial layout of
 * appendPresetControlNode so the visual rhythm matches.
 *
 * PREV / NEXT are action buttons (cbTypePrev / cbTypeNext) that step
 * the focused instrument's voiceType ±1 through the 3-element ring
 * SAMPLE -> FM -> BLEP. The label cell between them is a static text
 * node (drawTypeLabelGuiNode) that re-derives its tag from the
 * currently selected instrument on every graph rebuild — PREV/NEXT
 * both call setInstrumentVoiceType + rebuildInstrumentGraph, so the
 * tag always shows the post-step type.
 *
 * VOICES is a dial bound to inst->voiceCountParam (range 1..8, created
 * in init_instrument with cb_setVoiceCount wired via createParameterPro).
 * incParameterBaseValue drives the dial; cb_setVoiceCount rebuilds the
 * channel's voice pool and writes back the snapped baseValue so the
 * dial and the actual voiceCount stay in lockstep (setChannelVoiceCount
 * clamps + rewrites, which absorbs the dial's fp jitter).
 *
 * WIDTH is a 2-weight blank placeholder reserved for a future stereo
 * width / unison-spread dial. Keeping it in the tree now preserves the
 * visual proportions of the row and the future dial just needs a swap,
 * not a layout change. (Was weight 6 in the old single-button layout;
 * the new PREV+TAG+NEXT trio eats more horizontal space so 2 is the
 * biggest weight that keeps the row from looking lopsided.)
 *
 * SELECTION: passing `selected=false` is intentional. createInstGraph
 * passes `true` only to the voice-type-specific row (appendFMInst
 * ControlNode / Sample / Blep), which assigns g->selected to its first
 * rat1/freq dial — that's the cursor position the existing fixtures
 * (preset_save_load.txt, add_route_delete.txt) navigate from. Stealing
 * selection here would re-route the cursor on every rebuild and break
 * those fixtures. */

static void appendMetaControlNode(Graph *g, GuiNode *container, Instrument *inst, VoiceManager *vm, int channel, int weight, bool selected) {
	(void)g;
	(void)channel;
	GuiNode *btnwrap = createGuiNode(0, 0, 100, 100, 2, na_horizontal, "META", 0, 0);
	btnwrap->draw = drawWrapperNode;
	btnwrap->drawable = true;

	GuiNode *prevBtn = createActionBtnGuiNode(0, 0, 100, 100, 2, na_horizontal, "TPREV", selected, cbTypePrev, vm);
	GuiNode *tag = createGuiNode(0, 0, 100, 100, 2, na_horizontal, "TYPE", 0, 0);
	tag->draw = drawTypeLabelGuiNode;
	tag->drawable = true;
	GuiNode *nextBtn = createActionBtnGuiNode(0, 0, 100, 100, 2, na_horizontal, "TNEXT", 0, cbTypeNext, vm);

	/* VOICES dial: inst->voiceCountParam was created in init_instrument
	 * (Task 6 voice.c) with onChange = cb_setVoiceCount. The default
	 * range is 1..8 (MAX_VOICES_PER_CHANNEL). incParameterBaseValue
	 * is the standard adjust callback used by every other dial in the
	 * instrument screen, so left/right + KM_EDIT+arrow work uniformly. */
	GuiNode *voicesDial = createDialGuiNode(0, 0, 100, 100, 2, na_horizontal, "VOICES", 0, incParameterBaseValue, inst->voiceCountParam);

	GuiNode *widthPad = createBlankGuiNode();

	appendItem(btnwrap, prevBtn, 1);
	appendItem(btnwrap, tag, 2);
	appendItem(btnwrap, nextBtn, 1);
	appendItem(btnwrap, voicesDial, 1);
	appendItem(btnwrap, widthPad, 2);
	appendItem(container, btnwrap, weight);
}


void rebuildInstrumentGraph(void) {
	if(!igui || !igui->vm) {
		return;
	}
	int idx = *igui->selectedInstrument;
	for(int i = 0; i < igui->instrumentCount; i++) {
		freeGuiNode(igui->instrumentScreenGraphs[i]->root);
		free(igui->instrumentScreenGraphs[i]);
		igui->instrumentScreenGraphs[i] = NULL;
	}
	for(int i = 0; i < igui->vm->enabledChannels; i++) {
		bool isSelected = (i == idx);
		igui->instrumentScreenGraphs[i] = createInstGraph(igui->vm->instruments[i], igui->vm, i, isSelected);
	}
}

/* Walk the selected GuiNode up to its mod_wrap container and remove
 * the source at the wrapped slot. Task 4 will prepend the mod-wrap
 * header row so the per-row index is offset by 1 — until then this
 * function intentionally uses idx - 1 to match the header layout that
 * Task 4 introduces (under-counts by 1 today, correct after Task 4). */

Instrument *getSelectedInstInstrument(void) {
	if(!igui || !igui->vm) {
		return NULL;
	}
	return igui->vm->instruments[*igui->selectedInstrument];
}


static void appendBlankNode(GuiNode *container, int weight) {
	GuiNode *bgn = createBlankGuiNode();
	appendItem(container, bgn, weight);
}


static Graph *createInstGraph(Instrument *inst, VoiceManager *vm, int channel, bool selected) {
	Graph *instGraph = createGraph(na_vertical);
	GuiNode *mainRow = createGuiNode(0, 0, 100, 100, 0, na_horizontal, "mainrow", 0, 0);
	GuiNode *margin1 = createBlankGuiNode();
	GuiNode *margin2 = createBlankGuiNode();
	GuiNode *presetWrap = createGuiNode(0, 0, 100, 100, 2, na_vertical, "presetwrappa", 0, 0);
	appendPresetControlNode(instGraph, presetWrap, "presetz", 2, 0, inst);
	// GuiNode *pad1 = createBlankGuiNode();
	GuiNode *pad2 = createBlankGuiNode();

	GuiNode *instwrap = createGuiNode(0, 0, 100, 100, 5, na_vertical, "inst_wrap", 0, 0);
	/* Task 4: meta row sits at the TOP of instwrap with weight 4 so it
	 * is one standard control row tall (~35px / 31px content), matching
	 * the AD-env dial row height. The old weight=1 shrank it to 4px —
	 * effectively invisible, breaking cursor navigation onto the row.
	 * presetWrap weight is dropped from 5 to 4 in the call below so
	 * both rows stay the same standard height. selected=false: never
	 * assign g->selected here, see the long comment on
	 * appendMetaControlNode for the fixture-compatibility reasoning. */
	appendMetaControlNode(instGraph, instwrap, inst, vm, channel, 5, false);
	appendItem(instwrap, presetWrap, 5);
	switch(inst->voiceType) {
		case VOICE_TYPE_FM:
			appendFMInstControlNode(instGraph, instwrap, "fmctrl", 8, true, inst);
			break;
		case VOICE_TYPE_SAMPLE:
			appendSampleInstControlNode(instGraph, instwrap, "sctrl", 8, true, inst);
			break;
		case VOICE_TYPE_BLEP:
			appendBlepInstControlNode(instGraph, instwrap, "blctrl", 8, true, inst);
			break;
	}
	appendItem(instwrap, pad2, 1);

	GuiNode *modwrap = createGuiNode(0, 0, 100, 100, 0, na_vertical, "mod_wrap", 0, 0);
	/* Header row: container label + ADD action button. */
	GuiNode *modHdr = createGuiNode(0, 0, 100, 100, 2, na_horizontal, "mods_hdr", 0, 0);
	modHdr->drawable = true;
	modHdr->draw = drawWrapperNode;
	GuiNode *modLabel = createGuiNode(0, 0, 100, 100, 2, na_horizontal, "MODS", 0, 0);
	GuiNode *modAdd = createActionBtnGuiNode(0, 0, 100, 100, 2, na_horizontal, "ADD", 0, cbAddModSource, inst);
	modAdd->name = strdup("MODS_ADD");
	appendItem(modHdr, modLabel, 4);
	appendItem(modHdr, modAdd, 1);
	appendItem(modwrap, modHdr, 1);
	for(int i = 0; i < inst->modList->count; i++) {
		appendModSourceEntry(instGraph, modwrap, inst, i, 1, false);
	}
	appendBlankNode(modwrap, 1);
	appendItem(instwrap, modwrap, 22);

	appendItem(mainRow, margin1, 1);
	appendItem(mainRow, instwrap, 18);
	appendItem(mainRow, margin2, 1);
	appendItem(instGraph->root, mainRow, 19);

	ModStripGuiNode *msgn = createModStripGuiNode(0, 0, 640, 100, vm, channel);
	if(msgn) {
		appendItem(instGraph->root, (GuiNode *)msgn, 4);
	} else {
		appendBlankNode(instGraph->root, 4);
	}
	return instGraph;
}



void gui_instrument_draw(void) {
	drawNode(igui->instrumentScreenGraphs[*igui->selectedInstrument]->root);
	if (igui) {
		/* route-lines overlay is driven by the focused selection each frame */
		syncRouteLinesOverlay(igui);
		layerStackDraw(&igui->overlayLayers);
	}
}
