/* gui_gui_pattern.c -- generated by the gui module split (lawn-mowing-gui).
 * One module per screen; shared node helpers live in gui_core.c.
 * Cross-module state/helpers: see gui_internal.h. */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "dstruct.h"
#include "raylib.h"
#include "gui.h"
#include "graph_gui.h"
#include "input.h"
#include "modsystem.h"
#include "notes.h"
#include "voice.h"
#include "io/preset_io.h"
#include "io.h"
#include "gui_internal.h"


/* ---- module-private state ---- */
static Graph *patternGraph;
static SongMinimapGui *smgui;
static BufferScroller *patternBufferScroller;

static void drawSongMinimapGui(void *self);

typedef struct {
	PatternList *pl;
	Sequencer *seq;
	int patternIndex;
	int stepIndex;
	int *selectedStepPtr;
} StepNodeData;

#define PATTERN_STEPS_PER_ROW 4

static StepNodeData stepData[MAX_SEQUENCE_LENGTH];
static GuiNode *stepNodes[MAX_SEQUENCE_LENGTH];
static PatternList *patternPl;
static Sequencer *patternSeq;
static int *patternSelectedPatternPtr;
static int *patternSelectedStepPtr;

SongMinimapGui *createSongMinimapGui(Arranger *arranger, int *songIndex, int x, int y) {
	SongMinimapGui *minimapGui = (SongMinimapGui *)malloc(sizeof(SongMinimapGui));
	minimapGui->base.draw = drawSongMinimapGui;
	minimapGui->arranger = arranger;
	minimapGui->songIndex = songIndex;
	minimapGui->shape.x = x;
	minimapGui->shape.y = y;
	minimapGui->shape.w = 4;
	minimapGui->shape.h = 4;
	minimapGui->padding = 1;
	minimapGui->maxMapLength = (SCREEN_H - 150) / (minimapGui->shape.h + minimapGui->padding);
	minimapGui->defaultCellColour = cs.defaultCell;
	minimapGui->selectedCellColour = cs.reddish;
	minimapGui->playingCellColour = cs.highlightedCell;
	minimapGui->blankCellColour = cs.blankCell;

	return minimapGui;
}



void setPatternBufferScroller(BufferScroller *bs) {
	patternBufferScroller = bs;
}


static void drawBufferScrollerNode(void *self) {
	GuiNode *gn = (GuiNode *)self;
	if(!patternBufferScroller) {
		return;
	}
	drawBufferScroller(patternBufferScroller, (Rectangle){ gn->x, gn->y, gn->w, gn->h });
}


static GuiNode *createStepNode(PatternList *pl, Sequencer *seq, int patternIndex, int stepIndex, int *selectedStepPtr) {
	GuiNode *step = createGuiNode(0, 0, 50, 50, 4, na_vertical, "step", 1, 0);
	stepData[stepIndex].pl = pl;
	stepData[stepIndex].seq = seq;
	stepData[stepIndex].patternIndex = patternIndex;
	stepData[stepIndex].stepIndex = stepIndex;
	stepData[stepIndex].selectedStepPtr = selectedStepPtr;
	step->p = (Parameter *)&stepData[stepIndex];
	step->drawable = true;
	step->draw = drawStepGuiNode;
	stepNodes[stepIndex] = step;
	return step;
}


void drawStepGuiNode(void *self) {
	GuiNode *gn = (GuiNode *)self;
	StepNodeData *d = (StepNodeData *)gn->p;
	int currentlyPlaying = -1;
	for(int i = 0; i < MAX_SEQUENCER_CHANNELS; i++) {
		if(d->seq->pattern_index[i] == d->patternIndex) {
			currentlyPlaying = i;
			break;
		}
	}
	Rectangle cell = (Rectangle){ gn->x, gn->y, gn->w, gn->h };
	if(*d->selectedStepPtr == d->stepIndex) {
		DrawRectangle(gn->x - 3, gn->y - 3, gn->w + 6, gn->h + 6, cs.outlineColour);
	}
	if(currentlyPlaying > -1 && d->seq->running[currentlyPlaying] && d->seq->playhead_index[currentlyPlaying] == d->stepIndex) {
		DrawRectangleRec(cell, cs.highlightedCell);
	} else {
		DrawRectangleRec(cell, cs.defaultCell);
	}
	int *note = getStep(d->pl, d->patternIndex, d->stepIndex);
	char *noteString = getNoteString(note[0], note[1]);
	DrawTextEx(textFont, noteString, (Vector2){ gn->x + 4, gn->y + 4 }, textFont.baseSize, 4, cs.fontColour);
}


void createPatternGraph(Sequencer *sequencer, PatternList *pl, int *selectedPattern, int *selectedStep) {
	patternPl = pl;
	patternSeq = sequencer;
	patternSelectedPatternPtr = selectedPattern;
	patternSelectedStepPtr = selectedStep;

	patternGraph = createGraph(na_vertical);
	int patternIndex = *selectedPattern;
	int size = 0;
	if(patternIndex >= 0 && patternIndex < pl->pattern_count) {
		size = pl->patterns[patternIndex].pattern_size;
	}
	int rows = (size + PATTERN_STEPS_PER_ROW - 1) / PATTERN_STEPS_PER_ROW;
	GuiNode *scrollerStrip = createGuiNode(0, 0, 640, 96, 0, na_horizontal, "scroller", 0, 0);
	scrollerStrip->drawable = true;
	scrollerStrip->draw = drawBufferScrollerNode;
	GuiNode *gridWrap = createGuiNode(10, 10, 230, 460, 6, na_vertical, "grid", 0, 0);
	for(int r = 0; r < rows; r++) {
		GuiNode *row = createGuiNode(0, 0, 100, 50, 4, na_horizontal, "row", 0, 0);
		for(int c = 0; c < PATTERN_STEPS_PER_ROW; c++) {
			int i = r * PATTERN_STEPS_PER_ROW + c;
			if(i >= size) {
				break;
			}
			appendItem(row, createStepNode(pl, sequencer, patternIndex, i, selectedStep), 1);
		}
		appendItem(gridWrap, row, 1);
	}
	appendItem(patternGraph->root, scrollerStrip, 4);
	appendItem(patternGraph->root, gridWrap, 16);
	if(size > 0) {
		int current = *selectedStep;
		if(current < 0) {
			current = 0;
		}
		if(current >= size) {
			current = size - 1;
		}
		patternGraph->selected = stepNodes[current];
		stepNodes[current]->selected = 1;
	}
}


void navigatePatternGraph(int keymapping) {
	if(!patternGraph || !patternGraph->selected) {
		return;
	}
	StepNodeData *d = (StepNodeData *)patternGraph->selected->p;
	int next = *d->selectedStepPtr;
	switch(keymapping) {
		case KM_LEFT:
			next = selectStep(d->pl, d->patternIndex, *d->selectedStepPtr - 1);
			break;
		case KM_RIGHT:
			next = selectStep(d->pl, d->patternIndex, *d->selectedStepPtr + 1);
			break;
		case KM_UP:
			next = selectStep(d->pl, d->patternIndex, *d->selectedStepPtr - PATTERN_STEPS_PER_ROW);
			break;
		case KM_DOWN:
			next = selectStep(d->pl, d->patternIndex, *d->selectedStepPtr + PATTERN_STEPS_PER_ROW);
			break;
		default:
			return;
	}
	*d->selectedStepPtr = next;
	changeGraphSelection(patternGraph, stepNodes[next]);
}


void rebuildPatternGraph() {
	if(!patternPl || !patternSeq || !patternGraph) {
		return;
	}
	freeGuiNode(patternGraph->root);
	free(patternGraph);
	patternGraph = NULL;
	createPatternGraph(patternSeq, patternPl, patternSelectedPatternPtr, patternSelectedStepPtr);
}


void setSongMinimapGui(SongMinimapGui *smg) {
	smgui = smg;
}


static void drawSongMinimapGui(void *self) {
	SongMinimapGui *smGui = (SongMinimapGui *)self;
	Arranger *arranger = (Arranger *)smGui->arranger;
	int startIndex = 0;
	// printf("coord %d,%d\n", smGui->songIndex[0], smGui->songIndex[1]);

	for(int i = startIndex; i < smGui->maxMapLength; i++) {
		int newy = smGui->shape.y + (i * smGui->shape.w) + (smGui->padding * i);
		for(int j = 0; j < MAX_SEQUENCER_CHANNELS; j++) {
			int newx = smGui->shape.x + (j * smGui->shape.h) + (smGui->padding * j);
			if(arranger->song[j][i] > -1) {
				if(smGui->songIndex[0] == j && smGui->songIndex[1] == i) {
					DrawRectangle(newx, newy, smGui->shape.w, smGui->shape.h, smGui->selectedCellColour);
				} else if(arranger->playhead_indices[j] == i) {
					DrawRectangle(newx, newy, smGui->shape.w, smGui->shape.h, smGui->playingCellColour);
				} else {
					DrawRectangle(newx, newy, smGui->shape.w, smGui->shape.h, smGui->defaultCellColour);
				}
			} else {
				DrawRectangle(newx, newy, smGui->shape.w, smGui->shape.h, smGui->blankCellColour);
			}
		}
	}
}



void gui_pattern_draw(void) {
	drawNode(patternGraph->root);
	if (smgui) {
		drawSongMinimapGui(smgui);
	}
}
