/* gui_gui_instrument.c -- generated by the gui module split (lawn-mowing-gui).
 * One module per screen; shared node helpers live in gui_core.c.
 * Cross-module state/helpers: see gui_internal.h. */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "dstruct.h"
#include "raylib.h"
#include "gui.h"
#include "graph_gui.h"
#include "input.h"
#include "modsystem.h"
#include "notes.h"
#include "voice.h"
#include "io/preset_io.h"
#include "io.h"
#include "gui_internal.h"

static void appendBlepInstControlNode(Graph *g, GuiNode *container, char *name, int weight, bool selected, Instrument *inst);
static void appendFMInstControlNode(Graph *g, GuiNode *container, char *name, int weight, bool selected, Instrument *inst);
static void appendMetaControlNode(Graph *g, GuiNode *container, Instrument *inst, VoiceManager *vm, int channel, int weight, bool selected);
static void appendSampleInstControlNode(Graph *g, GuiNode *container, char *name, int weight, bool selected, Instrument *inst);
static void cbOpenLoadList(void *ctx);
static void commitPresetName(PresetNameGuiNode *pn);
static Graph *createInstGraph(Instrument *inst, VoiceManager *vm, int channel, bool selected);
static GuiNode *createPresetNameGuiNode(int x, int y, int w, int h, Instrument *inst, bool selected);
static SampleWaveformGuiNode *createSampleWaveformGuiNode(int x, int y, int w, int h, int padding, NodeAlignment na, const char *name, bool selected, Instrument *inst, Parameter *loopStart, Parameter *loopEnd);
static void drawSampleWaveformGuiNode(void *self);
static void guiBuildDirtyConfirmLayer(InstrumentGui *ig, Instrument *inst);
static void guiBuildLoadListLayer(InstrumentGui *ig);
static void guiBuildOverwriteLayer(InstrumentGui *ig, const char *pendingName);
static void guiOpenLoadList(void);
static void guiSetOverwritePending(const char *name);
static void guiShowDirtyConfirmModal(Instrument *inst);
static bool isPresetNameNode(GuiNode *n);

/* ---- module-private state ---- */
static InstrumentGui *igui;

/* Task 8: the current preset-name node. Set on every graph build
 * (createPresetNameGuiNode). The SAVE action button uses it to commit
 * the instrument under the name currently shown. */
static PresetNameGuiNode *g_presetNameNode;


static void appendBlankNode(GuiNode *container, int weight);

static void appendBlepInstControlNode(Graph *g, GuiNode *container, char *name, int weight, bool selected, Instrument *inst);

static void appendFMInstControlNode(Graph *g, GuiNode *container, char *name, int weight, bool selected, Instrument *inst);

static void appendMetaControlNode(Graph *g, GuiNode *container, Instrument *inst, VoiceManager *vm, int channel, int weight, bool selected);

static void appendSampleInstControlNode(Graph *g, GuiNode *container, char *name, int weight, bool selected, Instrument *inst);

static void cbOpenLoadList(void *ctx);

static void commitPresetName(PresetNameGuiNode *pn);

static Graph *createInstGraph(Instrument *inst, VoiceManager *vm, int channel, bool selected);

static GuiNode *createPresetNameGuiNode(int x, int y, int w, int h, Instrument *inst, bool selected);

static SampleWaveformGuiNode *createSampleWaveformGuiNode(int x, int y, int w, int h, int padding, NodeAlignment na, const char *name, bool selected, Instrument *inst, Parameter *loopStart, Parameter *loopEnd);

static void drawSampleWaveformGuiNode(void *self);

static void guiBuildDirtyConfirmLayer(InstrumentGui *ig, Instrument *inst);

static void guiBuildLoadListLayer(InstrumentGui *ig);

static void guiBuildOverwriteLayer(InstrumentGui *ig, const char *pendingName);

static void guiOpenLoadList(void);

static void guiSetOverwritePending(const char *name);

static void guiShowDirtyConfirmModal(Instrument *inst);

static bool isPresetNameNode(GuiNode *n);

/* Task 9: preset-load-list state. g_loadList is populated by guiOpenLoadList
 * by enumerating data/instrument_presets/ .ipb files, stripping the
 * extension, and sorting alphabetically. While g_loadListActive is true,
 * handlePresetUiInput routes UP/DOWN/START/SELECT to the load-list node
 * regardless of which node is selected in the instrument graph. */
#define LOADLIST_MAX 256
#define LOADLIST_NAME_MAX 32
typedef struct {
	char names[LOADLIST_MAX][LOADLIST_NAME_MAX];
	int count;
	int highlight;
} PresetLoadList;

static PresetNameGuiNode *g_presetNameNode;


Texture2D btnOn;

Texture2D btnOff;


void createInstrumentGui(VoiceManager *vm, int *selectedInstrument, int scene) {
	InstrumentGui *ig = (InstrumentGui *)malloc(sizeof(InstrumentGui));
	if(!ig) return;
	memset(ig, 0, sizeof(InstrumentGui));
	ig->vm = vm;
	ig->selectedInstrument = selectedInstrument;

	for(int i = 0; i < vm->enabledChannels; i++) {
		bool isSelected = *selectedInstrument == i;
		ig->instrumentScreenGraphs[i] = createInstGraph(vm->instruments[i], vm, i, isSelected);
		ig->instrumentCount++;
	}
	/* Task 7: initialise the overlay layer stack. The stack starts empty;
	 * modals push layers on demand, the instrument input/draw path drains
	 * it when empty. */
	initLayerStack(&ig->overlayLayers);
	igui = ig;
}


Graph *getSelectedInstGraph() {
	return igui->instrumentScreenGraphs[*igui->selectedInstrument];
}



InstrumentGui *getInstrumentGui(void) {
	return igui;
}





MixRing *arrangerMixRing;


void drawSampleWaveLinesNode(void *self) {
	GuiNode *gn = (GuiNode *)self;
	if(!arrangerMixRing) {
		return;
	}
	drawSampleWaveLines(arrangerMixRing, (Rectangle){ gn->x, gn->y, gn->w, gn->h });
	DrawTextEx(pixelFont, "VLINE", (Vector2){ gn->x + 2, gn->y + 2 }, 9, 1, cs.vline);
}


void drawSampleWavePolylineNode(void *self) {
	GuiNode *gn = (GuiNode *)self;
	if(!arrangerMixRing) {
		return;
	}
	drawSampleWavePolyline(arrangerMixRing, (Rectangle){ gn->x, gn->y, gn->w, gn->h });
	DrawTextEx(pixelFont, "POLY", (Vector2){ gn->x + 2, gn->y + 2 }, 9, 1, cs.poly);
}


static SampleWaveformGuiNode *createSampleWaveformGuiNode(int x, int y, int w, int h, int padding, NodeAlignment na, const char *name, bool selected, Instrument *inst, Parameter *loopStart, Parameter *loopEnd) {
	SampleWaveformGuiNode *swgn = malloc(sizeof(SampleWaveformGuiNode));
	GuiNode *gn = (GuiNode *)swgn;
	if(!initGuiNode(gn, x, y, w, h, padding, na, name, 1, selected)) {
		printf("SampleWaveformGuiNode init problem, returning NULL.\n");
		return NULL;
	}

	swgn->instrument = inst;
	swgn->bgColour = cs.waveformBg;
	swgn->wfColour = cs.waveform;
	swgn->wfAltColour = cs.waveformAlt;
	swgn->loopStart = loopStart;
	swgn->loopEnd = loopEnd;

	gn->drawable = true;
	gn->draw = drawSampleWaveformGuiNode;
	return swgn;
}


static void drawSampleWaveformGuiNode(void *self) {
	SampleWaveformGuiNode *swgn = (SampleWaveformGuiNode *)self;
	GuiNode *gn = (GuiNode *)swgn;
	int yOffset = gn->h / 2;
	int sampleIndexRatio = swgn->instrument->id.sampler.sample->length / gn->w;
	float phaseInc = 1.0 / gn->w;
	DrawRectangle(gn->x, gn->y, gn->w, gn->h, swgn->bgColour);
	for(int i = 0; i < gn->w; i++) {
		float sp = i * sampleIndexRatio;
		float s = getSampleValueFwd(swgn->instrument->id.sampler.sample, &sp, phaseInc, 0);
		s *= yOffset;
		DrawLine(gn->x + i, gn->y + yOffset, gn->x + i, gn->y + yOffset + s, swgn->wfColour);
	}

	int loopStart = getParameterValueAsInt(swgn->loopStart);
	int loopEnd = getParameterValueAsInt(swgn->loopEnd);

	int nx = gn->x + loopStart / sampleIndexRatio;
	DrawLine(nx, gn->y, nx, gn->y + gn->h, swgn->wfAltColour);
	nx = gn->x + loopEnd / sampleIndexRatio;
	DrawLine(nx, gn->y, nx, gn->y + gn->h, swgn->wfAltColour);

	DrawTextEx(pixelFont, swgn->instrument->id.sampler.sample->name, (Vector2){ gn->x + gn->padding, gn->y + gn->padding }, 12, 2, swgn->wfAltColour);
}

/* Task 3: copy the (ch, row) of g->selected into the Arranger
 * state (selected_x/selected_y) and fire the selection callbacks
 * (onCellSelect + onPatternSelection) so the pattern screen + the
 * app state follow arranger navigation. Falls back to the existing
 * selected_x/selected_y if the selection isn't a cell (chip row /
 * preset row). Does NOT re-aim visibleStart — that's the job of
 * scrollArrangerWindow / scrollArrangerWindowTo / the edge-scroll
 * branch in navigateArrangerGraphTo. NULL guards make every path
 * a no-op. */

static void drawRouteDestNode(void *self) {
	GuiNode *gn = (GuiNode *)self;
	if(!gn) {
		return;
	}
	drawColourRectangle(gn->x, gn->y, gn->w, gn->h, 0.6, 3.5, gn->selected);
	Color labelColour = gn->selected ? cs.labelSelected : cs.label;
	DrawTextEx(pixelFont, gn->name, (Vector2){ gn->x + gn->padding + 4, gn->y + gn->padding + 4 }, 10, 1, labelColour);
}



const Color chipPalette[8] = {
	{ 70, 130, 180, 255 }, /* steel-blue   */
	{ 200, 120, 60, 255 }, /* amber        */
	{ 90, 160, 90, 255 },  /* moss         */
	{ 170, 80, 130, 255 }, /* mulberry     */
	{ 210, 180, 70, 255 }, /* gold         */
	{ 110, 90, 170, 255 }, /* violet       */
	{ 80, 160, 160, 255 }, /* teal         */
	{ 180, 90, 90, 255 },  /* brick        */
};


static PresetLoadList g_loadList;

static bool g_loadListActive = false;


bool guiIsLoadListActive(void) { return g_loadListActive; }

/* qsort helper: compare two fixed-width name strings lexicographically. */

static int loadListCmp(const void *a, const void *b) {
	const char *na = (const char *)a;
	const char *nb = (const char *)b;
	return strncmp(na, nb, LOADLIST_NAME_MAX);
}

/* Strip the trailing ".ipb" from a filename in-place; no-op if the
 * suffix is absent. */

static void stripIpbExtension(char *s) {
	size_t len = strlen(s);
	const char *suffix = ".ipb";
	size_t slen = strlen(suffix);
	if(len > slen && strcmp(s + len - slen, suffix) == 0) {
		s[len - slen] = '\0';
	}
}


static void guiOpenLoadList(void);


void guiOpenLoadList(void) {
	g_loadList.count = 0;
	g_loadList.highlight = 0;
	DirectoryList *dl = createDirectoryList();
	if(dl) {
		populateDirectoryList(dl, "data/instrument_presets/");
		for(size_t i = 0; i < dl->count && g_loadList.count < LOADLIST_MAX; i++) {
			/* Take only the basename so we don't show the dir prefix. */
			const char *path = dl->file_paths[i];
			const char *slash = strrchr(path, '/');
			const char *base = slash ? slash + 1 : path;
			strncpy(g_loadList.names[g_loadList.count], base, LOADLIST_NAME_MAX - 1);
			g_loadList.names[g_loadList.count][LOADLIST_NAME_MAX - 1] = '\0';
			stripIpbExtension(g_loadList.names[g_loadList.count]);
			g_loadList.count++;
		}
		freeDirectoryList(dl);
	}
	if(g_loadList.count > 1) {
		qsort(g_loadList.names, (size_t)g_loadList.count, LOADLIST_NAME_MAX, loadListCmp);
	}
	g_loadListActive = true;
	/* Task 7: also push the load-list layer so the user can navigate
	 * the presets within an overlay graph. */
	if(igui) {
		guiBuildLoadListLayer(igui);
	}
}


static void guiCloseLoadList(void) {
	g_loadListActive = false;
	if(igui) {
		popLayer(&igui->overlayLayers);
	}
}

/* Task 8: overwrite-modal state. The modal is the only modal in the app
 * (per the brief), so a single-state-machine + a pending-name slot is
 * sufficient. g_overwriteChoice is the user's current YES/NO selection
 * while the modal is up (defaults to NO = false on open). */

static ModalState g_modalState = MODAL_NONE;

static char g_pendingName[33];

static bool g_overwriteChoice; /* false = NO, true = YES */


static void guiSetOverwritePending(const char *name) {
	if(!name) {
		return;
	}
	strncpy(g_pendingName, name, sizeof(g_pendingName) - 1);
	g_pendingName[sizeof(g_pendingName) - 1] = '\0';
	g_overwriteChoice = false; /* safe default = NO */
	g_modalState = MODAL_CONFIRM_OVERWRITE;
	/* Task 7: push the overwrite-confirm layer so the user can
	 * navigate YES/NO with arrow keys + START. */
	if(igui) {
		guiBuildOverwriteLayer(igui, name);
	}
}


/* Task 6: forward decl — defined further down. Used by both
 * guiSavePreset() and the overwrite-confirmation path. */

static void markInstrumentSavedAs(Instrument *inst, const char *name);


PresetFileResult guiSavePreset(Instrument *inst, const char *name) {
	if(!inst || !name) {
		return PRESET_ERROR_FORMAT;
	}
	PresetFileResult r;
	if(inst->selectedPresetIndex) {
		int curSlot = getParameterValueAsInt(inst->selectedPresetIndex);
		if(curSlot >= inst->presetBank->presetCount) {
			/* Task 8: parked on a blank slot -- save INTO it so the
			 * bank doesn't grow past the slot the user is viewing. */
			r = saveInstrumentAsPresetToSlot(inst, name, "data/instrument_presets/", curSlot);
		} else {
			r = saveInstrumentAsPreset(inst, name, "data/instrument_presets/");
		}
	} else {
		r = saveInstrumentAsPreset(inst, name, "data/instrument_presets/");
	}
	if(r == PRESET_EXISTS) {
		/* Defer the actual overwrite to the modal: the user hasn't
		 * confirmed yet. handlePresetUiInput drives the modal and
		 * calls saveInstrumentAsPresetOverwrite() on YES. We still
		 * propagate PRESET_EXISTS to the caller (commitPresetName)
		 * so it can skip firing either flash — the modal is the UI. */
		guiSetOverwritePending(name);
	} else if(r == PRESET_OK) {
		/* Task 6: save success → live state now matches disk, so
		 * the dirty flag clears and the loaded snapshot updates
		 * to this preset's name. */
		markInstrumentSavedAs(inst, name);
	}
	return r;
}

/* Task 6 stub: full modal layer lands in Task 7. Currently this is
 * a no-op so the load-list button can call it without crashing.
 * Task 7 will replace this body with a modalState push and a
 * three-way choice (discard / save / cancel) that falls through
 * to guiOpenLoadList() on discard. */
// (removed in Task 7: real implementation is below)


static void guiShowDirtyConfirmModal(Instrument *inst) {
	if(!inst) {
		return;
	}
	/* Task 7: the dirty-confirm layer's SAVE branch uses g_pendingName,
	 * so seed it from the currently-loaded preset's name. The user
	 * edited this preset and we're offering to flush those edits to
	 * the same slot on disk. */
	strncpy(g_pendingName, inst->loaded.name, sizeof(g_pendingName) - 1);
	g_pendingName[sizeof(g_pendingName) - 1] = '\0';
	if(igui) {
		guiBuildDirtyConfirmLayer(igui, inst);
	}
}

/* Task 6 helper: after a successful save (or overwrite) the live
 * instrument now matches a specific preset on disk. Locate the slot
 * in the bank by name and stamp the LoadedPreset snapshot, which
 * also clears the dirty bit. Sharing this between the new-save
 * branch in guiSavePreset() and the overwrite branch in
 * handlePresetUiInput() keeps the two save paths from drifting. */

static void markInstrumentSavedAs(Instrument *inst, const char *name) {
	if(!inst || !name || !name[0]) {
		return;
	}
	PresetBank *pb = inst->presetBank;
	if(!pb) {
		return;
	}
	for(int i = 0; i < pb->presetCount; i++) {
		if(strncmp(pb->patches[i].name, name, sizeof(pb->patches[i].name)) == 0) {
			markPresetLoaded(inst, name);
			return;
		}
	}
}

/* Task 7: Layer-based overlay system. The three modals (overwrite,
 * dirty-confirm, load-list) each build a self-contained Graph of
 * action nodes and push it as a Layer on the instrument's overlay
 * stack. Input is routed to the topmost layer; drawing stacks
 * bottom-up. */

/* Modal-side callbacks. These close the topmost layer (pop it) and
 * perform the user-confirmed action. They store the pending state
 * in file-static globals below so they don't need to thread
 * per-layer state. */

static void cbOverwriteConfirm(void *ctx) {
	Instrument *inst = (Instrument *)ctx;
	InstrumentGui *ig = igui;
	if(inst && ig) {
		saveInstrumentAsPresetOverwrite(inst, g_pendingName, "data/instrument_presets/");
		markInstrumentSavedAs(inst, g_pendingName);
	}
	if(ig) {
		popLayer(&ig->overlayLayers);
	}
	g_modalState = MODAL_NONE;
}


static void cbOverwriteCancel(void *ctx) {
	(void)ctx;
	InstrumentGui *ig = igui;
	if(ig) {
		popLayer(&ig->overlayLayers);
	}
	g_modalState = MODAL_NONE;
}


static void cbDirtyDiscard(void *ctx) {
	Instrument *inst = (Instrument *)ctx;
	InstrumentGui *ig = igui;
	/* Discard edits and proceed straight to the load list. */
	if(inst) {
		markPresetLoaded(inst, NULL);
	}
	if(ig) {
		popLayer(&ig->overlayLayers);
	}
	if(inst) {
		guiOpenLoadList();
	}
}


static void cbDirtySave(void *ctx) {
	Instrument *inst = (Instrument *)ctx;
	InstrumentGui *ig = igui;
	/* Save with the currently-staged name. If it exists, push the
	 * overwrite layer on top of this one; otherwise commit and
	 * pop straight to the load list. */
	if(inst && inst->presetBank) {
		PresetFileResult r = saveInstrumentAsPreset(inst, g_pendingName, "data/instrument_presets/");
		if(r == PRESET_OK) {
			markInstrumentSavedAs(inst, g_pendingName);
			if(ig) {
				popLayer(&ig->overlayLayers);
			}
			guiOpenLoadList();
			return;
		}
		if(r == PRESET_EXISTS) {
			/* Replace the dirty-confirm with overwrite-confirm.
			 * Pop the dirty layer first so the overwrite layer
			 * is the only thing on the stack. */
			if(ig) {
				popLayer(&ig->overlayLayers);
			}
			guiBuildOverwriteLayer(ig, g_pendingName);
			return;
		}
	}
	/* Any other error: just close the dirty-confirm and bail. */
	if(ig) {
		popLayer(&ig->overlayLayers);
	}
}


static void cbDirtyCancel(void *ctx) {
	(void)ctx;
	InstrumentGui *ig = igui;
	if(ig) {
		popLayer(&ig->overlayLayers);
	}
}


static void cbLoadListPick(void *ctx) {
	/* ctx is the index into g_loadList.names (and inst->presetBank->patches). */
	int idx = (int)(intptr_t)ctx;
	InstrumentGui *ig = igui;
	Instrument *inst = ig ? ig->vm->instruments[*ig->selectedInstrument] : NULL;
	if(!inst || !inst->presetBank || idx < 0 || idx >= g_loadList.count) {
		if(ig) {
			popLayer(&ig->overlayLayers);
		}
		g_loadListActive = false;
		return;
	}
	if(idx < inst->presetBank->presetCount) {
		/* Task 8 slot model: the chosen preset lands in the CURRENT
		 * bank slot (the one the user had selected via PREV/NEXT), not
		 * appended somewhere new. This makes "load a preset into this
		 * blank slot" work: the blank slot (index >= presetCount) gets
		 * the loaded patch, and the selection stays on that slot. */
		int slot = getParameterValueAsInt(inst->selectedPresetIndex);
		if(slot < 0 || slot >= PRESET_BANK_SLOTS) {
			slot = 0;
		}
		inst->presetBank->patches[slot] = inst->presetBank->patches[idx];
		applyInstrumentPreset(inst, inst->presetBank->patches[slot]);
		/* Task 6: refresh the loaded-preset snapshot so dirty=false and
		 * loaded.name is set. Without this the dirty-confirm gate in
		 * cbOpenLoadList never opens because isInstrumentDirty returns
		 * false on a fresh instrument with no baseline name. */
		markPresetLoaded(inst, inst->presetBank->patches[slot].name);
		if(inst->selectedPresetIndex) {
			inst->selectedPresetIndex->baseValue = (float)slot;
			inst->selectedPresetIndex->currentValue = (float)slot;
		}
		if(inst->vm) {
			pthread_mutex_lock(&g_audioLock);
			inst->rebuilding = true;
			rebuildVoicesForInstrument(inst->vm, inst);
			inst->rebuilding = false;
			pthread_mutex_unlock(&g_audioLock);
		}
		rebuildInstrumentGraph();
	}
	if(ig) {
		popLayer(&ig->overlayLayers);
	}
	g_loadListActive = false;
}


static void cbLoadListCancel(void *ctx) {
	(void)ctx;
	InstrumentGui *ig = igui;
	if(ig) {
		popLayer(&ig->overlayLayers);
	}
	g_loadListActive = false;
}

/* Build the overwrite-confirm layer. The graph has two action
 * buttons: YES (confirms overwrite) and NO (cancels). Both pop
 * the layer; YES additionally commits the overwrite. */

static void guiBuildOverwriteLayer(InstrumentGui *ig, const char *pendingName) {
	if(!ig) {
		return;
	}
	if(pendingName) {
		strncpy(g_pendingName, pendingName, sizeof(g_pendingName) - 1);
		g_pendingName[sizeof(g_pendingName) - 1] = '\0';
	}
	g_overwriteChoice = false; /* safe default: NO */
	g_modalState = MODAL_CONFIRM_OVERWRITE;

	/* The layer's graph. We use a vertical container as the root
	 * and the two action buttons as children. The createGraph()
	 * root covers the whole screen — the actual visual panel is
	 * drawn by the layer's draw step (DrawRectangle + DrawText),
	 * not by the graph nodes themselves. Action buttons need a
	 * position and size; we give them the same y to make the
	 * horizontal nav obvious (LEFT/RIGHT). */
	Graph *g = createGraph(na_horizontal);
	const int py = (SCREEN_H - 80) / 2;
	const int px = (SCREEN_W - 280) / 2;
	GuiNode *noBtn = createActionBtnGuiNode(px + 30, py + 44, 100, 22, 0, na_horizontal, "NO", 0, cbOverwriteCancel, NULL);
	noBtn->name = strdup("OVERWRITE_NO");
	GuiNode *yesBtn = createActionBtnGuiNode(px + 150, py + 44, 100, 22, 0, na_horizontal, "YES", 0, cbOverwriteConfirm, ig->vm->instruments[*ig->selectedInstrument]);
	yesBtn->name = strdup("OVERWRITE_YES");
	appendItem(g->root, noBtn, 1);
	appendItem(g->root, yesBtn, 1);
	changeGraphSelection(g, noBtn);

	Layer *layer = createLayer(g, px, py, 280, 80, "OVERWRITE", true, true);
	pushLayer(&ig->overlayLayers, layer);
}

/* Build the dirty-confirm layer. Three-way: DISCARD, CANCEL, SAVE.
 * The graph is a single row of three action buttons. */

static void guiBuildDirtyConfirmLayer(InstrumentGui *ig, Instrument *inst) {
	if(!ig) {
		return;
	}
	(void)inst; /* inst is recovered from the ig->vm at callback time */
	g_modalState = MODAL_CONFIRM_OVERWRITE; /* keep legacy field in sync */

	Graph *g = createGraph(na_horizontal);
	const int pw = 360;
	const int ph = 70;
	const int px = (SCREEN_W - pw) / 2;
	const int py = (SCREEN_H - ph) / 2;
	GuiNode *discardBtn = createActionBtnGuiNode(px + 10, py + 38, 100, 22, 0, na_horizontal, "DISCARD", 1, cbDirtyDiscard, ig->vm->instruments[*ig->selectedInstrument]);
	GuiNode *saveBtn = createActionBtnGuiNode(px + 130, py + 38, 100, 22, 0, na_horizontal, "SAVE", 0, cbDirtySave, ig->vm->instruments[*ig->selectedInstrument]);
	GuiNode *cancelBtn = createActionBtnGuiNode(px + 250, py + 38, 100, 22, 0, na_horizontal, "CANCEL", 0, cbDirtyCancel, NULL);
	discardBtn->name = strdup("DIRTY_DISCARD");
	saveBtn->name = strdup("DIRTY_SAVE");
	cancelBtn->name = strdup("DIRTY_CANCEL");
	appendItem(g->root, discardBtn, 1);
	appendItem(g->root, saveBtn, 1);
	appendItem(g->root, cancelBtn, 1);
	g->selected = discardBtn;

	Layer *layer = createLayer(g, px, py, pw, ph, "DIRTY_CONFIRM", true, true);
	pushLayer(&ig->overlayLayers, layer);
}

/* Build the load-list layer. The graph is a vertical list of
 * action buttons, one per preset in the bank. Up/Down moves
 * through the list; START triggers cbLoadListPick with the
 * preset index. */

static void guiBuildLoadListLayer(InstrumentGui *ig) {
	if(!ig) {
		return;
	}
	g_loadListActive = true;

	Graph *g = createGraph(na_vertical);
	const int pw = 200;
	const int rowH = 14;
	const int maxRows = 8;
	int ph = (g_loadList.count < maxRows ? g_loadList.count : maxRows) * rowH + 8;
	if(ph < rowH * 2) {
		ph = rowH * 2;
	}
	const int px = (SCREEN_W - pw) / 2;
	const int py = (SCREEN_H - ph) / 2;

	int rows = g_loadList.count;
	if(rows > maxRows) {
		rows = maxRows;
	}
	GuiNode *firstEntry = NULL;
	for(int i = 0; i < rows; i++) {
		GuiNode *row = createActionBtnGuiNode(px, py + i * rowH, pw, rowH, 0, na_horizontal, g_loadList.names[i], 0, cbLoadListPick, (void *)(intptr_t)i);
		row->name = strdup(g_loadList.names[i]);
		appendItem(g->root, row, 1);
		if(!firstEntry) {
			firstEntry = row;
		}
	}
	/* Cancel/back button lives at the bottom of the list so the
	 * default selection is the first preset entry. */
	GuiNode *cancelBtn = createActionBtnGuiNode(px, py + ph - rowH, pw, rowH, 0, na_horizontal, "< BACK", 0, cbLoadListCancel, NULL);
	cancelBtn->name = strdup("LOADLIST_BACK");
	appendItem(g->root, cancelBtn, 1);
	if(firstEntry) {
		changeGraphSelection(g, firstEntry);
	} else {
		changeGraphSelection(g, cancelBtn);
	}

	Layer *layer = createLayer(g, px, py, pw, ph, "LOADLIST", true, true);
	pushLayer(&ig->overlayLayers, layer);
}


/* Task 7: stub fill. Pushed here as a layer so the LOAD button
 * gates the load list on the dirty bit (Task 6). */
// (the real guiShowDirtyConfirmModal definition is later in this file
// once getSelectedInstInstrument / guiBuildDirtyConfirmLayer are visible)


#define NAME_CHARS "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 _-. "

static int charIndex(char c) {
	if(c >= 'a' && c <= 'z') {
		c -= 32;
	}
	for(int i = 0; i < (int)strlen(NAME_CHARS); i++) {
		if(NAME_CHARS[i] == c) {
			return i;
		}
	}
	return 0;
}


static void cycleNameChar(PresetNameGuiNode *pn, int delta) {
	int idx = charIndex(pn->name[pn->cursor]);
	int count = (int)strlen(NAME_CHARS);
	idx = (idx + delta + count) % count;
	pn->name[pn->cursor] = NAME_CHARS[idx];
}

/* Task 5: forward decl so commitPresetName (defined below) can call it
 * before the static definition. The real implementation lives next to
 * effectiveNameLen further down. */

static int currentFrameIndex(void);


static void commitPresetName(PresetNameGuiNode *pn) {
	/* trim + default, then run the save flow (overwrite check happens here) */
	if(strlen(pn->name) == 0 || strspn(pn->name, " ") == strlen(pn->name)) {
		strncpy(pn->name, "UNNAMED", sizeof(pn->name) - 1);
		pn->name[sizeof(pn->name) - 1] = '\0';
	}
	/* Task 5: strip trailing spaces. The old "Xm1  " (cursor-left-padded
	 * to 32 chars) used to bypass the EXISTS check because strncmp(_,32)
	 * matched the trailing NULs of the shorter stored name. With the
	 * trim the save call below always sees the same "Xm1" the bank
	 * already holds, so PRESET_EXISTS fires and the modal opens. */
	for(int i = (int)strlen(pn->name) - 1; i >= 0 && pn->name[i] == ' '; i--) {
		pn->name[i] = '\0';
	}
	pn->editing = false;
	PresetFileResult r = guiSavePreset(pn->inst, pn->name);
	/* PRESET_OK -> green/success flash. PRESET_EXISTS is handled out of
	 * band by the modal (guiSetOverwritePending), so it's NOT an error
	 * from the user's perspective; the flash fires when the overwrite
	 * actually commits via saveInstrumentAsPresetOverwrite.
	 *
	 * Every other PresetFileResult (format / io / null arg) is a real
	 * failure — light the red error flash. */
	if(r == PRESET_OK) {
		pn->savedFlashUntil = currentFrameIndex() + 30;
	} else if(r != PRESET_EXISTS) {
		pn->errorFlashUntil = currentFrameIndex() + 30;
	}
}

/* Forward decls so handlePresetUiInput can activate the SAVE/LOAD buttons. */

static void cbFocusNameNode(void *ctx);

static void cbOpenLoadList(void *ctx);

static void cbPresetPrev(void *ctx);

static void cbPresetNext(void *ctx);
/* Task 4: forward decls for the unified mod-source container's
 * action buttons (ADD button in the mod-wrap header + TYPE cycler on
 * each runtime entry). */

static void cbAddModSource(void *ctx);

static void cbCycleSourceType(void *ctx);
/* Task 5: DEL button (per runtime entry) opens a YES/NO confirm layer
 * that, on YES, calls removeSource(inst, idx) and pops the layer. The
 * implementation lives further down, after SourceCtx is defined. */

static void cbDeleteSource(void *ctx);

/* Task 7+: PREV/NEXT action buttons. Activate on KM_EDIT (same as
 * SAVE/LOAD). The Instrument is the ctx. setParameterBaseValue triggers
 * selectedPresetIndex's onChange (cb_setInstrumentPreset) which applies
 * the new preset and rebuilds voices. */

static void cbPresetPrev(void *ctx) {
	Instrument *inst = (Instrument *)ctx;
	if(!inst || !inst->selectedPresetIndex || !inst->presetBank) {
		return;
	}
	int cur = getParameterValueAsInt(inst->selectedPresetIndex);
	if(cur > 0) {
		setParameterBaseValue(inst->selectedPresetIndex, (float)(cur - 1));
	}
}

/* Task 8: PREV/NEXT walk the full PRESET_BANK_SLOTS range, including
 * blank slots (indices >= presetCount hold a default FM patch). */

static void cbPresetNext(void *ctx) {
	Instrument *inst = (Instrument *)ctx;
	if(!inst || !inst->selectedPresetIndex || !inst->presetBank) {
		return;
	}
	int cur = getParameterValueAsInt(inst->selectedPresetIndex);
	if(cur < PRESET_BANK_SLOTS - 1) {
		setParameterBaseValue(inst->selectedPresetIndex, (float)(cur + 1));
	}
}

/* Task 6: TYPE action button cycles SAMPLE -> FM -> BLEP -> SAMPLE for the
 * currently focused instrument. ctx is the VoiceManager (the brief asks for
 * VM-resolution rather than a stored channel so the same callback can serve
 * every meta row across all channels). We locate the channel by pointer
 * identity against getSelectedInstInstrument() BEFORE the swap (because
 * setInstrumentVoiceType frees the old Instrument and replaces it). If the
 * swap succeeds we tear down + rebuild the affected instrument screen so
 * the new voice-type-specific row (appendFMInstControlNode / appendSample
 * / appendBlep) appears below the meta row, and the dial / preset bindings
 * move onto the new Instrument's params.
 *
 * Task 4: replaced by cbTypePrev / cbTypeNext (PREV/NEXT action buttons on
 * the meta row). The cycle order is identical; the old single-button
 * `cbCycleVoiceType` is gone, but the behaviour is split into ±1 steps so
 * the user can step backward if they overshoot. */

/* Task 4: voiceType cycle helpers. The META row's PREV/NEXT buttons
 * step the focused instrument's voiceType through the 3-element ring
 * SAMPLE -> FM -> BLEP (and the reverse). Exposed for the unit test
 * test_type_cycle_order (gui.h). Unknown types fall through to FM so
 * the caller's `setInstrumentVoiceType` always lands on a valid type. */

VoiceType nextVoiceType(VoiceType t) {
	switch(t) {
		case VOICE_TYPE_SAMPLE: return VOICE_TYPE_FM;
		case VOICE_TYPE_FM:     return VOICE_TYPE_BLEP;
		case VOICE_TYPE_BLEP:   return VOICE_TYPE_SAMPLE;
		default:                return VOICE_TYPE_FM;
	}
}


VoiceType prevVoiceType(VoiceType t) {
	switch(t) {
		case VOICE_TYPE_SAMPLE: return VOICE_TYPE_BLEP;
		case VOICE_TYPE_BLEP:   return VOICE_TYPE_FM;
		case VOICE_TYPE_FM:     return VOICE_TYPE_SAMPLE;
		default:                return VOICE_TYPE_FM;
	}
}

/* Task 4: resolve the channel whose Instrument is `sel` by pointer
 * identity. Returns -1 if no match. Both cbTypePrev and cbTypeNext
 * call this; the channel must be captured BEFORE setInstrumentVoiceType
 * because that call frees the old Instrument. */

static int resolveTypeChannel(VoiceManager *vm, Instrument *sel) {
	if(!vm || !sel) return -1;
	for(int i = 0; i < vm->enabledChannels; i++) {
		if(vm->instruments[i] == sel) return i;
	}
	return -1;
}


static void cbTypePrev(void *ctx) {
	VoiceManager *vm = (VoiceManager *)ctx;
	Instrument *sel = getSelectedInstInstrument();
	int ch = resolveTypeChannel(vm, sel);
	if(ch < 0) return;
	if(setInstrumentVoiceType(vm, ch, prevVoiceType(sel->voiceType))) {
		rebuildInstrumentGraph();
	}
}


static void cbTypeNext(void *ctx) {
	VoiceManager *vm = (VoiceManager *)ctx;
	Instrument *sel = getSelectedInstInstrument();
	int ch = resolveTypeChannel(vm, sel);
	if(ch < 0) return;
	if(setInstrumentVoiceType(vm, ch, nextVoiceType(sel->voiceType))) {
		rebuildInstrumentGraph();
	}
}

/* Task 4: the type-tag label drawn between the PREV and NEXT action
 * buttons on the instrument-screen META row. It's a static text node
 * (not an action button and not a dial) — the tag updates every time
 * the graph rebuilds after a PREV/NEXT click, so we re-derive it from
 * the currently focused Instrument. The selected outline matches the
 * action buttons so the cursor is visible when the user navigates onto
 * the label cell. */

static void drawTypeLabelGuiNode(void *self) {
	GuiNode *gn = (GuiNode *)self;
	/* the current tag comes from the selected instrument's voiceType */
	Instrument *inst = getSelectedInstInstrument();
	const char *tag = inst ? voiceTypeTag(inst->voiceType) : "--";
	int tw = MeasureText(tag, 10);
	DrawTextEx(pixelFont, tag, (Vector2){ gn->x + (gn->w - tw) / 2, gn->y + (gn->h - 10) / 2 }, 10, 1, cs.label);
	if(gn->selected) DrawRectangleLinesEx((Rectangle){ gn->x, gn->y, gn->w, gn->h }, 2.0, cs.outlineColour);
}

/* Task 4: number of valid cursor slots for the preset name node. name[33]
 * holds 32 chars + 1 NUL. effectiveNameLen returns the exclusive upper bound
 * on the cursor index (the number of editable slots). NULL or empty name
 * returns 0 so the cursor stays pinned at slot 0. Capped at PRESET_NAME_MAX. */
#define PRESET_NAME_MAX 32

static int effectiveNameLen(const char *name) {
	if(!name || !name[0]) {
		return 0;
	}
	int n = (int)strlen(name);
	if(n > PRESET_NAME_MAX) {
		n = PRESET_NAME_MAX;
	}
	return n;
}

/* Task 5: cheap wall-clock frame index used by the save/error flash
 * bookkeeping in PresetNameGuiNode. raylib's GetTime returns seconds
 * since InitWindow(); multiplying by 60 gives a 60fps counter. Not
 * exactly frame-accurate (the real dt may differ), but stable enough
 * for "flash for ~0.5s after a save". Flash getters compare against
 * this with a strict `>` so the flash dies exactly at the boundary. */

static int currentFrameIndex(void) {
	return (int)(GetTime() * 60.0f);
}


bool handlePresetUiInput(InputState *is, Instrument *inst) {
	/* Task 7: while ANY overlay layer is open we route the entire input
	 * stream to the topmost layer's graph via layerStackInput. This
	 * replaces the old "is modal open" / "is load-list active" branches
	 * — those state flags are still maintained (for legacy assertions)
	 * but the input is now driven by the layer system's navigateGraph +
	 * actionCb machinery. Returning true here is critical: the rest of
	 * the instrument input must NOT run while a layer is up, otherwise
	 * arrow keys would simultaneously navigate the layer AND change
	 * instrument parameter values. */
	InstrumentGui *ig = getInstrumentGui();
	if(ig && !layerStackIsEmpty(&ig->overlayLayers)) {
		Layer *top = topLayer(&ig->overlayLayers);
		/* The ROUTELINES overlay is draw-only (Task 7): it must NOT
		 * capture the input stream — only the real modal layers do. */
		bool isPassiveOverlay = top && top->name && strcmp(top->name, "ROUTELINES") == 0;
		if(!isPassiveOverlay) {
			layerStackInput(&ig->overlayLayers, is);
			return true;
		}
	}

	/* Task 8: while the overwrite modal is up we consume ALL input and
	 * drive the modal state machine. This must run BEFORE the name-node
	 * check so a modal doesn't accidentally drop back to name editing. */
	if(g_modalState == MODAL_CONFIRM_OVERWRITE) {
		if(isKeyJustPressed(is, KM_LEFT) || isKeyJustPressed(is, KM_RIGHT)) {
			g_overwriteChoice = !g_overwriteChoice;
			return true;
		}
		if(isKeyJustPressed(is, KM_START)) {
			if(g_overwriteChoice) {
				/* User confirmed overwrite — actually overwrite now.
				 * saveInstrumentAsPresetOverwrite skips the EXISTS check
				 * and replaces the bank slot at g_pendingName. */
				saveInstrumentAsPresetOverwrite(inst, g_pendingName, "data/instrument_presets/");
				/* Task 6: after a successful overwrite, live state now
				 * matches the on-disk preset, so refresh the LoadedPreset
				 * snapshot and clear the dirty bit. */
				markInstrumentSavedAs(inst, g_pendingName);
			}
			/* Either branch: close the modal. On NO we just drop back to
			 * the name-edit screen so the user can change the name. */
			g_modalState = MODAL_NONE;
			return true;
		}
		if(isKeyJustPressed(is, KM_SELECT)) {
			/* SELECT also dismisses (same as choosing NO) — handy escape. */
			g_modalState = MODAL_NONE;
			return true;
		}
		/* Consume anything else while the modal is up so the underlying
		 * scene doesn't react to stray presses. */
		return true;
	}

	/* Task 9: while the load-list is open we hijack UP/DOWN/START/SELECT
	 * to drive list navigation. We don't need the selected node to be
	 * the load-list node — the LOAD button's callback already opened the
	 * list, and we should keep routing input to it regardless of where
	 * the user navigated in the meantime. */
	if(g_loadListActive) {
		if(g_loadList.count == 0) {
			/* Nothing to load — just close on any input and fall through. */
			guiCloseLoadList();
			return true;
		}
		if(isKeyJustPressed(is, KM_UP)) {
			g_loadList.highlight = (g_loadList.highlight + g_loadList.count - 1) % g_loadList.count;
			return true;
		}
		if(isKeyJustPressed(is, KM_DOWN)) {
			g_loadList.highlight = (g_loadList.highlight + 1) % g_loadList.count;
			return true;
		}
		if(isKeyJustPressed(is, KM_START)) {
			/* Find the highlighted preset in the bank and apply it. The
			 * name list came from the directory, so the bank's patches
			 * are 1:1 with the displayed names. */
			const char *want = g_loadList.names[g_loadList.highlight];
			if(inst && inst->presetBank) {
				for(int i = 0; i < inst->presetBank->presetCount; i++) {
					if(strcmp(inst->presetBank->patches[i].name, want) == 0) {
						applyInstrumentPreset(inst, inst->presetBank->patches[i]);
						/* Mirror the preset-selector callback pattern
						 * (see cb_setInstrumentPreset): the selector param
						 * was recreated at 0 by applyInstrumentPreset, so
						 * write the index directly to avoid re-entering
						 * the onChange callback. */
						if(inst->selectedPresetIndex) {
							inst->selectedPresetIndex->baseValue = (float)i;
							inst->selectedPresetIndex->currentValue = (float)i;
						}
						if(inst->vm) {
							inst->rebuilding = true;
							rebuildVoicesForInstrument(inst->vm, inst);
							inst->rebuilding = false;
						}
						/* NOTE: arranger->channelSlots[channel] is the
						 * authoritative "which patch this channel uses"
						 * slot for save/load sequencing. There's no
						 * backref from inst or vm to the arranger, so
						 * updating the slot from here would require a new
						 * GUI-side getter or a vm->arranger field. We
						 * skip it for now — loading updates the live
						 * instrument, and the next save-song round-trip
						 * will reconcile channelSlots when needed. */
						break;
					}
				}
			}
			guiCloseLoadList();
			return true;
		}
		if(isKeyJustPressed(is, KM_SELECT)) {
			/* Cancel without loading. */
			guiCloseLoadList();
			return true;
		}
		/* List is open but no relevant key was pressed — fall through
		 * to the rest of the instrument input path so L/R navigation
		 * (handled downstream) still works. */
		return false;
	}

	(void)inst;
	Graph *g = getSelectedInstGraph();
	GuiNode *sel = (g) ? g->selected : NULL;
	/* KM_EDIT (z) on a preset action button (SAVE/LOAD) activates it.
	 * KM_START deliberately does NOT fire buttons -- START is reserved
	 * for modal confirmation/cancel semantics. Holding KM_EDIT to fire
	 * the button mirrors the dial-edit gesture (KM_EDIT + arrow edits
	 * the selected dial); here KM_EDIT alone activates the button. */
	if(sel && isKeyJustPressed(is, KM_EDIT)) {
		/* Generic actionCb dispatch (Task 4): any selected GuiNode whose
		 * actionCb is non-NULL fires on KM_EDIT. PREV/NEXT get a follow-up
		 * rebuild so the dials re-address the freshly-built paramList; the
		 * new mod-source callbacks (cbAddModSource / cbCycleSourceType)
		 * rebuild internally and need no extra rebuild here.
		 *
		 * IMPORTANT: the callback may rebuild the graph and FREE `sel`
		 * (cbAddModSource, cbCycleSourceType, cbDeleteSource all do). So
		 * snapshot the callback pointer BEFORE firing; reading `sel` after
		 * the call is a use-after-free. */
		ActionCallback cb = sel->actionCb;
		if(cb) {
			bool needsRebuild = (cb == cbPresetPrev || cb == cbPresetNext);
			cb(sel->actionCtx);
			/* PREV/NEXT apply a preset, which rebuilds the paramList;
			 * the graph's dials still point at the freed params. Rebuild
			 * so the dials re-address the new params. cbTypePrev/cbTypeNext
			 * and the source callbacks rebuild internally. */
			if(needsRebuild) {
				rebuildInstrumentGraph();
			}
			return true;
		}
	}
	/* Task 4: edit mode is no longer auto-armed by a fresh selection. The
	 * user must press KM_EDIT to enter, and KM_EDIT/KM_SELECT to exit.
	 * Arrows cycle chars / move the cursor only while editing; when not
	 * editing they fall through to normal navigation. */
	if(!sel || !isPresetNameNode(sel)) {
		return false;
	}
	PresetNameGuiNode *pn = (PresetNameGuiNode *)sel;

	if(!pn->editing) {
		/* Selected but not editing: KM_EDIT (z) enters edit mode, KM_START
		 * commits, and arrows + KM_SELECT fall through to normal navigation. */
		if(isKeyJustPressed(is, KM_EDIT)) {
			pn->editing = true;
			return true;
		}
		if(isKeyJustPressed(is, KM_START)) {
			commitPresetName(pn);
			return true;
		}
		return false;
	}

	/* Editing: arrows cycle the active char (UP/DOWN) and move the cursor
	 * (LEFT/RIGHT, bounded to effectiveNameLen); KM_START commits; KM_EDIT
	 * and KM_SELECT toggle edit off. */
	if(isKeyJustPressed(is, KM_UP)) {
		cycleNameChar(pn, 1);
		return true;
	}
	if(isKeyJustPressed(is, KM_DOWN)) {
		cycleNameChar(pn, -1);
		return true;
	}
	if(isKeyJustPressed(is, KM_LEFT)) {
		if(pn->cursor > 0) {
			pn->cursor--;
		}
		return true;
	}
	if(isKeyJustPressed(is, KM_RIGHT)) {
		if(pn->cursor < effectiveNameLen(pn->name)) {
			pn->cursor++;
		}
		return true;
	}
	if(isKeyJustPressed(is, KM_START)) {
		/* trim + default, then run the save flow (overwrite check happens here) */
		pn->editing = false;
		commitPresetName(pn);
		return true;
	}
	if(isKeyJustPressed(is, KM_EDIT)) {
		pn->editing = false;
		return true;
	}
	if(isKeyJustPressed(is, KM_SELECT)) {
		pn->editing = false;
		return true;
	}
	return false;
}


static void drawPresetNameGuiNode(void *self) {
	PresetNameGuiNode *pn = (PresetNameGuiNode *)self;
	GuiNode *gn = (GuiNode *)pn;
	/* Task 5: pick the background tint based on which flash (if any) is
	 * active. Error flash wins over saved flash if both somehow fire in
	 * the same frame — PRESET_OK and PRESET_ERROR_* are mutually
	 * exclusive in commitPresetName, but be defensive anyway. Default
	 * is the original solid black. */
	Color bg = BLACK;
	if(currentFrameIndex() < pn->errorFlashUntil) {
		bg = cs.sampleBg;
	} else if(currentFrameIndex() < pn->savedFlashUntil) {
		bg = cs.sampleAltBg;
	}
	DrawRectangleRec((Rectangle){ gn->x, gn->y, gn->w, gn->h }, bg);
	/* Selected-but-not-editing outline: the "you can press z to edit me"
	 * affordance. The inverted cursor block already covers the editing
	 * state, so the outline is only drawn outside edit mode. */
	if(gn->selected && !pn->editing) {
		DrawRectangleLinesEx((Rectangle){ gn->x, gn->y, gn->w, gn->h }, 2.0f, cs.sampleBorder);
	}
	/* copy the current name into the node once per selection */
	int n = (int)strlen(pn->name);
	if(n < 32) {
		n = 32;
	}
	int cellW = gn->w / 32;
	if(cellW < 20) {
		cellW = 20;
	}
	for(int i = 0; i < 32; i++) {
		int cx = gn->x + i * cellW;
		int cy = gn->y;
		char ch = (i < (int)strlen(pn->name)) ? pn->name[i] : ' ';
		if(pn->editing && i == pn->cursor) {
			DrawRectangle(cx, cy, cellW, gn->h, RED);          /* inverted cursor block */
			DrawText((char[]){ ch, '\0' }, cx + 1, cy + gn->h / 2 - 15, 30, BLACK);
		} else {
			DrawText((char[]){ ch, '\0' }, cx + 1, cy + gn->h / 2 - 15, 30, RED);
		}
	}
}


static bool isPresetNameNode(GuiNode *n) {
	return n && n->draw == drawPresetNameGuiNode;
}

/* Task 5: flash getters. Strict `>` so the flash dies exactly on the
 * boundary frame. isPresetNameNode guards the downcast. */

bool presetNameGuiNodeSavedFlashActive(GuiNode *n) {
	if(!isPresetNameNode(n)) {
		return false;
	}
	PresetNameGuiNode *pn = (PresetNameGuiNode *)n;
	return currentFrameIndex() < pn->savedFlashUntil;
}


/* Task 3: KM_EDIT + arrow dispatch guard. The action button and preset
 * name / load-list nodes also live in the instrument graph; calling
 * their `callback` slot with a float delta would either be meaningless
 * (action buttons have no Parameter*) or, for the name node, dispatch
 * into a NULL/stale function pointer and crash. Only true for a real
 * dial node (drawDialGuiNode + non-NULL OnPressCallback). */

static GuiNode *createPresetNameGuiNode(int x, int y, int w, int h, Instrument *inst, bool selected) {
	PresetNameGuiNode *pn = malloc(sizeof(PresetNameGuiNode));
	if(!pn) {
		return NULL;
	}
	GuiNode *gn = (GuiNode *)pn;
	if(!initGuiNode(gn, x, y, w, h, 0, na_horizontal, "PRESET_NAME", 1, 0)) {
		free(pn);
		return NULL;
	}
	pn->inst = inst;
	memset(pn->name, 0, sizeof(pn->name));
	/* seed from the current preset's name so the node shows what's loaded */
	if(inst && inst->selectedPresetIndex && inst->presetBank) {
		int idx = getParameterValueAsInt(inst->selectedPresetIndex);
		if(idx >= 0 && idx < inst->presetBank->presetCount) {
			strncpy(pn->name, inst->presetBank->patches[idx].name, sizeof(pn->name) - 1);
		}
	}
	pn->cursor = 0;
	pn->editing = false;
	g_presetNameNode = pn;
	/* Task 5: no flash active at construction. 0 is also strictly <= any
	 * currentFrameIndex() that returns >= 0 after raylib InitWindow. */
	pn->savedFlashUntil = 0;
	pn->errorFlashUntil = 0;
	gn->drawable = true;
	gn->draw = drawPresetNameGuiNode;
	return gn;
}

/* Task 8: SAVE action. Captures the current instrument under the name
 * shown in the preset-name node (g_presetNameNode), running the same
 * commit flow as KM_START on the name node. This makes the SAVE button
 * an actual save: guiSavePreset returns PRESET_EXISTS when the name is
 * already in the bank, which opens the overwrite-confirm modal. */

static void cbFocusNameNode(void *ctx) {
	(void)ctx;
	if(g_presetNameNode) {
		commitPresetName(g_presetNameNode);
	}
}

static void cbOpenLoadList(void *ctx) {
	/* Task 6: gate the load list on the dirty bit. If the user has
	 * edits in flight, yanking the instrument away to a different
	 * preset silently throws those edits on the floor — push the
	 * dirty-confirm modal instead and let the user pick
	 * discard/save/cancel. Task 7 fills in the modal body; for now
	 * the no-op stub returns without opening the list. */
	Instrument *inst = (Instrument *)ctx;
	if(inst && isInstrumentDirty(inst)) {
		guiShowDirtyConfirmModal(inst);
		return;
	}
	guiOpenLoadList();
}

/* Task 9: scrollable preset-load-list node. The list contents live in
 * the file-static g_loadList state populated by guiOpenLoadList(); this
 * node is purely a renderer + presence-in-the-graph. Identifying the
 * node by draw fn pointer (mirroring isPresetNameNode) lets handlePresetUiInput
 * route input even when the graph's selected node has moved on. */
#define LOADLIST_VISIBLE_ROWS 6
#define LOADLIST_ROW_PX 12


static void drawPresetLoadListNode(void *self) {
	GuiNode *gn = (GuiNode *)self;
	DrawRectangleRec((Rectangle){ gn->x, gn->y, gn->w, gn->h }, BLACK);
	DrawRectangleLinesEx((Rectangle){ gn->x, gn->y, gn->w, gn->h }, 1.0f, cs.stepBorder);
	if(!g_loadListActive) {
		/* Closed: render an inert placeholder so the layout doesn't
		 * collapse in tests / harness. */
		DrawText("(CLOSED)", gn->x + 6, gn->y + 6, 10, cs.stepClosed);
		return;
	}
	int rows = LOADLIST_VISIBLE_ROWS;
	if(rows > g_loadList.count) {
		rows = g_loadList.count;
	}
	for(int i = 0; i < rows; i++) {
		int ry = gn->y + 4 + i * LOADLIST_ROW_PX;
		bool isHi = (i == g_loadList.highlight);
		if(isHi) {
			DrawRectangle(gn->x + 2, ry - 1, gn->w - 4, LOADLIST_ROW_PX - 2, RED);
		}
		Color fg = isHi ? BLACK : RED;
		const char *label = g_loadList.names[i];
		DrawText(label, gn->x + 6, ry, 10, fg);
	}
}





void appendPresetControlNode(Graph *g, GuiNode *container, char *name, int weight, bool selected, Instrument *inst) {
	GuiNode *btnwrap = createGuiNode(0, 0, 100, 100, 0, na_horizontal, "PRESET_CONTROLS", 0, 0);
	btnwrap->draw = drawWrapperNode;
	btnwrap->drawable = true;
	/* PREV/NEXT action buttons replace the old PRESET dial. The dial
	 * had display problems (it showed the modulated currentValue and
	 * swung wildly when the algo param got a coarse >-range increment)
	 * and its left/right increment semantics weren't obvious in the
	 * arcade UX. Two action buttons + a KM_EDIT fire is unambiguous. */
	GuiNode *prevBtn = createActionBtnGuiNode(0, 0, 100, 100, 2, na_horizontal, "PREV", selected, cbPresetPrev, inst);
	GuiNode *pad1 = createBlankGuiNode();
	GuiNode *nameNode = createPresetNameGuiNode(0, 0, 100, 100, inst, 0);
	GuiNode *saveBtn = createActionBtnGuiNode(0, 0, 100, 100, 2, na_horizontal, "SAVE", 0, cbFocusNameNode, inst);
	GuiNode *loadBtn = createActionBtnGuiNode(0, 0, 100, 100, 2, na_horizontal, "LOAD", 0, cbOpenLoadList, inst);
	GuiNode *nextBtn = createActionBtnGuiNode(0, 0, 100, 100, 2, na_horizontal, "NEXT", 0, cbPresetNext, inst);
	appendItem(btnwrap, prevBtn, 1);
	appendItem(btnwrap, pad1, 7);
	appendItem(btnwrap, nameNode, 4);
	appendItem(btnwrap, saveBtn, 1);
	appendItem(btnwrap, loadBtn, 1);
	appendItem(btnwrap, nextBtn, 1);
	appendItem(container, btnwrap, weight);
	/* Task 7: the preset load list is no longer a child node in the
	 * PRESET controls row. It now lives as its own overlay Layer,
	 * pushed onto ig->overlayLayers when the user opens it (see
	 * guiOpenLoadList / guiBuildLoadListLayer). The action button
	 * (loadBtn) is still here so the user can request the list, but
	 * the list itself is rendered in the overlay. */
	if(selected) {
		g->selected = prevBtn;
	}
}

/* Task 4: meta row (PREV action btn | TYPE label | NEXT action btn |
 * VOICES dial | WIDTH blank). Sits at the top of instwrap, above the
 * preset row and the voice-type-specific control row. Mirrors the
 * horizontal wrapper + action-buttons + dial layout of
 * appendPresetControlNode so the visual rhythm matches.
 *
 * PREV / NEXT are action buttons (cbTypePrev / cbTypeNext) that step
 * the focused instrument's voiceType ±1 through the 3-element ring
 * SAMPLE -> FM -> BLEP. The label cell between them is a static text
 * node (drawTypeLabelGuiNode) that re-derives its tag from the
 * currently selected instrument on every graph rebuild — PREV/NEXT
 * both call setInstrumentVoiceType + rebuildInstrumentGraph, so the
 * tag always shows the post-step type.
 *
 * VOICES is a dial bound to inst->voiceCountParam (range 1..8, created
 * in init_instrument with cb_setVoiceCount wired via createParameterPro).
 * incParameterBaseValue drives the dial; cb_setVoiceCount rebuilds the
 * channel's voice pool and writes back the snapped baseValue so the
 * dial and the actual voiceCount stay in lockstep (setChannelVoiceCount
 * clamps + rewrites, which absorbs the dial's fp jitter).
 *
 * WIDTH is a 2-weight blank placeholder reserved for a future stereo
 * width / unison-spread dial. Keeping it in the tree now preserves the
 * visual proportions of the row and the future dial just needs a swap,
 * not a layout change. (Was weight 6 in the old single-button layout;
 * the new PREV+TAG+NEXT trio eats more horizontal space so 2 is the
 * biggest weight that keeps the row from looking lopsided.)
 *
 * SELECTION: passing `selected=false` is intentional. createInstGraph
 * passes `true` only to the voice-type-specific row (appendFMInst
 * ControlNode / Sample / Blep), which assigns g->selected to its first
 * rat1/freq dial — that's the cursor position the existing fixtures
 * (preset_save_load.txt, add_route_delete.txt) navigate from. Stealing
 * selection here would re-route the cursor on every rebuild and break
 * those fixtures. */

static void appendMetaControlNode(Graph *g, GuiNode *container, Instrument *inst, VoiceManager *vm, int channel, int weight, bool selected) {
	(void)g;
	(void)channel;
	GuiNode *btnwrap = createGuiNode(0, 0, 100, 100, 2, na_horizontal, "META", 0, 0);
	btnwrap->draw = drawWrapperNode;
	btnwrap->drawable = true;

	GuiNode *prevBtn = createActionBtnGuiNode(0, 0, 100, 100, 2, na_horizontal, "TPREV", selected, cbTypePrev, vm);
	GuiNode *tag = createGuiNode(0, 0, 100, 100, 2, na_horizontal, "TYPE", 0, 0);
	tag->draw = drawTypeLabelGuiNode;
	tag->drawable = true;
	GuiNode *nextBtn = createActionBtnGuiNode(0, 0, 100, 100, 2, na_horizontal, "TNEXT", 0, cbTypeNext, vm);

	/* VOICES dial: inst->voiceCountParam was created in init_instrument
	 * (Task 6 voice.c) with onChange = cb_setVoiceCount. The default
	 * range is 1..8 (MAX_VOICES_PER_CHANNEL). incParameterBaseValue
	 * is the standard adjust callback used by every other dial in the
	 * instrument screen, so left/right + KM_EDIT+arrow work uniformly. */
	GuiNode *voicesDial = createDialGuiNode(0, 0, 100, 100, 2, na_horizontal, "VOICES", 0, incParameterBaseValue, inst->voiceCountParam);

	GuiNode *widthPad = createBlankGuiNode();

	appendItem(btnwrap, prevBtn, 1);
	appendItem(btnwrap, tag, 2);
	appendItem(btnwrap, nextBtn, 1);
	appendItem(btnwrap, voicesDial, 1);
	appendItem(btnwrap, widthPad, 2);
	appendItem(container, btnwrap, weight);
}


static void appendFMInstControlNode(Graph *g, GuiNode *container, char *name, int weight, bool selected, Instrument *inst) {
	GuiNode *btnwrap = createGuiNode(0, 0, 100, 100, 0, na_vertical, "FM_CONTROLS", 0, 0);
	btnwrap->draw = drawWrapperNode;
	btnwrap->drawable = true;

	GuiNode *btnrow1 = createGuiNode(0, 0, 100, 100, 2, na_horizontal, "R_1", 0, 0);
	GuiNode *btnrow2 = createGuiNode(0, 0, 100, 100, 2, na_horizontal, "R_2", 0, 0);

	GuiNode *rat1 = createDialGuiNode(0, 0, 100, 100, 2, na_horizontal, "RATIO1", 1, incParameterBaseValue, inst->id.fm.ops[0]->ratio);
	GuiNode *fb1 = createDialGuiNode(0, 0, 100, 100, 2, na_horizontal, "FEEDBACK1", 0, incParameterBaseValue, inst->id.fm.ops[0]->feedbackAmount);
	GuiNode *lvl1 = createDialGuiNode(0, 0, 100, 100, 2, na_horizontal, "LEVEL1", 0, incParameterBaseValue, inst->id.fm.ops[0]->level);
	GuiNode *rat2 = createDialGuiNode(0, 0, 100, 100, 2, na_horizontal, "RATIO2", 0, incParameterBaseValue, inst->id.fm.ops[1]->ratio);
	GuiNode *fb2 = createDialGuiNode(0, 0, 100, 100, 2, na_horizontal, "FEEDBACK2", 0, incParameterBaseValue, inst->id.fm.ops[1]->feedbackAmount);
	GuiNode *lvl2 = createDialGuiNode(0, 0, 100, 100, 2, na_horizontal, "LEVEL2", 0, incParameterBaseValue, inst->id.fm.ops[1]->level);
	GuiNode *rat3 = createDialGuiNode(0, 0, 100, 100, 2, na_horizontal, "RATIO3", 0, incParameterBaseValue, inst->id.fm.ops[2]->ratio);
	GuiNode *fb3 = createDialGuiNode(0, 0, 100, 100, 2, na_horizontal, "FEEDBACK3", 0, incParameterBaseValue, inst->id.fm.ops[2]->feedbackAmount);
	GuiNode *lvl3 = createDialGuiNode(0, 0, 100, 100, 2, na_horizontal, "LEVEL3", 0, incParameterBaseValue, inst->id.fm.ops[2]->level);
	GuiNode *rat4 = createDialGuiNode(0, 0, 100, 100, 2, na_horizontal, "RATIO4", 0, incParameterBaseValue, inst->id.fm.ops[3]->ratio);
	GuiNode *fb4 = createDialGuiNode(0, 0, 100, 100, 2, na_horizontal, "FEEDBACK4", 0, incParameterBaseValue, inst->id.fm.ops[3]->feedbackAmount);
	GuiNode *lvl4 = createDialGuiNode(0, 0, 100, 100, 2, na_horizontal, "LEVEL4", 0, incParameterBaseValue, inst->id.fm.ops[3]->level);
	GuiNode *alg = createDialGuiNode(0, 0, 100, 100, 2, na_horizontal, "ALG", 0, incParameterBaseValue, inst->id.fm.selectedAlgorithm);
	GuiNode *pan = createDialGuiNode(0, 0, 100, 100, 2, na_horizontal, "PAN", 0, incParameterBaseValue, inst->panning);
	alg->draw = drawDiscreteDialGuiNode;
	pan->draw = drawDiscreteDialGuiNode;
	if(selected) {
		g->selected = rat1;
	}

	GuiNode *sp1 = createBlankGuiNode();
	GuiNode *sp2 = createBlankGuiNode();
	GuiNode *sp4 = createBlankGuiNode();
	GuiNode *sp5 = createBlankGuiNode();

	appendItem(btnrow1, rat1, 40);
	appendItem(btnrow1, fb1, 40);
	appendItem(btnrow1, lvl1, 40);
	appendItem(btnrow1, sp1, 5);
	appendItem(btnrow1, rat2, 40);
	appendItem(btnrow1, fb2, 40);
	appendItem(btnrow1, lvl2, 40);
	appendItem(btnrow1, sp2, 5);
	appendItem(btnrow1, pan, 20);

	appendItem(btnrow2, rat3, 40);
	appendItem(btnrow2, fb3, 40);
	appendItem(btnrow2, lvl3, 40);
	appendItem(btnrow2, sp4, 5);
	appendItem(btnrow2, rat4, 40);
	appendItem(btnrow2, fb4, 40);
	appendItem(btnrow2, lvl4, 40);
	appendItem(btnrow2, sp5, 5);
	appendItem(btnrow2, alg, 20);

	appendItem(btnwrap, btnrow1, 1);
	appendItem(btnwrap, btnrow2, 1);

	appendItem(container, btnwrap, weight);
}


static void appendSampleInstControlNode(Graph *g, GuiNode *container, char *name, int weight, bool selected, Instrument *inst) {
	GuiNode *btnwrap = createGuiNode(0, 0, 100, 100, 0, na_vertical, "SAMPLE_CONTROLS", 0, 0);
	btnwrap->draw = drawWrapperNode;
	btnwrap->drawable = true;

	GuiNode *btnrow1 = createGuiNode(0, 0, 100, 100, 2, na_horizontal, "R_1", 0, 0);
	GuiNode *btnrow2 = createGuiNode(0, 0, 100, 100, 2, na_horizontal, "R_2", 0, 0);

	GuiNode *sampleIndex = createDialGuiNode(0, 0, 100, 100, 5, na_horizontal, "SAMPLE", selected, incParameterBaseValue, inst->id.sampler.sampleIndex);
	GuiNode *pan = createDialGuiNode(0, 0, 100, 100, 5, na_horizontal, "PAN", 0, incParameterBaseValue, inst->panning);
	GuiNode *loop = createDialGuiNode(0, 0, 100, 100, 5, na_horizontal, "LOOP", 0, incParameterBaseValue, inst->id.sampler.loopSample);
	pan->draw = drawDiscreteDialGuiNode;
	GuiNode *loopStart = createDialGuiNode(0, 0, 100, 100, 5, na_horizontal, "START", 0, incParameterBaseValue, inst->id.sampler.loopStartIndex);
	GuiNode *loopEnd = createDialGuiNode(0, 0, 100, 100, 5, na_horizontal, "END", 0, incParameterBaseValue, inst->id.sampler.loopEndIndex);
	GuiNode *playbackType = createDialGuiNode(0, 0, 100, 100, 5, na_horizontal, "PLAYBACK", 0, incParameterBaseValue, inst->id.sampler.playbackType);
	SampleWaveformGuiNode *swgn = createSampleWaveformGuiNode(0, 0, 100, 100, 5, na_vertical, "WFRM", 0, inst, inst->id.sampler.loopStartIndex, inst->id.sampler.loopEndIndex);
	if(selected) {
		g->selected = sampleIndex;
	}

	GuiNode *sp1 = createBlankGuiNode();
	GuiNode *sp2 = createBlankGuiNode();

	appendItem(btnrow1, sampleIndex, 1);
	appendItem(btnrow1, pan, 1);
	appendItem(btnrow1, loop, 1);
	appendItem(btnrow1, loopStart, 1);
	appendItem(btnrow1, loopEnd, 1);
	appendItem(btnrow1, playbackType, 1);
	appendItem(btnrow1, sp1, 2);

	appendItem(btnrow2, (GuiNode *)swgn, 3);
	appendItem(btnrow2, sp2, 1);

	appendItem(btnwrap, btnrow1, 1);
	appendItem(btnwrap, btnrow2, 1);

	appendItem(container, btnwrap, weight);
}


static void appendBlepInstControlNode(Graph *g, GuiNode *container, char *name, int weight, bool selected, Instrument *inst) {
	GuiNode *btnwrap = createGuiNode(0, 0, 100, 100, 0, na_vertical, "SAMPLE_CONTROLS", 0, 0);
	btnwrap->draw = drawWrapperNode;
	btnwrap->drawable = true;

	GuiNode *btnrow1 = createGuiNode(0, 0, 100, 100, 2, na_horizontal, "R_1", 0, 0);
	GuiNode *btnrow2 = createGuiNode(0, 0, 100, 100, 2, na_horizontal, "R_2", 0, 0);

	GuiNode *waveShape = createDialGuiNode(0, 0, 100, 100, 5, na_horizontal, "SHAPE", selected, incParameterBaseValue, inst->id.blep.shape);
	GuiNode *pan = createDialGuiNode(0, 0, 100, 100, 5, na_horizontal, "PAN", 0, incParameterBaseValue, inst->panning);
	pan->draw = drawDiscreteDialGuiNode;

	if(selected) {
		g->selected = waveShape;
	}

	GuiNode *sp1 = createBlankGuiNode();
	GuiNode *sp2 = createBlankGuiNode();

	appendItem(btnrow1, waveShape, 1);
	appendItem(btnrow1, pan, 1);
	appendItem(btnrow1, sp1, 4);

	appendItem(btnrow2, sp2, 1);

	appendItem(btnwrap, btnrow1, 1);
	appendItem(btnwrap, btnrow2, 1);

	appendItem(container, btnwrap, weight);
}




void addRuntimeSource(Instrument *inst) {
	if(!inst || !inst->modList || inst->modList->count >= MAX_ENVELOPES) {
		return;
	}
	/* Task 8: the audio thread iterates inst->paramList/modList every
	 * buffer; hold the rebuilding flag while we mutate the lists. The
	 * audio lock closes the flag's check-then-use race. */
	pthread_mutex_lock(&g_audioLock);
	inst->rebuilding = true;
	Envelope *env = createAD(inst->paramList, inst->modList, 0.25f, 4.25f, "AD+");
	/* Task 3 fix: mirror the freshly-created envelope into inst->envelopes[]
	 * BEFORE syncing envelopeCount, so the old builder's rebuildInstrumentGraph
	 * call below can dereference inst->envelopes[envIndex] safely. Task 4 will
	 * replace this builder with a modList-based one and the mirror goes away. */
	if(env && inst->envelopeCount < MAX_ENVELOPES) {
		inst->envelopes[inst->envelopeCount] = env;
	}
	/* Task 3: envelopeCount now mirrors modList->count so the harness
	 * ASSERT envcount reads the synced value. */
	inst->envelopeCount = inst->modList->count;
	rebuildInstrumentGraph();
	inst->rebuilding = false;
	pthread_mutex_unlock(&g_audioLock);
}


void removeSource(Instrument *inst, int srcIndex) {
	if(!inst || !inst->modList || srcIndex < inst->coreEnvelopeCount || srcIndex >= inst->modList->count) {
		return;
	}
	/* Task 8: hold the rebuilding flag while we mutate + free from the
	 * modList/paramList the audio thread iterates. The audio lock
	 * closes the flag's check-then-use race. */
	pthread_mutex_lock(&g_audioLock);
	inst->rebuilding = true;
	removeMod(inst->modList, inst->paramList, inst->modList->mods[srcIndex]);
	/* Task 3 fix: clear the mirror slot so the old builder's
	 * rebuildInstrumentGraph does not deref a freed envelope. Task 4 will
	 * remove the mirror entirely when it replaces the builder. */
	if(srcIndex < MAX_ENVELOPES) {
		inst->envelopes[srcIndex] = NULL;
	}
	/* Task 3: keep envelopeCount synced with modList->count. */
	inst->envelopeCount = inst->modList->count;
	rebuildInstrumentGraph();
	inst->rebuilding = false;
	pthread_mutex_unlock(&g_audioLock);
}


void rebuildInstrumentGraph(void) {
	if(!igui || !igui->vm) {
		return;
	}
	int idx = *igui->selectedInstrument;
	for(int i = 0; i < igui->instrumentCount; i++) {
		freeGuiNode(igui->instrumentScreenGraphs[i]->root);
		free(igui->instrumentScreenGraphs[i]);
		igui->instrumentScreenGraphs[i] = NULL;
	}
	for(int i = 0; i < igui->vm->enabledChannels; i++) {
		bool isSelected = (i == idx);
		igui->instrumentScreenGraphs[i] = createInstGraph(igui->vm->instruments[i], igui->vm, i, isSelected);
	}
}

/* Walk the selected GuiNode up to its mod_wrap container and remove
 * the source at the wrapped slot. Task 4 will prepend the mod-wrap
 * header row so the per-row index is offset by 1 — until then this
 * function intentionally uses idx - 1 to match the header layout that
 * Task 4 introduces (under-counts by 1 today, correct after Task 4). */

void removeSelectedSource(void) {
	if(!igui || !igui->vm || !igui->selectedInstrument) {
		return;
	}
	GuiNode *sel = getSelectedInstGraph()->selected;
	if(!sel) {
		return;
	}
	GuiNode *n = sel;
	while(n && n->container) {
		if(strcmp(n->container->name, "mod_wrap") == 0) {
			int idx = 0;
			ListElement *l = n->container->items->head;
			while(l && *(GuiNode **)l->data != n) {
				idx++;
				l = l->next;
			}
			Instrument *inst = igui->vm->instruments[*igui->selectedInstrument];
			/* idx - 1: account for the mod-wrap header row that Task 4
			 * adds. With the header absent the mapping currently
			 * under-counts by 1; that is intentional and matches the
			 * brief's transitional note. */
			removeSource(inst, idx - 1);
			return;
		}
		n = n->container;
	}
}

/* Compatibility wrapper — preserves the no-header mapping that existed
 * before Task 3, used by callers that have not yet been ported to the
 * header-offset index used by removeSelectedSource. */

void removeSelectedEnvelope(void) {
	if(!igui || !igui->vm || !igui->selectedInstrument) {
		return;
	}
	GuiNode *sel = getSelectedInstGraph()->selected;
	if(!sel) {
		return;
	}
	GuiNode *n = sel;
	while(n && n->container) {
		if(strcmp(n->container->name, "mod_wrap") == 0) {
			int idx = 0;
			ListElement *l = n->container->items->head;
			while(l && *(GuiNode **)l->data != n) {
				idx++;
				l = l->next;
			}
			Instrument *inst = igui->vm->instruments[*igui->selectedInstrument];
			if(idx < inst->envelopeCount) {
				removeSource(inst, idx);
			}
			return;
		}
		n = n->container;
	}
}


Instrument *getSelectedInstInstrument(void) {
	if(!igui || !igui->vm) {
		return NULL;
	}
	return igui->vm->instruments[*igui->selectedInstrument];
}


static void appendBlankNode(GuiNode *container, int weight) {
	GuiNode *bgn = createBlankGuiNode();
	appendItem(container, bgn, weight);
}


static void drawModStripGuiNode(void *self) {
	ModStripGuiNode *msgn = (ModStripGuiNode *)self;
	GuiNode *gn = (GuiNode *)msgn;
	drawModStrip(&msgn->strip, (Rectangle){ gn->x, gn->y, gn->w, gn->h });
}


static ModStripGuiNode *createModStripGuiNode(int x, int y, int w, int h, VoiceManager *vm, int channel) {
	ModStripGuiNode *msgn = malloc(sizeof(ModStripGuiNode));
	GuiNode *gn = (GuiNode *)msgn;
	if(!initGuiNode(gn, x, y, w, h, 0, na_horizontal, "modstrip", 0, 0)) {
		printf("ModStripGuiNode init problem.\n");
		free(msgn);
		return NULL;
	}
	initModStrip(&msgn->strip, vm->voicePools[channel], vm->voiceCount[channel], w, h);
	gn->drawable = true;
	gn->draw = drawModStripGuiNode;
	return msgn;
}

/* Task 4: Unified mod-source container. Each entry row in the mod-wrap
 * represents one Mod (core envelope or runtime envelope/LFO/RND). The
 * wrap is rebuilt from inst->modList, so the type-changing cbCycleSourceType
 * + addRuntimeSource + removeSource trio all funnel through the same
 * modList->count sync path. The header row (MODS + ADD) at index 0
 * makes removeSelectedSource's `idx - 1` mapping correct. */
typedef struct {
	Instrument *inst;
	int idx;
} SourceCtx;


static SourceCtx g_sourceCtx[MAX_ENVELOPES];


static void refreshSourceCtx(Instrument *inst) {
	for(int i = 0; i < MAX_ENVELOPES; i++) {
		g_sourceCtx[i].inst = inst;
		g_sourceCtx[i].idx = i;
	}
}

/* Task 5: delete-confirm modal for runtime mod sources.
 *
 * The DEL button on each runtime mod-source entry pushes a YES/NO confirm
 * layer. NO just pops; YES pops first (so the layer is gone before the
 * graph rebuild from removeSource reshuffles everything) and then calls
 * removeSource(inst, idx), which rebuilds the instrument graph. The
 * SourceCtx for the entry was refreshed by refreshSourceCtx() above when
 * the graph was last built, so inst+idx are still valid as long as no
 * other mutation has happened in the interim. */

static void cbDeleteCancel(void *ctx) {
	(void)ctx;
	InstrumentGui *ig = igui;
	if(ig) {
		popLayer(&ig->overlayLayers);
	}
}


static void cbDeleteConfirmYes(void *ctx) {
	SourceCtx *sc = (SourceCtx *)ctx;
	InstrumentGui *ig = igui;
	if(ig) {
		popLayer(&ig->overlayLayers);
	}
	if(sc) {
		removeSource(sc->inst, sc->idx);
	}
}


static void cbDeleteSource(void *ctx) {
	SourceCtx *sc = (SourceCtx *)ctx;
	InstrumentGui *ig = igui;
	if(!ig || !sc) {
		return;
	}
	Graph *g = createGraph(na_horizontal);
	const int py = (SCREEN_H - 80) / 2;
	const int px = (SCREEN_W - 280) / 2;
	GuiNode *noBtn = createActionBtnGuiNode(px + 30, py + 44, 100, 22, 0, na_horizontal, "NO", 0, cbDeleteCancel, NULL);
	noBtn->name = strdup("DELETE_NO");
	GuiNode *yesBtn = createActionBtnGuiNode(px + 150, py + 44, 100, 22, 0, na_horizontal, "YES", 0, cbDeleteConfirmYes, sc);
	yesBtn->name = strdup("DELETE_YES");
	appendItem(g->root, noBtn, 1);
	appendItem(g->root, yesBtn, 1);
	changeGraphSelection(g, noBtn);
	Layer *layer = createLayer(g, px, py, 280, 80, "DELETE", true, true);
	pushLayer(&ig->overlayLayers, layer);
}

/* Task 6: route-destination picker.
 *
 * cbOpenRouteLayer (actionCb on the ROUTE button) walks the instrument
 * graph, gathers every routable dial (a dial node = a GuiNode whose draw
 * is drawDialGuiNode or drawDiscreteDialGuiNode and whose Parameter
 * pointer is non-NULL), then pushes a dim, full-screen overlay. The
 * overlay's graph holds one selectable action-button node per routable
 * dial, named after the dial. The first dial is auto-selected so the
 * harness + a fresh player can press EDIT to route into the first dial
 * without navigating. Selecting any dest node and EDIT'ing fires
 * cbRouteToDest which toggles the source's route (add 1.0/MO_ADD or
 * remove) and pops the layer.
 *
 * Why file-static g_destCtx[]: each dest node carries a DestCtx* so the
 * actionCb can find inst + srcIdx + the dest Parameter without having
 * to walk the graph again at EDIT time. Mirrors g_sourceCtx from Task 4.
 *
 * IMPORTANT: appendItem runs reflowCoordinates, which OVERWRITES child
 * rects. We must set each dest node's x/y/w/h to the dial's rect AFTER
 * appendItem, otherwise the picking buttons overlap the dial at the dial's
 * position. set x/y/w/h here explicitly; reflow would otherwise reset
 * them to the container's last-children default. */
typedef struct {
	Instrument *inst;
	int srcIdx;
	Parameter *dest;
} DestCtx;

static DestCtx g_destCtx[MAX_PARAMS];


static void collectRoutableDialsRecurse(GuiNode *node, Parameter **outParams, GuiNode **outNodes, int cap, int *n) {
	if(!node || *n >= cap) {
		return;
	}
	/* A routable dial = draw == drawDialGuiNode || draw == drawDiscreteDialGuiNode
	 * and p != NULL (dials created with a non-NULL Parameter). */
	if(node->draw && node->p && (node->draw == drawDialGuiNode || node->draw == drawDiscreteDialGuiNode)) {
		if(*n < cap) {
			outParams[*n] = node->p;
			outNodes[*n] = node;
			(*n)++;
		}
	}
	if(node->items) {
		ListElement *le = node->items->head;
		while(le) {
			/* Items store the child pointer BY VALUE in an 8-byte block
			 * (appendItem -> appendToList copies sizeof(GuiNode*)). Read
			 * the pointer with *(GuiNode **)le->data, matching every other
			 * graph walk (freeGuiNode, collectSelectables, navigateGraph).
			 * Casting le->data directly treats the block address as the
			 * node and reads past the allocation. */
			GuiNode *cn = *(GuiNode **)le->data;
			if(cn && cn != node) {
				collectRoutableDialsRecurse(cn, outParams, outNodes, cap, n);
			}
			le = le->next;
		}
	}
}


static void collectRoutableDials(GuiNode *node, Parameter **outParams, GuiNode **outNodes, int cap, int *n) {
	*n = 0;
	collectRoutableDialsRecurse(node, outParams, outNodes, cap, n);
}


static void cbRouteToDest(void *ctx) {
	DestCtx *dc = (DestCtx *)ctx;
	InstrumentGui *ig = igui;
	if(!ig) {
		return;
	}
	/* Pop the layer first (so any listener-driven graph work doesn't
	 * run against a stale g->selected). The mutation below rebuilds
	 * the instrument graph via rebuildInstrumentGraph() so popping
	 * first keeps the same ordering pattern as cbDeleteConfirmYes. */
	popLayer(&ig->overlayLayers);
	if(!dc || !dc->inst || !dc->dest) {
		return;
	}
	/* Walk the destination's modulator chain to decide whether to add
	 * or remove. There is no public hasModulation() — the connection
	 * list is the source of truth. */
	Mod *src = dc->inst->modList->mods[dc->srcIdx];
	if(!src) {
		return;
	}
	bool already = false;
	for(ModConnection *c = dc->dest->modulators; c; c = c->next) {
		if(c->source == src) {
			already = true;
			break;
		}
	}
	/* Task 8: route mutation touches the modList the audio thread
	 * iterates; hold the rebuilding flag across the swap. The audio
	 * lock closes the flag's check-then-use race. */
	pthread_mutex_lock(&g_audioLock);
	dc->inst->rebuilding = true;
	if(already) {
		removeModulation(dc->inst->paramList, dc->dest, src);
	} else {
		addModulation(dc->inst->paramList, src, dc->dest, 1.0f, MO_ADD);
	}
	rebuildInstrumentGraph();
	dc->inst->rebuilding = false;
	pthread_mutex_unlock(&g_audioLock);
}

/* cbOpenRouteLayer builds the picking layer. Each routable dial becomes
 * a selectable button drawn at the dial's own x/y/w/h so the visual
 * position matches the underlying dial exactly. */

static void cbOpenRouteLayer(void *ctx) {
	SourceCtx *sc = (SourceCtx *)ctx;
	InstrumentGui *ig = igui;
	if(!ig || !sc || !sc->inst || sc->idx < 0 || sc->idx >= sc->inst->modList->count) {
		return;
	}
	/* Build the destination list by walking the CURRENT instrument graph
	 * (we want the dials as they appear RIGHT NOW — before our own
	 * rebuild — so the user can see what they will route into). */
	Graph *instGraph = getSelectedInstGraph();
	if(!instGraph || !instGraph->root) {
		return;
	}
	Parameter *params[MAX_PARAMS];
	GuiNode *nodes[MAX_PARAMS];
	int n = 0;
	collectRoutableDials(instGraph->root, params, nodes, MAX_PARAMS, &n);
	if(n <= 0) {
		return;
	}
	/* One Graph holds all dest nodes. The Layer dims the rest of the
	 * screen. The first dial is selected so EDIT routes into it
	 * immediately. */
	/* The dest button's name must outlive the paramList / instrument
	 * graph — when rebuildInstrumentGraph() later frees the previous
	 * graph's nodes, params[i]->name's storage goes with it. The
	 * initial heap-copy done by createActionBtnGuiNode (via
	 * initGuiNode) already achieves that, so no further strdup is
	 * needed. */
	Graph *g = createGraph(na_vertical);
	GuiNode *firstDest = NULL;
	GuiNode *destBtns[MAX_PARAMS];
	/* Loop 1: create + append each button. Do NOT pin rects here —
	 * appendItem runs reflowCoordinates, which re-stamps x/y/w/h of
	 * EVERY child already in the container. Pinning after a single
	 * appendItem only to be over-written by the next iteration's
	 * reflow (and by every subsequent iter) leaves only the LAST
	 * button correctly aligned with its dial. */
	for(int i = 0; i < n; i++) {
		g_destCtx[i].inst = sc->inst;
		g_destCtx[i].srcIdx = sc->idx;
		g_destCtx[i].dest = params[i];
		GuiNode *destBtn = createActionBtnGuiNode(0, 0, 100, 100, 0, na_horizontal, params[i]->name, 0, cbRouteToDest, &g_destCtx[i]);
		destBtn->draw = drawRouteDestNode;
		destBtns[i] = destBtn;
		appendItem(g->root, destBtn, 1);
		if(i == 0) {
			firstDest = destBtn;
		}
	}
	/* Loop 2: now that every append has run, no further reflow will
	 * happen — pin each button's rect to its dial's rect so the
	 * picker visually lines up with the underlying dials. */
	for(int i = 0; i < n; i++) {
		destBtns[i]->x = nodes[i]->x;
		destBtns[i]->y = nodes[i]->y;
		destBtns[i]->w = nodes[i]->w;
		destBtns[i]->h = nodes[i]->h;
	}
	if(firstDest) {
		changeGraphSelection(g, firstDest);
	}
	Layer *layer = createLayer(g, 0, 0, SCREEN_W, SCREEN_H, "ROUTE", true, true);
	pushLayer(&ig->overlayLayers, layer);
}

/* Task 7: route-lines overlay. When a ROUTE button is FOCUSED (selected),
 * draw colour-coded lines from the source's route button to every
 * destination dial it currently modulates. Draw-only, non-interactive. */
typedef struct {
	Instrument *inst;
	int srcIdx;
} RouteLinesCtx;


static RouteLinesCtx g_routeLinesCtx;


static int findDialRectForParam(GuiNode *node, Parameter *p, Rectangle *out) {
	if(!node || !p) {
		return 0;
	}
	if((node->draw == drawDialGuiNode || node->draw == drawDiscreteDialGuiNode) && node->p == p) {
		*out = (Rectangle){ node->x, node->y, node->w, node->h };
		return 1;
	}
	if(node->items) {
		ListElement *e = node->items->head;
		for(int i = 0; i < node->itemCount && e; i++) {
			if(findDialRectForParam(*(GuiNode **)e->data, p, out)) {
				return 1;
			}
			e = e->next;
		}
	}
	return 0;
}

/* Find the ROUTE button (actionCb == cbOpenRouteLayer) in the base graph. */

static int findRouteButtonRect(GuiNode *node, Rectangle *out) {
	if(!node) {
		return 0;
	}
	if(node->actionCb == cbOpenRouteLayer) {
		*out = (Rectangle){ node->x, node->y, node->w, node->h };
		return 1;
	}
	if(node->items) {
		ListElement *e = node->items->head;
		for(int i = 0; i < node->itemCount && e; i++) {
			if(findRouteButtonRect(*(GuiNode **)e->data, out)) {
				return 1;
			}
			e = e->next;
		}
	}
	return 0;
}


static void drawRouteLinesNode(void *self) {
	GuiNode *gn = (GuiNode *)self;
	RouteLinesCtx *rc = &g_routeLinesCtx;
	(void)gn;
	if(!rc->inst || rc->srcIdx < 0 || rc->srcIdx >= rc->inst->modList->count) {
		return;
	}
	Mod *src = rc->inst->modList->mods[rc->srcIdx];
	Graph *base = getSelectedInstGraph();
	if(!base || !base->root) {
		return;
	}
	Rectangle anchor = { 0, 0, 0, 0 };
	findRouteButtonRect(base->root, &anchor);
	if(anchor.width <= 0.0f || anchor.height <= 0.0f) {
		return;
	}
	Vector2 from = { anchor.x + anchor.width / 2, anchor.y + anchor.height / 2 };
	for(int i = 0; i < rc->inst->paramList->count; i++) {
		Parameter *p = rc->inst->paramList->params[i];
		if(!p) {
			continue;
		}
		ModConnection *c = p->modulators;
		while(c) {
			if(c->source == src) {
				Rectangle r;
				if(findDialRectForParam(base->root, p, &r)) {
					Vector2 to = { r.x + r.width / 2, r.y + r.height / 2 };
					Color col = (c->type && getParameterValueAsInt(c->type) == MO_MUL) ? cs.routeMul : cs.routeAdd;
					DrawLineEx(from, to, 2.0f, col);
				}
			}
			c = c->next;
		}
	}
}


static void syncRouteLinesOverlay(InstrumentGui *ig) {
	if(!ig) {
		return;
	}
	Graph *base = getSelectedInstGraph();
	GuiNode *sel = base ? base->selected : NULL;
	bool onRouteBtn = sel && sel->actionCb == cbOpenRouteLayer;
	Layer *top = topLayer(&ig->overlayLayers);
	bool hasOverlay = top && top->name && strcmp(top->name, "ROUTELINES") == 0;
	/* Only show ROUTELINES when the stack is otherwise empty — pushing on
	 * top of the ROUTE picking layer (EDIT on the button) would make the
	 * passive overlay the top layer and break modal input/selection. */
	if(onRouteBtn && layerStackIsEmpty(&ig->overlayLayers)) {
		/* Route the source through the overlay ctx: the ROUTE button's
		 * actionCtx is &g_sourceCtx[idx] (SourceCtx { inst, idx }). */
		SourceCtx *sc = (SourceCtx *)sel->actionCtx;
		if(sc && sc->inst) {
			g_routeLinesCtx.inst = sc->inst;
			g_routeLinesCtx.srcIdx = sc->idx;
		}
		Graph *g = createGraph(na_horizontal);
		GuiNode *lines = createGuiNode(0, 0, SCREEN_W, SCREEN_H, 0, na_horizontal, "routelines", 0, 0);
		lines->drawable = true;
		lines->draw = drawRouteLinesNode;
		appendItem(g->root, lines, 1);
		Layer *l = createLayer(g, 0, 0, SCREEN_W, SCREEN_H, "ROUTELINES", false, true);
		pushLayer(&ig->overlayLayers, l);
	} else if(!onRouteBtn && hasOverlay) {
		Layer *l = popLayer(&ig->overlayLayers);
		if(l) {
			destroyLayer(l);
		}
	}
}


static void cbAddModSource(void *ctx) {
	Instrument *inst = (Instrument *)ctx;
	addRuntimeSource(inst);
}


static void cbCycleSourceType(void *ctx) {
	SourceCtx *sc = (SourceCtx *)ctx;
	if(!sc || !sc->inst || sc->idx < 0 || sc->idx >= sc->inst->modList->count) {
		return;
	}
	Mod *mod = sc->inst->modList->mods[sc->idx];
	ModType next = MT_ENV;
	switch(mod->type) {
		case MT_ENV: next = MT_LFO; break;
		case MT_LFO: next = MT_RND; break;
		default:     next = MT_ENV; break;
	}
	/* Task 8: hold the rebuilding flag while we mutate the lists the audio
	 * thread iterates. The audio lock closes the flag's check-then-use
	 * race. */
	pthread_mutex_lock(&g_audioLock);
	sc->inst->rebuilding = true;
	if(changeModType(sc->inst->modList, mod, next, sc->inst->paramList)) {
		sc->inst->envelopeCount = sc->inst->modList->count;
		rebuildInstrumentGraph();
	}
	sc->inst->rebuilding = false;
	pthread_mutex_unlock(&g_audioLock);
}


static const char *modTypeTag(ModType t) {
	switch(t) {
		case MT_LFO: return "LFO";
		case MT_RND: return "RND";
		default:     return "ENV";
	}
}


static void appendModSourceEntry(Graph *g, GuiNode *container, Instrument *inst, int idx, int weight, bool selected) {
	Mod *mod = inst->modList->mods[idx];
	bool core = idx < inst->coreEnvelopeCount;
	GuiNode *wrap = createGuiNode(0, 0, 100, 100, 2, na_horizontal, "MODSRC", 0, 0);
	wrap->drawable = true;
	wrap->draw = drawWrapperNode;

	if(!core) {
		refreshSourceCtx(inst);
		GuiNode *typeBtn = createActionBtnGuiNode(0, 0, 100, 100, 2, na_horizontal,
		                                         modTypeTag(mod->type), 0, cbCycleSourceType, &g_sourceCtx[idx]);
		typeBtn->name = strdup(modTypeTag(mod->type));
		appendItem(wrap, typeBtn, 3);
	}

	switch(mod->type) {
		case MT_ENV: {
			Envelope *e = (Envelope *)mod;
			appendItem(wrap, createDialGuiNode(0, 0, 100, 100, 2, na_horizontal, "ATTACK", selected, incParameterBaseValue, e->stages[0].duration), 4);
			appendItem(wrap, createDialGuiNode(0, 0, 100, 100, 2, na_horizontal, "CURVE", 0, incParameterBaseValue, e->stages[0].curvature), 4);
			appendItem(wrap, createDialGuiNode(0, 0, 100, 100, 2, na_horizontal, "DECAY", 0, incParameterBaseValue, e->stages[1].duration), 4);
			appendItem(wrap, createDialGuiNode(0, 0, 100, 100, 2, na_horizontal, "CURVE", 0, incParameterBaseValue, e->stages[1].curvature), 4);
			break;
		}
		case MT_LFO: {
			LFO *l = (LFO *)mod;
			appendItem(wrap, createDialGuiNode(0, 0, 100, 100, 2, na_horizontal, "RATE", selected, incParameterBaseValue, l->rate), 4);
			if(l->shape) {
				appendItem(wrap, createDialGuiNode(0, 0, 100, 100, 2, na_horizontal, "SHAPE", 0, incParameterBaseValue, l->shape), 4);
			}
			break;
		}
		case MT_RND: {
			Random *r = (Random *)mod;
			appendItem(wrap, createDialGuiNode(0, 0, 100, 100, 2, na_horizontal, "RATE", selected, incParameterBaseValue, r->rate), 4);
			if(r->shape) {
				appendItem(wrap, createDialGuiNode(0, 0, 100, 100, 2, na_horizontal, "SHAPE", 0, incParameterBaseValue, r->shape), 4);
			}
			break;
		}
		default:
			break;
	}

	if(!core) {
		/* Task 6: ROUTE opens the destination-picker layer. cbOpenRouteLayer
		 * reads inst+idx from this entry's SourceCtx (refreshed above by
		 * refreshSourceCtx) so the picker always sees the right Mod. */
		appendItem(wrap, createActionBtnGuiNode(0, 0, 100, 100, 2, na_horizontal, "ROUTE", 0, cbOpenRouteLayer, &g_sourceCtx[idx]), 3);
		/* Task 5: DEL opens the YES/NO confirm layer; cbDeleteSource reads
		 * inst+idx off the per-entry SourceCtx slot refreshed by
		 * refreshSourceCtx() above. */
		appendItem(wrap, createActionBtnGuiNode(0, 0, 100, 100, 2, na_horizontal, "DEL", 0, cbDeleteSource, &g_sourceCtx[idx]), 2);
	}
	appendItem(wrap, createBlankGuiNode(), 1);
	appendItem(container, wrap, weight);
	(void)g;
}


static Graph *createInstGraph(Instrument *inst, VoiceManager *vm, int channel, bool selected) {
	Graph *instGraph = createGraph(na_vertical);
	GuiNode *mainRow = createGuiNode(0, 0, 100, 100, 0, na_horizontal, "mainrow", 0, 0);
	GuiNode *margin1 = createBlankGuiNode();
	GuiNode *margin2 = createBlankGuiNode();
	GuiNode *presetWrap = createGuiNode(0, 0, 100, 100, 2, na_vertical, "presetwrappa", 0, 0);
	appendPresetControlNode(instGraph, presetWrap, "presetz", 2, 0, inst);
	// GuiNode *pad1 = createBlankGuiNode();
	GuiNode *pad2 = createBlankGuiNode();

	GuiNode *instwrap = createGuiNode(0, 0, 100, 100, 5, na_vertical, "inst_wrap", 0, 0);
	/* Task 4: meta row sits at the TOP of instwrap with weight 4 so it
	 * is one standard control row tall (~35px / 31px content), matching
	 * the AD-env dial row height. The old weight=1 shrank it to 4px —
	 * effectively invisible, breaking cursor navigation onto the row.
	 * presetWrap weight is dropped from 5 to 4 in the call below so
	 * both rows stay the same standard height. selected=false: never
	 * assign g->selected here, see the long comment on
	 * appendMetaControlNode for the fixture-compatibility reasoning. */
	appendMetaControlNode(instGraph, instwrap, inst, vm, channel, 5, false);
	appendItem(instwrap, presetWrap, 5);
	switch(inst->voiceType) {
		case VOICE_TYPE_FM:
			appendFMInstControlNode(instGraph, instwrap, "fmctrl", 8, true, inst);
			break;
		case VOICE_TYPE_SAMPLE:
			appendSampleInstControlNode(instGraph, instwrap, "sctrl", 8, true, inst);
			break;
		case VOICE_TYPE_BLEP:
			appendBlepInstControlNode(instGraph, instwrap, "blctrl", 8, true, inst);
			break;
	}
	appendItem(instwrap, pad2, 1);

	GuiNode *modwrap = createGuiNode(0, 0, 100, 100, 0, na_vertical, "mod_wrap", 0, 0);
	/* Header row: container label + ADD action button. */
	GuiNode *modHdr = createGuiNode(0, 0, 100, 100, 2, na_horizontal, "mods_hdr", 0, 0);
	modHdr->drawable = true;
	modHdr->draw = drawWrapperNode;
	GuiNode *modLabel = createGuiNode(0, 0, 100, 100, 2, na_horizontal, "MODS", 0, 0);
	GuiNode *modAdd = createActionBtnGuiNode(0, 0, 100, 100, 2, na_horizontal, "ADD", 0, cbAddModSource, inst);
	modAdd->name = strdup("MODS_ADD");
	appendItem(modHdr, modLabel, 4);
	appendItem(modHdr, modAdd, 1);
	appendItem(modwrap, modHdr, 1);
	for(int i = 0; i < inst->modList->count; i++) {
		appendModSourceEntry(instGraph, modwrap, inst, i, 1, false);
	}
	appendBlankNode(modwrap, 1);
	appendItem(instwrap, modwrap, 22);

	appendItem(mainRow, margin1, 1);
	appendItem(mainRow, instwrap, 18);
	appendItem(mainRow, margin2, 1);
	appendItem(instGraph->root, mainRow, 19);

	ModStripGuiNode *msgn = createModStripGuiNode(0, 0, 640, 100, vm, channel);
	if(msgn) {
		appendItem(instGraph->root, (GuiNode *)msgn, 4);
	} else {
		appendBlankNode(instGraph->root, 4);
	}
	return instGraph;
}



void gui_instrument_draw(void) {
	drawNode(igui->instrumentScreenGraphs[*igui->selectedInstrument]->root);
	if (igui) {
		/* route-lines overlay is driven by the focused selection each frame */
		syncRouteLinesOverlay(igui);
		layerStackDraw(&igui->overlayLayers);
	}
}
