/* gui_gui_arranger.c -- generated by the gui module split (lawn-mowing-gui).
 * One module per screen; shared node helpers live in gui_core.c.
 * Cross-module state/helpers: see gui_internal.h. */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "dstruct.h"
#include "raylib.h"
#include "gui.h"
#include "graph_gui.h"
#include "input.h"
#include "modsystem.h"
#include "notes.h"
#include "voice.h"
#include "io/preset_io.h"
#include "io.h"
#include "gui_internal.h"


/* ---- module-private state ---- */
static Graph *agui;
/* Task 4: chip node registry. createArrangerGraph populates g_chipNodes[ch]
 * with the InstChipGuiNode for each enabled channel. expandChip() indexes
 * this array directly instead of walking the agui tree (Task 3 nests chips
 * two layers deep: root → gridColumn → chipRow → chip — a fragile walk
 * that would break the moment Task 5+ adds anything else into chipRow).
 * NULL slots (disabled channels / out-of-range) are skipped. */

/* Task 5: shared arcade char table for chip label editing. Defined up
 * here so the chip helpers below can use it; the original definition
 * for the preset-name node lives at line ~1517 and is a no-op
 * re-definition of the same literal (C allows identical #define
 * re-declarations). This keeps both consumers' char cycles in lock-
 * step without forcing the preset-node fixtures to share an
 * implementation. */
#define NAME_CHARS "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 _-. "
static GuiNode *g_chipNodes[MAX_SEQUENCER_CHANNELS];
/* Task 2 (arranger window rework): currently-active Arranger. Set
 * inside createArrangerGraph so scrollArrangerWindow / getArrangerRowCell
 * can find the cell rows without re-passing the arranger every call.
 * NULL when no arranger graph has been built (unit-test path). */
Arranger *g_arranger;

void createArrangerGraph(Arranger *a, PatternList *pl) {
	agui = createGraph(na_vertical);
	GuiNode *arrWrap = createGuiNode(0, 0, 100, 100, 5, na_horizontal, "awrap", 0, 0);
	GuiNode *songControls = createGuiNode(0, 0, 100, 100, 5, na_vertical, "song", 0, 0);

	GuiNode *pad0 = createNamedBlankGuiNode("pad00");
	GuiNode *pad1 = createNamedBlankGuiNode("pad01");
	GuiNode *bpm = createDialGuiNode(0, 0, 100, 100, 5, na_vertical, "BPM", false, incParameterBaseValue, a->tempoSettings.bpm);
	GuiNode *swing = createDialGuiNode(0, 0, 100, 100, 5, na_vertical, "Swing", false, incParameterBaseValue, a->tempoSettings.swing);
	GuiNode *pad2 = createNamedBlankGuiNode("pad02");
	appendItem(songControls, pad0, 1);
	appendItem(songControls, bpm, 1);
	appendItem(songControls, swing, 1);
	appendItem(songControls, pad2, 8);

	GuiNode *margin2 = createNamedBlankGuiNode("Marge!");
	appendItem(agui->root, pad1, 1);

	appendItem(arrWrap, songControls, 1);
	appendItem(arrWrap, margin2, 1);

	/* Task 3: instrument chip row sits above the arranger grid. One chip
	 * per enabled sequencer channel; chipRow is horizontal, the grid
	 * gets the lion's share (weight 8). */
	GuiNode *gridColumn = createGuiNode(0, 0, 100, 100, 2, na_vertical, "gcol", 0, 0);
	gridColumn->drawable = true;
	gridColumn->draw = drawWrapperNode;
	GuiNode *chipRow = createGuiNode(0, 0, 100, 100, 2, na_horizontal, "chipr", 0, 0);
	chipRow->drawable = true;
	chipRow->draw = drawWrapperNode;
	/* Task 4: zero the chip registry so any channel that doesn't get a
	 * chip this build (e.g. enabledChannels shrank between rebuilds)
	 * doesn't keep a stale pointer. */
	for(int ch = 0; ch < MAX_SEQUENCER_CHANNELS; ch++) {
		g_chipNodes[ch] = NULL;
	}
	for(int ch = 0; ch < a->enabledChannels; ch++) {
		GuiNode *chip = createInstChipGuiNode(0, 0, 100, 40, false, a->vm, ch, a);
		g_chipNodes[ch] = chip;
		appendItem(chipRow, chip, 1);
	}
	appendItem(gridColumn, chipRow, 2);
	/* Task 2 (arranger window rework): the grid slice. The arranger
	 * song array is MAX_SONG_LENGTH rows deep, but the GUI only renders
	 * ARRANGER_WINDOW_ROWS of them at a time — the visible slice is
	 * [a->visibleStart, a->visibleStart + ARRANGER_WINDOW_ROWS). One
	 * row container per visible row; each container holds one
	 * ArrangerCellGuiNode per enabled channel. scrollArrangerWindow
	 * later retargets the cell nodes' row field when visibleStart
	 * moves. */
	GuiNode *selectedCell = NULL;
	for(int r = 0; r < ARRANGER_WINDOW_ROWS; r++) {
		GuiNode *rowc = createGuiNode(0, 0, 100, 100, 2, na_horizontal, "row", 0, 0);
		rowc->drawable = true;
		rowc->draw = drawWrapperNode;
		for(int ch = 0; ch < a->enabledChannels; ch++) {
			bool sel = (ch == a->selected_x && a->visibleStart + r == a->selected_y);
			GuiNode *cell = createArrangerCellGuiNode(0, 0, 100, 100, sel, a, ch, a->visibleStart + r);
			if(sel) {
				selectedCell = cell;
			}
			appendItem(rowc, cell, 1);
		}
		appendItem(gridColumn, rowc, 1);
	}
	g_arranger = a;
	appendItem(arrWrap, gridColumn, 4);
	appendItem(agui->root, arrWrap, 15);
	/* Task 2: prefer the cell that matches the current selection; fall
	 * back to the legacy gn selection if no cell matches (which can
	 * happen on the first build before selected_x/_y are in range, or
	 * for arranger modes that don't use the cell grid). */
	agui->selected = selectedCell ? selectedCell : agui->selected;

	GuiNode *demoStack = createGuiNode(0, 0, 100, 100, 0, na_vertical, "demo", 0, 0);
	GuiNode *linesNode = createGuiNode(0, 0, 100, 100, 2, na_horizontal, "vline", 0, 0);
	linesNode->drawable = true;
	linesNode->draw = drawSampleWaveLinesNode;
	GuiNode *polyNode = createGuiNode(0, 0, 100, 100, 2, na_horizontal, "poly", 0, 0);
	polyNode->drawable = true;
	polyNode->draw = drawSampleWavePolylineNode;
	appendItem(demoStack, linesNode, 1);
	appendItem(demoStack, polyNode, 1);
	appendItem(agui->root, demoStack, 5);
}

#define PATTERN_STEPS_PER_ROW 4


void setArrangerMixRing(MixRing *r) {
	arrangerMixRing = r;
}


void arrangerGraphControlInput(int keymapping) {
	if(!agui || !agui->selected || !agui->selected->callback) {
		return;
	}
	switch(keymapping) {
		case KM_LEFT:
			agui->selected->callback(agui->selected->p, -0.1f);
			break;
		case KM_RIGHT:
			agui->selected->callback(agui->selected->p, 0.1f);
			break;
		case KM_UP:
			agui->selected->callback(agui->selected->p, 1.0f);
			break;
		case KM_DOWN:
			agui->selected->callback(agui->selected->p, -1.0f);
			break;
		default:
			break;
	}
}


void printArrGraph() {
	printGraph(agui->root, 0);
}


void syncArrangerSelectionTo(Graph *g, Arranger *a) {
	if(!g || !g->selected || !a) {
		return;
	}
	if(isArrangerCellNode(g->selected)) {
		int x = 0;
		int y = 0;
		getArrangerCellCoords(g->selected, &x, &y);
		a->selected_x = x;
		a->selected_y = y;
		int cell[2] = { x, y };
		if(a->onCellSelect.f) {
			a->onCellSelect.f(a->onCellSelect.appstateRef, cell);
		}
		int patternIndex = a->song[x][y];
		if(a->onPatternSelection.f) {
			a->onPatternSelection.f(a->onPatternSelection.appstateRef, &patternIndex);
		}
	}
}

/* Task 3: geometry-based nav pipeline. Runs navigateGraphRefined on
 * `g` (geometry-based nav that understands the cell-grid layout, so
 * LEFT/RIGHT across rows wraps around correctly), then edge-scrolls
 * `a`'s visible window if the resulting selection lands at the
 * top/bottom row (UP at top scrolls back, DOWN at bottom scrolls
 * forward), and finally syncs selection + callbacks. NULL `g` is a
 * no-op so main.c + instrument_harness.c are safe when no arranger
 * graph is built yet. */

void navigateArrangerGraphTo(Graph *g, Arranger *a, int keymapping) {
	if(!g) {
		return;
	}
	navigateGraphRefined(g, keymapping);
	if(g->selected && isArrangerCellNode(g->selected) && a) {
		int x;
		int y;
		getArrangerCellCoords(g->selected, &x, &y);
		if(keymapping == KM_UP && y == a->visibleStart && a->visibleStart > 0) {
			scrollArrangerWindow(a, -1);
		}
		if(keymapping == KM_DOWN && y == a->visibleStart + ARRANGER_WINDOW_ROWS - 1
				&& a->visibleStart < MAX_SONG_LENGTH - ARRANGER_WINDOW_ROWS) {
			scrollArrangerWindow(a, 1);
		}
	}
	syncArrangerSelectionTo(g, a);
}

/* Task 3: thin wrapper used by main.c + instrument_harness.c — pulls
 * the file-static g_arranger + agui so callers don't have to know
 * about the graph plumbing. */

void navigateArrangerGraph(int keymapping) {
	navigateArrangerGraphTo(agui, g_arranger, keymapping);
}


void drawInstChipGuiNode(void *self) {
	InstChipGuiNode *chip = (InstChipGuiNode *)self;
	if(!chip->vm || !chip->arranger) return;
	Instrument *inst = chip->vm->instruments[chip->channel];
	if(!inst) return;

	GuiNode *gn = &chip->base;
	int paletteIdx = chip->arranger->labelColourIdx[chip->channel];
	if(paletteIdx < 0) paletteIdx = 0;
	if(paletteIdx >= 8) paletteIdx = paletteIdx % 8;
	Color bg = chipPalette[paletteIdx];
	DrawRectangle(gn->x, gn->y, gn->w, gn->h, bg);
	DrawRectangleLinesEx((Rectangle){ gn->x, gn->y, gn->w, gn->h }, 2.0, gn->selected ? cs.outlineColour : cs.wrapperBorder);

	/* top-left: voice count */
	char vbuf[16];
	snprintf(vbuf, sizeof(vbuf), "V:%d", chip->vm->voiceCount[chip->channel]);
	DrawTextEx(pixelFont, vbuf, (Vector2){ gn->x + 4, gn->y + 2 }, 9, 1, cs.label);

	/* top-right: type tag */
	const char *tag = voiceTypeTag(inst->voiceType);
	int tagW = MeasureText(tag, 9);
	DrawTextEx(pixelFont, tag, (Vector2){ gn->x + gn->w - tagW - 4, gn->y + 2 }, 9, 1, cs.label);

	/* centre: 8-char channel label */
	const char *lbl = chip->arranger->label[chip->channel];
	char lblBuf[9];
	strncpy(lblBuf, lbl, 8);
	lblBuf[8] = '\0';
	int lblW = MeasureText(lblBuf, 12);
	DrawTextEx(pixelFont, lblBuf, (Vector2){ gn->x + (gn->w - lblW) / 2, gn->y + (gn->h - 12) / 2 }, 12, 1, cs.label);

	/* bottom-left: patch name (inst->loaded.name) */
	const char *patch = inst->loaded.name;
	if(!patch) patch = "";
	char patchBuf[32];
	strncpy(patchBuf, patch, sizeof(patchBuf) - 1);
	patchBuf[sizeof(patchBuf) - 1] = '\0';
	DrawTextEx(pixelFont, patchBuf, (Vector2){ gn->x + 4, gn->y + gn->h - 11 }, 8, 1, cs.label);

	/* bottom-right: voice-active light per voice */
	int n = chip->vm->voiceCount[chip->channel];
	int dotSize = 4;
	int dotGap = 2;
	int rowW = n * dotSize + (n > 0 ? (n - 1) * dotGap : 0);
	int startX = gn->x + gn->w - rowW - 3;
	int dotY = gn->y + gn->h - dotSize - 3;
	for(int i = 0; i < n; i++) {
		Voice *v = chip->vm->voicePools[chip->channel][i];
		Color c = (v && v->active) ? cs.outlineColour : cs.wrapperBorder;
		DrawRectangle(startX + i * (dotSize + dotGap), dotY, dotSize, dotSize, c);
	}

	/* Task 5: expanded overlay. When `expanded` is true, render the 8
	 * colour swatches + the 8-char label input directly ABOVE the chip's
	 * rectangle so the chip itself stays visible underneath. The strip
	 * is 32px tall: top 16px = swatches, bottom 16px = label input row.
	 * Geometry is bounded by the chip's own (x, y, w): the swatches and
	 * label input are never wider than the chip and never bleed above
	 * y=0 — callers must guarantee that, just like the chip itself. */
	if(!chip->expanded) return;

	int swatchH = 16;
	int labelH = 16;
	int stripTopY = gn->y - swatchH - labelH;
	if(stripTopY < 0) stripTopY = 0;  /* defensive clamp; pin to 0 */

	/* Swatches: 8 squares side by side. Width per swatch = gn->w / 8. */
	int swW = gn->w / 8;
	for(int i = 0; i < 8; i++) {
		int sx = gn->x + i * swW;
		DrawRectangle(sx, stripTopY, swW, swatchH, chipPalette[i]);
		if(i == chip->swatchFocus) {
			/* inverted cursor block + outline so the focused swatch is
			 * obvious even when its colour is the same as the chip's bg */
			DrawRectangleLinesEx((Rectangle){ sx, stripTopY, swW, swatchH }, 2.0f, cs.outlineColour);
		} else {
			DrawRectangleLinesEx((Rectangle){ sx, stripTopY, swW, swatchH }, 1.0f, cs.wrapperBorder);
		}
	}

	/* Label input: 8 cells mirroring the preset-name node's model.
	 * Each cell is swW wide, labelH tall, drawn as the char with an
	 * inverted cursor block when i == chip->cursor. The visible label
	 * is bounded to 8 chars; positions beyond the current NUL show as
	 * blanks so the user can see there's room to extend. */
	const char *label = chip->arranger->label[chip->channel];
	int labelLen = (int)strlen(label);
	if(labelLen > 8) labelLen = 8;
	int inputY = stripTopY + swatchH;
	for(int i = 0; i < 8; i++) {
		int cx = gn->x + i * swW;
		char ch = (i < labelLen) ? label[i] : ' ';
		if(i == chip->cursor) {
			DrawRectangle(cx, inputY, swW, labelH, cs.outlineColour);
			DrawTextEx(pixelFont, (char[]){ ch, '\0' }, (Vector2){ cx + 1, inputY + 2 }, 12, 1, BLACK);
		} else {
			DrawTextEx(pixelFont, (char[]){ ch, '\0' }, (Vector2){ cx + 1, inputY + 2 }, 12, 1, cs.label);
		}
	}
}


bool isInstChipNode(const GuiNode *n) {
	if(!n) return false;
	return n->draw == drawInstChipGuiNode;
}

/* Task 4: returns the channel of the currently-selected chip in agui,
 * or -1 when the selection isn't a chip (or agui hasn't been built yet).
 * Used by main.c's SCENE_ARRANGER EDIT+arrows handler to decide whether
 * to do chip-specific input (jump to instrument page / expand chip) or
 * fall through to the dial-edit dispatch. */

int getSelectedChipChannel(void) {
	if(!agui || !agui->selected || !isInstChipNode(agui->selected)) return -1;
	InstChipGuiNode *chip = (InstChipGuiNode *)agui->selected;
	return chip->channel;
}

/* Task 7: expose the arranger graph's selected GuiNode so the scripted
 * harness's runAssertSelected() can read it from outside gui.c. */

GuiNode *getArrangerSelectedNode(void) {
	if(!agui) return NULL;
	return agui->selected;
}

/* Task 4: set the chip's `expanded` flag by channel. Channels with no
 * registered chip (disabled or out-of-range) are no-ops. Task 5+ will
 * render the expanded chip content; for now this just flips the flag
 * so the wiring is verifiable. */

void expandChip(int channel, bool expanded) {
	if(!agui) return;
	if(channel < 0 || channel >= MAX_SEQUENCER_CHANNELS) return;
	GuiNode *node = g_chipNodes[channel];
	if(!node || !isInstChipNode(node)) return;
	((InstChipGuiNode *)node)->expanded = expanded;
}

/* Task 4: read the chip's current `expanded` flag. Used by the
 * EDIT+UP handler to toggle. Returns false for unknown / unregistered
 * channels. */

bool isChipExpanded(int channel) {
	if(!agui) return false;
	if(channel < 0 || channel >= MAX_SEQUENCER_CHANNELS) return false;
	GuiNode *node = g_chipNodes[channel];
	if(!node || !isInstChipNode(node)) return false;
	return ((InstChipGuiNode *)node)->expanded;
}

/* Task 5: cap on the chip label length. label[channel] is char[9] in
 * Arranger (8 chars + NUL); the cursor is bounded to 0..8 inclusive
 * so the user can sit at the end and insert one more. */
#define CHIP_LABEL_MAX 8

/* Task 5: find the index of `c` in the arcade NAME_CHARS table, with
 * a-z folded to A-Z the same way the preset-node helper does. Returns
 * 0 for chars not in the table so cycling wraps to 'A'. Declared in
 * gui.h so tests/dsp/test_mod_voice.c can unit-test the cycle logic
 * directly; the preset node keeps its own identical helper to avoid
 * sharing fixture-critical code. */

int chipLabelCharIndex(char c) {
	if(c >= 'a' && c <= 'z') {
		c = (char)(c - 32);
	}
	for(int i = 0; i < (int)strlen(NAME_CHARS); i++) {
		if(NAME_CHARS[i] == c) {
			return i;
		}
	}
	return 0;
}

/* Task 5: cycle the char at chip->cursor through NAME_CHARS by `delta`
 * (+1 for UP, -1 for DOWN). The slot is whatever it currently holds —
 * NUL (cursor sits past the end of the label) is treated as index 0,
 * so UP lands on NAME_CHARS[1] = 'B' (not 'A', since 0 is already
 * where NUL maps). This mirrors the preset node's cycleNameChar
 * exactly so the two surfaces behave identically. */

static void chipLabelCycleChar(InstChipGuiNode *chip, int delta) {
	int count = (int)strlen(NAME_CHARS);
	int idx = chipLabelCharIndex(chip->arranger->label[chip->channel][chip->cursor]);
	idx = (idx + delta + count) % count;
	chip->arranger->label[chip->channel][chip->cursor] = NAME_CHARS[idx];
	/* ensure NUL stays at position CHIP_LABEL_MAX */
	chip->arranger->label[chip->channel][CHIP_LABEL_MAX] = '\0';
}

/* Task 5: pure helper — cycle the char at *slot through NAME_CHARS by
 * `dir` (typically +1 for UP, -1 for DOWN). Treats '\0' (NUL) as 'A'
 * so cycling past the end of a label lands on 'A', same as the preset
 * node's cycleNameChar. The slot is left untouched if the table is
 * empty (defensive — NAME_CHARS is a string literal so it's never
 * empty in practice, but the function must not UB if that changes). */

void chipLabelCycleCharAt(char *slot, int dir) {
	if(!slot) return;
	int count = (int)strlen(NAME_CHARS);
	if(count <= 0) return;
	int idx = chipLabelCharIndex(*slot);
	idx = (idx + dir + count) % count;
	*slot = NAME_CHARS[idx];
}

/* Task 5: pure helper — move *cursor by `dir` (-1 left, +1 right),
 * bounded to [0..strlen(label)] AND [0..maxLen] so a corrupt strlen
 * (label somehow larger than the buffer) can never push the cursor
 * past the array end. Anything outside {-1, +1} is silently ignored
 * so the input layer can be forgiving. */

void chipLabelCursorMove(int *cursor, const char *label, int maxLen, int dir) {
	if(!cursor) return;
	if(dir != -1 && dir != 1) return;
	int len = label ? (int)strlen(label) : 0;
	if(len > maxLen) len = maxLen;
	int next = *cursor + dir;
	if(next < 0) next = 0;
	if(next > len) next = len;
	if(next > maxLen) next = maxLen;
	*cursor = next;
}

/* Task 5: route input for the expanded chip. When KM_EDIT is NOT held:
 * LEFT/RIGHT move the swatch focus + write labelColourIdx live. When
 * KM_EDIT IS held: LEFT/RIGHT move the cursor (bounded to strlen),
 * UP/DOWN cycle the char under the cursor through NAME_CHARS. Bare
 * KM_EDIT / KM_SELECT / KM_START collapse (expandChip(channel, false)).
 * Returns nothing — the caller (main.c SCENE_ARRANGER KM_EDIT branch)
 * is responsible for routing when this function should fire. */

void handleExpandedChipInput(int channel, int km, bool editHeld) {
	if(!agui) return;
	if(channel < 0 || channel >= MAX_SEQUENCER_CHANNELS) return;
	GuiNode *node = g_chipNodes[channel];
	if(!node || !isInstChipNode(node)) return;
	InstChipGuiNode *chip = (InstChipGuiNode *)node;
	if(!chip->arranger) return;

	/* Collapse: SELECT / START (and bare EDIT, which is what flips
	 * back to the normal chip view). Bare EDIT means KM_EDIT without
	 * an arrow — callers check that with isKeyJustPressed alone. */
	if(km == KM_SELECT || km == KM_START || km == KM_EDIT) {
		expandChip(channel, false);
		return;
	}

	if(editHeld) {
		/* KM_EDIT + arrow: label edit, mirrors the preset-name node's
		 * model exactly. LEFT/RIGHT = cursor (bounded by the pure
		 * helper), UP/DOWN = char cycle. Cursor is bounded to
		 * [0..len] so it can sit one past NUL. */
		if(km == KM_LEFT) {
			chipLabelCursorMove(&chip->cursor,
				chip->arranger->label[channel], CHIP_LABEL_MAX, -1);
			return;
		}
		if(km == KM_RIGHT) {
			chipLabelCursorMove(&chip->cursor,
				chip->arranger->label[channel], CHIP_LABEL_MAX, 1);
			return;
		}
		if(km == KM_UP) {
			chipLabelCycleChar(chip, 1);
			return;
		}
		if(km == KM_DOWN) {
			chipLabelCycleChar(chip, -1);
			return;
		}
		return;
	}

	/* Bare arrow: swatch navigation. LEFT/RIGHT move the focus +
	 * commit the colour live so the chip's bg tint updates instantly. */
	if(km == KM_LEFT) {
		chip->swatchFocus = (chip->swatchFocus + 7) % 8;
		chip->arranger->labelColourIdx[channel] = chip->swatchFocus;
		return;
	}
	if(km == KM_RIGHT) {
		chip->swatchFocus = (chip->swatchFocus + 1) % 8;
		chip->arranger->labelColourIdx[channel] = chip->swatchFocus;
		return;
	}
}


GuiNode *createInstChipGuiNode(int x, int y, int w, int h, bool selected, struct VoiceManager *vm, int channel, Arranger *arranger) {
	InstChipGuiNode *chip = (InstChipGuiNode *)malloc(sizeof(InstChipGuiNode));
	if(!chip) return NULL;
	memset(chip, 0, sizeof(InstChipGuiNode));
	if(!initGuiNode(&chip->base, x, y, w, h, 2, na_horizontal, "chip", true, selected)) {
		free(chip);
		return NULL;
	}
	chip->base.draw = drawInstChipGuiNode;
	chip->base.drawable = true;
	chip->vm = vm;
	chip->channel = channel;
	chip->arranger = arranger;
	chip->expanded = false;
	chip->swatchFocus = 0;
	/* Task 5: cursor starts at 0 (first slot of the 8-char label).
	 * Bounded at runtime by handleExpandedChipInput + chipLabelMaxLen
	 * so the cursor never indexes past the NUL. */
	chip->cursor = 0;
	return &chip->base;
}

/* ----- Task 1: arranger cell node primitive -----
 *
 * One ArrangerCellGuiNode = one song[ch][row] cell rendered in the
 * arranger grid. It's a tiny GuiNode: base init + (ch, row) + backref
 * to the Arranger. We don't need an InstChipGuiNode-style embedded
 * GuiNode because there's nothing graph-children-related to manage —
 * the arranger window builds a flat grid of these directly.
 *
 * Draw: cell outline, tinted fill when selected. Text content + the
 * playhead marker are intentionally deferred — they're window-level
 * concerns that layer on once visibleStart is wired up in later tasks.
 */
typedef struct {
	GuiNode base;
	Arranger *arranger;
	int ch;
	int row;
} ArrangerCellGuiNode;

/* Arranger cell fill colour decision, exposed for unit tests. The
 * playhead highlight only applies to cells that actually hold a pattern
 * (song value > -1) — empty cells stay blank even if the channel's
 * playhead index happens to coincide with their row (non-playing
 * channels keep a stale playhead index from startPlaying). */

Color arrangerCellFill(int cellValue, int playheadIndex, int row, bool playing, Color playhead, Color defaultC, Color blankC) {
	if(cellValue > -1 && playheadIndex == row && playing) {
		return playhead;
	}
	if(cellValue > -1) {
		return defaultC;
	}
	return blankC;
}


static void drawArrangerCellGuiNode(void *self) {
	ArrangerCellGuiNode *cell = (ArrangerCellGuiNode *)self;
	if(cell->arranger == NULL) {
		return;
	}
	GuiNode *gn = &cell->base;
	Arranger *a = cell->arranger;
	Color bg = arrangerCellFill(a->song[cell->ch][cell->row], a->playhead_indices[cell->ch], cell->row, a->playing, cs.arrangerPlayhead, cs.defaultCell, cs.blankCell);
	DrawRectangle(gn->x, gn->y, gn->w, gn->h, bg);
	int fs = (gn->h / 3 > 6) ? gn->h / 3 : 6;
	char buf[8];
	if(a->song[cell->ch][cell->row] > -1) {
		snprintf(buf, sizeof(buf), "%02i", a->song[cell->ch][cell->row]);
	} else {
		snprintf(buf, sizeof(buf), "--");
	}
	int tw = MeasureText(buf, fs);
	DrawTextEx(pixelFont, buf, (Vector2){ gn->x + (gn->w - tw) / 2, gn->y + (gn->h - fs) / 2 }, fs, 1, cs.arrangerCellText);
	if(gn->selected) {
		DrawRectangleLinesEx((Rectangle){ gn->x, gn->y, gn->w, gn->h }, 2.0, cs.outlineColour);
	}
}


bool isArrangerCellNode(const GuiNode *n) {
	return n != NULL && n->draw == drawArrangerCellGuiNode;
}


void getArrangerCellCoords(const GuiNode *n, int *x, int *y) {
	if(!n || !isArrangerCellNode(n)) {
		if(x) *x = -1;
		if(y) *y = -1;
		return;
	}
	const ArrangerCellGuiNode *cell = (const ArrangerCellGuiNode *)n;
	if(x) *x = cell->ch;
	if(y) *y = cell->row;
}


GuiNode *createArrangerCellGuiNode(int x, int y, int w, int h, bool selected, Arranger *arranger, int ch, int row) {
	ArrangerCellGuiNode *cell = (ArrangerCellGuiNode *)malloc(sizeof(ArrangerCellGuiNode));
	if(!cell) return NULL;
	memset(cell, 0, sizeof(ArrangerCellGuiNode));
	if(!initGuiNode(&cell->base, x, y, w, h, 0, na_horizontal, "cell", true, selected)) {
		free(cell);
		return NULL;
	}
	cell->base.draw = drawArrangerCellGuiNode;
	cell->base.drawable = true;
	cell->arranger = arranger;
	cell->ch = ch;
	cell->row = row;
	return &cell->base;
}

/* Task 2 (arranger window rework): locate the gridColumn node inside
 * the built arranger graph. Walks agui->root → first horizontal child
 * (arrWrap) → gridColumn (named "gcol"). Returns NULL if anything is
 * missing. The graph layout is fixed (see createArrangerGraph), so a
 * linear walk is enough. */

static GuiNode *findGridColumn(void) {
	if(!agui || !agui->root || !agui->root->items || agui->root->itemCount <= 0) {
		return NULL;
	}
	ListElement *e = agui->root->items->head;
	for(int i = 0; i < agui->root->itemCount; i++) {
		GuiNode *top = *(GuiNode **)e->data;
		if(!top || !top->items) {
			e = e->next;
			continue;
		}
		ListElement *fe = top->items->head;
		for(int j = 0; j < top->itemCount; j++) {
			GuiNode *cand = *(GuiNode **)fe->data;
			if(cand && cand->name && strcmp(cand->name, "gcol") == 0) {
				return cand;
			}
			fe = fe->next;
		}
		e = e->next;
	}
	return NULL;
}

/* Task 2: return the cell GuiNode at visible-row `rowIdx`, channel `ch`
 * in the currently-built arranger graph. Returns NULL if no graph is
 * built or the indices are out of range. Layout: gridColumn children
 * are [chipRow, row0, row1, ..., rowN-1] — rows start at index 1. */

GuiNode *getArrangerRowCell(int rowIdx, int ch) {
	if(!g_arranger) return NULL;
	GuiNode *gc = findGridColumn();
	if(!gc || rowIdx < 0 || rowIdx >= ARRANGER_WINDOW_ROWS) return NULL;
	/* gridColumn children: [chipRow, row0, ..., rowN-1] */
	ListElement *e = gc->items->head;
	for(int skip = 0; skip <= rowIdx && e; skip++) {
		if(skip == rowIdx) {
			GuiNode *row = *(GuiNode **)e->data;
			if(!row || !row->items || ch < 0 || ch >= row->itemCount) return NULL;
			ListElement *ce = row->items->head;
			for(int c = 0; c < ch && ce; c++) ce = ce->next;
			if(!ce) return NULL;
			return *(GuiNode **)ce->data;
		}
		e = e->next;
	}
	return NULL;
}

/* Task 3: shared cell-retarget walk used by both scrollArrangerWindow
 * (delta-driven) and scrollArrangerWindowTo (absolute-driven). After a
 * visibleStart change, walk the grid column's children, skip the chip
 * row at index 0, then for each of the ARRANGER_WINDOW_ROWS row
 * containers reassign every cell's `row` to `newStart + r` and toggle
 * its `selected` flag against the Arranger's (selected_x,
 * selected_y) so the user's focus cell follows the scroll. No-op if
 * no arranger graph is built yet. */

static void retargetWindowCells(Arranger *a, int newStart) {
	if(!g_arranger || !agui || !a) return;
	GuiNode *gc = findGridColumn();
	if(!gc || gc->itemCount < 1 + ARRANGER_WINDOW_ROWS) return;
	ListElement *e = gc->items->head;
	/* skip chipRow (index 0) */
	e = e->next;
	for(int r = 0; r < ARRANGER_WINDOW_ROWS && e; r++) {
		GuiNode *row = *(GuiNode **)e->data;
		if(row && row->items) {
			ListElement *ce = row->items->head;
			for(int c = 0; c < row->itemCount && ce; c++) {
				GuiNode *cell = *(GuiNode **)ce->data;
				if(cell) {
					ArrangerCellGuiNode *ac = (ArrangerCellGuiNode *)cell;
					int songRow = newStart + r;
					ac->row = songRow;
					bool sel = (c == a->selected_x && songRow == a->selected_y);
					ac->base.selected = sel;
				}
				ce = ce->next;
			}
		}
		e = e->next;
	}
}

/* Task 2: scroll the visible arranger window by `delta` rows. The
 * visible slice [visibleStart, visibleStart + ARRANGER_WINDOW_ROWS) is
 * clamped into [0, MAX_SONG_LENGTH - ARRANGER_WINDOW_ROWS]. If an
 * arranger graph is currently built, every cell row is retargeted to
 * its new song row, and selection is moved to the cell at
 * (selected_x, selected_y) so the user's focus point follows the scroll
 * (clamped to the new window). If no graph is built, only the
 * arithmetic clamp runs — the unit test relies on this. */

void scrollArrangerWindow(Arranger *a, int delta) {
	if(!a) return;
	int next = a->visibleStart + delta;
	int maxStart = MAX_SONG_LENGTH - ARRANGER_WINDOW_ROWS;
	if(maxStart < 0) maxStart = 0; /* defensive — MAX_SONG_LENGTH could
								   * in theory be < ARRANGER_WINDOW_ROWS */
	if(next < 0) next = 0;
	if(next > maxStart) next = maxStart;
	a->visibleStart = next;
	retargetWindowCells(a, next);
}

/* Task 3: jump the visible arranger window to the absolute song row
 * `targetStart` (clamped to [0, MAX_SONG_LENGTH - ARRANGER_WINDOW_ROWS]).
 * Used by main.c's playhead-follow so the rendered cells track the
 * playhead without losing the user's focus cell. Same retarget walk
 * as scrollArrangerWindow — extracted into retargetWindowCells so
 * the two stay in sync. */

void scrollArrangerWindowTo(Arranger *a, int targetStart) {
	if(!a) return;
	int maxStart = MAX_SONG_LENGTH - ARRANGER_WINDOW_ROWS;
	if(maxStart < 0) maxStart = 0;
	if(targetStart < 0) targetStart = 0;
	if(targetStart > maxStart) targetStart = maxStart;
	if(targetStart == a->visibleStart) return;
	a->visibleStart = targetStart;
	retargetWindowCells(a, targetStart);
}

void gui_arranger_draw(void) {
	drawNode(agui->root);
}
