/* gui_gui_instrument.c -- generated by the gui module split (lawn-mowing-gui).
 * One module per screen; shared node helpers live in gui_core.c.
 * Cross-module state/helpers: see gui_internal.h. */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "dstruct.h"
#include "raylib.h"
#include "gui.h"
#include "graph_gui.h"
#include "input.h"
#include "modsystem.h"
#include "notes.h"
#include "voice.h"
#include "io/preset_io.h"
#include "io.h"
#include "gui_internal.h"
#include "gui_inst_internal.h"

static void drawRouteDestNode(void *self) {
	GuiNode *gn = (GuiNode *)self;
	if(!gn) {
		return;
	}
	drawColourRectangle(gn->x, gn->y, gn->w, gn->h, 0.6, 3.5, gn->selected);
	Color labelColour = gn->selected ? cs.labelSelected : cs.label;
	DrawTextEx(pixelFont, gn->name, (Vector2){ gn->x + gn->padding + 4, gn->y + gn->padding + 4 }, 10, 1, labelColour);
}



void addRuntimeSource(Instrument *inst) {
	if(!inst || !inst->modList || inst->modList->count >= MAX_ENVELOPES) {
		return;
	}
	/* Task 8: the audio thread iterates inst->paramList/modList every
	 * buffer; hold the rebuilding flag while we mutate the lists. The
	 * audio lock closes the flag's check-then-use race. */
	pthread_mutex_lock(&g_audioLock);
	inst->rebuilding = true;
	Envelope *env = createAD(inst->paramList, inst->modList, 0.25f, 4.25f, "AD+");
	/* Task 3 fix: mirror the freshly-created envelope into inst->envelopes[]
	 * BEFORE syncing envelopeCount, so the old builder's rebuildInstrumentGraph
	 * call below can dereference inst->envelopes[envIndex] safely. Task 4 will
	 * replace this builder with a modList-based one and the mirror goes away. */
	if(env && inst->envelopeCount < MAX_ENVELOPES) {
		inst->envelopes[inst->envelopeCount] = env;
	}
	/* Task 3: envelopeCount now mirrors modList->count so the harness
	 * ASSERT envcount reads the synced value. */
	inst->envelopeCount = inst->modList->count;
	rebuildInstrumentGraph();
	inst->rebuilding = false;
	pthread_mutex_unlock(&g_audioLock);
}


void removeSource(Instrument *inst, int srcIndex) {
	if(!inst || !inst->modList || srcIndex < inst->coreEnvelopeCount || srcIndex >= inst->modList->count) {
		return;
	}
	/* Task 8: hold the rebuilding flag while we mutate + free from the
	 * modList/paramList the audio thread iterates. The audio lock
	 * closes the flag's check-then-use race. */
	pthread_mutex_lock(&g_audioLock);
	inst->rebuilding = true;
	removeMod(inst->modList, inst->paramList, inst->modList->mods[srcIndex]);
	/* Task 3 fix: clear the mirror slot so the old builder's
	 * rebuildInstrumentGraph does not deref a freed envelope. Task 4 will
	 * remove the mirror entirely when it replaces the builder. */
	if(srcIndex < MAX_ENVELOPES) {
		inst->envelopes[srcIndex] = NULL;
	}
	/* Task 3: keep envelopeCount synced with modList->count. */
	inst->envelopeCount = inst->modList->count;
	rebuildInstrumentGraph();
	inst->rebuilding = false;
	pthread_mutex_unlock(&g_audioLock);
}


void removeSelectedSource(void) {
	if(!igui || !igui->vm || !igui->selectedInstrument) {
		return;
	}
	GuiNode *sel = getSelectedInstGraph()->selected;
	if(!sel) {
		return;
	}
	GuiNode *n = sel;
	while(n && n->container) {
		if(strcmp(n->container->name, "mod_wrap") == 0) {
			int idx = 0;
			ListElement *l = n->container->items->head;
			while(l && *(GuiNode **)l->data != n) {
				idx++;
				l = l->next;
			}
			Instrument *inst = igui->vm->instruments[*igui->selectedInstrument];
			/* idx - 1: account for the mod-wrap header row that Task 4
			 * adds. With the header absent the mapping currently
			 * under-counts by 1; that is intentional and matches the
			 * brief's transitional note. */
			removeSource(inst, idx - 1);
			return;
		}
		n = n->container;
	}
}

/* Compatibility wrapper — preserves the no-header mapping that existed
 * before Task 3, used by callers that have not yet been ported to the
 * header-offset index used by removeSelectedSource. */

void removeSelectedEnvelope(void) {
	if(!igui || !igui->vm || !igui->selectedInstrument) {
		return;
	}
	GuiNode *sel = getSelectedInstGraph()->selected;
	if(!sel) {
		return;
	}
	GuiNode *n = sel;
	while(n && n->container) {
		if(strcmp(n->container->name, "mod_wrap") == 0) {
			int idx = 0;
			ListElement *l = n->container->items->head;
			while(l && *(GuiNode **)l->data != n) {
				idx++;
				l = l->next;
			}
			Instrument *inst = igui->vm->instruments[*igui->selectedInstrument];
			if(idx < inst->envelopeCount) {
				removeSource(inst, idx);
			}
			return;
		}
		n = n->container;
	}
}


static void drawModStripGuiNode(void *self) {
	ModStripGuiNode *msgn = (ModStripGuiNode *)self;
	GuiNode *gn = (GuiNode *)msgn;
	drawModStrip(&msgn->strip, (Rectangle){ gn->x, gn->y, gn->w, gn->h });
}


ModStripGuiNode *createModStripGuiNode(int x, int y, int w, int h, VoiceManager *vm, int channel) {
	ModStripGuiNode *msgn = malloc(sizeof(ModStripGuiNode));
	GuiNode *gn = (GuiNode *)msgn;
	if(!initGuiNode(gn, x, y, w, h, 0, na_horizontal, "modstrip", 0, 0)) {
		printf("ModStripGuiNode init problem.\n");
		free(msgn);
		return NULL;
	}
	initModStrip(&msgn->strip, vm->voicePools[channel], vm->voiceCount[channel], w, h);
	gn->drawable = true;
	gn->draw = drawModStripGuiNode;
	vizfxRegisterModStrip(channel, &msgn->strip);
	return msgn;
}

/* Task 4: Unified mod-source container. Each entry row in the mod-wrap
 * represents one Mod (core envelope or runtime envelope/LFO/RND). The
 * wrap is rebuilt from inst->modList, so the type-changing cbCycleSourceType
 * + addRuntimeSource + removeSource trio all funnel through the same
 * modList->count sync path. The header row (MODS + ADD) at index 0
 * makes removeSelectedSource's `idx - 1` mapping correct. */
typedef struct {
	Instrument *inst;
	int idx;
} SourceCtx;

static SourceCtx g_sourceCtx[MAX_ENVELOPES];


static void refreshSourceCtx(Instrument *inst) {
	for(int i = 0; i < MAX_ENVELOPES; i++) {
		g_sourceCtx[i].inst = inst;
		g_sourceCtx[i].idx = i;
	}
}

/* Task 5: delete-confirm modal for runtime mod sources.
 *
 * The DEL button on each runtime mod-source entry pushes a YES/NO confirm
 * layer. NO just pops; YES pops first (so the layer is gone before the
 * graph rebuild from removeSource reshuffles everything) and then calls
 * removeSource(inst, idx), which rebuilds the instrument graph. The
 * SourceCtx for the entry was refreshed by refreshSourceCtx() above when
 * the graph was last built, so inst+idx are still valid as long as no
 * other mutation has happened in the interim. */

static void cbDeleteCancel(void *ctx) {
	(void)ctx;
	InstrumentGui *ig = igui;
	if(ig) {
		popLayer(&ig->overlayLayers);
	}
}


static void cbDeleteConfirmYes(void *ctx) {
	SourceCtx *sc = (SourceCtx *)ctx;
	InstrumentGui *ig = igui;
	if(ig) {
		popLayer(&ig->overlayLayers);
	}
	if(sc) {
		removeSource(sc->inst, sc->idx);
	}
}


static void cbDeleteSource(void *ctx) {
	SourceCtx *sc = (SourceCtx *)ctx;
	InstrumentGui *ig = igui;
	if(!ig || !sc) {
		return;
	}
	Graph *g = createGraph(na_horizontal);
	const int py = (SCREEN_H - 80) / 2;
	const int px = (SCREEN_W - 280) / 2;
	GuiNode *noBtn = createActionBtnGuiNode(px + 30, py + 44, 100, 22, 0, na_horizontal, "NO", 0, cbDeleteCancel, NULL);
	noBtn->name = strdup("DELETE_NO");
	GuiNode *yesBtn = createActionBtnGuiNode(px + 150, py + 44, 100, 22, 0, na_horizontal, "YES", 0, cbDeleteConfirmYes, sc);
	yesBtn->name = strdup("DELETE_YES");
	appendItem(g->root, noBtn, 1);
	appendItem(g->root, yesBtn, 1);
	changeGraphSelection(g, noBtn);
	Layer *layer = createLayer(g, px, py, 280, 80, "DELETE", true, true);
	pushLayer(&ig->overlayLayers, layer);
}

/* Task 6: route-destination picker.
 *
 * cbOpenRouteLayer (actionCb on the ROUTE button) walks the instrument
 * graph, gathers every routable dial (a dial node = a GuiNode whose draw
 * is drawDialGuiNode or drawDiscreteDialGuiNode and whose Parameter
 * pointer is non-NULL), then pushes a dim, full-screen overlay. The
 * overlay's graph holds one selectable action-button node per routable
 * dial, named after the dial. The first dial is auto-selected so the
 * harness + a fresh player can press EDIT to route into the first dial
 * without navigating. Selecting any dest node and EDIT'ing fires
 * cbRouteToDest which toggles the source's route (add 1.0/MO_ADD or
 * remove) and pops the layer.
 *
 * Why file-static g_destCtx[]: each dest node carries a DestCtx* so the
 * actionCb can find inst + srcIdx + the dest Parameter without having
 * to walk the graph again at EDIT time. Mirrors g_sourceCtx from Task 4.
 *
 * IMPORTANT: appendItem runs reflowCoordinates, which OVERWRITES child
 * rects. We must set each dest node's x/y/w/h to the dial's rect AFTER
 * appendItem, otherwise the picking buttons overlap the dial at the dial's
 * position. set x/y/w/h here explicitly; reflow would otherwise reset
 * them to the container's last-children default. */
typedef struct {
	Instrument *inst;
	int srcIdx;
	Parameter *dest;
} DestCtx;

static DestCtx g_destCtx[MAX_PARAMS];


static void collectRoutableDialsRecurse(GuiNode *node, Parameter **outParams, GuiNode **outNodes, int cap, int *n) {
	if(!node || *n >= cap) {
		return;
	}
	/* A routable dial = draw == drawDialGuiNode || draw == drawDiscreteDialGuiNode
	 * and p != NULL (dials created with a non-NULL Parameter). */
	if(node->draw && node->p && (node->draw == drawDialGuiNode || node->draw == drawDiscreteDialGuiNode)) {
		if(*n < cap) {
			outParams[*n] = node->p;
			outNodes[*n] = node;
			(*n)++;
		}
	}
	if(node->items) {
		ListElement *le = node->items->head;
		while(le) {
			/* Items store the child pointer BY VALUE in an 8-byte block
			 * (appendItem -> appendToList copies sizeof(GuiNode*)). Read
			 * the pointer with *(GuiNode **)le->data, matching every other
			 * graph walk (freeGuiNode, collectSelectables, navigateGraph).
			 * Casting le->data directly treats the block address as the
			 * node and reads past the allocation. */
			GuiNode *cn = *(GuiNode **)le->data;
			if(cn && cn != node) {
				collectRoutableDialsRecurse(cn, outParams, outNodes, cap, n);
			}
			le = le->next;
		}
	}
}


static void collectRoutableDials(GuiNode *node, Parameter **outParams, GuiNode **outNodes, int cap, int *n) {
	*n = 0;
	collectRoutableDialsRecurse(node, outParams, outNodes, cap, n);
}


static void cbRouteToDest(void *ctx) {
	DestCtx *dc = (DestCtx *)ctx;
	InstrumentGui *ig = igui;
	if(!ig) {
		return;
	}
	/* Pop the layer first (so any listener-driven graph work doesn't
	 * run against a stale g->selected). The mutation below rebuilds
	 * the instrument graph via rebuildInstrumentGraph() so popping
	 * first keeps the same ordering pattern as cbDeleteConfirmYes. */
	popLayer(&ig->overlayLayers);
	if(!dc || !dc->inst || !dc->dest) {
		return;
	}
	/* Walk the destination's modulator chain to decide whether to add
	 * or remove. There is no public hasModulation() — the connection
	 * list is the source of truth. */
	Mod *src = dc->inst->modList->mods[dc->srcIdx];
	if(!src) {
		return;
	}
	bool already = false;
	for(ModConnection *c = dc->dest->modulators; c; c = c->next) {
		if(c->source == src) {
			already = true;
			break;
		}
	}
	/* Task 8: route mutation touches the modList the audio thread
	 * iterates; hold the rebuilding flag across the swap. The audio
	 * lock closes the flag's check-then-use race. */
	pthread_mutex_lock(&g_audioLock);
	dc->inst->rebuilding = true;
	if(already) {
		removeModulation(dc->inst->paramList, dc->dest, src);
	} else {
		addModulation(dc->inst->paramList, src, dc->dest, 1.0f, MO_ADD);
	}
	rebuildInstrumentGraph();
	dc->inst->rebuilding = false;
	pthread_mutex_unlock(&g_audioLock);
}

/* cbOpenRouteLayer builds the picking layer. Each routable dial becomes
 * a selectable button drawn at the dial's own x/y/w/h so the visual
 * position matches the underlying dial exactly. */

static void cbOpenRouteLayer(void *ctx) {
	SourceCtx *sc = (SourceCtx *)ctx;
	InstrumentGui *ig = igui;
	if(!ig || !sc || !sc->inst || sc->idx < 0 || sc->idx >= sc->inst->modList->count) {
		return;
	}
	/* Build the destination list by walking the CURRENT instrument graph
	 * (we want the dials as they appear RIGHT NOW — before our own
	 * rebuild — so the user can see what they will route into). */
	Graph *instGraph = getSelectedInstGraph();
	if(!instGraph || !instGraph->root) {
		return;
	}
	Parameter *params[MAX_PARAMS];
	GuiNode *nodes[MAX_PARAMS];
	int n = 0;
	collectRoutableDials(instGraph->root, params, nodes, MAX_PARAMS, &n);
	if(n <= 0) {
		return;
	}
	/* One Graph holds all dest nodes. The Layer dims the rest of the
	 * screen. The first dial is selected so EDIT routes into it
	 * immediately. */
	/* The dest button's name must outlive the paramList / instrument
	 * graph — when rebuildInstrumentGraph() later frees the previous
	 * graph's nodes, params[i]->name's storage goes with it. The
	 * initial heap-copy done by createActionBtnGuiNode (via
	 * initGuiNode) already achieves that, so no further strdup is
	 * needed. */
	Graph *g = createGraph(na_vertical);
	GuiNode *firstDest = NULL;
	GuiNode *destBtns[MAX_PARAMS];
	/* Loop 1: create + append each button. Do NOT pin rects here —
	 * appendItem runs reflowCoordinates, which re-stamps x/y/w/h of
	 * EVERY child already in the container. Pinning after a single
	 * appendItem only to be over-written by the next iteration's
	 * reflow (and by every subsequent iter) leaves only the LAST
	 * button correctly aligned with its dial. */
	for(int i = 0; i < n; i++) {
		g_destCtx[i].inst = sc->inst;
		g_destCtx[i].srcIdx = sc->idx;
		g_destCtx[i].dest = params[i];
		GuiNode *destBtn = createActionBtnGuiNode(0, 0, 100, 100, 0, na_horizontal, params[i]->name, 0, cbRouteToDest, &g_destCtx[i]);
		destBtn->draw = drawRouteDestNode;
		destBtns[i] = destBtn;
		appendItem(g->root, destBtn, 1);
		if(i == 0) {
			firstDest = destBtn;
		}
	}
	/* Loop 2: now that every append has run, no further reflow will
	 * happen — pin each button's rect to its dial's rect so the
	 * picker visually lines up with the underlying dials. */
	for(int i = 0; i < n; i++) {
		destBtns[i]->x = nodes[i]->x;
		destBtns[i]->y = nodes[i]->y;
		destBtns[i]->w = nodes[i]->w;
		destBtns[i]->h = nodes[i]->h;
	}
	if(firstDest) {
		changeGraphSelection(g, firstDest);
	}
	Layer *layer = createLayer(g, 0, 0, SCREEN_W, SCREEN_H, "ROUTE", true, true);
	pushLayer(&ig->overlayLayers, layer);
}

/* Task 7: route-lines overlay. When a ROUTE button is FOCUSED (selected),
 * draw colour-coded lines from the source's route button to every
 * destination dial it currently modulates. Draw-only, non-interactive. */
typedef struct {
	Instrument *inst;
	int srcIdx;
} RouteLinesCtx;


static RouteLinesCtx g_routeLinesCtx;


static int findDialRectForParam(GuiNode *node, Parameter *p, Rectangle *out) {
	if(!node || !p) {
		return 0;
	}
	if((node->draw == drawDialGuiNode || node->draw == drawDiscreteDialGuiNode) && node->p == p) {
		*out = (Rectangle){ node->x, node->y, node->w, node->h };
		return 1;
	}
	if(node->items) {
		ListElement *e = node->items->head;
		for(int i = 0; i < node->itemCount && e; i++) {
			if(findDialRectForParam(*(GuiNode **)e->data, p, out)) {
				return 1;
			}
			e = e->next;
		}
	}
	return 0;
}

/* Find the ROUTE button (actionCb == cbOpenRouteLayer) in the base graph. */

static int findRouteButtonRect(GuiNode *node, Rectangle *out) {
	if(!node) {
		return 0;
	}
	if(node->actionCb == cbOpenRouteLayer) {
		*out = (Rectangle){ node->x, node->y, node->w, node->h };
		return 1;
	}
	if(node->items) {
		ListElement *e = node->items->head;
		for(int i = 0; i < node->itemCount && e; i++) {
			if(findRouteButtonRect(*(GuiNode **)e->data, out)) {
				return 1;
			}
			e = e->next;
		}
	}
	return 0;
}


static void drawRouteLinesNode(void *self) {
	GuiNode *gn = (GuiNode *)self;
	RouteLinesCtx *rc = &g_routeLinesCtx;
	(void)gn;
	if(!rc->inst || rc->srcIdx < 0 || rc->srcIdx >= rc->inst->modList->count) {
		return;
	}
	Mod *src = rc->inst->modList->mods[rc->srcIdx];
	Graph *base = getSelectedInstGraph();
	if(!base || !base->root) {
		return;
	}
	Rectangle anchor = { 0, 0, 0, 0 };
	findRouteButtonRect(base->root, &anchor);
	if(anchor.width <= 0.0f || anchor.height <= 0.0f) {
		return;
	}
	Vector2 from = { anchor.x + anchor.width / 2, anchor.y + anchor.height / 2 };
	for(int i = 0; i < rc->inst->paramList->count; i++) {
		Parameter *p = rc->inst->paramList->params[i];
		if(!p) {
			continue;
		}
		ModConnection *c = p->modulators;
		while(c) {
			if(c->source == src) {
				Rectangle r;
				if(findDialRectForParam(base->root, p, &r)) {
					Vector2 to = { r.x + r.width / 2, r.y + r.height / 2 };
					Color col = (c->type && getParameterValueAsInt(c->type) == MO_MUL) ? cs.routeMul : cs.routeAdd;
					DrawLineEx(from, to, 2.0f, col);
				}
			}
			c = c->next;
		}
	}
}


void syncRouteLinesOverlay(InstrumentGui *ig) {
	if(!ig) {
		return;
	}
	Graph *base = getSelectedInstGraph();
	GuiNode *sel = base ? base->selected : NULL;
	bool onRouteBtn = sel && sel->actionCb == cbOpenRouteLayer;
	Layer *top = topLayer(&ig->overlayLayers);
	bool hasOverlay = top && top->name && strcmp(top->name, "ROUTELINES") == 0;
	/* Only show ROUTELINES when the stack is otherwise empty — pushing on
	 * top of the ROUTE picking layer (EDIT on the button) would make the
	 * passive overlay the top layer and break modal input/selection. */
	if(onRouteBtn && layerStackIsEmpty(&ig->overlayLayers)) {
		/* Route the source through the overlay ctx: the ROUTE button's
		 * actionCtx is &g_sourceCtx[idx] (SourceCtx { inst, idx }). */
		SourceCtx *sc = (SourceCtx *)sel->actionCtx;
		if(sc && sc->inst) {
			g_routeLinesCtx.inst = sc->inst;
			g_routeLinesCtx.srcIdx = sc->idx;
		}
		Graph *g = createGraph(na_horizontal);
		GuiNode *lines = createGuiNode(0, 0, SCREEN_W, SCREEN_H, 0, na_horizontal, "routelines", 0, 0);
		lines->drawable = true;
		lines->draw = drawRouteLinesNode;
		appendItem(g->root, lines, 1);
		Layer *l = createLayer(g, 0, 0, SCREEN_W, SCREEN_H, "ROUTELINES", false, true);
		pushLayer(&ig->overlayLayers, l);
	} else if(!onRouteBtn && hasOverlay) {
		Layer *l = popLayer(&ig->overlayLayers);
		if(l) {
			destroyLayer(l);
		}
	}
}


void cbAddModSource(void *ctx) {
	Instrument *inst = (Instrument *)ctx;
	addRuntimeSource(inst);
}


static void cbCycleSourceType(void *ctx) {
	SourceCtx *sc = (SourceCtx *)ctx;
	if(!sc || !sc->inst || sc->idx < 0 || sc->idx >= sc->inst->modList->count) {
		return;
	}
	Mod *mod = sc->inst->modList->mods[sc->idx];
	ModType next = MT_ENV;
	switch(mod->type) {
		case MT_ENV: next = MT_LFO; break;
		case MT_LFO: next = MT_RND; break;
		default:     next = MT_ENV; break;
	}
	/* Task 8: hold the rebuilding flag while we mutate the lists the audio
	 * thread iterates. The audio lock closes the flag's check-then-use
	 * race. */
	pthread_mutex_lock(&g_audioLock);
	sc->inst->rebuilding = true;
	if(changeModType(sc->inst->modList, mod, next, sc->inst->paramList)) {
		sc->inst->envelopeCount = sc->inst->modList->count;
		rebuildInstrumentGraph();
	}
	sc->inst->rebuilding = false;
	pthread_mutex_unlock(&g_audioLock);
}


static const char *modTypeTag(ModType t) {
	switch(t) {
		case MT_LFO: return "LFO";
		case MT_RND: return "RND";
		default:     return "ENV";
	}
}


void appendModSourceEntry(Graph *g, GuiNode *container, Instrument *inst, int idx, int weight, bool selected) {
	Mod *mod = inst->modList->mods[idx];
	bool core = idx < inst->coreEnvelopeCount;
	GuiNode *wrap = createGuiNode(0, 0, 100, 100, 2, na_horizontal, "MODSRC", 0, 0);
	wrap->drawable = true;
	wrap->draw = drawWrapperNode;

	if(!core) {
		refreshSourceCtx(inst);
		GuiNode *typeBtn = createActionBtnGuiNode(0, 0, 100, 100, 2, na_horizontal,
		                                         modTypeTag(mod->type), 0, cbCycleSourceType, &g_sourceCtx[idx]);
		typeBtn->name = strdup(modTypeTag(mod->type));
		appendItem(wrap, typeBtn, 3);
	}

	switch(mod->type) {
		case MT_ENV: {
			Envelope *e = (Envelope *)mod;
			appendItem(wrap, createDialGuiNode(0, 0, 100, 100, 2, na_horizontal, "ATTACK", selected, incParameterBaseValue, e->stages[0].duration), 4);
			appendItem(wrap, createDialGuiNode(0, 0, 100, 100, 2, na_horizontal, "CURVE", 0, incParameterBaseValue, e->stages[0].curvature), 4);
			appendItem(wrap, createDialGuiNode(0, 0, 100, 100, 2, na_horizontal, "DECAY", 0, incParameterBaseValue, e->stages[1].duration), 4);
			appendItem(wrap, createDialGuiNode(0, 0, 100, 100, 2, na_horizontal, "CURVE", 0, incParameterBaseValue, e->stages[1].curvature), 4);
			break;
		}
		case MT_LFO: {
			LFO *l = (LFO *)mod;
			appendItem(wrap, createDialGuiNode(0, 0, 100, 100, 2, na_horizontal, "RATE", selected, incParameterBaseValue, l->rate), 4);
			if(l->shape) {
				appendItem(wrap, createDialGuiNode(0, 0, 100, 100, 2, na_horizontal, "SHAPE", 0, incParameterBaseValue, l->shape), 4);
			}
			break;
		}
		case MT_RND: {
			Random *r = (Random *)mod;
			appendItem(wrap, createDialGuiNode(0, 0, 100, 100, 2, na_horizontal, "RATE", selected, incParameterBaseValue, r->rate), 4);
			if(r->shape) {
				appendItem(wrap, createDialGuiNode(0, 0, 100, 100, 2, na_horizontal, "SHAPE", 0, incParameterBaseValue, r->shape), 4);
			}
			break;
		}
		default:
			break;
	}

	if(!core) {
		/* Task 6: ROUTE opens the destination-picker layer. cbOpenRouteLayer
		 * reads inst+idx from this entry's SourceCtx (refreshed above by
		 * refreshSourceCtx) so the picker always sees the right Mod. */
		appendItem(wrap, createActionBtnGuiNode(0, 0, 100, 100, 2, na_horizontal, "ROUTE", 0, cbOpenRouteLayer, &g_sourceCtx[idx]), 3);
		/* Task 5: DEL opens the YES/NO confirm layer; cbDeleteSource reads
		 * inst+idx off the per-entry SourceCtx slot refreshed by
		 * refreshSourceCtx() above. */
		appendItem(wrap, createActionBtnGuiNode(0, 0, 100, 100, 2, na_horizontal, "DEL", 0, cbDeleteSource, &g_sourceCtx[idx]), 2);
	}
	appendItem(wrap, createBlankGuiNode(), 1);
	appendItem(container, wrap, weight);
	(void)g;
}


