/* gui_gui_instrument.c -- generated by the gui module split (lawn-mowing-gui).
 * One module per screen; shared node helpers live in gui_core.c.
 * Cross-module state/helpers: see gui_internal.h. */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "dstruct.h"
#include "raylib.h"
#include "gui.h"
#include "graph_gui.h"
#include "input.h"
#include "modsystem.h"
#include "notes.h"
#include "voice.h"
#include "io/preset_io.h"
#include "io.h"
#include "gui_internal.h"
#include "gui_inst_internal.h"
#include "gui_layer.h"

/* Spec #1+2: dest cells in the route picker are now outline-only — no
 * label, no fill, just an osc orange/gold rectangle. The label of the
 * dial this cell maps to is drawn by the ROUTELINES overlay (see
 * drawRouteLinesNode) on top of the selected cell so the user can still
 * read what they're about to route into. Erase mode tints the outline
 * routeMul-blue to make the destructive intent obvious. */
static void drawRouteDestNode(void *self) {
	GuiNode *gn = (GuiNode *)self;
	if(!gn) {
		return;
	}
	(void)drawColourRectangle; /* intentionally unused now */
	/* Spec #2: animate the green channel of cs.routeAdd between
	 * ~120 and ~210 using a slow sine so the outline pulses
	 * orange↔gold. Erase-mode swaps to routeMul (blue) so the
	 * destructive intent is obvious. */
	Color outline = cs.routeAdd;
	if(g_routeErase) {
		outline = cs.routeMul;
	} else {
		float pulse = 120.0f + 90.0f * (0.5f + 0.5f * sinf(GetTime() * 4.0f));
		outline.g = (unsigned char)pulse;
	}
	if(gn->selected) {
		/* Selected gets the focused gold border. Erase-mode selected
		 * picks the destructive red so the user can't miss the intent.
		 * Spec #2 also says selected brightens by ~40 on r and g. */
		outline = g_routeErase ? cs.reddish : cs.labelSelected;
		if(!g_routeErase) {
			int r2 = (int)outline.r + 40;
			int g2 = (int)outline.g + 40;
			if(r2 > 255) {
				r2 = 255;
			}
			if(g2 > 255) {
				g2 = 255;
			}
			outline.r = (unsigned char)r2;
			outline.g = (unsigned char)g2;
		}
	}
	Rectangle r = { gn->x, gn->y, gn->w, gn->h };
	float thickness = gn->selected ? 3.0f : 2.0f;
	DrawRectangleLinesEx(r, thickness, outline);
}



void addRuntimeSource(Instrument *inst) {
	if(!inst || !inst->modList || inst->modList->count >= MAX_ENVELOPES) {
		return;
	}
	/* Task 8: the audio thread iterates inst->paramList/modList every
	 * buffer; hold the rebuilding flag while we mutate the lists. The
	 * audio lock closes the flag's check-then-use race. */
	pthread_mutex_lock(&g_audioLock);
	inst->rebuilding = true;
	Envelope *env = createAD(inst->paramList, inst->modList, 0.25f, 4.25f, "AD+");
	/* Task 3 fix: mirror the freshly-created envelope into inst->envelopes[]
	 * BEFORE syncing envelopeCount, so the old builder's rebuildInstrumentGraph
	 * call below can dereference inst->envelopes[envIndex] safely. Task 4 will
	 * replace this builder with a modList-based one and the mirror goes away. */
	if(env && inst->envelopeCount < MAX_ENVELOPES) {
		inst->envelopes[inst->envelopeCount] = env;
	}
	/* Task 3: envelopeCount now mirrors modList->count so the harness
	 * ASSERT envcount reads the synced value. */
	inst->envelopeCount = inst->modList->count;
	rebuildInstrumentGraph();
	inst->rebuilding = false;
	pthread_mutex_unlock(&g_audioLock);
}


void removeSource(Instrument *inst, int srcIndex) {
	if(!inst || !inst->modList || srcIndex < inst->coreEnvelopeCount || srcIndex >= inst->modList->count) {
		return;
	}
	/* Task 8: hold the rebuilding flag while we mutate + free from the
	 * modList/paramList the audio thread iterates. The audio lock
	 * closes the flag's check-then-use race. */
	pthread_mutex_lock(&g_audioLock);
	inst->rebuilding = true;
	removeMod(inst->modList, inst->paramList, inst->modList->mods[srcIndex]);
	/* Task 3 fix: clear the mirror slot so the old builder's
	 * rebuildInstrumentGraph does not deref a freed envelope. Task 4 will
	 * remove the mirror entirely when it replaces the builder. */
	if(srcIndex < MAX_ENVELOPES) {
		inst->envelopes[srcIndex] = NULL;
	}
	/* Task 3: keep envelopeCount synced with modList->count. */
	inst->envelopeCount = inst->modList->count;
	rebuildInstrumentGraph();
	inst->rebuilding = false;
	pthread_mutex_unlock(&g_audioLock);
}


void removeSelectedSource(void) {
	if(!igui || !igui->vm || !igui->selectedInstrument) {
		return;
	}
	GuiNode *sel = getSelectedInstGraph()->selected;
	if(!sel) {
		return;
	}
	GuiNode *n = sel;
	while(n && n->container) {
		if(strcmp(n->container->name, "mod_wrap") == 0) {
			int idx = 0;
			ListElement *l = n->container->items->head;
			while(l && *(GuiNode **)l->data != n) {
				idx++;
				l = l->next;
			}
			Instrument *inst = igui->vm->instruments[*igui->selectedInstrument];
			/* idx - 1: account for the mod-wrap header row that Task 4
			 * adds. With the header absent the mapping currently
			 * under-counts by 1; that is intentional and matches the
			 * brief's transitional note. */
			removeSource(inst, idx - 1);
			return;
		}
		n = n->container;
	}
}

/* Compatibility wrapper — preserves the no-header mapping that existed
 * before Task 3, used by callers that have not yet been ported to the
 * header-offset index used by removeSelectedSource. */

void removeSelectedEnvelope(void) {
	if(!igui || !igui->vm || !igui->selectedInstrument) {
		return;
	}
	GuiNode *sel = getSelectedInstGraph()->selected;
	if(!sel) {
		return;
	}
	GuiNode *n = sel;
	while(n && n->container) {
		if(strcmp(n->container->name, "mod_wrap") == 0) {
			int idx = 0;
			ListElement *l = n->container->items->head;
			while(l && *(GuiNode **)l->data != n) {
				idx++;
				l = l->next;
			}
			Instrument *inst = igui->vm->instruments[*igui->selectedInstrument];
			if(idx < inst->envelopeCount) {
				removeSource(inst, idx);
			}
			return;
		}
		n = n->container;
	}
}


static void freeModStripGuiNode(void *self) {
	ModStripGuiNode *msgn = (ModStripGuiNode *)self;
	freeModStrip(&msgn->strip);
	vizfxUnregisterModStrip(msgn->channel);
}

static void drawModStripGuiNode(void *self) {
	ModStripGuiNode *msgn = (ModStripGuiNode *)self;
	GuiNode *gn = (GuiNode *)msgn;
	drawModStrip(&msgn->strip, (Rectangle){ gn->x, gn->y, gn->w, gn->h });
}


ModStripGuiNode *createModStripGuiNode(int x, int y, int w, int h, VoiceManager *vm, int channel) {
	ModStripGuiNode *msgn = malloc(sizeof(ModStripGuiNode));
	GuiNode *gn = (GuiNode *)msgn;
	if(!initGuiNode(gn, x, y, w, h, 0, na_horizontal, "modstrip", 0, 0)) {
		printf("ModStripGuiNode init problem.\n");
		free(msgn);
		return NULL;
	}
	initModStrip(&msgn->strip, vm->voicePools[channel], vm->voiceCount[channel], w, h);
	msgn->channel = channel;
	gn->drawable = true;
	gn->draw = drawModStripGuiNode;
	gn->destructor = freeModStripGuiNode;
	vizfxRegisterModStrip(channel, &msgn->strip);
	return msgn;
}

/* Task 4: Unified mod-source container. Each entry row in the mod-wrap
 * represents one Mod (core envelope or runtime envelope/LFO/RND). The
 * wrap is rebuilt from inst->modList, so the type-changing cbCycleSourceType
 * + addRuntimeSource + removeSource trio all funnel through the same
 * modList->count sync path. The header row (MODS + ADD) at index 0
 * makes removeSelectedSource's `idx - 1` mapping correct. */
typedef struct {
	Instrument *inst;
	int idx;
} SourceCtx;

static SourceCtx g_sourceCtx[MAX_ENVELOPES];

/* DestCtx and g_destCtx are referenced by the probe helper
 * probePickFirstRoute (declared below) and must therefore be visible
 * before it. The picker layer also writes to g_destCtx[i] when it
 * builds its dest buttons; cbRouteToDest reads from it on EDIT. */
typedef struct {
	Instrument *inst;
	int srcIdx;
	Parameter *dest;
} DestCtx;

static DestCtx g_destCtx[MAX_PARAMS];


/* Spec #4+#5: gradient + label overlay. The gradient renderer needs the
 * runtime source so it can map MO_ADD vs MO_MUL onto the warm/cool
 * endpoints of each line. drawRouteLinesNode is the only consumer. */
typedef struct {
	Instrument *inst;
	int srcIdx;
	Mod *srcMod;
} RouteLinesCtx;

static RouteLinesCtx g_routeLinesCtx;


static void cbRouteToDest(void *ctx);
void cbOpenRouteLayer(void *ctx);

/* Probe helper: returns true when running under the --probe-route
 * diagnostic. Tests that link gui_inst_mod.c without main.c get a
 * weak fallback that always returns false. */
#include "main.h"
__attribute__((weak)) bool isProbeRouteActive(void);

static void refreshSourceCtx(Instrument *inst) {
	for(int i = 0; i < MAX_ENVELOPES; i++) {
		g_sourceCtx[i].inst = inst;
		g_sourceCtx[i].idx = i;
	}
}

/* Probe-only helper: wire the most recently added runtime source into
 * the first few routable parameters of the selected instrument. Wires
 * up to PROBE_ROUTE_COUNT destinations (skipping the ALGO parameter
 * which is a discrete selector). Returns the number of modulations
 * added. Gated behind g_probeRoute from main.c (zero effect when
 * --probe-route is absent). */
#define PROBE_ROUTE_COUNT 4
int probePickFirstRoute(void) {
	InstrumentGui *ig = igui;
	if(!ig || !ig->vm) {
		return 0;
	}
	Instrument *inst = ig->vm->instruments[*ig->selectedInstrument];
	if(!inst || !inst->modList || !inst->paramList) {
		return 0;
	}
	int srcIdx = inst->modList->count - 1;
	if(srcIdx < 0) {
		return 0;
	}
	Mod *m = inst->modList->mods[srcIdx];
	if(!m) {
		return 0;
	}
	int added = 0;
	for(int i = 0; i < inst->paramList->count && added < PROBE_ROUTE_COUNT; i++) {
		Parameter *dest = inst->paramList->params[i];
		if(!dest) {
			continue;
		}
		if(dest->modulator_count > 0) {
			continue;
		}
		if(!addModulation(inst->paramList, inst->modList, m, dest, 1.0f, MO_ADD)) {
			continue;
		}
		added++;
	}
	if(added == 0) {
		return 0;
	}
	/* Point the gradient overlay at this source so the line + end-
	 * circles actually render. */
	g_routeLinesCtx.inst = inst;
	g_routeLinesCtx.srcIdx = srcIdx;
	g_routeLinesCtx.srcMod = m;
	return added;
}

/* Spec #3 (picker bookkeeping): how many ROUTE picker layers are
 * currently open. Bumped in cbOpenRouteLayer, decremented in any path
 * that closes one. Used by cbRouteToDest's rebuild path so a single
 * EDIT can rebuild the ROUTE graph in place without re-pushing the
 * picker. Also used by syncRouteLinesOverlay to decide whether the
 * gradient overlay should be visible (it tracks the picker state, not
 * the ROUTE button hover). */
int g_routePickerCount = 0;

/* Spec #6 (erase mode): the second EDIT on a dest that already has a
 * route, or any dest EDIT while this flag is true, calls
 * removeModulation instead of addModulation. Toggled by guiSetRouteEraseMode
 * from the topmost ROUTE layer's input handler when the user holds the
 * erase modifier; reset to false on every ROUTE pop. */
bool g_routeErase = false;

void guiSetRouteEraseMode(bool on) {
	g_routeErase = on;
}

bool guiRouteEraseMode(void) {
	return g_routeErase;
}

/* Spec #3 helper: true when any non-passive layer on the stack is
 * named "ROUTE". Drives the "overlay visible" decision from the picker
 * state alone (no hover coupling) so the picker and overlay stay
 * coupled across edit/rebuild. */
static bool routePickerIsOpen(const InstrumentGui *ig) {
	if(!ig || !ig->overlayLayers.count <= 0) {
		return false;
	}
	const LayerStack *stack = &ig->overlayLayers;
	for(int i = stack->count - 1; i >= 0; i--) {
		const Layer *l = &stack->layers[i];
		if(l->name && strcmp(l->name, "ROUTE") == 0 && !l->passive) {
			return true;
		}
	}
	return false;
}

/* Task 5: delete-confirm modal for runtime mod sources.
 *
 * The DEL button on each runtime mod-source entry pushes a YES/NO confirm
 * layer. NO just pops; YES pops first (so the layer is gone before the
 * graph rebuild from removeSource reshuffles everything) and then calls
 * removeSource(inst, idx), which rebuilds the instrument graph. The
 * SourceCtx for the entry was refreshed by refreshSourceCtx() above when
 * the graph was last built, so inst+idx are still valid as long as no
 * other mutation has happened in the interim. */

static void cbDeleteCancel(void *ctx) {
	(void)ctx;
	InstrumentGui *ig = igui;
	if(ig) {
		popLayer(&ig->overlayLayers);
	}
}


static void cbDeleteConfirmYes(void *ctx) {
	SourceCtx *sc = (SourceCtx *)ctx;
	InstrumentGui *ig = igui;
	if(ig) {
		popLayer(&ig->overlayLayers);
	}
	if(sc) {
		removeSource(sc->inst, sc->idx);
	}
}


static void cbDeleteSource(void *ctx) {
	SourceCtx *sc = (SourceCtx *)ctx;
	InstrumentGui *ig = igui;
	if(!ig || !sc) {
		return;
	}
	Graph *g = createGraph(na_horizontal);
	const int py = (SCREEN_H - 80) / 2;
	const int px = (SCREEN_W - 280) / 2;
	GuiNode *noBtn = createActionBtnGuiNode(px + 30, py + 44, 100, 22, 0, na_horizontal, "NO", 0, cbDeleteCancel, NULL);
	noBtn->name = strdup("DELETE_NO");
	GuiNode *yesBtn = createActionBtnGuiNode(px + 150, py + 44, 100, 22, 0, na_horizontal, "YES", 0, cbDeleteConfirmYes, sc);
	yesBtn->name = strdup("DELETE_YES");
	appendItem(g->root, noBtn, 1);
	appendItem(g->root, yesBtn, 1);
	changeGraphSelection(g, noBtn);
	Layer *layer = createLayer(g, px, py, 280, 80, "DELETE", true, true);
	pushLayer(&ig->overlayLayers, layer);
}

/* Task 6: route-destination picker.
 *
 * cbOpenRouteLayer (actionCb on the ROUTE button) walks the instrument
 * graph, gathers every routable dial (a dial node = a GuiNode whose draw
 * is drawDialGuiNode or drawDiscreteDialGuiNode and whose Parameter
 * pointer is non-NULL), then pushes a dim, full-screen overlay. The
 * overlay's graph holds one selectable action-button node per routable
 * dial, named after the dial. The first dial is auto-selected so the
 * harness + a fresh player can press EDIT to route into the first dial
 * without navigating. Selecting any dest node and EDIT'ing fires
 * cbRouteToDest which toggles the source's route (add 1.0/MO_ADD or
 * remove) and pops the layer.
 *
 * Why file-static g_destCtx[]: each dest node carries a DestCtx* so the
 * actionCb can find inst + srcIdx + the dest Parameter without having
 * to walk the graph again at EDIT time. Mirrors g_sourceCtx from Task 4.
 *
 * IMPORTANT: appendItem runs reflowCoordinates, which OVERWRITES child
 * rects. We must set each dest node's x/y/w/h to the dial's rect AFTER
 * appendItem, otherwise the picking buttons overlap the dial at the dial's
 * position. set x/y/w/h here explicitly; reflow would otherwise reset
 * them to the container's last-children default. */


static void collectRoutableDialsRecurse(GuiNode *node, Parameter **outParams, GuiNode **outNodes, int cap, int *n) {
	if(!node || *n >= cap) {
		return;
	}
	/* A routable dial = draw == drawDialGuiNode || draw == drawDiscreteDialGuiNode
	 * and p != NULL (dials created with a non-NULL Parameter). */
	if(node->draw && node->p && (node->draw == drawDialGuiNode || node->draw == drawDiscreteDialGuiNode)) {
		if(*n < cap) {
			outParams[*n] = node->p;
			outNodes[*n] = node;
			(*n)++;
		}
	}
	if(node->items) {
		ListElement *le = node->items->head;
		while(le) {
			/* Items store the child pointer BY VALUE in an 8-byte block
			 * (appendItem -> appendToList copies sizeof(GuiNode*)). Read
			 * the pointer with *(GuiNode **)le->data, matching every other
			 * graph walk (freeGuiNode, collectSelectables, navigateGraph).
			 * Casting le->data directly treats the block address as the
			 * node and reads past the allocation. */
			GuiNode *cn = *(GuiNode **)le->data;
			if(cn && cn != node) {
				collectRoutableDialsRecurse(cn, outParams, outNodes, cap, n);
			}
			le = le->next;
		}
	}
}


static void collectRoutableDials(GuiNode *node, Parameter **outParams, GuiNode **outNodes, int cap, int *n) {
	*n = 0;
	collectRoutableDialsRecurse(node, outParams, outNodes, cap, n);
}


/* Spec #6: route erase mode is a temporary destructive toggle that
 * lives for the duration of one ROUTE picker open. The picker bookkeeping
 * (g_routePickerCount) is the authority on whether the overlay should be
 * pushed; cbRouteToDest is the single point where picker count, erase
 * flag, and the picked modList mutation come together. */

static void cbRouteToDest(void *ctx) {
	DestCtx *dc = (DestCtx *)ctx;
	InstrumentGui *ig = igui;
	if(!ig) {
		return;
	}
	if(!dc || !dc->inst || !dc->dest) {
		return;
	}
	/* Walk the destination's modulator chain to decide whether to add
	 * or remove. There is no public hasModulation() — the connection
	 * list is the source of truth. */
	Mod *src = dc->inst->modList->mods[dc->srcIdx];
	if(!src) {
		return;
	}
	/* Spec #6: KM_FUNCTION+KM_EDIT erases mode. Hold the rebuilding
	 * flag + audio lock, walk dc->dest->modulators removing EVERY
	 * connection whose source == src, leave the picker layer open
	 * so the user can clear several destinations in a row, and
	 * skip the post-edit pop+rebuild. */
	if(g_routeErase) {
		pthread_mutex_lock(&g_audioLock);
		dc->inst->rebuilding = true;
		for(;;) {
			ModConnection *match = NULL;
			for(ModConnection *c = dc->dest->modulators; c; c = c->next) {
				if(c->source == src) {
					match = c;
					break;
				}
			}
			if(!match) {
				break;
			}
			removeModulation(dc->inst->paramList, dc->inst->modList, dc->dest, src);
		}
		dc->inst->rebuilding = false;
		pthread_mutex_unlock(&g_audioLock);
		/* No pop, no rebuild — the picker stays open and the
		 * gradient overlay reflects the new topology next frame. */
		g_routeErase = false;
		(void)ig;
		return;
	}
	bool already = false;
	for(ModConnection *c = dc->dest->modulators; c; c = c->next) {
		if(c->source == src) {
			already = true;
			break;
		}
	}
	/* Pop the picker (so any listener-driven graph work doesn't run
	 * against a stale g->selected). The mutation below rebuilds the
	 * instrument graph via rebuildInstrumentGraph() so popping first
	 * keeps the same ordering pattern as cbDeleteConfirmYes. */
	popLayer(&ig->overlayLayers);
	if(g_routePickerCount > 0) {
		g_routePickerCount--;
	}
	g_routeErase = false;
	/* Task 8: route mutation touches the modList the audio thread
	 * iterates; hold the rebuilding flag across the swap. The audio
	 * lock closes the flag's check-then-use race. */
	pthread_mutex_lock(&g_audioLock);
	dc->inst->rebuilding = true;
	if(already) {
		removeModulation(dc->inst->paramList, dc->inst->modList, dc->dest, src);
	} else {
		addModulation(dc->inst->paramList, dc->inst->modList, src, dc->dest, 1.0f, MO_ADD);
	}
	rebuildInstrumentGraph();
	dc->inst->rebuilding = false;
	pthread_mutex_unlock(&g_audioLock);
	/* Spec #3: the source graph just rebuilt — re-sync the gradient
	 * overlay so the new line topology shows up before the next frame. */
	syncRouteLinesOverlay(ig);
}

/* cbOpenRouteLayer builds the picking layer. Each routable dial becomes
 * a selectable button drawn at the dial's own x/y/w/h so the visual
 * position matches the underlying dial exactly. */

void cbOpenRouteLayer(void *ctx) {
	SourceCtx *sc = (SourceCtx *)ctx;
	InstrumentGui *ig = igui;
	if(!ig || !sc || !sc->inst || sc->idx < 0 || sc->idx >= sc->inst->modList->count) {
		return;
	}
	/* Build the destination list by walking the CURRENT instrument graph
	 * (we want the dials as they appear RIGHT NOW — before our own
	 * rebuild — so the user can see what they will route into). */
	Graph *instGraph = getSelectedInstGraph();
	if(!instGraph || !instGraph->root) {
		return;
	}
	Parameter *params[MAX_PARAMS];
	GuiNode *nodes[MAX_PARAMS];
	int n = 0;
	collectRoutableDials(instGraph->root, params, nodes, MAX_PARAMS, &n);
	if(n <= 0) {
		return;
	}
	/* One Graph holds all dest nodes. The Layer dims the rest of the
	 * screen. The first dial is selected so EDIT routes into it
	 * immediately. */
	/* The dest button's name must outlive the paramList / instrument
	 * graph — when rebuildInstrumentGraph() later frees the previous
	 * graph's nodes, params[i]->name's storage goes with it. The
	 * initial heap-copy done by createActionBtnGuiNode (via
	 * initGuiNode) already achieves that, so no further strdup is
	 * needed. */
	Graph *g = createGraph(na_vertical);
	GuiNode *firstDest = NULL;
	GuiNode *destBtns[MAX_PARAMS];
	/* Loop 1: create + append each button. Do NOT pin rects here —
	 * appendItem runs reflowCoordinates, which re-stamps x/y/w/h of
	 * EVERY child already in the container. Pinning after a single
	 * appendItem only to be over-written by the next iteration's
	 * reflow (and by every subsequent iter) leaves only the LAST
	 * button correctly aligned with its dial. */
	for(int i = 0; i < n; i++) {
		g_destCtx[i].inst = sc->inst;
		g_destCtx[i].srcIdx = sc->idx;
		g_destCtx[i].dest = params[i];
		GuiNode *destBtn = createActionBtnGuiNode(0, 0, 100, 100, 0, na_horizontal, params[i]->name, 0, cbRouteToDest, &g_destCtx[i]);
		destBtn->draw = drawRouteDestNode;
		destBtns[i] = destBtn;
		appendItem(g->root, destBtn, 1);
		if(i == 0) {
			firstDest = destBtn;
		}
	}
	/* Loop 2: now that every append has run, no further reflow will
	 * happen — pin each button's rect to its dial's rect so the
	 * picker visually lines up with the underlying dials. */
	for(int i = 0; i < n; i++) {
		destBtns[i]->x = nodes[i]->x;
		destBtns[i]->y = nodes[i]->y;
		destBtns[i]->w = nodes[i]->w;
		destBtns[i]->h = nodes[i]->h;
	}
	if(firstDest) {
		changeGraphSelection(g, firstDest);
	}
	Layer *layer = createLayer(g, 0, 0, SCREEN_W, SCREEN_H, "ROUTE", true, true);
	pushLayer(&ig->overlayLayers, layer);
	g_routePickerCount++;
	g_routeErase = false;
	/* Spec #3: the gradient overlay rides on top of the picker so the
	 * user can see existing routes while picking. Reuse the existing
	 * sync path so this stays in lock-step with the standalone
	 * hover-driven case. */
	syncRouteLinesOverlay(ig);
}

/* Task 7: route-lines overlay. When a ROUTE button is FOCUSED (selected),
* draw colour-coded lines from the source's route button to every
 * destination dial it currently modulates. Draw-only, non-interactive. */


static int findDialRectForParam(GuiNode *node, Parameter *p, Rectangle *out) {
	if(!node || !p) {
		return 0;
	}
	if((node->draw == drawDialGuiNode || node->draw == drawDiscreteDialGuiNode) && node->p == p) {
		*out = (Rectangle){ node->x, node->y, node->w, node->h };
		return 1;
	}
	if(node->items) {
		ListElement *e = node->items->head;
		for(int i = 0; i < node->itemCount && e; i++) {
			if(findDialRectForParam(*(GuiNode **)e->data, p, out)) {
				return 1;
			}
			e = e->next;
		}
	}
	return 0;
}

/* Find the ROUTE button (actionCb == cbOpenRouteLayer) in the base graph. */

static int findRouteButtonRect(GuiNode *node, Rectangle *out) {
	if(!node) {
		return 0;
	}
	if(node->actionCb == cbOpenRouteLayer) {
		*out = (Rectangle){ node->x, node->y, node->w, node->h };
		return 1;
	}
	if(node->items) {
		ListElement *e = node->items->head;
		for(int i = 0; i < node->itemCount && e; i++) {
			if(findRouteButtonRect(*(GuiNode **)e->data, out)) {
				return 1;
			}
			e = e->next;
		}
	}
	return 0;
}


/* Spec #2 helper: find the GuiNode that hosts a given Parameter. We
 * need this so we can call dialLabelPos on it (Spec #2). */
static GuiNode *findDialNodeForParam(GuiNode *node, Parameter *p) {
	if(!node || !p) {
		return NULL;
	}
	if((node->draw == drawDialGuiNode || node->draw == drawDiscreteDialGuiNode) && node->p == p) {
		return node;
	}
	if(node->items) {
		ListElement *e = node->items->head;
		for(int i = 0; i < node->itemCount && e; i++) {
			GuiNode *r = findDialNodeForParam(*(GuiNode **)e->data, p);
			if(r) {
				return r;
			}
			e = e->next;
		}
	}
	return NULL;
}


/* Spec #4: pre-baked gradient palette. The picker draws many line
 * segments per frame from a single source to N destinations; computing
 * a fresh Color each segment was the per-frame hot spot. A 64-step LUT
 * interpolating between the routeAdd (orange) and routeMul (blue)
 * accent colours is built once on the first call and reused. The same
 * palette is used for the per-line end-circle fill. */
#define ROUTE_LINE_LUT_STEPS 64
static Color g_routeLineLut[ROUTE_LINE_LUT_STEPS];
static bool g_routeLineLutInit = false;

static void buildRouteLineLut(void) {
	if(g_routeLineLutInit) {
		return;
	}
	/* Spec #4: lerp from cs.routeAdd (warm orange) to (255,220,60)
	 * (warm yellow). Static LUT — computed once on first use. */
	Color a = cs.routeAdd;
	Color b = (Color){ 255, 220, 60, 255 };
	for(int i = 0; i < ROUTE_LINE_LUT_STEPS; i++) {
		float t = (float)i / (float)(ROUTE_LINE_LUT_STEPS - 1);
		g_routeLineLut[i] = (Color){
			(unsigned char)((float)a.r + ((float)b.r - (float)a.r) * t),
			(unsigned char)((float)a.g + ((float)b.g - (float)a.g) * t),
			(unsigned char)((float)a.b + ((float)b.b - (float)a.b) * t),
			255
		};
	}
	g_routeLineLutInit = true;
}


static void drawRouteLinesNode(void *self) {
	GuiNode *gn = (GuiNode *)self;
	RouteLinesCtx *rc = &g_routeLinesCtx;
	(void)gn;
	if(!rc->inst || rc->srcIdx < 0 || rc->srcIdx >= rc->inst->modList->count) {
		return;
	}
	Mod *src = rc->inst->modList->mods[rc->srcIdx];
	Graph *base = getSelectedInstGraph();
	if(!base || !base->root) {
		return;
	}
	Rectangle anchor = { 0, 0, 0, 0 };
	findRouteButtonRect(base->root, &anchor);
	if(anchor.width <= 0.0f || anchor.height <= 0.0f) {
		return;
	}
	buildRouteLineLut();
	Vector2 from = { anchor.x + anchor.width / 2, anchor.y + anchor.height / 2 };
	for(int i = 0; i < rc->inst->paramList->count; i++) {
		Parameter *p = rc->inst->paramList->params[i];
		if(!p) {
			continue;
		}
		ModConnection *c = p->modulators;
		while(c) {
			if(c->source == src) {
				GuiNode *dialNode = findDialNodeForParam(base->root, p);
				if(!dialNode) {
					c = c->next;
					continue;
				}
				Rectangle r = { dialNode->x, dialNode->y, dialNode->w, dialNode->h };
				Vector2 to = { r.x + r.width / 2, r.y + r.height / 2 };
				/* Spec #4: gradient along the line via 16 DrawLineEx
				 * segments, each coloured by t along the
				 * source->dest vector. */
				const int SEGMENTS = 16;
				const float lineThickness = 2.5f;
				for(int s = 0; s < SEGMENTS; s++) {
					float t0 = (float)s / (float)SEGMENTS;
					float t1 = (float)(s + 1) / (float)SEGMENTS;
					Vector2 p0 = { from.x + (to.x - from.x) * t0, from.y + (to.y - from.y) * t0 };
					Vector2 p1 = { from.x + (to.x - from.x) * t1, from.y + (to.y - from.y) * t1 };
					int lutIdx = (int)(t0 * (float)(ROUTE_LINE_LUT_STEPS - 1));
					if(lutIdx < 0) {
						lutIdx = 0;
					}
					if(lutIdx >= ROUTE_LINE_LUT_STEPS) {
						lutIdx = ROUTE_LINE_LUT_STEPS - 1;
					}
					DrawLineEx(p0, p1, lineThickness, g_routeLineLut[lutIdx]);
				}
				/* Spec #4: end-cap circles tinted by the LUT
				 * extremes — warm orange at the source, warm yellow
				 * at the destination. */
				DrawCircleV(from, 3.5f, g_routeLineLut[0]);
				DrawCircleV(to, 3.5f, g_routeLineLut[ROUTE_LINE_LUT_STEPS - 1]);
				/* Spec #2: echo the destination dial's label on top
				 * of the dest cell using dialLabelPos, so the user
				 * can read what they're about to wire into. */
				if(p->name) {
					Vector2 labelPos = dialLabelPos(dialNode, 0, 0);
					DrawTextEx(pixelFont, p->name, labelPos, 9, 1, cs.labelSelected);
				}
				/* Skip the remaining chained connections from the
				 * same source so we don't draw the same line twice. */
				break;
			}
			c = c->next;
		}
	}
}


/* Spec #3: ROUTELINES is pushed when EITHER the ROUTE button is the
 * selected action (legacy hover) OR a ROUTE picker is currently open.
 * The picker count is the authority on the latter case — we don't
 * try to re-derive it from the layer stack to keep this loop free of
 * graph-walk logic. When the picker is open the overlay rides on top
 * of the picker so the user can see existing routes while picking.
 * The overlay is passive (transparent to input) so ROUTE stays modal. */
void syncRouteLinesOverlay(InstrumentGui *ig) {
	if(!ig) {
		return;
	}
	Graph *base = getSelectedInstGraph();
	GuiNode *sel = base ? base->selected : NULL;
	bool onRouteBtn = sel && sel->actionCb == cbOpenRouteLayer;
	bool pickerOpen = g_routePickerCount > 0;
	bool shouldShow = onRouteBtn || pickerOpen;
	Layer *existing = findLayerByName(&ig->overlayLayers, "ROUTELINES");
	if(shouldShow) {
		if(existing) {
			return; /* already up — no-op so we don't churn layers */
		}
		if(onRouteBtn) {
			SourceCtx *sc = (SourceCtx *)sel->actionCtx;
			if(sc && sc->inst) {
				g_routeLinesCtx.inst = sc->inst;
				g_routeLinesCtx.srcIdx = sc->idx;
			}
		}
		/* When only the picker is open (no source button is currently
		 * hovered), the picker already bumped g_routeLinesCtx before
		 * it pushed the picker — nothing to copy here. */
		Graph *g = createGraph(na_horizontal);
		GuiNode *lines = createGuiNode(0, 0, SCREEN_W, SCREEN_H, 0, na_horizontal, "routelines", 0, 0);
		lines->drawable = true;
		lines->draw = drawRouteLinesNode;
		appendItem(g->root, lines, 1);
		Layer *l = createLayer(g, 0, 0, SCREEN_W, SCREEN_H, "ROUTELINES", false, true);
		/* Spec #3: passive overlay. ROUTE stays modal — arrow keys
		 * and EDIT go to the picker, not the overlay. Set this BEFORE
		 * pushLayer: pushLayer takes ownership of `l` and frees the
		 * malloc'd struct, so post-push edits go to freed memory. */
		setLayerPassive(l, true);
		pushLayer(&ig->overlayLayers, l);
	} else if(existing) {
		/* Walk down from the top and remove the overlay; we don't
		 * assume it's at the very top because a confirmation modal
		 * could have pushed on top of it. */
		for(int i = ig->overlayLayers.count - 1; i >= 0; i--) {
			if(strcmp(ig->overlayLayers.layers[i].name, "ROUTELINES") == 0) {
				Layer *popped = (Layer *)malloc(sizeof(Layer));
				if(!popped) {
					break;
				}
				*popped = ig->overlayLayers.layers[i];
				/* Shift the rest down to keep the array contiguous. */
				for(int j = i; j < ig->overlayLayers.count - 1; j++) {
					ig->overlayLayers.layers[j] = ig->overlayLayers.layers[j + 1];
				}
				ig->overlayLayers.count--;
				destroyLayer(popped);
				break;
			}
		}
	}
}


void cbAddModSource(void *ctx) {
	Instrument *inst = (Instrument *)ctx;
	addRuntimeSource(inst);
}


static void cbCycleSourceType(void *ctx) {
	SourceCtx *sc = (SourceCtx *)ctx;
	if(!sc || !sc->inst || sc->idx < 0 || sc->idx >= sc->inst->modList->count) {
		return;
	}
	Mod *mod = sc->inst->modList->mods[sc->idx];
	ModType next = MT_ENV;
	switch(mod->type) {
		case MT_ENV: next = MT_LFO; break;
		case MT_LFO: next = MT_RND; break;
		default:     next = MT_ENV; break;
	}
	/* Task 8: hold the rebuilding flag while we mutate the lists the audio
	 * thread iterates. The audio lock closes the flag's check-then-use
	 * race. */
	pthread_mutex_lock(&g_audioLock);
	sc->inst->rebuilding = true;
	if(changeModType(sc->inst->modList, mod, next, sc->inst->paramList)) {
		sc->inst->envelopeCount = sc->inst->modList->count;
		rebuildInstrumentGraph();
	}
	sc->inst->rebuilding = false;
	pthread_mutex_unlock(&g_audioLock);
}


static const char *modTypeTag(ModType t) {
	switch(t) {
		case MT_LFO: return "LFO";
		case MT_RND: return "RND";
		case MT_ATTEN: return "ATTN";
		default:     return "ENV";
	}
}


void appendModSourceEntry(Graph *g, GuiNode *container, Instrument *inst, int idx, int weight, bool selected) {
	Mod *mod = inst->modList->mods[idx];
	bool core = idx < inst->coreEnvelopeCount;
	GuiNode *wrap = createGuiNode(0, 0, 100, 100, 2, na_horizontal, "MODSRC", 0, 0);
	wrap->drawable = true;
	wrap->draw = drawWrapperNode;

	if(!core) {
		refreshSourceCtx(inst);
		GuiNode *typeBtn = createActionBtnGuiNode(0, 0, 100, 100, 2, na_horizontal,
		                                         modTypeTag(mod->type), 0, cbCycleSourceType, &g_sourceCtx[idx]);
		typeBtn->name = strdup(modTypeTag(mod->type));
		appendItem(wrap, typeBtn, 3);
	}

	switch(mod->type) {
		case MT_ENV: {
			Envelope *e = (Envelope *)mod;
			appendItem(wrap, createDialGuiNode(0, 0, 100, 100, 2, na_horizontal, "ATTACK", selected, incParameterBaseValue, e->stages[0].duration), 4);
			appendItem(wrap, createDialGuiNode(0, 0, 100, 100, 2, na_horizontal, "CURVE", 0, incParameterBaseValue, e->stages[0].curvature), 4);
			appendItem(wrap, createDialGuiNode(0, 0, 100, 100, 2, na_horizontal, "DECAY", 0, incParameterBaseValue, e->stages[1].duration), 4);
			appendItem(wrap, createDialGuiNode(0, 0, 100, 100, 2, na_horizontal, "CURVE", 0, incParameterBaseValue, e->stages[1].curvature), 4);
			break;
		}
		case MT_LFO: {
			LFO *l = (LFO *)mod;
			appendItem(wrap, createDialGuiNode(0, 0, 100, 100, 2, na_horizontal, "RATE", selected, incParameterBaseValue, l->rate), 4);
			if(l->shape) {
				appendItem(wrap, createDialGuiNode(0, 0, 100, 100, 2, na_horizontal, "SHAPE", 0, incParameterBaseValue, l->shape), 4);
			}
			break;
		}
		case MT_RND: {
			Random *r = (Random *)mod;
			appendItem(wrap, createDialGuiNode(0, 0, 100, 100, 2, na_horizontal, "RATE", selected, incParameterBaseValue, r->rate), 4);
			if(r->shape) {
				appendItem(wrap, createDialGuiNode(0, 0, 100, 100, 2, na_horizontal, "SHAPE", 0, incParameterBaseValue, r->shape), 4);
			}
			break;
		}
		default:
			break;
	}

	if(!core) {
		/* Task 6: ROUTE opens the destination-picker layer. cbOpenRouteLayer
		 * reads inst+idx from this entry's SourceCtx (refreshed above by
		 * refreshSourceCtx) so the picker always sees the right Mod. */
		appendItem(wrap, createActionBtnGuiNode(0, 0, 100, 100, 2, na_horizontal, "ROUTE", 0, cbOpenRouteLayer, &g_sourceCtx[idx]), 3);
		/* Task 5: DEL opens the YES/NO confirm layer; cbDeleteSource reads
		 * inst+idx off the per-entry SourceCtx slot refreshed by
		 * refreshSourceCtx() above. */
		appendItem(wrap, createActionBtnGuiNode(0, 0, 100, 100, 2, na_horizontal, "DEL", 0, cbDeleteSource, &g_sourceCtx[idx]), 2);
	}
	appendItem(wrap, createBlankGuiNode(), 1);
	appendItem(container, wrap, weight);
	(void)g;
}


/* task scroll: walk a graph for the named scroll container and bring
 * the current selection into view. Called once per frame from
 * gui_instrument_draw before drawNode runs, so the scissor in the
 * scrollable branch of drawNode clips against the correct offset on
 * the same frame selection changes. */
static GuiNode *findScrollContainerByName(GuiNode *n, const char *name) {
	if(!n) {
		return NULL;
	}
	if(n->scrollable && n->name && strcmp(n->name, name) == 0) {
		return n;
	}
	if(n->itemCount > 0 && n->items) {
		ListElement *cur = n->items->head;
		for(int i = 0; i < n->itemCount; i++) {
			GuiNode *hit = findScrollContainerByName(*(GuiNode **)cur->data, name);
			if(hit) {
				return hit;
			}
			cur = cur->next;
		}
	}
	return NULL;
}

void syncModWrapScroll(void) {
	if(!igui || !igui->vm || !igui->selectedInstrument) {
		return;
	}
	Graph *g = igui->instrumentScreenGraphs[*igui->selectedInstrument];
	if(!g || !g->root) {
		return;
	}
	GuiNode *sel = g->selected;
	if(!sel) {
		return;
	}
	GuiNode *sc = findScrollContainerByName(g->root, "mod_wrap");
	if(!sc) {
		return;
	}
	scrollToVisible((ScrollContainer *)sc, sel);
}


