/* gui_gui_pattern.c -- generated by the gui module split (lawn-mowing-gui).
 * One module per screen; shared node helpers live in gui_core.c.
 * Cross-module state/helpers: see gui_internal.h. */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "dstruct.h"
#include "raylib.h"
#include "gui.h"
#include "gui_style.h"
#include "graph_gui.h"
#include "input.h"
#include "modsystem.h"
#include "notes.h"
#include "voice.h"
#include "io/preset_io.h"
#include "io.h"
#include "gui_internal.h"


/* ---- module-private state ---- */
static Graph *patternGraph;
static SongMinimapGui *smgui;
static BufferScroller *patternBufferScroller;
static int patternPage = 0;

void setPatternPage(int page) { patternPage = page; }
int getPatternPage(void) { return patternPage; }

static void drawSongMinimapGui(void *self);

typedef struct {
	PatternList *pl;
	Sequencer *seq;
	int patternIndex;
	int stepIndex;
	int *selectedStepPtr;
} StepNodeData;

#define PATTERN_STEPS_PER_ROW 4

static StepNodeData stepData[MAX_SEQUENCE_LENGTH];
static GuiNode *stepNodes[MAX_SEQUENCE_LENGTH];
static PatternList *patternPl;
static Sequencer *patternSeq;
static int *patternSelectedPatternPtr;
static int *patternSelectedStepPtr;

/* ---- track-page state (patternPage > 0) ---- */
typedef struct {
	int stepIndex;
	PatternState *pattern;
	Instrument *inst;
	int *selectedStepPtr;
} TrackStepData;

static GuiNode *trackDialStrip = NULL;
static GuiNode *trackDialNodes[PATTERN_TRACKS] = {0};
static GuiNode *trackStepNodes[MAX_PATTERN_STEPS] = {0};
static TrackStepData trackStepData[MAX_PATTERN_STEPS];
static PatternState *trackPagePattern = NULL;

static void drawPatternIndicatorNode(void *self);
static void drawTrackStepNode(void *self);
static GuiNode *createTrackStepNode(PatternState *pattern, Instrument *inst, int stepIndex, int *selectedStepPtr);

SongMinimapGui *createSongMinimapGui(Arranger *arranger, int *songIndex, int x, int y) {
	SongMinimapGui *minimapGui = (SongMinimapGui *)malloc(sizeof(SongMinimapGui));
	minimapGui->base.draw = drawSongMinimapGui;
	minimapGui->arranger = arranger;
	minimapGui->songIndex = songIndex;
	minimapGui->shape.x = x;
	minimapGui->shape.y = y;
	minimapGui->shape.w = 4;
	minimapGui->shape.h = 4;
	minimapGui->padding = 1;
	minimapGui->maxMapLength = (SCREEN_H - 150) / (minimapGui->shape.h + minimapGui->padding);
	minimapGui->defaultCellColour = cs.defaultCell;
	minimapGui->selectedCellColour = cs.reddish;
	minimapGui->playingCellColour = cs.highlightedCell;
	minimapGui->blankCellColour = cs.blankCell;

	return minimapGui;
}



void setPatternBufferScroller(BufferScroller *bs) {
	patternBufferScroller = bs;
}


static void drawBufferScrollerNode(void *self) {
	GuiNode *gn = (GuiNode *)self;
	if(!patternBufferScroller) {
		return;
	}
	drawBufferScroller(patternBufferScroller, (Rectangle){ gn->x, gn->y, gn->w, gn->h });
}


static GuiNode *createStepNode(PatternList *pl, Sequencer *seq, int patternIndex, int stepIndex, int *selectedStepPtr) {
	GuiNode *step = createGuiNode(0, 0, 50, 50, 4, na_vertical, "step", 1, 0);
	stepData[stepIndex].pl = pl;
	stepData[stepIndex].seq = seq;
	stepData[stepIndex].patternIndex = patternIndex;
	stepData[stepIndex].stepIndex = stepIndex;
	stepData[stepIndex].selectedStepPtr = selectedStepPtr;
	step->p = (Parameter *)&stepData[stepIndex];
	step->drawable = true;
	step->draw = drawStepGuiNode;
	stepNodes[stepIndex] = step;
	return step;
}


void drawStepGuiNode(void *self) {
	GuiNode *gn = (GuiNode *)self;
	StepNodeData *d = (StepNodeData *)gn->p;
	const StepCellStyle *st = resolveStepCellStyle(gn);
	int currentlyPlaying = -1;
	for(int i = 0; i < MAX_SEQUENCER_CHANNELS; i++) {
		if(d->seq->pattern_index[i] == d->patternIndex) {
			currentlyPlaying = i;
			break;
		}
	}
	Rectangle cell = (Rectangle){ gn->x, gn->y, gn->w, gn->h };
	if(*d->selectedStepPtr == d->stepIndex) {
		DrawRectangle(gn->x - 3, gn->y - 3, gn->w + 6, gn->h + 6, st->borderSelected);
	}
	if(currentlyPlaying > -1 && d->seq->running[currentlyPlaying] && d->seq->playhead_index[currentlyPlaying] == d->stepIndex) {
		DrawRectangleRec(cell, st->bgPlaying);
	} else {
		DrawRectangleRec(cell, st->bgEmpty);
	}
	int *note = getStep(d->pl, d->patternIndex, d->stepIndex);
	char *noteString = getNoteString(note[0], note[1]);
	Font *font = styleFont(st->note.fontName);
	float fontSize = st->note.fontSize ? (float)st->note.fontSize : (float)textFont.baseSize;
	DrawTextEx(*font, noteString, (Vector2){ gn->x + st->note.offsetX, gn->y + st->note.offsetY }, fontSize, (float)st->note.spacing, st->note.color);
}


static const char *PTN_SHAPE_NAMES[] = { "HOLD", "LINEAR", "SLEW", "CURVE" };
static const char *PTN_POL_NAMES[] = { "UNI", "BI" };

static bool isDialStripSelected(const GuiNode *n) {
	if(!n) {
		return false;
	}
	for(int i = 0; i < PATTERN_TRACKS; i++) {
		if(n == trackDialNodes[i]) {
			return true;
		}
	}
	return false;
}

static GuiNode *firstDialNode(void) {
	return trackDialNodes[0];
}

static int selectedStepIndex(void) {
	if(patternSelectedStepPtr) {
		int s = *patternSelectedStepPtr;
		if(s < 0) s = 0;
		if(s >= MAX_PATTERN_STEPS) s = MAX_PATTERN_STEPS - 1;
		return s;
	}
	return 0;
}

static void drawPatternIndicatorNode(void *self) {
	GuiNode *gn = (GuiNode *)self;
	Rectangle r = (Rectangle){ gn->x, gn->y, gn->w, gn->h };
	DrawRectangleRec(r, cs.panel);
	DrawRectangleLinesEx(r, 1, cs.panelBorder);
	char title[32];
	snprintf(title, sizeof(title), "PTN %d/%d", patternPage, PATTERN_TRACKS);
	DrawText(title, gn->x + 6, gn->y + 6, 20, cs.fontColour);
	if(trackPagePattern) {
		int len = getParameterValueAsInt(trackPagePattern->length);
		int shape = getParameterValueAsInt(trackPagePattern->shape);
		int pol = getParameterValueAsInt(trackPagePattern->polarity);
		if(shape < 0 || shape >= SH_COUNT) shape = 0;
		if(pol < 0 || pol >= PP_COUNT) pol = 0;
		char detail[64];
		snprintf(detail, sizeof(detail), "LEN %d  %s  %s", len, PTN_SHAPE_NAMES[shape], PTN_POL_NAMES[pol]);
		DrawText(detail, gn->x + 6, gn->y + 30, 14, cs.secondaryFontColour);
	}
}

static void drawTrackStepNode(void *self) {
	GuiNode *gn = (GuiNode *)self;
	TrackStepData *d = (TrackStepData *)gn->p;
	if(!d || !d->pattern) {
		return;
	}
	const StepCellStyle *st = resolveStepCellStyle(gn);
	Rectangle cell = (Rectangle){ gn->x, gn->y, gn->w, gn->h };
	if(d->selectedStepPtr && *d->selectedStepPtr == d->stepIndex) {
		DrawRectangle(gn->x - 3, gn->y - 3, gn->w + 6, gn->h + 6, st->borderSelected);
	}
	bool inRange = (d->stepIndex < d->pattern->stepCount);
	float frac = inRange ? d->pattern->steps[d->stepIndex] : 0.0f;
	DrawRectangleRec(cell, st->bgEmpty);
	int barH = (int)(frac * (float)gn->h);
	DrawRectangle((int)gn->x, (int)(gn->y + gn->h - barH), gn->w, barH, st->bgPlaying);
	char buf[8];
	snprintf(buf, sizeof(buf), "%d", (int)(frac * 100.0f));
	DrawText(buf, gn->x + 2, gn->y + 2, 10, st->note.color);
}

static GuiNode *createTrackStepNode(PatternState *pattern, Instrument *inst, int stepIndex, int *selectedStepPtr) {
	GuiNode *n = createGuiNode(0, 0, 50, 50, 4, na_vertical, "step", 1, 0);
	trackStepData[stepIndex].stepIndex = stepIndex;
	trackStepData[stepIndex].pattern = pattern;
	trackStepData[stepIndex].inst = inst;
	trackStepData[stepIndex].selectedStepPtr = selectedStepPtr;
	n->p = (Parameter *)&trackStepData[stepIndex];
	n->drawable = true;
	n->draw = drawTrackStepNode;
	trackStepNodes[stepIndex] = n;
	return n;
}

void createPatternGraph(Sequencer *sequencer, PatternList *pl, int *selectedPattern, int *selectedStep) {
	patternPl = pl;
	patternSeq = sequencer;
	patternSelectedPatternPtr = selectedPattern;
	patternSelectedStepPtr = selectedStep;

	patternGraph = createGraph(na_vertical);
	if(patternPage > 0) {
		Instrument *inst = getSelectedInstInstrument();
		Mod *pat = NULL;
		PatternState *ps = NULL;
		if(inst && inst->modList && patternPage - 1 < PATTERN_TRACKS) {
			int mi = modIndexAt(inst->modList, inst->coreEnvelopeCount - PATTERN_TRACKS + (patternPage - 1));
			if(mi >= 0) {
				pat = inst->modList->mods[mi];
			}
		}
		if(pat && pat->type == MT_PATTERN) {
			ps = &pat->data.pattern;
		}
		trackPagePattern = ps;

		GuiNode *indicator = createGuiNode(10, 10, 620, 40, 4, na_horizontal, "PTN_IND", 0, 0);
		indicator->drawable = true;
		indicator->draw = drawPatternIndicatorNode;
		appendItem(patternGraph->root, indicator, 2);

		if(ps) {
			GuiNode *strip = createGuiNode(10, 60, 620, 60, 6, na_horizontal, "PTN_DIALS", 0, 0);
			trackDialStrip = strip;
			trackDialNodes[0] = createDialGuiNode(0, 0, 100, 100, 2, na_horizontal, "LEN", 1, incParameterBaseValue, ps->length);
			trackDialNodes[1] = createDialGuiNode(0, 0, 100, 100, 2, na_horizontal, "SHAPE", 0, incParameterBaseValue, ps->shape);
			trackDialNodes[2] = createDialGuiNode(0, 0, 100, 100, 2, na_horizontal, "SLEW", 0, incParameterBaseValue, ps->slew);
			trackDialNodes[3] = createDialGuiNode(0, 0, 100, 100, 2, na_horizontal, "POL", 0, incParameterBaseValue, ps->polarity);
			for(int i = 0; i < PATTERN_TRACKS; i++) {
				appendItem(strip, trackDialNodes[i], 1);
			}
			appendItem(patternGraph->root, strip, 6);

			GuiNode *gridWrap = createGuiNode(10, 130, 230, 300, 6, na_vertical, "PTN_GRID", 0, 0);
			for(int r = 0; r < 4; r++) {
				GuiNode *row = createGuiNode(0, 0, 100, 50, 4, na_horizontal, "row", 0, 0);
				for(int c = 0; c < 4; c++) {
					int i = r * 4 + c;
					appendItem(row, createTrackStepNode(ps, inst, i, selectedStep), 1);
				}
				appendItem(gridWrap, row, 1);
			}
			appendItem(patternGraph->root, gridWrap, 16);
		}
		patternGraph->selected = trackDialNodes[0];
		return;
	}
	trackDialStrip = NULL;
	for(int i = 0; i < PATTERN_TRACKS; i++) {
		trackDialNodes[i] = NULL;
	}
	for(int i = 0; i < MAX_PATTERN_STEPS; i++) {
		trackStepNodes[i] = NULL;
	}
	trackPagePattern = NULL;
	int patternIndex = *selectedPattern;
	int size = 0;
	if(patternIndex >= 0 && patternIndex < pl->pattern_count) {
		size = pl->patterns[patternIndex].pattern_size;
	}
	int rows = (size + PATTERN_STEPS_PER_ROW - 1) / PATTERN_STEPS_PER_ROW;
	GuiNode *scrollerStrip = createGuiNode(0, 0, 640, 96, 0, na_horizontal, "scroller", 0, 0);
	scrollerStrip->drawable = true;
	scrollerStrip->draw = drawBufferScrollerNode;
	GuiNode *gridWrap = createGuiNode(10, 10, 230, 460, 6, na_vertical, "grid", 0, 0);
	for(int r = 0; r < rows; r++) {
		GuiNode *row = createGuiNode(0, 0, 100, 50, 4, na_horizontal, "row", 0, 0);
		for(int c = 0; c < PATTERN_STEPS_PER_ROW; c++) {
			int i = r * PATTERN_STEPS_PER_ROW + c;
			if(i >= size) {
				break;
			}
			appendItem(row, createStepNode(pl, sequencer, patternIndex, i, selectedStep), 1);
		}
		appendItem(gridWrap, row, 1);
	}
	appendItem(patternGraph->root, scrollerStrip, 4);
	appendItem(patternGraph->root, gridWrap, 16);
	if(size > 0) {
		int current = *selectedStep;
		if(current < 0) {
			current = 0;
		}
		if(current >= size) {
			current = size - 1;
		}
		patternGraph->selected = stepNodes[current];
		stepNodes[current]->selected = 1;
	}
}


void navigatePatternGraph(int keymapping) {
	if(!patternGraph || !patternGraph->selected) {
		return;
	}
	if(patternPage > 0) {
		if(isDialStripSelected(patternGraph->selected)) {
			switch(keymapping) {
				case KM_LEFT:
					changeGraphSelection(patternGraph, selectAdjacent(patternGraph, patternGraph->selected, true));
					return;
				case KM_RIGHT:
					changeGraphSelection(patternGraph, selectAdjacent(patternGraph, patternGraph->selected, false));
					return;
				case KM_DOWN:
					changeGraphSelection(patternGraph, trackStepNodes[selectedStepIndex()]);
					return;
				default:
					return;
			}
		}
		TrackStepData *td = (TrackStepData *)patternGraph->selected->p;
		if(!td) {
			return;
		}
		int cur = *td->selectedStepPtr;
		int next = cur;
		switch(keymapping) {
			case KM_LEFT:
				if(cur % 4 > 0) next = cur - 1;
				break;
			case KM_RIGHT:
				if(cur % 4 < 3) next = cur + 1;
				break;
			case KM_UP:
				if(cur < 4) {
					changeGraphSelection(patternGraph, firstDialNode());
					return;
				}
				next = cur - 4;
				break;
			case KM_DOWN:
				if(cur < 12) next = cur + 4;
				break;
			default:
				return;
		}
		*td->selectedStepPtr = next;
		changeGraphSelection(patternGraph, trackStepNodes[next]);
		return;
	}
	StepNodeData *d = (StepNodeData *)patternGraph->selected->p;
	int next = *d->selectedStepPtr;
	switch(keymapping) {
		case KM_LEFT:
			next = selectStep(d->pl, d->patternIndex, *d->selectedStepPtr - 1);
			break;
		case KM_RIGHT:
			next = selectStep(d->pl, d->patternIndex, *d->selectedStepPtr + 1);
			break;
		case KM_UP:
			next = selectStep(d->pl, d->patternIndex, *d->selectedStepPtr - PATTERN_STEPS_PER_ROW);
			break;
		case KM_DOWN:
			next = selectStep(d->pl, d->patternIndex, *d->selectedStepPtr + PATTERN_STEPS_PER_ROW);
			break;
		default:
			return;
	}
	*d->selectedStepPtr = next;
	changeGraphSelection(patternGraph, stepNodes[next]);
}


bool handlePatternTrackEdit(int keymapping) {
	if(patternPage == 0 || !patternGraph || !patternGraph->selected) {
		return false;
	}
	GuiNode *sel = patternGraph->selected;
	if(isDialStripSelected(sel)) {
		if(!isSelectedDialNode(patternGraph) || !sel->callback) {
			return false;
		}
		float delta = (keymapping == KM_UP) ? 0.05f
		            : (keymapping == KM_DOWN) ? -0.05f
		            : 0.0f;
		if(delta == 0.0f) {
			return false;
		}
		sel->callback((Parameter *)sel->p, delta);
		Instrument *inst = getSelectedInstInstrument();
		if(inst) {
			inst->loaded.dirty = true;
			capturePatternTracksToInstrument(inst);
		}
		return true;
	}
	TrackStepData *d = (TrackStepData *)sel->p;
	if(!d || !d->pattern) {
		return false;
	}
	float delta = (keymapping == KM_UP) ? (1.0f / 16.0f)
	            : (keymapping == KM_DOWN) ? -(1.0f / 16.0f)
	            : 0.0f;
	if(delta == 0.0f) {
		return false;
	}
	float v = d->pattern->steps[d->stepIndex] + delta;
	if(v > 1.0f) v = 1.0f;
	if(v < 0.0f) v = 0.0f;
	d->pattern->steps[d->stepIndex] = v;
	if(d->inst) {
		d->inst->loaded.dirty = true;
		capturePatternTracksToInstrument(d->inst);
	}
	return true;
}

void rebuildPatternGraph() {
	if(!patternPl || !patternSeq || !patternGraph) {
		return;
	}
	freeGuiNode(patternGraph->root);
	free(patternGraph);
	patternGraph = NULL;
	createPatternGraph(patternSeq, patternPl, patternSelectedPatternPtr, patternSelectedStepPtr);
}


void setSongMinimapGui(SongMinimapGui *smg) {
	smgui = smg;
}


static void drawSongMinimapGui(void *self) {
	SongMinimapGui *smGui = (SongMinimapGui *)self;
	Arranger *arranger = (Arranger *)smGui->arranger;
	int startIndex = 0;
	// printf("coord %d,%d\n", smGui->songIndex[0], smGui->songIndex[1]);

	for(int i = startIndex; i < smGui->maxMapLength; i++) {
		int newy = smGui->shape.y + (i * smGui->shape.w) + (smGui->padding * i);
		for(int j = 0; j < MAX_SEQUENCER_CHANNELS; j++) {
			int newx = smGui->shape.x + (j * smGui->shape.h) + (smGui->padding * j);
			if(arranger->song[j][i] > -1) {
				if(smGui->songIndex[0] == j && smGui->songIndex[1] == i) {
					DrawRectangle(newx, newy, smGui->shape.w, smGui->shape.h, smGui->selectedCellColour);
				} else if(arranger->playhead_indices[j] == i) {
					DrawRectangle(newx, newy, smGui->shape.w, smGui->shape.h, smGui->playingCellColour);
				} else {
					DrawRectangle(newx, newy, smGui->shape.w, smGui->shape.h, smGui->defaultCellColour);
				}
			} else {
				DrawRectangle(newx, newy, smGui->shape.w, smGui->shape.h, smGui->blankCellColour);
			}
		}
	}
}



void gui_pattern_draw(void) {
	drawNode(patternGraph->root);
	if (smgui) {
		drawSongMinimapGui(smgui);
	}
}
